import { VocabItem, VocabularyPart } from '../../types';

const test1_words: VocabItem[] = [
    { word: "Infrastructure", definition: "cơ sở hạ tầng", example: "The city is investing in sustainable infrastructure." },
    { word: "Implementation", definition: "sự thực hiện, triển khai", example: "The implementation of the new policy was successful." },
    { word: "Collaboration", definition: "sự hợp tác", example: "Cross-departmental collaboration is essential for this project." },
    { word: "Feasibility", definition: "tính khả thi", example: "We are conducting a feasibility study for the expansion." },
    { word: "Specification", definition: "thông số kỹ thuật, đặc điểm", example: "The machine meets all the required specifications." },
    { word: "Compliance", definition: "sự tuân thủ", example: "Our company ensures full compliance with safety regulations." },
    { word: "Procurement", definition: "sự thu mua, cung ứng", example: "The procurement department handles all supplier contracts." },
    { word: "Diversification", definition: "sự đa dạng hóa", example: "Market diversification reduces financial risk." },
    { word: "Restructuring", definition: "sự tái cơ cấu", example: "The company underwent a major restructuring last year." },
    { word: "Logistics", definition: "hậu cần", example: "Effective logistics are key to timely delivery." },
    { word: "Carry", definition: "Mang, vác, xách", example: "He is carrying the supplies to the warehouse." },
    { word: "Remove", definition: "Loại bỏ, dời đi", example: "Please remove the old equipment from the hall." },
    { word: "Pour", definition: "Rót, đổ", example: "The server is pouring a beverage for the guest." },
    { word: "Beverage", definition: "Đồ uống", example: "Cold beverages are available in the cafeteria." },
    { word: "Light fixture", definition: "Đèn chùm, thiết bị chiếu sáng", example: "The technician is installing a new light fixture." },
    { word: "Install", definition: "Cài đặt, lắp đặt", example: "We need to install the software updates." },
    { word: "Warehouse", definition: "Nhà kho", example: "The shipment is waiting at the warehouse." },
    { word: "Meeting minutes", definition: "Biên bản cuộc họp", example: "The assistant is taking the meeting minutes." },
    { word: "Accounting", definition: "Kế toán", example: "The accounting department reviewed the budget." },
    { word: "Assistant", definition: "Trợ lý", example: "The manager's assistant scheduled the meeting." },
    { word: "Account", definition: "Tài khoản", example: "Please update your user account information." },
    { word: "Analyst", definition: "Chuyên viên phân tích", example: "The financial analyst predicted a growth in revenue." },
    { word: "Decoration", definition: "Sự trang trí, đồ trang trí", example: "We added some decorations to the lobby." },
    { word: "Competent", definition: "Có năng lực, thạo việc", example: "She is a highly competent project manager." },
    { word: "Retreat", definition: "Chuyến nghỉ dưỡng (công ty)", example: "The annual company retreat is next weekend." },
    { word: "Solve", definition: "Giải quyết", example: "We need to solve the technical issue immediately." },
    { word: "Departure", definition: "Sự khởi hành", example: "Check the screen for departure times." },
    { word: "Introduction", definition: "Sự giới thiệu, mở đầu", example: "The director gave a brief introduction." },
    { word: "Retirement", definition: "Sự nghỉ hưu", example: "We are holding a party for his retirement." },
    { word: "Appointment", definition: "Cuộc hẹn", example: "I have an appointment with the dentist." },
    { word: "Borrow", definition: "Mượn", example: "Can I borrow a pen for a moment?" },
    { word: "Brochure", definition: "Tờ gấp quảng cáo", example: "The travel brochure shows beautiful beaches." },
    { word: "Confirmation", definition: "Sự xác nhận", example: "Wait for the confirmation email." },
    { word: "Process", definition: "Quy trình / Xử lý", example: "The hiring process takes two weeks." },
    { word: "Expense", definition: "Chi phí", example: "Travel expenses will be reimbursed." },
    { word: "Finance", definition: "Tài chính", example: "The finance team approved the project." },
    { word: "Correct", definition: "Chính xác / Sửa chữa", example: "That is the correct password." },
    { word: "Demonstration", definition: "Sự minh họa, làm mẫu", example: "The demonstration was very helpful." },
    { word: "Charge", definition: "Tính phí / Phí", example: "Is there an extra charge for shipping?" },
    { word: "Device", definition: "Thiết bị", example: "Connect your mobile device to the network." },
    { word: "Cost", definition: "Chi phí / Trị giá", example: "The total cost was fifty dollars." },
    { word: "Extra", definition: "Thêm, phụ", example: "Do you need any extra supplies?" },
    { word: "In charge of", definition: "Phụ trách, chịu trách nhiệm", example: "Who is in charge of the event?" },
    { word: "Crew", definition: "Đội, nhóm (công tác)", example: "The maintenance crew is working on the site." },
    { word: "Available", definition: "Có sẵn, rảnh rỗi", example: "Are you available for a meeting?" },
    { word: "Depend on", definition: "Phụ thuộc vào", example: "The results depend on the data accuracy." },
    { word: "Addition", definition: "Sự thêm vào, phần thêm", example: "The new wing is a great addition." },
    { word: "Consider", definition: "Cân nhắc, xem xét", example: "Please consider our proposal." },
    { word: "Lower", definition: "Hạ thấp, giảm", example: "We need to lower our operating costs." },
    { word: "Headquarters", definition: "Trụ sở chính", example: "The company headquarters is in London." },
    { word: "Book", definition: "Đặt chỗ", example: "I need to book a hotel room." },
    { word: "Regional", definition: "Thuộc vùng, miền", example: "The regional manager is visiting today." },
    { word: "Performance", definition: "Hiệu suất, sự thể hiện", example: "Employee performance is reviewed annually." },
    { word: "Advance", definition: "Sự thăng tiến / Tiến bộ", example: "There are many chances to advance here." },
    { word: "Payment", definition: "Sự thanh toán", example: "The payment is due on Monday." },
    { word: "Required", definition: "Bắt buộc, được yêu cầu", example: "Identification is required for entry." },
    { word: "Sign up for", definition: "Đăng ký", example: "Sign up for the newsletter online." },
    { word: "Competition", definition: "Sự cạnh tranh, cuộc thi", example: "The competition for the role was intense." },
    { word: "Merchandise", definition: "Hàng hóa", example: "The store sells high-quality merchandise." },
    { word: "Permit", definition: "Giấy phép", example: "You need a building permit for the project." },
    { word: "Agree", definition: "Đồng ý", example: "Do you agree with the terms?" },
    { word: "Annual", definition: "Hàng năm", example: "The annual report is ready." },
    { word: "Expand", definition: "Mở rộng", example: "The firm plans to expand its market." },
    { word: "Take care of", definition: "Chăm sóc, lo liệu", example: "I will take care of the details." },
    { word: "Attendee", definition: "Người tham dự", example: "Each attendee received a packet." },
    { word: "Job opening", definition: "Vị trí tuyển dụng", example: "There is a new job opening in Sales." },
    { word: "Author", definition: "Tác giả", example: "The author signed the book." },
    { word: "Reserve", definition: "Đặt trước, để dành", example: "Reserve a seat in advance." },
    { word: "Revise", definition: "Chỉnh sửa, ôn lại", example: "Please revise the draft by Friday." },
    { word: "Budget", definition: "Ngân sách", example: "The project is within budget." },
    { word: "Get rid of", definition: "Loại bỏ, vứt bỏ", example: "Get rid of the old files." },
    { word: "Unfortunately", definition: "Không may thay", example: "Unfortunately, the flight was delayed." },
    { word: "Operation", definition: "Hoạt động, vận hành", example: "Daily operations are running smoothly." },
    { word: "Application", definition: "Đơn xin, ứng dụng", example: "Submit your application online." },
    { word: "Directions", definition: "Sự hướng dẫn, chỉ đường", example: "Follow the directions on the sign." },
    { word: "Owner", definition: "Chủ sở hữu", example: "The owner is very friendly." },
    { word: "Location", definition: "Địa điểm, vị trí", example: "What is the meeting location?" },
    { word: "Local", definition: "Địa phương", example: "Support local businesses." },
    { word: "Advantage", definition: "Lợi thế", example: "The new system has many advantages." },
    { word: "Rental", definition: "Sự thuê mướn", example: "We need a rental car." },
    { word: "Release", definition: "Phát hành, tung ra", example: "The new product release is tomorrow." },
    { word: "Issue", definition: "Vấn đề / Số báo", example: "This is a recurring issue." },
    { word: "Secure", definition: "Bảo đảm, đạt được", example: "Ensure the files are secure." },
    { word: "Conduct", definition: "Tiến hành, thực hiện", example: "Conduct a survey of the customers." },
    { word: "Negotiate", definition: "Đàm phán, thương lượng", example: "We need to negotiate a better deal." },
    { word: "Maintenance", definition: "Sự bảo trì", example: "Regular maintenance is essential." },
    { word: "Randomly", definition: "Một cách ngẫu nhiên", example: "The names were chosen randomly." },
    { word: "Malfunction", definition: "Sự trục trặc, lỗi", example: "The scanner had a malfunction." },
    { word: "Complete", definition: "Hoàn thành", example: "Complete the form before leaving." },
    { word: "Increase", definition: "Tăng lên", example: "Sales have seen an increase this month." },
];

const test2_words: VocabItem[] = [
    { word: "Intermittent", definition: "gián đoạn, từng hồi", example: "We experienced intermittent power outages during the storm." },
    { word: "Consolidation", definition: "sự hợp nhất, củng cố", example: "The consolidation of the two firms improved efficiency." },
    { word: "Disruption", definition: "sự gián đoạn, phá vỡ", example: "New technologies often cause industry disruption." },
    { word: "Benchmark", definition: "điểm chuẩn, tiêu chuẩn đối sánh", example: "Our performance set a new benchmark for the industry." },
    { word: "Incentive", definition: "động lực, sự khuyến khích", example: "The government offers tax incentives for green energy." },
    { word: "Retention", definition: "sự giữ lại, duy trì", example: "Employee retention is a top priority for HR." },
    { word: "Outsource", definition: "thuê ngoài", example: "Many companies outsource their IT support services." },
    { word: "Proprietary", definition: "độc quyền, thuộc về sở hữu", example: "The company uses proprietary software for data analysis." },
    { word: "Redundancy", definition: "sự dư thừa", example: "Automation might lead to workforce redundancy." },
    { word: "Volatility", definition: "sự biến động", example: "Stock market volatility is expected this month." },
    { word: "hang", definition: "Treo, mắc", example: "Please hang your coat in the closet." },
    { word: "luggage", definition: "Hành lý", example: "Do you need help with your luggage?" },
    { word: "lean against", definition: "Dựa vào", example: "The ladder is leaning against the wall." },
    { word: "railing", definition: "Lan can, rào chắn", example: "Hold on to the railing while walking." },
    { word: "vehicle", definition: "Phương tiện, xe cộ", example: "The electric vehicle is fully charged." },
    { word: "stack", definition: "Xếp chồng / Đống", example: "Please stack the boxes in the corner." },
    { word: "reach for", definition: "Với lấy", example: "She is reaching for a book on the shelf." },
    { word: "shelf", definition: "Cái kệ, giá", example: "The files are on the top shelf." },
    { word: "set up", definition: "Thiết lập, sắp đặt", example: "Set up the meeting room for tomorrow." },
    { word: "postpone", definition: "Trì hoãn", example: "The meeting was postponed due to rain." },
    { word: "proposal", definition: "Bản đề xuất, sự đề nghị", example: "Submit your proposal by Friday." },
    { word: "convenient", definition: "Thuận tiện, tiện lợi", example: "The location is very convenient." },
    { word: "take place", definition: "Diễn ra", example: "The festival will take place in the park." },
    { word: "last", definition: "Kéo dài", example: "The workshop will last for two hours." },
    { word: "rate", definition: "Mức giá, tỷ lệ", example: "The interest rate has increased." },
    { word: "renovation", definition: "Sự cải tạo, nâng cấp", example: "The building is under renovation." },
    { word: "material", definition: "Tài liệu, nguyên liệu", example: "We need more construction materials." },
    { word: "fee", definition: "Phí, lệ phí", example: "There is an additional processing fee." },
    { word: "discontinue", definition: "Ngừng, đình chỉ", example: "The model was discontinued last year." },
    { word: "instructor", definition: "Người hướng dẫn", example: "Follow the instructor's directions." },
    { word: "cafeteria", definition: "Quán ăn tự phục vụ, căng tin", example: "Lunch is served in the cafeteria." },
    { word: "sold out", definition: "Bán hết", example: "The concert tickets are sold out." },
    { word: "strategy", definition: "Chiến lược", example: "Our marketing strategy needs revision." },
    { word: "opposite", definition: "Đối diện / Trái ngược", example: "The bank is opposite the library." },
    { word: "submit", definition: "Nộp, đệ trình", example: "Submit your report online." },
    { word: "residential", definition: "(Thuộc) khu dân cư", example: "This is a quiet residential area." },
    { word: "broken", definition: "Bị hỏng, bị vỡ", example: "The printer is currently broken." },
    { word: "complain", definition: "Phàn nàn, khiếu nại", example: "Customers rarely complain about the service." },
    { word: "instructions", definition: "Hướng dẫn", example: "Read the instructions carefully." },
    { word: "expired", definition: "Hết hạn", example: "Your library card has expired." },
    { word: "volunteer", definition: "Tình nguyện viên / Tình nguyện", example: "She is a volunteer at the clinic." },
    { word: "approval", definition: "Sự chấp thuận", example: "Wait for management's approval." },
    { word: "access", definition: "Quyền truy cập / Truy cập", example: "Unauthorized access is restricted." },
    { word: "transportation", definition: "Giao thông, vận tải", example: "Public transportation is efficient." },
    { word: "promotional", definition: "(Thuộc) quảng cáo, khuyến mãi", example: "We have some promotional gifts for you." },
    { word: "currently", definition: "Hiện tại, hiện nay", example: "He is currently out of town." },
    { word: "address", definition: "Giải quyết / Địa chỉ", example: "What is your current address?" },
    { word: "decline", definition: "Từ chối / Giảm sút", example: "Sales have begun to decline." },
    { word: "organize", definition: "Tổ chức, sắp xếp", example: "Organize the files alphabetically." },
    { word: "celebrity", definition: "Người nổi tiếng", example: "The event featured a local celebrity." },
    { word: "sponsor", definition: "Tài trợ / Nhà tài trợ", example: "The race is sponsored by the city." },
    { word: "reduce", definition: "Giảm bớt", example: "Reduce the number of errors." },
    { word: "property", definition: "Tài sản, bất động sản", example: "The property is located downtown." },
    { word: "reward", definition: "Phần thưởng / Thưởng", example: "There is a reward for the winner." },
    { word: "demand", definition: "Nhu cầu / Yêu cầu", example: "Demand for the product is high." },
    { word: "potential", definition: "Tiềm năng", example: "We have many potential clients." },
    { word: "candidate", definition: "Ứng viên", example: "She is a strong candidate for the job." },
    { word: "competitor", definition: "Đối thủ cạnh tranh", example: "Our competitors offer lower prices." },
    { word: "venue", definition: "Địa điểm (tổ chức sự kiện)", example: "The venue for the party is nice." },
    { word: "former", definition: "Cựu, trước đây", example: "He is a former company president." },
    { word: "résumé", definition: "Sơ yếu lý lịch (CV)", example: "Send your résumé to HR." },
    { word: "arrange", definition: "Sắp xếp", example: "Arrange a meeting for next week." },
    { word: "colleague", definition: "Đồng nghiệp", example: "Talk to your colleagues for feedback." },
    { word: "appropriate", definition: "Thích hợp, phù hợp", example: "Wear appropriate attire for work." },
    { word: "recruitment", definition: "Sự tuyển dụng", example: "The recruitment process is underway." },
    { word: "reject", definition: "Từ chối, bác bỏ", example: "Do not reject the proposal yet." },
    { word: "assistance", definition: "Sự hỗ trợ, giúp đỡ", example: "Do you need any assistance?" },
    { word: "affordable", definition: "Giá cả phải chăng", example: "We offer affordable dental services." },
    { word: "invitation", definition: "Lời mời, thiệp mời", example: "I received an invitation to the party." },
    { word: "typically", definition: "Thông thường, điển hình", example: "The tour typically lasts an hour." },
    { word: "merger", definition: "Sự sáp nhập", example: "The merger was announced today." },
    { word: "durable", definition: "Bền", example: "The material is very durable." },
    { word: "justify", definition: "Biện minh, chứng minh là đúng", example: "Can you justify the expense?" },
    { word: "inspection", definition: "Sự kiểm tra, thanh tra", example: "The annual safety inspection is due." },
    { word: "prototype", definition: "Nguyên mẫu", example: "The prototype is still being tested." },
    { word: "originally", definition: "Ban đầu, lúc đầu", example: "The building was originally a factory." },
    { word: "share", definition: "Chia sẻ / Cổ phiếu", example: "Share the news with the team." },
    { word: "shorten", definition: "Rút ngắn", example: "We need to shorten the presentation." },
    { word: "accept", definition: "Chấp nhận", example: "Accept the invitation promptly." },
    { word: "loan", definition: "Khoản vay / Cho vay", example: "The bank approved the loan." },
    { word: "layout", definition: "Bố cục, cách bài trí", example: "The layout of the store is nice." },
    { word: "proof", definition: "Bằng chứng", example: "We have proof of the purchase." },
    { word: "insurance", definition: "Bảo hiểm", example: "The car insurance is in effect." },
    { word: "upcoming", definition: "Sắp tới", example: "The upcoming event is busy." },
    { word: "opportunity", definition: "Cơ hội", example: "It is a great opportunity." },
    { word: "brief", definition: "Ngắn gọn", example: "The director gave a brief talk." },
    { word: "screen", definition: "Màn hình / Sàng lọc", example: "Check the screen for flight status." },
    { word: "invoice", definition: "Hóa đơn (yêu cầu thanh toán)", example: "The invoice is due next week." },
    { word: "incorrect", definition: "Không chính xác, sai", example: "The password is incorrect." },
    { word: "frequent", definition: "Thường xuyên", example: "She is a frequent guest on the show." },
];

const test3_words: VocabItem[] = [
    { word: "Asynchronous", definition: "không đồng bộ", example: "Asynchronous communication allows team members to respond at their own pace." },
    { word: "Flexibility", definition: "sự linh hoạt", example: "Modern workers value flexibility in their schedules." },
    { word: "Connectivity", definition: "khả năng kết nối", example: "Strong connectivity is vital for a smooth remote work experience." },
    { word: "Engagement", definition: "sự gắn kết", example: "Employee engagement levels are monitored through annual surveys." },
    { word: "Autonomy", definition: "quyền tự chủ", example: "Remote workers often have more autonomy over their daily tasks." },
    { word: "Burnout", definition: "sự kiệt sức", example: "Managing workload effectively helps prevent employee burnout." },
    { word: "Virtual", definition: "ảo", example: "The team held a virtual meeting using specialized software." },
    { word: "Boundary", definition: "ranh giới", example: "Maintaining a boundary between work and home life is crucial." },
    { word: "Resilience", definition: "sự kiên cường", example: "The company showed great resilience during the economic crisis." },
    { word: "Cohesion", definition: "sự gắn kết (trong nhóm)", example: "Regular team-building activities improve group cohesion." },
    { word: "Fix", definition: "Sửa chữa", example: "We need to fix the projector." },
    { word: "Pedestrian", definition: "Người đi bộ", example: "The pedestrian crossing is nearby." },
    { word: "Attend", definition: "Tham dự", example: "I will attend the meeting tomorrow." },
    { word: "Face", definition: "Đối mặt", example: "They are facing a shelving unit." },
    { word: "Certificate", definition: "Giấy chứng nhận", example: "I received my safety certificate." },
    { word: "Press conference", definition: "Cuộc họp báo", example: "The press conference is at ten." },
    { word: "Weigh", definition: "Cân / Cân nhắc", example: "Weigh your options carefully." },
    { word: "Quarter", definition: "Quý (3 tháng) / 1 phần 4", example: "The second quarter ends in June." },
    { word: "Directory", definition: "Danh bạ / Thư mục", example: "Check the employee directory." },
    { word: "Be supposed to", definition: "Được cho là / Phải", example: "I am supposed to leave at noon." },
    { word: "Replace", definition: "Thay thế", example: "Replace the old printer." },
    { word: "Lead", definition: "Dẫn dắt / Lãnh đạo", example: "She will lead the training today." },
    { word: "Award-winning", definition: "Từng đoạt giải thưởng", example: "He is an award-winning chef." },
    { word: "Supplies", definition: "Vật tư / Nhu yếu phẩm", example: "The office supplies are in the closet." },
    { word: "Storage", definition: "Kho lưu trữ", example: "The storage room is full." },
    { word: "Manufacturer", definition: "Nhà sản xuất", example: "Contact the manufacturer for parts." },
    { word: "Measures", definition: "Biện pháp", example: "We are taking safety measures." },
    { word: "Success", definition: "Sự thành công", example: "The project was a success." },
    { word: "Upstairs", definition: "Tầng trên", example: "The office is upstairs." },
    { word: "Draft", definition: "Bản nháp", example: "Please review the draft budget." },
    { word: "Appreciate", definition: "Trân trọng / Cảm kích", example: "I appreciate your hard work." },
    { word: "Extend", definition: "Gia hạn / Kéo dài", example: "Extend the project deadline." },
    { word: "Warranty", definition: "Bảo hành", example: "The repair is covered under warranty." },
    { word: "Qualification", definition: "Trình độ chuyên môn", example: "What are your qualifications?" },
    { word: "Unexpected", definition: "Bất ngờ / Không lường trước", example: "There were unexpected delays." },
    { word: "Floor plan", definition: "Sơ đồ mặt bằng", example: "Check the floor plan for the exit." },
    { word: "Architect", definition: "Kiến trúc sư", example: "The architect designed the villa." },
    { word: "Inspect", definition: "Kiểm tra / Thanh tra", example: "The crew will inspect the machinery." },
    { word: "Approximately", definition: "Xấp xỉ / Khoảng", example: "The trip takes approximately one hour." },
    { word: "Recommendation", definition: "Sự giới thiệu / Đề xuất", example: "Follow the doctor's recommendation." },
    { word: "Patron", definition: "Khách quen / Người bảo trợ", example: "We thank our loyal patrons." },
    { word: "Regular", definition: "Thường xuyên / Đều đặn", example: "Regular maintenance is required." },
    { word: "Deposit", definition: "Đặt cọc / Gửi tiền", example: "A deposit is necessary to reserve." },
    { word: "Reschedule", definition: "Sắp xếp lại lịch", example: "We need to reschedule the conference." },
    { word: "Prescription", definition: "Đơn thuốc", example: "The pharmacist filled the prescription." },
    { word: "Inconvenient", definition: "Bất tiện", example: "The closure is inconvenient for residents." },
    { word: "Medication", definition: "Thuốc men", example: "Take your medication regularly." },
    { word: "Inventory", definition: "Hàng tồn kho / Kiểm kê", example: "The inventory is low on paper." },
    { word: "Drop", definition: "Giảm / Làm rơi", example: "Sales have begun to drop." },
    { word: "Stand out", definition: "Nổi bật", example: "She really stands out in the group." },
    { word: "Input", definition: "Ý kiến đóng góp / Đầu vào", example: "We value your input." },
    { word: "Athlete", definition: "Vận động viên", example: "The athlete won a ribbon." },
    { word: "Consult", definition: "Tham khảo / Hỏi ý kiến", example: "Consult the manual for help." },
    { word: "Faulty", definition: "Bị lỗi / Hỏng", example: "The scanner is faulty." },
    { word: "Understaffed", definition: "Thiếu nhân sự", example: "The department is understaffed." },
    { word: "Feature", definition: "Có / Tính năng", example: "The show features local music." },
    { word: "Public", definition: "Công chúng / Công cộng", example: "The park is open to the public." },
    { word: "Expire", definition: "Hết hạn", example: "When does the contract expire?" },
    { word: "Archive", definition: "Lưu trữ / Kho lưu trữ", example: "Check the company archive for photos." },
    { word: "Verify", definition: "Xác minh", example: "Verify the account information." },
    { word: "Confirm", definition: "Xác nhận", example: "Confirm your attendance by Friday." },
    { word: "Deadline", definition: "Hạn chót", example: "The deadline is approaching." },
    { word: "Apply for", definition: "Nộp đơn cho", example: "Apply for the position online." },
    { word: "Renew", definition: "Gia hạn / Làm mới", example: "Renew your license online." },
    { word: "Subscription", definition: "Sự đăng ký (báo/tạp chí)", example: "My subscription was canceled." },
    { word: "Appear", definition: "Xuất hiện / Dường như", example: "The results appear positive." },
    { word: "Nominate", definition: "Đề cử", example: "He was nominated for an award." },
    { word: "Refund", definition: "Hoàn tiền", example: "Receive a full refund." },
    { word: "Goods", definition: "Hàng hóa", example: "The store sells household goods." },
    { word: "Authority", definition: "Thẩm quyền / Chính quyền", example: "Contact the port authority." },
    { word: "Transaction", definition: "Giao dịch", example: "The transaction was successful." },
    { word: "Efficiently", definition: "Một cách hiệu quả", example: "Use your time efficiently." },
    { word: "Significant", definition: "Đáng kể / Quan trọng", example: "The increase was significant." },
    { word: "Advertisement", definition: "Quảng cáo", example: "I saw your advertisement online." },
    { word: "Regulation", definition: "Quy định", example: "Follow the safety regulations." },
    { word: "Organic", definition: "Hữu cơ", example: "Support organic farming." },
    { word: "Entirely", definition: "Hoàn toàn", example: "The building is entirely solar-powered." },
    { word: "Individual", definition: "Cá nhân", example: "Receive individualized instruction." },
    { word: "Nutritional", definition: "(Thuộc) Dinh dưỡng", example: "Eat nutritional foods." },
    { word: "Investment", definition: "Sự đầu tư", example: "It is a worthwhile investment." },
    { word: "Donate", definition: "Quyên góp", example: "Donate surplus produce." },
    { word: "Charity", definition: "Từ thiện / Tổ chức từ thiện", example: "It's a charity event." },
    { word: "Unavailable", definition: "Không có sẵn / Bận", example: "The model is currently unavailable." },
    { word: "Participate in", definition: "Tham gia vào", example: "Participate in the survey." },
    { word: "Relocate", definition: "Di dời / Chuyển địa điểm", example: "The firm will relocate next month." },
    { word: "Affect", definition: "Ảnh hưởng", example: "The rain will affect the commute." },
    { word: "Condition", definition: "Điều kiện / Tình trạng", example: "The building is in bad condition." },
    { word: "Reference", definition: "Tài liệu tham khảo / Sự giới thiệu", example: "Keep a schedule for reference." },
    { word: "Hygienist", definition: "Chuyên viên vệ sinh (nha khoa)", example: "The hygienist cleaned my teeth." },
    { word: "Reimbursement", definition: "Sự hoàn lại (tiền công tác phí)", example: "Request reimbursement for travel." },
];

const test4_words: VocabItem[] = [
    { word: "Automation", definition: "tự động hóa", example: "Warehouse automation has significantly increased shipping speeds." },
    { word: "Predictive", definition: "tiên đoán", example: "Predictive analytics help us anticipate market shifts." },
    { word: "Integration", definition: "sự tích hợp", example: "The integration of AI tools has streamlined our operations." },
    { word: "Algorithm", definition: "thuật toán", example: "The search algorithm was updated to provide better results." },
    { word: "Scalability", definition: "khả năng mở rộng", example: "Our current system lacks the scalability needed for global growth." },
    { word: "Interface", definition: "giao diện", example: "The new user interface is much more intuitive than the previous one." },
    { word: "Analytics", definition: "phân tích dữ liệu", example: "We rely on advanced analytics to make informed business decisions." },
    { word: "Database", definition: "cơ sở dữ liệu", example: "Customer information is stored in a secure central database." },
    { word: "Digitization", definition: "sự số hóa", example: "The digitization of all records was a massive undertaking." },
    { word: "Framework", definition: "khuôn khổ, khung sườn", example: "The technical framework supports multiple programming languages." },
    { word: "cross", definition: "băng qua", example: "Use the pedestrian crossing to cross the street." },
    { word: "traffic", definition: "giao thông", example: "Traffic is heavy during the morning commute." },
    { word: "put together", definition: "lắp ráp, tập hợp", example: "We need to put together the project proposal." },
    { word: "empty", definition: "trống rỗng", example: "The storage room is currently empty." },
    { word: "reservation", definition: "sự đặt trước", example: "I have a reservation for two." },
    { word: "commute", definition: "đi lại (đi làm)", example: "My daily commute takes an hour." },
    { word: "usually", definition: "thường xuyên", example: "I usually arrive at eight A.M." },
    { word: "negative", definition: "tiêu cực", example: "There were no negative comments." },
    { word: "job posting", definition: "thông báo tuyển dụng", example: "Check the job posting online." },
    { word: "council", definition: "hội đồng", example: "The city council approved the budget." },
    { word: "review", definition: "xem xét, đánh giá", example: "The manager will review the reports." },
    { word: "shift", definition: "ca làm việc", example: "My shift ends at five." },
    { word: "valid", definition: "có hiệu lực", example: "The contract is now valid." },
    { word: "identification", definition: "giấy tờ tùy thân", example: "Show your identification at the desk." },
    { word: "post", definition: "đăng tải, gửi thư", example: "Post the announcement online." },
    { word: "transfer", definition: "chuyển đổi, thuyên chuyển", example: "Transfer the funds immediately." },
    { word: "in time", definition: "kịp giờ", example: "We arrived just in time." },
    { word: "in person", definition: "trực tiếp (gặp mặt)", example: "I need to meet him in person." },
    { word: "tenant", definition: "người thuê nhà", example: "The tenant reported a leak." },
    { word: "particular", definition: "cụ thể, đặc biệt", example: "This particular model is popular." },
    { word: "district", definition: "quận, khu vực", example: "The business district is busy." },
    { word: "routinely", definition: "thường lệ", example: "The system is routinely checked." },
    { word: "congested", definition: "tắc nghẽn", example: "The road is often congested." },
    { word: "temporarily", definition: "tạm thời", example: "The road is temporarily closed." },
    { word: "ingredient", definition: "nguyên liệu, thành phần", example: "Fresh ingredients make a difference." },
    { word: "fairly", definition: "khá là / công bằng", example: "The test was fairly difficult." },
    { word: "guarantee", definition: "đảm bảo", example: "We guarantee 100 percent satisfaction." },
    { word: "forward", definition: "chuyển tiếp", example: "Forward the email to the team." },
    { word: "household", definition: "hộ gia đình", example: "The store sells household goods." },
    { word: "industrial", definition: "thuộc về công nghiệp", example: "He is an industrial engineer." },
    { word: "textile", definition: "dệt may", example: "The textile company is expanding." },
    { word: "pharmaceutical", definition: "thuộc về dược phẩm", example: "She works at a pharmaceutical firm." },
    { word: "skilled", definition: "lành nghề", example: "Our skilled tailors are helpful." },
    { word: "details", definition: "chi tiết", example: "Check the brochure for details." },
    { word: "overseas", definition: "nước ngoài", example: "We export products overseas." },
    { word: "vendor", definition: "nhà cung cấp", example: "Contact the vendor for delivery." },
    { word: "timeline", definition: "mốc thời gian / tiến độ", example: "Update the project timeline." },
    { word: "appearance", definition: "ngoại hình / sự xuất hiện", example: "His appearance was expected." },
    { word: "act", definition: "hành động / diễn", example: "The opening act was great." },
    { word: "fill", definition: "lấp đầy", example: "Fill the order immediately." },
    { word: "revised", definition: "đã được chỉnh sửa", example: "The revised plan is ready." },
    { word: "workstation", definition: "trạm làm việc / bàn làm việc", example: "Set up the workstation today." },
    { word: "unpredictability", definition: "sự không thể đoán trước", example: "Market unpredictability is a risk." },
    { word: "in advance", definition: "trước", example: "Book your tickets in advance." },
    { word: "collection", definition: "bộ sưu tập", example: "The museum has a large collection." },
    { word: "positive", definition: "tích cực", example: "The results were positive." },
    { word: "contribution", definition: "sự đóng góp", example: "We value your contribution." },
    { word: "recognize", definition: "nhận ra / công nhận", example: "Recognize the effort of the team." },
    { word: "priority", definition: "sự ưu tiên", example: "Safety is our top priority." },
    { word: "exceptional", definition: "xuất sắc, đặc biệt", example: "The service was exceptional." },
    { word: "criticism", definition: "sự chỉ chỉ trích", example: "The project received minimal criticism." },
    { word: "accurate", definition: "chính xác", example: "Ensure the data is accurate." },
    { word: "outcome", definition: "kết quả", example: "The outcome was successful." },
    { word: "encourage", definition: "khuyến khích", example: "Encourage staff to join the gym." },
    { word: "focus on", definition: "tập trung vào", example: "Focus on the main objectives." },
    { word: "definitely", definition: "chắc chắn", example: "He is definitely the best choice." },
    { word: "entire", definition: "toàn bộ", example: "The entire building is renovated." },
    { word: "knowledgeable", definition: "có kiến thức / am hiểu", example: "She is knowledgeable about the system." },
    { word: "own", definition: "sở hữu", example: "They own a local business." },
    { word: "stock", definition: "hàng tồn kho / cổ phiếu", example: "The stock level is increasing." },
    { word: "illustrator", definition: "người vẽ minh họa", example: "The illustrator designed the logo." },
    { word: "temporary", definition: "tạm thời", example: "It is a temporary solution." },
    { word: "concerned", definition: "lo lắng / quan tâm", example: "The residents are concerned." },
    { word: "statement", definition: "lời tuyên bố / sao kê", example: "Read the monthly statement." },
    { word: "abroad", definition: "ở nước ngoài", example: "He traveled abroad for work." },
    { word: "clarify", definition: "làm rõ", example: "Clarify the new regulations." },
    { word: "resource", definition: "nguồn lực / tài nguyên", example: "Use all available resources." },
    { word: "fertilizer", definition: "phân bón", example: "Regular fertilizer improves growth." },
    { word: "tolerant", definition: "khoan dung", example: "He is a tolerant manager." },
    { word: "irrigation", definition: "sự tưới tiêu", example: "The irrigation system is working." },
    { word: "disruption", definition: "sự gián đoạn", example: "Minimize the disruption." },
    { word: "multiple", definition: "nhiều", example: "There are multiple options." },
    { word: "discover", definition: "khám phá", example: "Discover new markets." },
    { word: "restore", definition: "khôi phục", example: "Restore the old building." },
    { word: "authentic", definition: "xác thực / chính cống", example: "It is an authentic recipe." },
    { word: "recruit", definition: "tuyển dụng", example: "Recruit more staff next year." },
    { word: "challenging", definition: "đầy thách thức", example: "The task was challenging." },
    { word: "unfavorable", definition: "không thuận lợi", example: "The weather was unfavorable." },
    { word: "prospective", definition: "tiềm năng", example: "Meet with prospective clients." },
    { word: "persuade", definition: "thuyết phục", example: "Persuade the board to agree." },
];

const test5_words: VocabItem[] = [
    { word: "Sustainability", definition: "sự bền vững", example: "The company is committed to long-term environmental sustainability." },
    { word: "Ecological", definition: "thuộc về sinh thái", example: "We conduct ecological impact assessments for all new projects." },
    { word: "Renewable", definition: "có thể tái tạo", example: "The factory is powered entirely by renewable energy sources." },
    { word: "Carbon-neutral", definition: "trung hòa carbon", example: "Our goal is to become carbon-neutral by the end of the decade." },
    { word: "Conservation", definition: "sự bảo tồn", example: "Wildlife conservation is a key part of our social responsibility program." },
    { word: "Ethical", definition: "thuộc về đạo đức", example: "We maintain high ethical standards in all our business dealings." },
    { word: "Biodegradable", definition: "có thể phân hủy sinh học", example: "All our packaging is now made from biodegradable materials." },
    { word: "Environmental", definition: "thuộc về môi trường", example: "Environmental regulations are becoming increasingly strict." },
    { word: "Footprint", definition: "dấu chân (sinh thái)", example: "We are actively working to reduce our environmental footprint." },
    { word: "Compliance", definition: "sự tuân thủ", example: "Full compliance with green energy laws is mandatory." },
    { word: "container", definition: "Đồ chứa, thùng chứa", example: "The shipping container is full." },
    { word: "information", definition: "Thông tin", example: "Read the information leaflet." },
    { word: "seal", definition: "Niêm phong / Con dấu", example: "Seal the envelope securely." },
    { word: "rack", definition: "Giá, kệ", example: "Place the files on the rack." },
    { word: "crowded", definition: "Đông đúc", example: "The cafeteria is very crowded." },
    { word: "inspector", definition: "Thanh tra, người kiểm tra", example: "The safety inspector is here." },
    { word: "exterior", definition: "Bên ngoài, ngoại thất", example: "The exterior of the building is nice." },
    { word: "due", definition: "Đến hạn, do bởi", example: "The payment is due today." },
    { word: "bill", definition: "Hóa đơn", example: "Pay the utility bill online." },
    { word: "fund-raising", definition: "Gây quỹ", example: "The fund-raising event was a success." },
    { word: "representative", definition: "Người đại diện", example: "Talk to a customer representative." },
    { word: "promote", definition: "Thăng chức, quảng bá", example: "Promote the new product line." },
    { word: "registration", definition: "Sự đăng ký", example: "Complete the registration form." },
    { word: "quarterly", definition: "Hàng quý", example: "The quarterly report is out." },
    { word: "include", definition: "Bao gồm", example: "The price includes tax." },
    { word: "adjust", definition: "Điều chỉnh", example: "Adjust the temperature." },
    { word: "pitch", definition: "Chào hàng / Bài thuyết trình", example: "He gave a great sales pitch." },
    { word: "analysis", definition: "Sự phân tích", example: "Conduct a data analysis." },
    { word: "greet", definition: "Chào hỏi", example: "Greet the guests at the door." },
    { word: "current", definition: "Hiện tại", example: "The current project is busy." },
    { word: "estimate", definition: "Ước tính / Bảng báo giá", example: "The cost estimate is ready." },
    { word: "contract", definition: "Hợp đồng", example: "Sign the employment contract." },
    { word: "onboarding", definition: "Quy trình nhập môn", example: "The onboarding process takes a day." },
    { word: "institution", definition: "Tổ chức, cơ quan", example: "It's a respected institution." },
    { word: "previous", definition: "Trước đó", example: "The previous manager resigned." },
    { word: "meet", definition: "Gặp gỡ, đáp ứng", example: "Meet the requirements." },
    { word: "supplier", definition: "Nhà cung cấp", example: "Contact the supplier for parts." },
    { word: "target audience", definition: "Khách hàng mục tiêu", example: "Identify your target audience." },
    { word: "develop", definition: "Phát triển", example: "Develop a new strategy." },
    { word: "launch", definition: "Ra mắt, phóng", example: "The product launch is tomorrow." },
    { word: "challenge", definition: "Thử thách", example: "Market volatility is a challenge." },
    { word: "doubtful", definition: "Nghi ngờ, không chắc chắn", example: "The outcome is doubtful." },
    { word: "suggestion", definition: "Lời đề nghị, sự gợi ý", example: "I have a suggestion for the plan." },
    { word: "associate", definition: "Liên kết / Cộng sự", example: "He is a sales associate." },
    { word: "highlight", definition: "Làm nổi bật / Điểm nổi bật", example: "Highlight the key points." },
    { word: "catch up", definition: "Bắt kịp, cập nhật", example: "Let's catch up over coffee." },
    { word: "organization", definition: "Tổ chức, sự sắp xếp", example: "The organization is efficient." },
    { word: "miss", definition: "Bỏ lỡ, nhớ", example: "I missed the flight." },
    { word: "avoid", definition: "Tránh", example: "Avoid unnecessary delays." },
    { word: "bid", definition: "Giá thầu / Đấu thầu", example: "Submit a bid for the project." },
    { word: "renovate", definition: "Cải tạo, tân trang", example: "Renovate the old office." },
    { word: "compile", definition: "Biên soạn, tổng hợp", example: "Compile the sales data." },
    { word: "comment", definition: "Bình luận, nhận xét", example: "Any comments on the proposal?" },
    { word: "recurring", definition: "Định kỳ, lặp lại", example: "This is a recurring order." },
    { word: "complaint", definition: "Lời phàn nàn", example: "Handle the customer complaint." },
    { word: "enlarge", definition: "Phóng to, mở rộng", example: "Enlarge the image." },
    { word: "take down", definition: "Ghi chép lại, tháo dỡ", example: "Take down the signs." },
    { word: "reception", definition: "Quầy lễ tân, sự tiếp đón", example: "The reception is in the lobby." },
    { word: "recycling", definition: "Sự tái chế", example: "The recycling program is good." },
    { word: "recent", definition: "Gần đây", example: "Check the recent news." },
    { word: "match", definition: "Phù hợp, khớp", example: "The color doesn't match." },
    { word: "management", definition: "Ban quản lý, sự quản lý", example: "Management approved the budget." },
    { word: "progress", definition: "Tiến độ, sự tiến bộ", example: "Track your progress online." },
    { word: "expedite", definition: "Xúc tiến, đẩy nhanh", example: "Expedite the shipping." },
    { word: "explain", definition: "Giải thích", example: "Explain the new policy." },
    { word: "attempt", definition: "Cố gắng / Sự nỗ lực", example: "I made an attempt to finish." },
    { word: "resolve", definition: "Giải quyết", example: "Resolve the issue quickly." },
    { word: "assemble", definition: "Lắp ráp, tập hợp", example: "Assemble the furniture." },
    { word: "attract", definition: "Thu hút", example: "Attract more customers." },
    { word: "summary", definition: "Tóm tắt", example: "Read the report summary." },
    { word: "trim", definition: "Cắt tỉa", example: "Trim the bushes." },
    { word: "figure", definition: "Số liệu, nhân vật", example: "The sales figures are up." },
    { word: "branch", definition: "Chi nhánh", example: "The bank branch is closed." },
    { word: "achieve", definition: "Đạt được", example: "Achieve your goals." },
    { word: "certification", definition: "Giấy chứng nhận", example: "The certification is required." },
    { word: "submission", definition: "Sự nộp, bài nộp", example: "Wait for the submission." },
    { word: "emphasize", definition: "Nhấn mạnh", example: "Emphasize the importance." },
    { word: "designated", definition: "Được chỉ định", example: "Go to your designated spot." },
    { word: "culinary", definition: "Thuộc về nấu nướng", example: "The culinary skills are good." },
    { word: "a variety of", definition: "Nhiều, sự đa dạng", example: "We have a variety of items." },
    { word: "original", definition: "Ban đầu, gốc", example: "It is an original design." },
    { word: "focus", definition: "Tập trung", example: "Focus on the task." },
    { word: "popularity", definition: "Sự phổ biến", example: "The product's popularity is high." },
    { word: "founder", definition: "Người sáng lập", example: "The founder is respected." },
    { word: "outstanding", definition: "Xuất sắc", example: "The performance was outstanding." },
    { word: "lack", definition: "Sự thiếu hụt / Thiếu", example: "A lack of clarity is a problem." },
    { word: "qualified", definition: "Đủ điều kiện", example: "He is a qualified applicant." },
    { word: "applicant", definition: "Ứng viên", example: "Each applicant is vetted." },
    { word: "unique", definition: "Độc nhất", example: "It is a unique opportunity." },
    { word: "income", definition: "Thu nhập", example: "His income has increased." },
];

const test6_words: VocabItem[] = [
    { word: "Distribution", definition: "sự phân phối", example: "The distribution network covers most of Southeast Asia." },
    { word: "Fulfillment", definition: "sự hoàn tất đơn hàng", example: "E-commerce fulfillment centers are operating at maximum capacity." },
    { word: "Inventory", definition: "hàng tồn kho", example: "We use sophisticated software to manage our inventory levels." },
    { word: "Outsourcing", definition: "thuê ngoài", example: "Outsourcing manufacturing has helped reduce production costs." },
    { word: "Supplier", definition: "nhà cung cấp", example: "We maintain close relationships with our primary suppliers." },
    { word: "Transit", definition: "sự vận chuyển, quá cảnh", example: "The goods were damaged while in transit to the customer." },
    { word: "Wholesaler", definition: "nhà bán buôn", example: "The wholesaler offers significant discounts for bulk orders." },
    { word: "Procurement", definition: "sự thu mua", example: "The procurement process has been digitized for better efficiency." },
    { word: "Logistics", definition: "hậu cần", example: "A delay in logistics can cause major supply chain issues." },
    { word: "Shipment", definition: "lô hàng", example: "The final shipment is expected to arrive tomorrow morning." },
    { word: "Repair", definition: "Sửa chữa", example: "I need to repair the device." },
    { word: "Tie", definition: "Buộc, thắt / Cà vạt", example: "Tie the laces of your boots." },
    { word: "Board", definition: "Ban quản trị / Lên tàu", example: "Board the flight now." },
    { word: "Doorway", definition: "Lối cửa ra vào", example: "Standing in the doorway." },
    { word: "Thorough", definition: "Kỹ lưỡng, thấu đáo", example: "The inspection was thorough." },
    { word: "Ship", definition: "Gửi hàng / Tàu thủy", example: "Ship the order today." },
    { word: "Voucher", definition: "Phiếu mua hàng, chứng từ", example: "Use the voucher for a discount." },
    { word: "Signature", definition: "Chữ ký", example: "The signature is required." },
    { word: "Lease", definition: "Hợp đồng thuê / Thuê", example: "The lease expires in June." },
    { word: "Replacement", definition: "Sự thay thế", example: "He is a replacement guide." },
    { word: "Recently", definition: "Gần đây", example: "Recently, sales have increased." },
    { word: "Elect", definition: "Bầu cử", example: "Elect the next leader." },
    { word: "Mayor", definition: "Thị trưởng", example: "The mayor will judge the contest." },
    { word: "Research", definition: "Nghiên cứu", example: "The research is interesting." },
    { word: "Open position", definition: "Vị trí còn trống", example: "Apply for the open position." },
    { word: "Store", definition: "Cửa hàng / Lưu trữ", example: "Store the files securely." },
    { word: "Protocol", definition: "Giao thức, quy định", example: "Follow the safety protocol." },
    { word: "Commercial", definition: "Thuộc thương mại / Quảng cáo", example: "The commercial was popular." },
    { word: "Advertising", definition: "Ngành quảng cáo", example: "The advertising campaign is busy." },
    { word: "Exploration", definition: "Sự thám hiểm, thăm dò", example: "The exploration of the ruin." },
    { word: "Approve", definition: "Chấp thuận, phê duyệt", example: "Approve the budget cuts." },
    { word: "Exit", definition: "Lối ra / Rời khỏi", example: "Exit the building immediately." },
    { word: "Landscaping", definition: "Cảnh quan sân vườn", example: "The landscaping is beautiful." },
    { word: "Reminder", definition: "Lời nhắc nhở", example: "This is a payment reminder." },
    { word: "Vote", definition: "Bỏ phiếu / Lá phiếu", example: "Your vote affects the election." },
    { word: "Deserve", definition: "Xứng đáng", example: "We deserved the retreat." },
    { word: "Honor", definition: "Danh dự / Vinh danh", example: "The dinner is to honor him." },
    { word: "Attention", definition: "Sự chú ý", example: "Pay close attention." },
    { word: "Celebrate", definition: "Ăn mừng, kỷ niệm", example: "Celebrate the anniversary." },
    { word: "Facility", definition: "Cơ sở vật chất", example: "The facility is state-of-the-art." },
    { word: "List", definition: "Danh sách / Liệt kê", example: "Check the list in the hall." },
    { word: "Coworker", definition: "Đồng nghiệp", example: "Help your coworker." },
    { word: "Abstract", definition: "Trừu tượng / Tóm tắt", example: "The abstract is concise." },
    { word: "Pack", definition: "Đóng gói", example: "Pack the items carefully." },
    { word: "Cover", definition: "Che phủ, bao gồm / Trang bìa", example: "The report is covered." },
    { word: "Funding", definition: "Kinh phí, quỹ", example: "We need more funding." },
    { word: "Resident", definition: "Cư dân", example: "The residents are happy." },
    { word: "Expansion", definition: "Sự mở rộng", example: "The expansion is on schedule." },
    { word: "Initiative", definition: "Sáng kiến, thế chủ động", example: "The new initiative is good." },
    { word: "Inquire", definition: "Hỏi thăm, điều tra", example: "Inquire about the vacancy." },
    { word: "Specifications", definition: "Thông số kỹ thuật", example: "Read the specifications." },
    { word: "Source", definition: "Nguồn / Tìm nguồn cung", example: "The source is reliable." },
    { word: "Mechanic", definition: "Thợ máy", example: "The mechanic fixed the car." },
    { word: "Accountant", definition: "Kế toán viên", example: "The accountant is busy." },
    { word: "Expedition", definition: "Cuộc thám hiểm, chuyến đi", example: "The expedition was long." },
    { word: "Overnight", definition: "Qua đêm", example: "Stay overnight." },
    { word: "Rent", definition: "Thuê / Tiền thuê", example: "Rent an office room." },
    { word: "Disagree", definition: "Không đồng ý", example: "Some colleagues disagree." },
    { word: "Route", definition: "Tuyến đường, lộ trình", example: "Follow the usual route." },
    { word: "Coordinator", definition: "Điều phối viên", example: "Talk to the coordinator." },
    { word: "Freezing", definition: "Lạnh cóng, đóng băng", example: "The temperature is freezing." },
    { word: "Temperature", definition: "Nhiệt độ", example: "The temperature is dropping." },
    { word: "Fabric", definition: "Vải", example: "The fabric is soft." },
    { word: "Translate", definition: "Dịch", example: "Translate the document." },
    { word: "Rush", definition: "Vội vã / Giờ cao điểm", example: "There's no rush." },
    { word: "Unusually", definition: "Một cách bất thường", example: "It is unusually hot." },
    { word: "Additional", definition: "Bổ sung, thêm", example: "Need additional help." },
    { word: "Day off", definition: "Ngày nghỉ", example: "Today is my day off." },
    { word: "Contain", definition: "Chứa đựng", example: "The box contains tools." },
    { word: "Anniversary", definition: "Lễ kỷ niệm", example: "It is our anniversary." },
    { word: "Banquet", definition: "Bữa tiệc lớn", example: "The banquet is at six." },
    { word: "Announcement", definition: "Thông báo", example: "Listen to the announcement." },
    { word: "Host", definition: "Chủ nhà / Đăng cai, tổ chức", example: "Host the fair this weekend." },
    { word: "Destination", definition: "Điểm đến", example: "What is your destination?" },
    { word: "Accommodate", definition: "Cung cấp chỗ ở, đáp ứng", example: "We can accommodate you." },
    { word: "Exhibit", definition: "Triển lãm / Vật trưng bày", example: "The exhibit is free." },
    { word: "Claim", definition: "Khẳng định, yêu cầu bồi thường", example: "Claim the luggage." },
    { word: "Term", definition: "Nhiệm kỳ, điều khoản, thuật ngữ", example: "Read the term of service." },
    { word: "Professional", definition: "Chuyên nghiệp / Chuyên gia", example: "He is very professional." },
    { word: "Inaccurate", definition: "Không chính xác", example: "The report is inaccurate." },
    { word: "Profession", definition: "Nghề nghiệp", example: "What is your profession?" },
    { word: "Definition", definition: "Định nghĩa", example: "Look up the definition." },
    { word: "Managerial", definition: "Thuộc quản lý", example: "He has managerial experience." },
    { word: "Supervisor", definition: "Người giám sát", example: "The supervisor is helpful." },
    { word: "Consumer", definition: "Người tiêu dùng", example: "Consumer behavior is changing." },
    { word: "Distribute", definition: "Phân phối", example: "Distribute the brochures." },
    { word: "Transport", definition: "Vận chuyển / Giao thông", example: "Transport the goods." },
    { word: "Afford", definition: "Đủ khả năng chi trả", example: "We can afford it." },
    { word: "Restoration", definition: "Sự phục hồi, trùng tu", example: "The restoration is significant." },
    { word: "Shortage", definition: "Sự thiếu hụt", example: "There is a shortage of staff." },
];

const test7_words: VocabItem[] = [
    { word: "Cybersecurity", definition: "an ninh mạng", example: "Investing in cybersecurity is a top priority for modern firms." },
    { word: "Encryption", definition: "mã hóa", example: "Data encryption ensures that sensitive information remains private." },
    { word: "Software", definition: "phần mềm", example: "The latest software update fixed several security vulnerabilities." },
    { word: "Modernization", definition: "sự hiện đại hóa", example: "The modernization of our IT infrastructure is nearly complete." },
    { word: "Transformation", definition: "sự chuyển đổi", example: "Digital transformation has changed how we interact with clients." },
    { word: "Privacy", definition: "quyền riêng tư", example: "We take customer data privacy very seriously." },
    { word: "Cloud", definition: "điện toán đámây", example: "Moving our files to the cloud has improved accessibility." },
    { word: "Network", definition: "mạng lưới", example: "The company network is protected by advanced firewalls." },
    { word: "Hardware", definition: "phần cứng", example: "The technical team is upgrading the server hardware this weekend." },
    { word: "Accessibility", definition: "khả năng tiếp cận", example: "The new app design focuses on accessibility for all users." },
    { word: "garage", definition: "Nhà để xe, ga-ra", example: "Park the car in the garage." },
    { word: "liquid", definition: "Chất lỏng", example: "Wipe off the liquid spill." },
    { word: "bulletin board", definition: "Bảng tin", example: "Check the bulletin board." },
    { word: "occupied", definition: "Đang sử dụng, bận rộn", example: "The room is occupied." },
    { word: "committee", definition: "Ủy ban, hội đồng", example: "The committee met today." },
    { word: "layover", definition: "Thời gian nghỉ (khi bay)", example: "I have a long layover." },
    { word: "astronomy", definition: "Thiên văn học", example: "He studied astronomy." },
    { word: "astronaut", definition: "Phi hành gia", example: "The astronaut is in training." },
    { word: "fit", definition: "Vừa vặn, phù hợp", example: "The shoes fit nicely." },
    { word: "cookware", definition: "Dụng cụ nấu ăn", example: "The cookware is on sale." },
    { word: "agreement", definition: "Hợp đồng, sự đồng ý", example: "Sign the agreement." },
    { word: "supervise", definition: "Giám sát, quản lý", example: "She will supervise the team." },
    { word: "forecast", definition: "Dự báo", example: "Check the weather forecast." },
    { word: "depart", definition: "Khởi hành", example: "The flight will depart soon." },
    { word: "short-staffed", definition: "Thiếu nhân sự", example: "The clinic is short-staffed." },
    { word: "storefront", definition: "Mặt tiền cửa hàng", example: "The storefront is attractive." },
    { word: "vacant", definition: "Trống, bỏ không", example: "The room is vacant." },
    { word: "analyze", definition: "Phân tích", example: "Analyze the sales data." },
    { word: "demonstrate", definition: "Chứng minh, làm mẫu", example: "Demonstrate the system." },
    { word: "itinerary", definition: "Lịch trình chuyến đi", example: "Follow the itinerary." },
    { word: "realize", definition: "Nhận ra", example: "I didn't realize the time." },
    { word: "distracting", definition: "Gây mất tập trung", example: "The noise is distracting." },
    { word: "flavor", definition: "Hương vị", example: "Try the new flavor." },
    { word: "expert", definition: "Chuyên gia", example: "He is an expert researcher." },
    { word: "extension", definition: "Sự gia hạn, máy nhánh", example: "Request an extension." },
    { word: "overtime", definition: "Làm thêm giờ", example: "Work overtime today." },
    { word: "exchange", definition: "Trao đổi", example: "Exchange your tickets." },
    { word: "receipt", definition: "Hóa đơn, biên lai", example: "Keep your receipt." },
    { word: "ancient", definition: "Cổ đại, xưa", example: "Study ancient cultures." },
    { word: "civilization", definition: "Nền văn minh", example: "The ancient civilization was vast." },
    { word: "last-minute", definition: "Phút chót", example: "A last-minute switch." },
    { word: "expertise", definition: "Chuyên môn", example: "She has great expertise." },
    { word: "memorable", definition: "Đáng nhớ", example: "The event was memorable." },
    { word: "immediately", definition: "Ngay lập tức", example: "Land immediately." },
    { word: "fair", definition: "Công bằng / Hội chợ", example: "Go to the job fair." },
    { word: "demolition", definition: "Sự phá dỡ", example: "The demolition is scheduled." },
    { word: "involvement", definition: "Sự tham gia/liên quan", example: "Community involvement is high." },
    { word: "invest", definition: "Đầu tư", example: "Invest in new technology." },
    { word: "substantial", definition: "Đáng kể", example: "A substantial harvest." },
    { word: "press", definition: "Báo chí / Nhấn", example: "Press the button." },
    { word: "improve", definition: "Cải thiện", example: "Improve the productivity." },
    { word: "partial", definition: "Một phần", example: "A partial list of rules." },
    { word: "motivate", definition: "Thúc đẩy, tạo động lực", example: "Motivate the students." },
    { word: "reassurance", definition: "Sự trấn an", example: "He needs some reassurance." },
    { word: "misunderstanding", definition: "Sự hiểu lầm", example: "A common misunderstanding." },
    { word: "specific", definition: "Cụ thể", example: "Be specific in your report." },
    { word: "guideline", definition: "Nguyên tắc chỉ đạo", example: "Follow the guidelines." },
    { word: "practical", definition: "Thực tế", example: "Provide practical tips." },
    { word: "disposal", definition: "Sự vứt bỏ / Sự tùy ý sử dụng", example: "Correct disposal of rác." },
    { word: "determine", definition: "Xác định, quyết định", example: "Determine the cause." },
    { word: "protective", definition: "Mang tính bảo vệ", example: "Wear protective gear." },
    { word: "represent", definition: "Đại diện", example: "Represent the company." },
    { word: "approach", definition: "Tiếp cận / Cách thức", example: "A new approach to sales." },
    { word: "yield", definition: "Mang lại / Sản lượng", example: "Yield a good result." },
    { word: "assembly", definition: "Sự lắp ráp / Hội đồng", example: "The assembly is busy." },
    { word: "authorize", definition: "Ủy quyền, cho phép", example: "Authorize the expenditure." },
    { word: "margin", definition: "Biên độ (lợi nhuận), lề", example: "A small profit margin." },
    { word: "adjustment", definition: "Sự điều chỉnh", example: "A minor adjustment." },
    { word: "broadcast", definition: "Phát sóng", example: "Broadcast the news live." },
    { word: "present", definition: "Trình bày", example: "Present the findings." },
    { word: "certainly", definition: "Chắc chắn", example: "Certainly, I can help." },
    { word: "policy", definition: "Chính sách", example: "Review the policy manual." },
    { word: "achievement", definition: "Thành tựu", example: "A great achievement." },
    { word: "feedback", definition: "Phản hồi, ý kiến", example: "We appreciate your feedback." },
    { word: "excuse", definition: "Lời bào chữa / Tha lỗi", example: "Pardon my excuse." },
    { word: "disappointment", definition: "Sự thất vọng", example: "It was a disappointment." },
    { word: "aboard", definition: "Trên tàu/xe", example: "Welcome aboard!" },
    { word: "renowned", definition: "Nổi tiếng", example: "He is a renowned author." },
    { word: "inconvenience", definition: "Sự bất tiện", example: "Sorry for the inconvenience." },
    { word: "architectural", definition: "(Thuộc) kiến trúc", example: "Study architectural features." },
    { word: "landmark", definition: "Địa danh, mốc", example: "A major landmark." },
    { word: "connection", definition: "Sự kết nối", example: "Strong connection is vital." },
    { word: "express", definition: "Bày tỏ / Tốc hành", example: "Express your opinion." },
    { word: "caution", definition: "Sự thận trọng", example: "Use caution." },
    { word: "conservation", definition: "Sự bảo tồn", example: "Environmental conservation is key." },
    { word: "catering", definition: "Dịch vụ ăn uống", example: "The catering service is good." },
    { word: "urban", definition: "Thuộc thành thị", example: "An urban apartment." },
    { word: "suburban", definition: "Thuộc ngoại ô", example: "A suburban area." },
    { word: "rating", definition: "Xếp hạng, đánh giá", example: "The rating is high." },
    { word: "organization", definition: "Tổ chức", example: "It is a global organization." },
];

const test8_words: VocabItem[] = [
    { word: "Diversity", definition: "sự đa dạng", example: "We celebrate diversity in our global workforce." },
    { word: "Inclusion", definition: "sự hòa nhập", example: "The company policy promotes a culture of inclusion and respect." },
    { word: "Equity", definition: "sự công bằng", example: "Pay equity is a fundamental goal of our HR department." },
    { word: "Representation", definition: "sự đại diện", example: "We are working to improve representation in leadership roles." },
    { word: "Bias", definition: "thành kiến", example: "Training helps employees recognize and reduce unconscious bias." },
    { word: "Multicultural", definition: "đa văn hóa", example: "We operate in a multicultural environment across thirty countries." },
    { word: "Policy", definition: "chính sách", example: "The updated policy ensures fair treatment for all candidates." },
    { word: "Mentorship", definition: "sự cố vấn", example: "The mentorship program pairs junior staff with senior executives." },
    { word: "Leadership", definition: "khả năng lãnh đạo", example: "Strong leadership is key during periods of rapid change." },
    { word: "Culture", definition: "văn hóa công ty", example: "Employee satisfaction is a major part of our corporate culture." },
    { word: "Flowerpot", definition: "Chậu hoa", example: "The flowerpot is on the patio." },
    { word: "Rug", definition: "Tấm thảm (nhỏ)", example: "The rug is rolled up." },
    { word: "Covered", definition: "Có mái che / Được bao phủ", example: "The patio is covered." },
    { word: "Patio", definition: "Sân hiên", example: "Sit outdoors on the patio." },
    { word: "Intersection", definition: "Giao lộ / Ngã tư", example: "Turn left at the intersection." },
    { word: "Flyer", definition: "Tờ rơi", example: "Distribute the flyers around." },
    { word: "Ceiling", definition: "Trần nhà", example: "The light fixture is suspended." },
    { word: "Unload", definition: "Dỡ hàng", example: "Unload the supplies." },
    { word: "Climb", definition: "Leo trèo / Tăng lên", example: "Climb the ladder carefully." },
    { word: "Rake", definition: "Cái cào / Cào", example: "Rake the leaves today." },
    { word: "Alert", definition: "Cảnh giác / Báo động", example: "Set a custom alert." },
    { word: "Agenda", definition: "Chương trình nghị sự", example: "Check the meeting agenda." },
    { word: "Informational", definition: "Cung cấp thông tin", example: "An informational seminar." },
    { word: "Satisfaction", definition: "Sự hài lòng", example: "Employee satisfaction is high." },
    { word: "Predict", definition: "Dự đoán", example: "Predict rising costs." },
    { word: "Assignment", definition: "Nhiệm vụ / Bài tập", example: "Complete the assignment." },
    { word: "Productive", definition: "Có năng suất / Hiệu quả", example: "Be more productive." },
    { word: "Comfortable", definition: "Thoải mái", example: "The hotel is comfortable." },
    { word: "Laboratory", definition: "Phòng thí nghiệm", example: "Work in the laboratory." },
    { word: "Worth", definition: "Đáng giá / Giá trị", example: "It is worth the extra cost." },
    { word: "Apply", definition: "Nộp đơn / Áp dụng", example: "Apply the new policy." },
    { word: "Calculate", definition: "Tính toán", example: "Calculate the total cost." },
    { word: "Degree", definition: "Bằng cấp / Độ", example: "He has a university degree." },
    { word: "Monitor", definition: "Giám sát / Màn hình", example: "Monitor the machinery." },
    { word: "Incomplete", definition: "Chưa hoàn thành / Thiếu", example: "The form is incomplete." },
    { word: "Insufficient", definition: "Không đủ", example: "The funding is insufficient." },
    { word: "Equipment", definition: "Thiết bị", example: "The equipment is broken." },
    { word: "Rare", definition: "Hiếm", example: "It's a rare opportunity." },
    { word: "Practice", definition: "Luyện tập / Thực tiễn", example: "Practice your pronunciation." },
    { word: "Publicity", definition: "Sự quảng bá / Dư luận", example: "The publicity campaign is good." },
    { word: "Wing", definition: "Cánh (nhà, chim)", example: "The new wing is open." },
    { word: "City hall", definition: "Tòa thị chính", example: "Go to city hall for permits." },
    { word: "Create", definition: "Tạo ra", example: "Create a new design." },
    { word: "Official", definition: "Chính thức / Quan chức", example: "An official statement." },
    { word: "Construction", definition: "Xây dựng", example: "Under construction now." },
    { word: "Soil", definition: "Đất trồng", example: "Put soil in the bag." },
    { word: "Agriculture", definition: "Nông nghiệp", example: "Study agriculture at university." },
    { word: "Curious", definition: "Tò mò", example: "He is a curious student." },
    { word: "Improvement", definition: "Sự cải thiện", example: "A major improvement." },
    { word: "Script", definition: "Kịch bản", example: "Read the audio script." },
    { word: "Episode", definition: "Tập (phim)", example: "Watch the latest episode." },
    { word: "Performer", definition: "Người biểu diễn", example: "The performer was great." },
    { word: "Outdoor", definition: "Ngoài trời", example: "Hold an outdoor event." },
    { word: "Flat rate", definition: "Mức phí cố định", example: "Pay a flat rate." },
    { word: "Varied", definition: "Đa dạng", example: "We have varied options." },
    { word: "Machinery", definition: "Máy móc (nói chung)", example: "Inspect the machinery." },
    { word: "Automated", definition: "Tự động hóa", example: "An automated system." },
    { word: "Transplant", definition: "Cấy ghép / Di dời", example: "Transplant the trees." },
    { word: "Handle", definition: "Xử lý / Tay cầm", example: "Handle the details." },
    { word: "Amazement", definition: "Sự kinh ngạc", example: "In total amazement." },
    { word: "Inclement weather", definition: "Thời tiết khắc nghiệt", example: "Due to inclement weather." },
    { word: "Doubt", definition: "Nghi ngờ", example: "Without a doubt." },
    { word: "Organizer", definition: "Người tổ chức", example: "He is the organizer." },
    { word: "Rebook", definition: "Đặt lại (vé, lịch)", example: "I need to rebook my flight." },
    { word: "Misinformation", definition: "Thông tin sai lệch", example: "Avoid misinformation." },
    { word: "Compliment", definition: "Lời khen / Khen ngợi", example: "Give him a compliment." },
    { word: "Pillow", definition: "Cái gối", example: "Rearrange the pillows." },
    { word: "Assist", definition: "Hỗ trợ", example: "Assist her with the files." },
    { word: "Position", definition: "Vị trí / Chức vụ", example: "Apply for the position." },
    { word: "Firm", definition: "Công ty / Chắc chắn", example: "Work for a legal firm." },
    { word: "Pain", definition: "Cơn đau", example: "He is in pain." },
    { word: "Objection", definition: "Sự phản đối", example: "He has no objection." },
    { word: "Paperwork", definition: "Thủ tục giấy tờ", example: "Complete the paperwork." },
    { word: "Autonomous", definition: "Tự chủ / Tự trị", example: "An autonomous division." },
    { word: "Remotely", definition: "Từ xa", example: "Work remotely on Tuesdays." },
    { word: "Operate", definition: "Vận hành / Hoạt động", example: "Operate the machine." },
    { word: "Maintain", definition: "Duy trì / Bảo trì", example: "Maintain the system." },
    { word: "Administer", definition: "Quản lý / Cung cấp (thuốc)", example: "Administer the survey." },
    { word: "Compliance", definition: "Sự tuân thủ", example: "In compliance with rules." },
    { word: "Primarily", definition: "Chủ yếu", example: "Primarily for tourists." },
    { word: "Exceed", definition: "Vượt quá", example: "Exceed the budget." },
    { word: "Standard", definition: "Tiêu chuẩn", example: "Set a high standard." },
    { word: "Responsibility", definition: "Trách nhiệm", example: "It is your responsibility." },
    { word: "Respond", definition: "Phản hồi", example: "Respond by Friday." },
    { word: "Control", definition: "Kiểm soát", example: "Control the temperature." },
    { word: "Allow", definition: "Cho phép", example: "Allow for extra time." },
    { word: "Clinical", definition: "Lâm sàng / Lạnh lùng", example: "Clinical research studies." },
    { word: "Alternative", definition: "Sự thay thế / Khác", example: "An alternative route." },
    { word: "Bulk", definition: "Số lượng lớn", example: "Purchase in bulk." },
    { word: "Officially", definition: "Một cách chính thức", example: "Officially signed today." },
];

const test9_words: VocabItem[] = [
    { word: "Strategy", definition: "chiến lược", example: "The marketing strategy focuses on social media engagement." },
    { word: "Branding", definition: "xây dựng thương hiệu", example: "Branding is essential for building long-term customer loyalty." },
    { word: "Demographic", definition: "nhân khẩu học", example: "Our target demographic is young professionals in urban areas." },
    { word: "Consumer", definition: "người tiêu dùng", example: "Consumer behavior has shifted significantly toward online shopping." },
    { word: "Promotion", definition: "khuyến mãi/thăng tiến", example: "The seasonal promotion led to a major spike in sales." },
    { word: "Research", definition: "nghiên cứu", example: "Thorough market research is required before any product launch." },
    { word: "Analytics", definition: "phân tích", example: "Marketing analytics show that video content has the highest reach." },
    { word: "Reach", definition: "tiếp cận", example: "The new ad campaign reached over a million potential customers." },
    { word: "Campaign", definition: "chiến dịch", example: "The charity campaign raised significant funds for local schools." },
    { word: "Brand", definition: "thương hiệu", example: "Our brand is known for quality and innovation." },
    { word: "shade", definition: "Bóng râm, tông màu", example: "The patio has a lot of shade." },
    { word: "bin", definition: "Thùng chứa (rác)", example: "Put rác in the bin." },
    { word: "frame", definition: "Khung (ảnh, cửa)", example: "Frame a wedding picture." },
    { word: "dentist", definition: "Nha sĩ", example: "Appointment with the dentist." },
    { word: "groceries", definition: "Thực phẩm, tạp hóa", example: "Scan the groceries." },
    { word: "select", definition: "Chọn lựa", example: "Select your own gift." },
    { word: "payroll", definition: "Bảng lương", example: "Process the payroll." },
    { word: "damaged", definition: "Bị hư hại", example: "The box was damaged." },
    { word: "purchase", definition: "Mua", example: "Purchase office supplies." },
    { word: "pass", definition: "Vượt qua, đưa cho", example: "Pass out the handouts." },
    { word: "athletic", definition: "(Thuộc) thể thao, khỏe khoắn", example: "An athletic apparel company." },
    { word: "question", definition: "Câu hỏi", example: "A question about the hotel." },
    { word: "treatment", definition: "Sự điều trị, sự đối xử", example: "Receive advanced skin-care treatment." },
    { word: "personalized", definition: "Cá nhân hóa", example: "Personalized room layout plan." },
    { word: "nutrition", definition: "Dinh dưỡng", example: "Eat nutritious foods." },
    { word: "previously", definition: "Trước đây", example: "Previously, he was a driver." },
    { word: "sanitize", definition: "Khử trùng, làm sạch", example: "Sanitize the preparation area." },
    { word: "sourcing", definition: "Tìm nguồn cung ứng", example: "Sourcing ingredients locally." },
    { word: "consideration", definition: "Sự cân nhắc", example: "Special consideration for groups." },
    { word: "cleanliness", definition: "Sự sạch sẽ", example: "Prioritize cleanliness." },
    { word: "attendance", definition: "Sự tham dự, điểm danh", example: "Attendance at the fair." },
    { word: "attractive", definition: "Hấp dẫn, lôi cuốn", example: "An attractive place to live." },
    { word: "inadequate", definition: "Không đủ, thiếu sót", example: "Inadequate shelf space." },
    { word: "reassign", definition: "Phân công lại", example: "Reassign the task." },
    { word: "publish", definition: "Xuất bản, công bố", example: "Publish the results." },
    { word: "retire", definition: "Nghỉ hưu", example: "Retire next month." },
    { word: "opening", definition: "Lễ khai trương, chỗ trống", example: "A job opening in Sales." },
    { word: "intensive", definition: "Chuyên sâu, cấp tốc", example: "An intensive training course." },
    { word: "encouragement", definition: "Sự khích lệ", example: "Give him some encouragement." },
    { word: "praise", definition: "Khen ngợi", example: "Praise the research team." },
    { word: "decision", definition: "Quyết định", example: "A hiring decision." },
    { word: "intrigued", definition: "Hứng thú, tò mò", example: "I am intrigued by the idea." },
    { word: "shred", definition: "Cắt nhỏ, xé nhỏ", example: "Shred the old documents." },
    { word: "discarded", definition: "Bị loại bỏ", example: "Discarded tree branches." },
    { word: "watery", definition: "Lỏng, như nước", example: "The soup is too watery." },
    { word: "mixture", definition: "Hỗn hợp", example: "A special soil mixture." },
    { word: "unnecessary", definition: "Không cần thiết", example: "Avoid unnecessary delays." },
    { word: "leftover", definition: "Thức ăn thừa", example: "Eat the leftover pie." },
    { word: "eventually", definition: "Cuối cùng thì", example: "Eventually, she was promoted." },
    { word: "decrease", definition: "Giảm xuống", example: "Decrease overall costs." },
    { word: "morale", definition: "Tinh thần, nhuệ khí", example: "Boost employee morale." },
    { word: "acquire", definition: "Đạt được, thu được", example: "Acquire the property." },
    { word: "adopt", definition: "Thông qua, nhận nuôi", example: "Adopt a new approach." },
    { word: "confident", definition: "Tự tin", example: "He is a confident speaker." },
    { word: "presence", definition: "Sự hiện diện", example: "Increase online presence." },
    { word: "spokesperson", definition: "Người phát ngôn", example: "The company spokesperson." },
    { word: "limited", definition: "Có hạn, hạn chế", example: "Space is limited." },
    { word: "availability", definition: "Sự có sẵn, khả năng đáp ứng", example: "Check the availability." },
    { word: "relevant", definition: "Liên quan, thích hợp", example: "Provide relevant details." },
    { word: "retrieve", definition: "Lấy lại, khôi phục", example: "Retrieve the audio files." },
    { word: "traditional", definition: "Truyền thống", example: "An authentic traditional recipe." },
    { word: "unusual", definition: "Bất thường, lạ", example: "It is unusual weather." },
    { word: "contemporary", definition: "Đương đại", example: "A contemporary design." },
    { word: "inspiration", definition: "Nguồn cảm hứng", example: "He is an inspiration." },
    { word: "combine", definition: "Kết hợp", example: "Combine the ingredients." },
    { word: "recipe", definition: "Công thức (nấu ăn)", example: "Follow the recipe." },
    { word: "intend", definition: "Có ý định", example: "I intend to sell." },
    { word: "measure", definition: "Đo lường", example: "Measure the windows." },
    { word: "method", definition: "Phương pháp", example: "Choose the best method." },
    { word: "sustainable", definition: "Bền vững", example: "A sustainable power plant." },
    { word: "ongoing", definition: "Đang diễn ra", example: "An ongoing commitment." },
    { word: "admission", definition: "Sự nhận vào, phí vào cửa", example: "Free admission today." },
    { word: "sturdy", definition: "Cứng cáp, bền", example: "The backpacks are sturdy." },
    { word: "promotion", definition: "Sự thăng chức, khuyến mãi", example: "A seasonal promotion." },
    { word: "refer", definition: "Tham khảo, đề cập", example: "Refer to the manual." },
    { word: "obtain", definition: "Đạt được, lấy được", example: "Obtain a permit." },
    { word: "belongings", definition: "Đồ dùng cá nhân", example: "Keep your belongings safe." },
    { word: "exclusive", definition: "Độc quyền, riêng biệt", example: "An exclusive travellers' lounge." },
    { word: "register", definition: "Đăng ký", example: "Register online in advance." },
    { word: "enrollment", definition: "Sự ghi danh, tuyển sinh", example: "Enrollment has increased." },
    { word: "form", definition: "Mẫu đơn, hình thức", example: "Complete the online form." },
    { word: "exercise", definition: "Bài tập, sự tập luyện", example: "Perform a group task." },
    { word: "installation", definition: "Sự lắp đặt", example: "Installation will take an hour." },
    { word: "lane", definition: "Làn đường", example: "Close off multiple lanes." },
    { word: "publication", definition: "Ấn phẩm, sự xuất bản", example: "The publication date is July 9." },
    { word: "immediate", definition: "Ngay lập tức", example: "Take immediate action." },
    { word: "comprehensive", definition: "Toàn diện", example: "A comprehensive report." },
    { word: "handbook", definition: "Sổ tay hướng dẫn", example: "Check the employee handbook." },
    { word: "procedure", definition: "Quy trình, thủ tục", example: "Follow the standard procedure." },
    { word: "pursue", definition: "Theo đuổi", example: "Pursue a career in art." },
];

const test10_words: VocabItem[] = [
    { word: "Audit", definition: "kiểm toán", example: "An external audit is conducted every fiscal year." },
    { word: "Transparency", definition: "sự minh bạch", example: "Financial transparency builds trust with our shareholders." },
    { word: "Statement", definition: "báo cáo tài chính", example: "The quarterly financial statement showed a 5% increase in profits." },
    { word: "Fiscal", definition: "thuộc tài chính/ngân khố", example: "The fiscal year ends on December 31." },
    { word: "Budget", definition: "ngân sách", example: "We must stay within the allocated budget for the marketing project." },
    { word: "Liability", definition: "trách nhiệm pháp lý/nợ", example: "The firm is not liable for any losses due to market volatility." },
    { word: "Asset", definition: "tài sản", example: "Human capital is considered our company's greatest asset." },
    { word: "Profitability", definition: "khả năng sinh lời", example: "Automation has improved our overall profitability." },
    { word: "Regulation", definition: "quy định", example: "New financial regulations will take effect next month." },
    { word: "Compliance", definition: "sự tuân thủ", example: "Maintaining full compliance with tax laws is essential." },
    { word: "bucket", definition: "Cái xô, thùng", example: "Fill the bucket with water." },
    { word: "stroll", definition: "Đi dạo, tản bộ", example: "Take a stroll in the park." },
    { word: "hand", definition: "Trao, đưa (bằng tay)", example: "Hand the box to the customer." },
    { word: "tow", definition: "Kéo (xe, tàu)", example: "The car was towed away." },
    { word: "dock", definition: "Bến tàu", example: "The boat reached the dock." },
    { word: "shore", definition: "Bờ biển, bờ hồ", example: "Walk along the shore." },
    { word: "downtown", definition: "Khu trung tâm thành phố", example: "Go to the downtown office." },
    { word: "cuisine", definition: "Ẩm thực", example: "Try the local cuisine." },
    { word: "lightweight", definition: "Nhẹ, hạng nhẹ", example: "The camera is lightweight." },
    { word: "sales", definition: "Doanh số, việc bán hàng", example: "Sales are up this quarter." },
    { word: "edit", definition: "Chỉnh sửa, biên tập", example: "Edit the video content." },
    { word: "advanced", definition: "Tiên tiến, cao cấp", example: "Study advanced mathematics." },
    { word: "result", definition: "Kết quả", example: "The result was successful." },
    { word: "pharmacy", definition: "Hiệu thuốc", example: "Go to the pharmacy for medicine." },
    { word: "keynote speech", definition: "Bài phát biểu chủ đạo", example: "Listen to the keynote speech." },
    { word: "inspiring", definition: "Truyền cảm hứng", example: "It was an inspiring talk." },
    { word: "technical", definition: "Thuộc về kỹ thuật", example: "Read the technical manual." },
    { word: "bookkeeping", definition: "Kế toán, giữ sổ sách", example: "Manage the bookkeeping." },
    { word: "luncheon", definition: "Tiệc trưa", example: "Attend the team luncheon." },
    { word: "indoors", definition: "Ở trong nhà", example: "Stay indoors during rain." },
    { word: "outdoors", definition: "Ở ngoài trời", example: "Hold the event outdoors." },
    { word: "retail", definition: "Bán lẻ", example: "Work in the retail industry." },
    { word: "private", definition: "Riêng tư, cá nhân", example: "A private event room." },
    { word: "craft", definition: "Thủ công, nghề thủ công", example: "Study the craft of soapmaking." },
    { word: "fade", definition: "Phai màu, mờ dần", example: "The color will fade in the sun." },
    { word: "custom", definition: "Phong tục / Tùy chỉnh (Adj)", example: "A custom fabric choice." },
    { word: "accidentally", definition: "Tình cờ, ngẫu nhiên", example: "He accidentally skipped a duty." },
    { word: "boarding pass", definition: "Thẻ lên máy bay", example: "Show your boarding pass." },
    { word: "locate", definition: "Xác định vị trí, tìm thấy", example: "Locate the booth." },
    { word: "describe", definition: "Mô tả", example: "Describe the picture." },
    { word: "benefits", definition: "Lợi ích, phúc lợi", example: "Enjoy employee benefits." },
    { word: "walkway", definition: "Lối đi bộ", example: "Clear the debris from the walkway." },
    { word: "durability", definition: "Độ bền", example: "The durability of the material." },
    { word: "anticipate", definition: "Dự đoán, mong đợi", example: "Anticipate market shifts." },
    { word: "negotiation", definition: "Sự đàm phán", example: "The negotiation was long." },
    { word: "passenger", definition: "Hành khách", example: "Attention passengers." },
    { word: "bypass", definition: "Đi vòng qua, phớt lờ", example: "Bypass the traffic." },
    { word: "correction", definition: "Sự sửa chữa, hiệu chỉnh", example: "Make a minor correction." },
    { word: "alternate", definition: "Xen kẽ, thay thế", example: "Take an alternate route." },
    { word: "cause", definition: "Nguyên nhân / Gây ra", example: "What caused the issue?" },
    { word: "attendant", definition: "Người phục vụ/tiếp viên", example: "Ask the flight attendant." },
    { word: "sterile", definition: "Vô trùng, tiệt trùng", example: "The lab environment is sterile." },
    { word: "separate", definition: "Riêng biệt, tách rời", example: "A separate caterer." },
    { word: "radius", definition: "Bán kính, phạm vi", example: "Within a 50-kilometer radius." },
    { word: "proceeds", definition: "Tiền thu được", example: "Proceeds go to charity." },
    { word: "go toward", definition: "Đóng góp vào, hướng tới", example: "Funds go toward repairs." },
    { word: "raffle", definition: "Xổ số (gây quỹ)", example: "Win a prize in the raffle." },
    { word: "donation", definition: "Sự quyên góp", example: "Generous donations help." },
    { word: "drawing", definition: "Sự bốc thăm (hoặc bản vẽ)", example: "Check the pencil drawing." },
    { word: "getaway", definition: "Chuyến đi nghỉ ngắn", example: "A weekend getaway." },
    { word: "arrangement", definition: "Sự sắp xếp", example: "Make an arrangement." },
    { word: "observe", definition: "Quan sát / Tuân thủ", example: "Observe the safety rules." },
    { word: "mark", definition: "Đánh dấu", example: "Mark the calendar." },
    { word: "completion", definition: "Sự hoàn thành", example: "Wait for project completion." },
    { word: "decorative", definition: "Có tính trang trí", example: "Decorative pillows." },
    { word: "harvest", definition: "Mùa gặt / Thu hoạch", example: "The harvest was substantial." },
    { word: "feed", definition: "Cho ăn", example: "Feed the horses." },
    { word: "hands-on", definition: "Thực hành, thực tế", example: "Get hands-on training." },
    { word: "grain", definition: "Ngũ cốc, hạt", example: "Whole grains are healthy." },
    { word: "enable", definition: "Cho phép, kích hoạt", example: "Enable two-step verification." },
    { word: "direct", definition: "Chỉ dẫn / Trực tiếp", example: "Direct the customers." },
    { word: "factor", definition: "Yếu tố", example: "A key factor." },
    { word: "distance", definition: "Khoảng cách", example: "Walking distance is short." },
    { word: "identity", definition: "Danh tính", example: "Show proof of identity." },
    { word: "status", definition: "Trạng thái, địa vị", example: "Check order status." },
    { word: "takeoff", definition: "Sự cất cánh", example: "Prepare for takeoff." },
    { word: "fasten", definition: "Thắt, buộc chặt", example: "Fasten your seatbelt." },
    { word: "overhead", definition: "Ở trên đầu", example: "Use the overhead bin." },
    { word: "compartment", definition: "Ngăn chứa", example: "The luggage compartment." },
    { word: "virtually", definition: "Hầu như, gần như (hoặc ảo)", example: "Virtually every student." },
    { word: "fulfill", definition: "Hoàn thành, đáp ứng", example: "Fulfill the order." },
    { word: "assure", definition: "Đảm bảo, trấn an", example: "I assure you it's safe." },
    { word: "remain", definition: "Còn lại, duy trì", example: "Remain in the room." },
    { word: "showcase", definition: "Trưng bày, phô diễn", example: "Showcase the talent." },
    { word: "talented", definition: "Có tài năng", example: "A talented musician." },
    { word: "enter", definition: "Đi vào, nhập vào", example: "Enter the code." },
    { word: "trend", definition: "Xu hướng", example: "The latest trend." },
    { word: "informal", definition: "Không trang trọng, thân mật", example: "An informal meeting." },
    { word: "inappropriate", definition: "Không phù hợp", example: "An inappropriate comment." },
    { word: "recipient", definition: "Người nhận", example: "Each recipient got a packet." },
];

export const listening2026Vocabulary: VocabularyPart = {
    id: 300,
    title: "Listening 2026",
    description: "Từ vựng Listening TRỌNG ĐIỂM trong năm 2026",
    tests: [
        { id: 3001, title: "Test 1: Corporate Operations", words: test1_words },
        { id: 3002, title: "Test 2: Industry Trends", words: test2_words },
        { id: 3003, title: "Test 3: Remote Work & Flexibility", words: test3_words },
        { id: 3004, title: "Test 4: Technological Integration", words: test4_words },
        { id: 3005, title: "Test 5: Sustainable Practices", words: test5_words },
        { id: 3006, title: "Test 6: Global Supply Chain", words: test6_words },
        { id: 3007, title: "Test 7: Digital Transformation", words: test7_words },
        { id: 3008, title: "Test 8: Diversity & Inclusion", words: test8_words },
        { id: 3009, title: "Test 9: Modern Marketing Strategies", words: test9_words },
        { id: 3010, title: "Test 10: Financial Compliance", words: test10_words },
    ]
};