import { VocabItem, VocabularyPart } from '../../types';

const listening_tong_hop_test_1: VocabItem[] = [
    { word: "Do for a living", definition: "làm nghề gì để sống", example: "" },
    { word: "Assignment", definition: "nhiệm vụ, bài tập", example: "" },
    { word: "Tenant", definition: "người thuê nhà", example: "" },
    { word: "Work order", definition: "phiếu công việc", example: "" },
    { word: "Vendor", definition: "người bán hàng, nhà cung cấp", example: "" },
    { word: "Personnel", definition: "nhân sự, cán bộ", example: "" },
    { word: "Cafeteria", definition: "quán ăn tự phục vụ", example: "" },
    { word: "Manual", definition: "sách hướng dẫn / thủ công", example: "" },
    { word: "Forecast", definition: "dự báo", example: "" },
    { word: "Corridor", definition: "hành lang", example: "" },
    { word: "Turn out", definition: "hóa ra, diễn ra", example: "" },
    { word: "Hike", definition: "sự tăng lên, đi bộ đường dài", example: "" },
    { word: "Boots", definition: "đôi ủng", example: "" },
    { word: "Enjoyable", definition: "thú vị, vui vẻ", example: "" },
    { word: "Make a reservation", definition: "đặt chỗ, đặt bàn", example: "" },
    { word: "Sold out", definition: "bán hết", example: "" },
    { word: "Blender", definition: "máy xay sinh tố", example: "" },
    { word: "Prototype", definition: "nguyên mẫu, mẫu thử", example: "" },
    { word: "Terminal", definition: "nhà ga / cuối cùng", example: "" },
    { word: "Bouquet", definition: "bó hoa", example: "" },
    { word: "Nominate", definition: "đề cử, bổ nhiệm", example: "" },
    { word: "Made a speech", definition: "phát biểu", example: "" },
    { word: "Merchandise", definition: "hàng hóa", example: "" },
    { word: "Prescription", definition: "đơn thuốc", example: "" },
    { word: "Look for", definition: "tìm kiếm", example: "" },
    { word: "Calculate", definition: "tính toán", example: "" },
    { word: "Expense", definition: "chi phí", example: "" },
    { word: "Reimbursement", definition: "sự hoàn trả", example: "" },
    { word: "Receipt", definition: "biên lai", example: "" },
    { word: "Accommodation", definition: "chỗ ở", example: "" },
    { word: "Sales representative", definition: "nhân viên kinh doanh", example: "" },
    { word: "Accurate", definition: "chính xác", example: "" },
    { word: "Follow", definition: "theo dõi, làm theo", example: "" },
    { word: "Authorize", definition: "ủy quyền, cho phép", example: "" },
    { word: "Spreadsheet", definition: "bảng tính", example: "" },
    { word: "Fog", definition: "sương mù", example: "" },
    { word: "Lift", definition: "thang máy / nâng lên", example: "" },
    { word: "Harbor", definition: "bến cảng", example: "" },
    { word: "Deck", definition: "boong tàu, sàn tàu", example: "" },
    { word: "Uneventful", definition: "yên ả, không có biến cố", example: "" },
    { word: "Cargo ship", definition: "tàu chở hàng", example: "" },
    { word: "Behind schedule", definition: "trễ tiến độ", example: "" },
    { word: "Port authority", definition: "cơ quan quản lý cảng", example: "" },
    { word: "Clear", definition: "dọn dẹp / rõ ràng", example: "" },
    { word: "Hospitality", definition: "lòng hiếu khách", example: "" },
    { word: "Meteorology", definition: "khí tượng học", example: "" },
    { word: "Properly", definition: "đúng cách, hợp lý", example: "" },
    { word: "Absent", definition: "vắng mặt", example: "" },
    { word: "Place a call", definition: "gọi điện thoại", example: "" },
    { word: "Seat", definition: "sắp xếp chỗ ngồi", example: "" },
    { word: "Terrace", definition: "sân thượng, hiên", example: "" },
    { word: "Cashier", definition: "nhân viên thu ngân", example: "" },
    { word: "Demonstrate", definition: "trình bày, chứng minh", example: "" },
    { word: "Compact", definition: "nhỏ gọn", example: "" },
    { word: "Tablet", definition: "máy tính bảng, viên thuốc", example: "" },
    { word: "Brochure", definition: "cuốn sách nhỏ quảng cáo", example: "" },
    { word: "Electronics store", definition: "cửa hàng điện tử", example: "" },
    { word: "Contest", definition: "cuộc thi / tranh đấu", example: "" },
    { word: "Concentrate on", definition: "tập trung vào", example: "" },
    { word: "Reduction", definition: "sự giảm", example: "" },
    { word: "Ingredient", definition: "nguyên liệu", example: "" },
    { word: "Similar", definition: "giống, tương tự", example: "" },
    { word: "Investigation", definition: "sự điều tra", example: "" },
    { word: "Find out", definition: "tìm ra", example: "" },
    { word: "Textile", definition: "dệt may, vải", example: "" },
    { word: "Lack of", definition: "thiếu", example: "" },
    { word: "Preference", definition: "sự ưu tiên, thích hơn", example: "" },
    { word: "Negotiate", definition: "đàm phán", example: "" },
    { word: "Expand", definition: "mở rộng", example: "" },
    { word: "Oversee", definition: "giám sát", example: "" },
    { word: "Description", definition: "sự mô tả", example: "" },
    { word: "Revise", definition: "chỉnh sửa, xem lại", example: "" },
    { word: "Flat", definition: "căn hộ / phẳng", example: "" },
    { word: "Be supposed to V", definition: "được cho là, có nhiệm vụ làm gì", example: "" },
    { word: "Catering", definition: "dịch vụ ăn uống", example: "" },
    { word: "Dealership", definition: "đại lý", example: "" },
    { word: "Eventually", definition: "cuối cùng", example: "" },
    { word: "Path", definition: "con đường, lối đi", example: "" },
    { word: "Merge", definition: "hợp nhất", example: "" },
    { word: "Relief", definition: "sự giảm nhẹ, khuây khỏa", example: "" },
    { word: "Initiative", definition: "sáng kiến, sự khởi xướng", example: "" },
    { word: "Doubt", definition: "sự nghi ngờ / nghi ngờ", example: "" },
    { word: "Relocate", definition: "di chuyển, chuyển chỗ", example: "" },
    { word: "Container", definition: "thùng chứa", example: "" },
    { word: "Straw", definition: "ống hút, rơm", example: "" },
    { word: "No longer", definition: "không còn", example: "" },
    { word: "Sculpture", definition: "tác phẩm điêu khắc", example: "" },
    { word: "Reach", definition: "liên hệ, với tới", example: "" },
    { word: "Repave", definition: "lát lại", example: "" },
    { word: "Adjacent", definition: "liền kề", example: "" },
    { word: "Resident", definition: "cư dân", example: "" },
    { word: "Designate", definition: "chỉ định", example: "" },
    { word: "Parking spot", definition: "chỗ đậu xe", example: "" },
    { word: "Lobby", definition: "sảnh", example: "" },
    { word: "Record", definition: "hồ sơ, kỷ lục", example: "" },
    { word: "Fine", definition: "tiền phạt", example: "" },
    { word: "Election ballot", definition: "lá phiếu bầu cử", example: "" },
    { word: "Episode", definition: "tập phim, sự kiện", example: "" },
    { word: "Go over", definition: "xem lại, kiểm tra", example: "" },
    { word: "Minor", definition: "nhỏ, không đáng kể", example: "" },
    { word: "Crack", definition: "vết nứt, nứt vỡ", example: "" },
    { word: "Track", definition: "đường ray, theo dõi", example: "" },
    { word: "Invent", definition: "phát minh", example: "" },
    { word: "Consult", definition: "tham khảo, tư vấn", example: "" },
    { word: "Drain", definition: "ống thoát nước, làm cạn kiệt", example: "" },
    { word: "Conservatory", definition: "nhà kính, nhạc viện", example: "" },
    { word: "Learn about", definition: "tìm hiểu về", example: "" },
    { word: "Renowned", definition: "nổi tiếng", example: "" },
    { word: "Lecture", definition: "bài giảng", example: "" },
    { word: "Conduct an interview", definition: "thực hiện một cuộc phỏng vấn", example: "" },
    { word: "Encourage", definition: "khuyến khích", example: "" },
    { word: "Proceeds", definition: "tiền thu được, doanh thu", example: "" },
    { word: "Rehearsal", definition: "buổi diễn tập", example: "" },
    { word: "Sponsor", definition: "tài trợ, nhà tài trợ", example: "" },
    { word: "Refreshment", definition: "đồ ăn thức uống", example: "" },
    { word: "Session", definition: "buổi họp, phiên", example: "" },
    { word: "Wisely", definition: "một cách khôn ngoan", example: "" },
    { word: "Factor", definition: "yếu tố", example: "" },
    { word: "Refer", definition: "tham khảo, giới thiệu", example: "" },
    { word: "Packet", definition: "gói, túi nhỏ", example: "" },
    { word: "Hand", definition: "đưa, giao", example: "" },
    { word: "Archaeologist", definition: "nhà khảo cổ học", example: "" },
    { word: "Uncover", definition: "phát hiện, khám phá", example: "" },
    { word: "Remain", definition: "còn lại, giữ nguyên", example: "" },
    { word: "Mosaic", definition: "tranh khảm", example: "" },
    { word: "Vibrant", definition: "sôi động, rực rỡ", example: "" },
    { word: "Ruin", definition: "tàn tích, làm hỏng", example: "" },
    { word: "Intricate", definition: "phức tạp, tinh xảo", example: "" },
    { word: "Dim", definition: "lờ mờ, tối", example: "" },
    { word: "Proceed", definition: "tiếp tục, tiến hành", example: "" },
    { word: "Handrail", definition: "tay vịn cầu thang", example: "" },
    { word: "Defensive", definition: "phòng thủ", example: "" },
    { word: "Inhabitant", definition: "cư dân", example: "" },
    { word: "Win a contract", definition: "giành được hợp đồng", example: "" },
    { word: "Priority", definition: "ưu tiên", example: "" },
    { word: "Rough", definition: "thô ráp, khó khăn", example: "" },
    { word: "Keep sb posted", definition: "thông báo cho ai liên tục", example: "" },
    { word: "Explore", definition: "khám phá", example: "" },
    { word: "Commemorate", definition: "tưởng nhớ", example: "" },
    { word: "Depth", definition: "độ sâu, chiều sâu", example: "" },
    { word: "Stay informed", definition: "luôn được cập nhật thông tin", example: "" },
];

const listening_tong_hop_test_2: VocabItem[] = [
    { word: "Trash bin", definition: "thùng rác", example: "" },
    { word: "Branch", definition: "chi nhánh, cành cây", example: "" },
    { word: "Water", definition: "tưới nước", example: "" },
    { word: "Seashore", definition: "bờ biển", example: "" },
    { word: "Brochure", definition: "tờ rơi quảng cáo", example: "" },
    { word: "Front desk", definition: "quầy lễ tân", example: "" },
    { word: "Delicious", definition: "ngon", example: "" },
    { word: "On time", definition: "đúng giờ", example: "" },
    { word: "Demonstration", definition: "sự trình diễn, minh họa", example: "" },
    { word: "Specialist", definition: "chuyên gia", example: "" },
    { word: "Involve", definition: "bao gồm, liên quan", example: "" },
    { word: "Palette", definition: "bảng màu", example: "" },
    { word: "Battery", definition: "pin, ắc quy", example: "" },
    { word: "Retire", definition: "nghỉ hưu", example: "" },
    { word: "Pick up", definition: "nhặt lên, đón", example: "" },
    { word: "Revise", definition: "sửa đổi, ôn tập", example: "" },
    { word: "Cover under warranty", definition: "bảo hành", example: "" },
    { word: "Interior", definition: "bên trong, nội thất", example: "" },
    { word: "Binder", definition: "bìa kẹp, bìa tài liệu", example: "" },
    { word: "Sample", definition: "mẫu", example: "" },
    { word: "Give sb a tour", definition: "dẫn ai đi tham quan", example: "" },
    { word: "Property", definition: "tài sản, bất động sản", example: "" },
    { word: "Dock", definition: "bến tàu, cập bến", example: "" },
    { word: "Avoid", definition: "tránh", example: "" },
    { word: "Behind schedule", definition: "trễ tiến độ", example: "" },
    { word: "Failure", definition: "thất bại", example: "" },
    { word: "Machinery", definition: "máy móc", example: "" },
    { word: "Lift", definition: "nâng lên, thang máy", example: "" },
    { word: "Work on sth", definition: "làm việc với", example: "" },
    { word: "Landscape", definition: "phong cảnh, làm vườn", example: "" },
    { word: "Acquire", definition: "đạt được, mua", example: "" },
    { word: "Significant", definition: "quan trọng, đáng kể", example: "" },
    { word: "Investigate", definition: "điều tra", example: "" },
    { word: "Stunning", definition: "tuyệt đẹp", example: "" },
    { word: "Unveil", definition: "tiết lộ, ra mắt", example: "" },
    { word: "Art restorer", definition: "người phục chế nghệ thuật", example: "" },
    { word: "Prefer", definition: "thích hơn", example: "" },
    { word: "Handout", definition: "tài liệu phát tay", example: "" },
    { word: "Impact", definition: "tác động", example: "" },
    { word: "Itinerary", definition: "lịch trình", example: "" },
    { word: "Mandatory", definition: "bắt buộc", example: "" },
    { word: "Casual", definition: "bình thường, không trang trọng", example: "" },
    { word: "Fill sb position", definition: "lấp vị trí", example: "" },
    { word: "Extended", definition: "kéo dài", example: "" },
    { word: "Gain", definition: "đạt được, sự tăng", example: "" },
    { word: "Segment", definition: "phân đoạn, khúc", example: "" },
    { word: "State-of-the-art", definition: "hiện đại nhất", example: "" },
    { word: "Athlete", definition: "vận động viên", example: "" },
    { word: "Compete", definition: "cạnh tranh", example: "" },
    { word: "Career path", definition: "con đường sự nghiệp", example: "" },
    { word: "Delighted", definition: "vui mừng", example: "" },
    { word: "Institute", definition: "học viện, thiết lập", example: "" },
    { word: "Goal", definition: "mục tiêu", example: "" },
    { word: "Draft", definition: "bản nháp, phác thảo", example: "" },
    { word: "Allocate", definition: "phân bổ", example: "" },
    { word: "Fund", definition: "quỹ, tài trợ", example: "" },
    { word: "Preliminary", definition: "sơ bộ, ban đầu", example: "" },
    { word: "Findings", definition: "kết quả nghiên cứu", example: "" },
    { word: "Credit card", definition: "thẻ tín dụng", example: "" },
    { word: "Keep track of", definition: "theo dõi", example: "" },
    { word: "Alert", definition: "cảnh báo, cảnh giác", example: "" },
    { word: "Inventory", definition: "hàng tồn kho", example: "" },
    { word: "Stock", definition: "hàng hóa, dự trữ", example: "" },
    { word: "Irrigation", definition: "sự tưới tiêu", example: "" },
    { word: "Figure out", definition: "tìm ra", example: "" },
    { word: "Orchard", definition: "vườn cây ăn quả", example: "" },
    { word: "Lawn", definition: "bãi cỏ", example: "" },
    { word: "Transplant", definition: "cấy ghép", example: "" },
    { word: "Terrible", definition: "kinh khủng", example: "" },
    { word: "Manual", definition: "sách hướng dẫn, thủ công", example: "" },
    { word: "On schedule", definition: "đúng tiến độ", example: "" },
    { word: "Suit", definition: "phù hợp", example: "" },
    { word: "Prize", definition: "giải thưởng", example: "" },
    { word: "Preferred", definition: "được ưu tiên", example: "" },
    { word: "Ahead of time", definition: "trước thời hạn", example: "" },
    { word: "Package", definition: "gói hàng, đóng gói", example: "" },
    { word: "Gallery", definition: "phòng trưng bày", example: "" },
    { word: "Occasion", definition: "dịp", example: "" },
    { word: "Digital", definition: "kỹ thuật số", example: "" },
    { word: "Guarantee", definition: "đảm bảo", example: "" },
    { word: "Caterer", definition: "nhà cung cấp thực phẩm", example: "" },
    { word: "Have sth done", definition: "nhờ ai làm gì", example: "" },
    { word: "Signature", definition: "chữ ký", example: "" },
    { word: "Warranty", definition: "bảo hành", example: "" },
    { word: "Newsletter", definition: "bản tin", example: "" },
    { word: "Patient", definition: "bệnh nhân, kiên nhẫn", example: "" },
    { word: "Known", definition: "được biết đến", example: "" },
    { word: "Try out", definition: "thử nghiệm", example: "" },
    { word: "Stimulation", definition: "sự kích thích", example: "" },
    { word: "Look for", definition: "tìm kiếm", example: "" },
    { word: "Determine", definition: "xác định", example: "" },
    { word: "Recruit", definition: "tuyển dụng, tân binh", example: "" },
    { word: "Innovative", definition: "sáng tạo", example: "" },
    { word: "Dependable", definition: "đáng tin cậy", example: "" },
    { word: "Upcoming", definition: "sắp tới", example: "" },
    { word: "Executive", definition: "giám đốc điều hành, điều hành", example: "" },
    { word: "Prepped", definition: "chuẩn bị sẵn sàng", example: "" },
    { word: "Launch", definition: "ra mắt, phóng", example: "" },
    { word: "Ingredient", definition: "thành phần", example: "" },
    { word: "Inspection", definition: "sự kiểm tra", example: "" },
    { word: "Suburb", definition: "vùng ngoại ô", example: "" },
    { word: "Metropolitan area", definition: "khu vực đô thị", example: "" },
    { word: "Voice", definition: "bày tỏ", example: "" },
    { word: "Clutter", definition: "bừa bộn, làm lộn xộn", example: "" },
    { word: "Neat", definition: "gọn gàng", example: "" },
    { word: "Mess", definition: "tình trạng bừa bộn", example: "" },
    { word: "Adjust", definition: "điều chỉnh", example: "" },
    { word: "Narrow", definition: "hẹp, thu hẹp", example: "" },
    { word: "Assemble", definition: "lắp ráp, tụ họp", example: "" },
    { word: "Collaborate", definition: "hợp tác", example: "" },
    { word: "Renowned", definition: "nổi tiếng", example: "" },
    { word: "Rave", definition: "khen ngợi", example: "" },
    { word: "Criticize", definition: "chỉ trích", example: "" },
    { word: "Underway", definition: "đang tiến hành", example: "" },
    { word: "Shortly", definition: "ngay lập tức, nhanh chóng", example: "" },
    { word: "Proceed", definition: "tiếp tục", example: "" },
    { word: "Pass", definition: "vé", example: "" },
    { word: "Press conference", definition: "cuộc họp báo", example: "" },
    { word: "Terminal", definition: "nhà ga", example: "" },
    { word: "Anticipate", definition: "dự đoán", example: "" },
    { word: "Reporter", definition: "phóng viên", example: "" },
];

const listening_tong_hop_test_3: VocabItem[] = [
    { word: "Flour", definition: "bột mì", example: "" },
    { word: "Out of stock", definition: "hết hàng", example: "" },
    { word: "Catering", definition: "dịch vụ ăn uống", example: "" },
    { word: "Vegetarian", definition: "ăn chay/người ăn chay", example: "" },
    { word: "Delicious", definition: "ngon miệng", example: "" },
    { word: "Networking event", definition: "sự kiện kết nối", example: "" },
    { word: "Pair of shoes", definition: "đôi giày", example: "" },
    { word: "Checkup", definition: "kiểm tra sức khỏe", example: "" },
    { word: "Corner", definition: "góc", example: "" },
    { word: "Reusable", definition: "có thể tái sử dụng", example: "" },
    { word: "Ink cartridge", definition: "hộp mực in", example: "" },
    { word: "Receipt", definition: "hóa đơn", example: "" },
    { word: "Power cable", definition: "dây nguồn", example: "" },
    { word: "Power button", definition: "nút nguồn", example: "" },
    { word: "Take a walk", definition: "đi dạo", example: "" },
    { word: "Tracker", definition: "thiết bị theo dõi", example: "" },
    { word: "Dealership", definition: "đại lý", example: "" },
    { word: "Rent", definition: "thuê", example: "" },
    { word: "Lease", definition: "hợp đồng thuê", example: "" },
    { word: "Maintenance", definition: "bảo trì", example: "" },
    { word: "Roadwork", definition: "công trình làm đường", example: "" },
    { word: "Hall", definition: "sảnh, hội trường", example: "" },
    { word: "Inspection", definition: "kiểm tra", example: "" },
    { word: "Supervisor", definition: "người giám sát", example: "" },
    { word: "Festival", definition: "lễ hội", example: "" },
    { word: "Coupon", definition: "phiếu giảm giá", example: "" },
    { word: "Cabinet", definition: "tủ", example: "" },
    { word: "Quite", definition: "khá, hoàn toàn", example: "" },
    { word: "Postpone", definition: "hoãn lại", example: "" },
    { word: "Figure", definition: "con số, tính toán", example: "" },
    { word: "Therapist", definition: "nhà trị liệu", example: "" },
    { word: "Pick up", definition: "nhặt lên, đón", example: "" },
    { word: "Demonstration", definition: "sự minh họa, trình diễn", example: "" },
    { word: "Aisle seat", definition: "ghế gần lối đi", example: "" },
    { word: "Official", definition: "viên chức, chính thức", example: "" },
    { word: "Expand", definition: "mở rộng", example: "" },
    { word: "Handbook", definition: "sổ tay", example: "" },
    { word: "Trade show", definition: "triển lãm thương mại", example: "" },
    { word: "Cover", definition: "che phủ, bìa", example: "" },
    { word: "Organizer", definition: "người tổ chức", example: "" },
    { word: "Participant", definition: "người tham gia", example: "" },
    { word: "Pleased", definition: "hài lòng", example: "" },
    { word: "Turnout", definition: "số người tham gia", example: "" },
    { word: "Executive", definition: "giám đốc, điều hành", example: "" },
    { word: "Vendor", definition: "người bán hàng", example: "" },
    { word: "Refreshment", definition: "đồ ăn nhẹ", example: "" },
    { word: "Specific", definition: "cụ thể", example: "" },
    { word: "Streamline", definition: "tinh giản", example: "" },
    { word: "Material", definition: "tài liệu, vật liệu", example: "" },
    { word: "Investment", definition: "sự đầu tư", example: "" },
    { word: "Cost estimate", definition: "ước tính chi phí", example: "" },
    { word: "Revise", definition: "chỉnh sửa", example: "" },
    { word: "Catch a train", definition: "bắt tàu", example: "" },
    { word: "Platform", definition: "sân ga", example: "" },
    { word: "Track", definition: "đường ray", example: "" },
    { word: "Upset", definition: "buồn, bực bội", example: "" },
    { word: "Shuttle bus", definition: "xe buýt đưa đón", example: "" },
    { word: "Escalator", definition: "thang cuốn", example: "" },
    { word: "Conduct an inspection", definition: "tiến hành kiểm tra", example: "" },
    { word: "Misunderstand", definition: "hiểu nhầm", example: "" },
    { word: "Board", definition: "lên tàu, máy bay", example: "" },
    { word: "File a complaint", definition: "nộp đơn khiếu nại", example: "" },
    { word: "Tough", definition: "khó khăn, cứng rắn", example: "" },
    { word: "Rack", definition: "giá đỡ", example: "" },
    { word: "Adjust", definition: "điều chỉnh", example: "" },
    { word: "Determine", definition: "xác định", example: "" },
    { word: "Reasonable", definition: "hợp lý", example: "" },
    { word: "Make decisions", definition: "đưa ra quyết định", example: "" },
    { word: "Prototype", definition: "nguyên mẫu", example: "" },
    { word: "Persuade", definition: "thuyết phục", example: "" },
    { word: "Prioritize", definition: "sự riêng tư, quyền riêng tư", example: "" },
    { word: "In the process of", definition: "ưu tiên", example: "" },
    { word: "Territory", definition: "trong quá trình", example: "" },
    { word: "Assemble", definition: "lắp ráp", example: "" },
    { word: "Lightweight", definition: "nhẹ", example: "" },
    { word: "Certificate", definition: "chứng chỉ", example: "" },
    { word: "Evaluate", definition: "đánh giá", example: "" },
    { word: "Head over", definition: "đi tới", example: "" },
    { word: "Ruin", definition: "phá hỏng, tàn tích", example: "" },
    { word: "Intern", definition: "thực tập sinh", example: "" },
    { word: "Shortage", definition: "sự thiếu hụt", example: "" },
    { word: "Revenue", definition: "doanh thu", example: "" },
    { word: "Script", definition: "kịch bản", example: "" },
    { word: "Come along", definition: "đến, xuất hiện", example: "" },
    { word: "Retire", definition: "nghỉ hưu", example: "" },
    { word: "Caterer", definition: "nhà cung cấp thực phẩm", example: "" },
    { word: "Retreat", definition: "buổi nghỉ dưỡng", example: "" },
    { word: "Wrap up", definition: "hoàn thành", example: "" },
    { word: "Capability", definition: "khả năng", example: "" },
    { word: "Peel", definition: "gọt, bóc vỏ", example: "" },
    { word: "Dock", definition: "bến tàu, cập bến", example: "" },
    { word: "Patient", definition: "bệnh nhân, kiên nhẫn", example: "" },
    { word: "Attract", definition: "thu hút", example: "" },
    { word: "Procedure", definition: "quy trình", example: "" },
    { word: "Mug", definition: "cốc", example: "" },
    { word: "Appreciate", definition: "đánh giá cao, cảm kích", example: "" },
    { word: "Bulk", definition: "số lượng lớn", example: "" },
    { word: "In bulk", definition: "với số lượng lớn", example: "" },
    { word: "Alter", definition: "thay đổi", example: "" },
    { word: "Alert", definition: "cảnh báo, cảnh giác", example: "" },
    { word: "Glitch", definition: "trục trặc", example: "" },
    { word: "Proud", definition: "tự hào", example: "" },
    { word: "Affordable", definition: "hợp túi tiền", example: "" },
    { word: "Dedication", definition: "sự tận tâm", example: "" },
    { word: "Award", definition: "giải thưởng, trao thưởng", example: "" },
    { word: "Principle", definition: "nguyên tắc", example: "" },
    { word: "Approach", definition: "phương pháp", example: "" },
    { word: "Real estate", definition: "bất động sản", example: "" },
    { word: "Complicated", definition: "phức tạp", example: "" },
    { word: "Brighten", definition: "làm sáng lên", example: "" },
    { word: "Reliever", definition: "vật/người làm dịu", example: "" },
    { word: "Relieve", definition: "làm dịu đi", example: "" },
    { word: "Vending machine", definition: "máy bán hàng tự động", example: "" },
    { word: "Abandon", definition: "từ bỏ, bỏ rơi", example: "" },
    { word: "Makeover", definition: "sự thay đổi diện mạo", example: "" },
    { word: "Convert into", definition: "chuyển đổi thành", example: "" },
    { word: "Elect", definition: "bầu cử", example: "" },
    { word: "Press conference", definition: "buổi họp báo", example: "" },
    { word: "Press release", definition: "thông cáo báo chí", example: "" },
    { word: "Tunnel", definition: "đường hầm", example: "" },
    { word: "Repave", definition: "lát lại", example: "" },
    { word: "Press (n)", definition: "báo chí", example: "" },
    { word: "Entrepreneur", definition: "doanh nhân", example: "" },
    { word: "Sluggish", definition: "chậm chạp", example: "" },
    { word: "Accelerate", definition: "tăng tốc", example: "" },
    { word: "Vary", definition: "thay đổi", example: "" },
    { word: "Clog", definition: "làm tắc", example: "" },
    { word: "Take a look", definition: "xem qua", example: "" },
    { word: "Parade", definition: "cuộc diễu hành", example: "" },
    { word: "Profitable", definition: "có lợi", example: "" },
    { word: "Designate", definition: "chỉ định", example: "" },
    { word: "Prompt", definition: "thúc giục, nhanh chóng", example: "" },
];

const listening_tong_hop_test_4: VocabItem[] = [
    { word: "Supplier", definition: "nhà cung cấp", example: "" },
    { word: "Make the reservation", definition: "đặt chỗ, đặt trước", example: "" },
    { word: "Locker room", definition: "phòng thay đồ", example: "" },
    { word: "Certain", definition: "chắc chắn, một vài", example: "" },
    { word: "Lobby", definition: "sảnh, hành lang", example: "" },
    { word: "Continent", definition: "lục địa", example: "" },
    { word: "Expedite", definition: "xúc tiến, đẩy nhanh", example: "" },
    { word: "Expedited delivery", definition: "giao hàng nhanh", example: "" },
    { word: "Sales associate", definition: "nhân viên bán hàng", example: "" },
    { word: "Handout", definition: "tài liệu phát tay", example: "" },
    { word: "Pursue", definition: "theo đuổi", example: "" },
    { word: "Reception desk", definition: "quầy lễ tân", example: "" },
    { word: "Speech", definition: "bài phát biểu", example: "" },
    { word: "Package", definition: "gói hàng, đóng gói", example: "" },
    { word: "Mark down", definition: "giảm giá", example: "" },
    { word: "Significant", definition: "quan trọng, đáng kể", example: "" },
    { word: "Surplus", definition: "thặng dư, dư thừa", example: "" },
    { word: "Ferry", definition: "phà, tàu phà", example: "" },
    { word: "Authority", definition: "thẩm quyền, chính quyền", example: "" },
    { word: "Suspend", definition: "đình chỉ, tạm ngưng", example: "" },
    { word: "Marine", definition: "thuộc về biển, hải quân", example: "" },
    { word: "Rough water", definition: "biển động, sóng lớn", example: "" },
    { word: "Pass in", definition: "nộp, gửi", example: "" },
    { word: "Terminal", definition: "nhà ga, trạm", example: "" },
    { word: "Understaff", definition: "thiếu nhân lực", example: "" },
    { word: "Overdue", definition: "quá hạn", example: "" },
    { word: "Librarian", definition: "thủ thư", example: "" },
    { word: "Price quote", definition: "báo giá", example: "" },
    { word: "Catering", definition: "dịch vụ cung cấp thực phẩm", example: "" },
    { word: "Deposit", definition: "tiền đặt cọc, đặt cọc", example: "" },
    { word: "Sample", definition: "mẫu thử, thử", example: "" },
    { word: "State-of-the-art", definition: "hiện đại nhất", example: "" },
    { word: "Treadmill", definition: "máy chạy bộ", example: "" },
    { word: "Consider", definition: "cân nhắc, xem xét", example: "" },
    { word: "Brochure", definition: "tờ rơi, tài liệu quảng cáo", example: "" },
    { word: "Lease", definition: "hợp đồng thuê, thuê", example: "" },
    { word: "Rent", definition: "tiền thuê, thuê", example: "" },
    { word: "Quite", definition: "khá, hoàn toàn", example: "" },
    { word: "Afford", definition: "có khả năng chi trả", example: "" },
    { word: "Tenant", definition: "người thuê nhà", example: "" },
    { word: "Carpenter", definition: "thợ mộc", example: "" },
    { word: "Interior", definition: "nội thất, bên trong", example: "" },
    { word: "Drop off", definition: "đưa đến, để lại", example: "" },
    { word: "Log", definition: "nhật ký, ghi lại", example: "" },
    { word: "Perhaps", definition: "có lẽ", example: "" },
    { word: "Ballroom", definition: "phòng khiêu vũ", example: "" },
    { word: "Acknowledge", definition: "thừa nhận, xác nhận", example: "" },
    { word: "Exposition", definition: "triển lãm, hội chợ", example: "" },
    { word: "Adjust", definition: "điều chỉnh", example: "" },
    { word: "Roof", definition: "mái nhà", example: "" },
    { word: "Inspection", definition: "kiểm tra, thanh tra", example: "" },
    { word: "Conduct an inspection", definition: "tiến hành kiểm tra", example: "" },
    { word: "Thorough", definition: "kỹ lưỡng, toàn diện", example: "" },
    { word: "Intact", definition: "nguyên vẹn", example: "" },
    { word: "Shingle", definition: "ngói, ván lợp mái", example: "" },
    { word: "Blow away", definition: "cuốn đi, làm kinh ngạc", example: "" },
    { word: "Relief", definition: "sự giảm nhẹ, nhẹ nhõm", example: "" },
    { word: "Major", definition: "quan trọng, chủ yếu", example: "" },
    { word: "Fence", definition: "hàng rào", example: "" },
    { word: "Minor", definition: "nhỏ, không quan trọng", example: "" },
    { word: "Forecast", definition: "dự báo", example: "" },
    { word: "Measurement", definition: "sự đo lường", example: "" },
    { word: "Commute", definition: "đi lại, quãng đường đi làm", example: "" },
    { word: "Horrendous", definition: "kinh khủng, tồi tệ", example: "" },
    { word: "Send out", definition: "gửi đi", example: "" },
    { word: "Aware of", definition: "nhận thức, ý thức về", example: "" },
    { word: "Badge", definition: "thẻ, huy hiệu", example: "" },
    { word: "Assumption", definition: "giả định, sự cho rằng", example: "" },
    { word: "Express", definition: "bày tỏ", example: "" },
    { word: "Justify", definition: "biện minh", example: "" },
    { word: "Activate", definition: "kích hoạt", example: "" },
    { word: "Forward", definition: "chuyển tiếp", example: "" },
    { word: "Firm", definition: "công ty, chắc chắn", example: "" },
    { word: "Clientele", definition: "nhóm khách hàng", example: "" },
    { word: "Reject", definition: "từ chối", example: "" },
    { word: "Clarification", definition: "sự làm rõ", example: "" },
    { word: "Rehearsal", definition: "buổi tập dượt", example: "" },
    { word: "Distract", definition: "làm xao lãng, phân tâm", example: "" },
    { word: "Costume", definition: "trang phục", example: "" },
    { word: "Publicity", definition: "sự công khai, quảng bá", example: "" },
    { word: "Archaeologist", definition: "nhà khảo cổ học", example: "" },
    { word: "Dig", definition: "đào, sự đào bới", example: "" },
    { word: "Footage", definition: "đoạn phim, cảnh quay", example: "" },
    { word: "Capture", definition: "ghi lại, bắt giữ", example: "" },
    { word: "Pottery", definition: "đồ gốm", example: "" },
    { word: "Unearth", definition: "khai quật", example: "" },
    { word: "Length", definition: "chiều dài", example: "" },
    { word: "Thunderstorm", definition: "cơn giông", example: "" },
    { word: "Slow down", definition: "làm chậm lại", example: "" },
    { word: "Documentary", definition: "phim tài liệu", example: "" },
    { word: "Reach", definition: "liên hệ, đạt được", example: "" },
    { word: "Electrical outage", definition: "mất điện", example: "" },
    { word: "On-site", definition: "tại chỗ", example: "" },
    { word: "Off-site", definition: "ngoài site, ngoài công ty", example: "" },
    { word: "Restore", definition: "khôi phục", example: "" },
    { word: "Utility", definition: "tiện ích", example: "" },
    { word: "Manual", definition: "hướng dẫn, thủ công", example: "" },
    { word: "Internal", definition: "nội bộ", example: "" },
    { word: "Involve", definition: "tham gia, bao gồm", example: "" },
    { word: "Shut down", definition: "tắt, đóng cửa", example: "" },
    { word: "Keep track of", definition: "theo dõi", example: "" },
    { word: "Inventory", definition: "tồn kho, kiểm kê", example: "" },
    { word: "Entrance", definition: "lối vào", example: "" },
    { word: "Widen", definition: "làm rộng, mở rộng", example: "" },
    { word: "Follow up", definition: "theo dõi, tiếp tục", example: "" },
    { word: "Complimentary", definition: "miễn phí, biếu tặng", example: "" },
    { word: "Back and forth", definition: "qua lại", example: "" },
    { word: "Alternative", definition: "thay thế, phương án thay thế", example: "" },
    { word: "Retain", definition: "giữ lại", example: "" },
    { word: "Exclusive", definition: "độc quyền, dành riêng", example: "" },
    { word: "Potential", definition: "tiềm năng", example: "" },
    { word: "Career path", definition: "con đường sự nghiệp", example: "" },
    { word: "Hospitality", definition: "lòng hiếu khách", example: "" },
    { word: "Willing", definition: "sẵn lòng, tình nguyện", example: "" },
    { word: "Carpool", definition: "đi chung xe", example: "" },
    { word: "Focus on", definition: "tập trung vào", example: "" },
    { word: "Mural", definition: "bức tranh tường", example: "" },
    { word: "Statue", definition: "bức tượng", example: "" },
    { word: "Motivate", definition: "thúc đẩy", example: "" },
    { word: "Rail", definition: "đường ray, lan can", example: "" },
    { word: "Initial (n, adj)", definition: "ban đầu, khởi đầu", example: "" },
    { word: "Ultimately", definition: "cuối cùng", example: "" },
    { word: "Straightforward", definition: "đơn giản, dễ hiểu", example: "" },
    { word: "Resident", definition: "cư dân", example: "" },
    { word: "Vendor", definition: "người bán, nhà cung cấp", example: "" },
    { word: "Artwork", definition: "tác phẩm nghệ thuật", example: "" },
    { word: "Incorporate", definition: "kết hợp, sáp nhập", example: "" },
    { word: "Element", definition: "yếu tố, thành phần", example: "" },
    { word: "Insulate", definition: "cách ly, cách nhiệt", example: "" },
    { word: "Repurpose", definition: "tái sử dụng, chuyển đổi mục đích", example: "" },
];

const listening_tong_hop_test_5: VocabItem[] = [
    { word: "Closet", definition: "tủ quần áo, phòng chứa đồ", example: "" },
    { word: "Mural", definition: "tranh tường", example: "" },
    { word: "Ladder", definition: "cái thang", example: "" },
    { word: "Recital", definition: "buổi biểu diễn (thơ, nhạc)", example: "" },
    { word: "Headsets", definition: "tai nghe có micro", example: "" },
    { word: "Hallway", definition: "hành lang", example: "" },
    { word: "Assembly", definition: "cuộc họp, sự lắp ráp", example: "" },
    { word: "Take note", definition: "ghi chú, lưu ý", example: "" },
    { word: "Extend", definition: "mở rộng, kéo dài", example: "" },
    { word: "Permit", definition: "giấy phép; cho phép", example: "" },
    { word: "Weight", definition: "trọng lượng", example: "" },
    { word: "Comedy", definition: "hài kịch", example: "" },
    { word: "Projector", definition: "máy chiếu", example: "" },
    { word: "Shut off", definition: "tắt", example: "" },
    { word: "Overheat", definition: "quá nóng", example: "" },
    { word: "Happen", definition: "xảy ra", example: "" },
    { word: "Control panel", definition: "bảng điều khiển", example: "" },
    { word: "Cable", definition: "dây cáp", example: "" },
    { word: "Printout", definition: "bản in", example: "" },
    { word: "Expert", definition: "chuyên gia", example: "" },
    { word: "Beforehand", definition: "trước", example: "" },
    { word: "Certificate", definition: "chứng nhận, giấy chứng nhận", example: "" },
    { word: "Badge", definition: "huy hiệu, thẻ", example: "" },
    { word: "Expiration date", definition: "ngày hết hạn", example: "" },
    { word: "Authorize", definition: "ủy quyền, cho phép", example: "" },
    { word: "Retirement", definition: "sự nghỉ hưu", example: "" },
    { word: "Guarantee", definition: "bảo đảm, cam kết", example: "" },
    { word: "Monitor", definition: "giám sát; màn hình", example: "" },
    { word: "Efficiency", definition: "hiệu suất", example: "" },
    { word: "Generate", definition: "tạo ra", example: "" },
    { word: "Lift", definition: "nâng lên; thang máy", example: "" },
    { word: "Object", definition: "vật thể; phản đối", example: "" },
    { word: "Testimonial", definition: "lời chứng thực, sự khen ngợi", example: "" },
    { word: "Cut over", definition: "chuyển đổi (hệ thống, quy trình)", example: "" },
    { word: "Postpone", definition: "trì hoãn", example: "" },
    { word: "File a complaint", definition: "nộp đơn khiếu nại", example: "" },
    { word: "Route", definition: "lộ trình", example: "" },
    { word: "Knowledgeable", definition: "am hiểu, có kiến thức", example: "" },
    { word: "Venue", definition: "địa điểm tổ chức", example: "" },
    { word: "Compliment", definition: "lời khen; khen ngợi", example: "" },
    { word: "Offerings", definition: "các sản phẩm, dịch vụ được cung cấp", example: "" },
    { word: "Recruit", definition: "tuyển dụng; nhân viên mới", example: "" },
    { word: "Flexible", definition: "linh hoạt", example: "" },
    { word: "Complimentary", definition: "miễn phí; ca ngợi", example: "" },
    { word: "Shuttle", definition: "xe đưa đón, phương tiện đưa đón", example: "" },
    { word: "Decline", definition: "từ chối; sự suy giảm", example: "" },
    { word: "Outreach", definition: "sự tiếp cận cộng đồng; tiếp cận", example: "" },
    { word: "Draft", definition: "bản nháp; phác thảo", example: "" },
    { word: "Upholstery", definition: "bọc ghế, vật liệu bọc nội thất", example: "" },
    { word: "Rebate", definition: "giảm giá, tiền hoàn lại", example: "" },
    { word: "Expedite", definition: "xúc tiến, đẩy nhanh", example: "" },
    { word: "Mineral oil", definition: "dầu khoáng", example: "" },
    { word: "Durability", definition: "độ bền", example: "" },
    { word: "Invoice", definition: "hóa đơn", example: "" },
    { word: "Modify", definition: "chỉnh sửa", example: "" },
    { word: "Job description", definition: "bản mô tả công việc", example: "" },
    { word: "Play", definition: "vở kịch, trò chơi", example: "" },
    { word: "Mild", definition: "nhẹ, dịu", example: "" },
    { word: "Crowded", definition: "đông đúc", example: "" },
    { word: "Fairly", definition: "khá, công bằng", example: "" },
    { word: "Trial", definition: "thử nghiệm, phiên tòa", example: "" },
    { word: "Lantern", definition: "đèn lồng", example: "" },
    { word: "Set aside", definition: "dành riêng, để dành", example: "" },
    { word: "Refund", definition: "hoàn tiền, tiền hoàn lại", example: "" },
    { word: "Landscape", definition: "phong cảnh; làm cảnh quan", example: "" },
    { word: "Debris", definition: "mảnh vụn", example: "" },
    { word: "Walkway", definition: "lối đi", example: "" },
    { word: "Patio", definition: "sân hiên", example: "" },
    { word: "Be eligible for", definition: "đủ điều kiện", example: "" },
    { word: "Botanical garden", definition: "vườn thực vật", example: "" },
    { word: "Ordinary", definition: "bình thường", example: "" },
    { word: "Inconvenient", definition: "bất tiện", example: "" },
    { word: "Land (v)", definition: "hạ cánh, đặt chân lên", example: "" },
    { word: "Alternative", definition: "sự thay thế; thay thế", example: "" },
    { word: "Retrieve", definition: "lấy lại", example: "" },
    { word: "Repurpose", definition: "tái sử dụng", example: "" },
    { word: "Landfill", definition: "bãi rác", example: "" },
    { word: "Leftover", definition: "đồ ăn thừa; còn sót lại", example: "" },
    { word: "Crayon", definition: "bút màu", example: "" },
    { word: "Gather", definition: "thu thập, tụ họp", example: "" },
    { word: "Portion", definition: "phần, đoạn", example: "" },
    { word: "Impact", definition: "tác động, ảnh hưởng", example: "" },
    { word: "Coordinator", definition: "điều phối viên", example: "" },
    { word: "Reassurance", definition: "sự cam đoan", example: "" },
    { word: "Argue", definition: "tranh luận", example: "" },
    { word: "Settle", definition: "giải quyết, dàn xếp", example: "" },
    { word: "Package", definition: "gói hàng; đóng gói", example: "" },
    { word: "Interior", definition: "nội thất; bên trong", example: "" },
    { word: "Point out a problem", definition: "chỉ ra vấn đề", example: "" },
    { word: "Expense", definition: "chi phí", example: "" },
    { word: "Take advantage of", definition: "tận dụng, lợi dụng", example: "" },
    { word: "Compensate", definition: "bồi thường", example: "" },
    { word: "Belongings", definition: "đồ đạc cá nhân", example: "" },
    { word: "Driveway", definition: "đường lái xe vào nhà", example: "" },
    { word: "Spray", definition: "bình xịt; phun", example: "" },
    { word: "Polish", definition: "đánh bóng; sự sáng bóng", example: "" },
    { word: "Due", definition: "đến hạn", example: "" },
];

const listening_tong_hop_test_6: VocabItem[] = [
    { word: "Leftover", definition: "đồ ăn thừa; còn sót lại", example: "" },
    { word: "Badge", definition: "phù hiệu, huy hiệu", example: "" },
    { word: "Reasonable", definition: "hợp lý", example: "" },
    { word: "Waterfront", definition: "bờ sông, bờ biển", example: "" },
    { word: "Trim (n)", definition: "đường viền, cắt tỉa", example: "" },
    { word: "Tablecloth", definition: "khăn trải bàn", example: "" },
    { word: "Savings", definition: "tiền tiết kiệm", example: "" },
    { word: "Bulletin board", definition: "bảng thông báo", example: "" },
    { word: "Lawn", definition: "bãi cỏ", example: "" },
    { word: "Manual", definition: "sách hướng dẫn; thủ công", example: "" },
    { word: "Shovel", definition: "cái xẻng; xúc", example: "" },
    { word: "Walkway", definition: "lối đi", example: "" },
    { word: "Walking stick", definition: "gậy đi bộ", example: "" },
    { word: "Food trolley", definition: "xe đẩy thức ăn", example: "" },
    { word: "Carry", definition: "mang, vác", example: "" },
    { word: "Water (v)", definition: "tưới nước", example: "" },
    { word: "Scrub", definition: "chà, cọ", example: "" },
    { word: "Bucket", definition: "cái xô", example: "" },
    { word: "A bucket of water", definition: "một xô nước", example: "" },
    { word: "Tile", definition: "gạch, lát gạch", example: "" },
    { word: "Occupied", definition: "đang sử dụng, bận rộn", example: "" },
    { word: "Fountain", definition: "đài phun nước", example: "" },
    { word: "Gather", definition: "thu thập, tụ họp", example: "" },
    { word: "Entrance", definition: "lối vào", example: "" },
    { word: "Block", definition: "khối, chặn", example: "" },
    { word: "Pedestrian", definition: "người đi bộ", example: "" },
    { word: "Log", definition: "khúc gỗ; ghi chép", example: "" },
    { word: "Pile", definition: "chồng, đống", example: "" },
    { word: "Brick", definition: "gạch", example: "" },
    { word: "Overdue", definition: "quá hạn", example: "" },
    { word: "Get sth done", definition: "hoàn thành", example: "" },
    { word: "Break (n)", definition: "sự nghỉ ngơi, sự đứt gãy", example: "" },
    { word: "Press conference", definition: "cuộc họp báo", example: "" },
    { word: "Expire", definition: "hết hạn", example: "" },
    { word: "Solar panel", definition: "tấm pin mặt trời", example: "" },
    { word: "Renewable", definition: "tái tạo, có thể tái sinh", example: "" },
    { word: "Rental", definition: "cho thuê, tiền thuê", example: "" },
    { word: "Commute", definition: "đi lại, quãng đường đi làm", example: "" },
    { word: "Flat", definition: "căn hộ chung cư; bằng phẳng", example: "" },
    { word: "Fulfill", definition: "hoàn thành, đáp ứng", example: "" },
    { word: "Storage", definition: "kho lưu trữ, sự chứa đựng", example: "" },
    { word: "Battery", definition: "pin", example: "" },
    { word: "Merger", definition: "sự sáp nhập", example: "" },
    { word: "Return", definition: "trả lại; sự trở lại", example: "" },
    { word: "Soil", definition: "đất", example: "" },
    { word: "Drainpipe", definition: "ống xả nước", example: "" },
    { word: "Retain", definition: "giữ lại", example: "" },
    { word: "Worth", definition: "giá trị", example: "" },
    { word: "Brick", definition: "gạch", example: "" },
    { word: "Durable", definition: "bền, chắc chắn", example: "" },
    { word: "Appliance", definition: "thiết bị gia dụng", example: "" },
    { word: "Handle", definition: "tay cầm; xử lý", example: "" },
    { word: "Out of office", definition: "vắng mặt, không có ở văn phòng", example: "" },
    { word: "Implement", definition: "thực hiện", example: "" },
    { word: "Eager", definition: "háo hức, nhiệt tình", example: "" },
    { word: "Exclusive", definition: "độc quyền, riêng biệt", example: "" },
    { word: "Documentary", definition: "phim tài liệu", example: "" },
    { word: "Itinerary", definition: "lịch trình", example: "" },
    { word: "Procedure", definition: "thủ tục", example: "" },
    { word: "Weedy", definition: "đầy cỏ dại", example: "" },
    { word: "Fertilizer", definition: "phân bón", example: "" },
    { word: "Foresee", definition: "thấy trước, dự đoán", example: "" },
    { word: "Unforeseeable", definition: "không thể lường trước", example: "" },
    { word: "Acquisition", definition: "sự mua lại, sự tiếp thu", example: "" },
    { word: "Cost estimate", definition: "ước tính chi phí", example: "" },
    { word: "Election", definition: "cuộc bầu cử", example: "" },
    { word: "Obligation", definition: "nghĩa vụ", example: "" },
    { word: "Mechanic", definition: "thợ cơ khí", example: "" },
    { word: "Pond", definition: "ao hồ", example: "" },
    { word: "Coat of paint", definition: "lớp sơn", example: "" },
    { word: "Element", definition: "yếu tố, phần tử", example: "" },
    { word: "Entrance", definition: "lối vào", example: "" },
    { word: "Proceeds", definition: "tiền thu được", example: "" },
    { word: "Revenue", definition: "doanh thu", example: "" },
    { word: "Charity", definition: "tổ chức từ thiện", example: "" },
    { word: "Auction", definition: "cuộc đấu giá", example: "" },
    { word: "Clinic", definition: "phòng khám", example: "" },
    { word: "Drone", definition: "máy bay không người lái", example: "" },
    { word: "Carpenter", definition: "thợ mộc", example: "" },
    { word: "Insurance", definition: "bảo hiểm", example: "" },
    { word: "Retail", definition: "bán lẻ", example: "" },
    { word: "Interact", definition: "tương tác", example: "" },
    { word: "Tape", definition: "băng dính, ghi lại", example: "" },
    { word: "Debris", definition: "mảnh vỡ, đống đổ nát", example: "" },
    { word: "Cable", definition: "cáp", example: "" },
    { word: "Precaution", definition: "sự phòng ngừa", example: "" },
    { word: "Host", definition: "người tổ chức", example: "" },
    { word: "Newsletter", definition: "bản tin", example: "" },
    { word: "Complex", definition: "khu phức hợp", example: "" },
    { word: "Drain", definition: "cống, làm cho thoát nước", example: "" },
    { word: "Indicate", definition: "chỉ ra, biểu thị", example: "" },
    { word: "Cleanup", definition: "sự dọn dẹp, làm sạch", example: "" },
    { word: "Rent", definition: "tiền thuê, thuê", example: "" },
    { word: "Catch up", definition: "bắt kịp, gặp gỡ sau một thời gian", example: "" },
    { word: "Claim", definition: "yêu cầu, yêu sách", example: "" },
    { word: "Commission", definition: "hoa hồng, ủy nhiệm", example: "" },
    { word: "Perspective", definition: "quan điểm, góc nhìn", example: "" },
    { word: "Resident", definition: "cư dân", example: "" },
    { word: "Artwork", definition: "tác phẩm nghệ thuật", example: "" },
    { word: "Preference", definition: "sự ưu tiên", example: "" },
    { word: "Praise", definition: "sự khen ngợi, khen ngợi", example: "" },
    { word: "Exhibit", definition: "cuộc triển lãm, trưng bày", example: "" },
    { word: "Set aside", definition: "để dành, gạt sang một bên", example: "" },
    { word: "Make up for", definition: "bù đắp, đền bù", example: "" },
];

const listening_tong_hop_test_7: VocabItem[] = [
    { word: "Florist", definition: "người bán hoa", example: "" },
    { word: "Projector", definition: "máy chiếu", example: "" },
    { word: "Manual", definition: "sổ tay, thủ công", example: "" },
    { word: "Drawer", definition: "ngăn kéo", example: "" },
    { word: "Switch", definition: "công tắc", example: "" },
    { word: "Press Release", definition: "thông cáo báo chí", example: "" },
    { word: "Renew", definition: "gia hạn, làm mới", example: "" },
    { word: "Reach", definition: "đạt tới, liên hệ", example: "" },
    { word: "Annual", definition: "hàng năm", example: "" },
    { word: "Checkup", definition: "kiểm tra sức khỏe", example: "" },
    { word: "Express Delivery", definition: "giao hàng nhanh", example: "" },
    { word: "Fountain", definition: "đài phun nước", example: "" },
    { word: "Merchandise", definition: "hàng hóa", example: "" },
    { word: "Lease", definition: "hợp đồng thuê, thuê", example: "" },
    { word: "Heater", definition: "máy sưởi", example: "" },
    { word: "Recipe", definition: "công thức nấu ăn", example: "" },
    { word: "Crate", definition: "thùng, sọt", example: "" },
    { word: "Presentation", definition: "bài thuyết trình", example: "" },
    { word: "Distribute", definition: "phân phối", example: "" },
    { word: "Handout", definition: "tài liệu phát tay", example: "" },
    { word: "Flat", definition: "bằng phẳng, căn hộ", example: "" },
    { word: "Tire", definition: "lốp xe", example: "" },
    { word: "Mandatory", definition: "bắt buộc", example: "" },
    { word: "Summary", definition: "bản tóm tắt", example: "" },
    { word: "Sample", definition: "mẫu vật, thử", example: "" },
    { word: "Set up", definition: "thiết lập, sắp xếp", example: "" },
    { word: "Aisle", definition: "lối đi", example: "" },
    { word: "Conduct an inspection", definition: "tiến hành kiểm tra", example: "" },
    { word: "Demonstration", definition: "buổi trình diễn, minh họa", example: "" },
    { word: "Carry", definition: "mang, vác", example: "" },
    { word: "Ingredient", definition: "thành phần", example: "" },
    { word: "Assemble", definition: "lắp ráp", example: "" },
    { word: "Overdue", definition: "quá hạn", example: "" },
    { word: "Malfunction", definition: "sự cố, trục trặc", example: "" },
    { word: "Credit Card", definition: "thẻ tín dụng", example: "" },
    { word: "Mail Carrier", definition: "người đưa thư", example: "" },
    { word: "Candidate", definition: "ứng cử viên", example: "" },
    { word: "Boardroom", definition: "phòng họp ban giám đốc", example: "" },
    { word: "Luncheon", definition: "bữa trưa trang trọng", example: "" },
    { word: "Colleague", definition: "đồng nghiệp", example: "" },
    { word: "Concern about", definition: "quan ngại về", example: "" },
    { word: "Direct (v)", definition: "hướng dẫn, chỉ đạo", example: "" },
    { word: "Receipt", definition: "biên lai", example: "" },
    { word: "Walking Trail", definition: "đường đi bộ", example: "" },
    { word: "Monitor", definition: "giám sát, màn hình", example: "" },
    { word: "Preserve", definition: "bảo tồn, giữ gìn", example: "" },
    { word: "Laboratory", definition: "phòng thí nghiệm", example: "" },
    { word: "Bulletin Board", definition: "bảng thông báo", example: "" },
    { word: "Entire", definition: "toàn bộ", example: "" },
    { word: "Battery", definition: "pin, ắc quy", example: "" },
    { word: "Route", definition: "tuyến đường", example: "" },
    { word: "Maintenance", definition: "bảo trì", example: "" },
    { word: "Accurate", definition: "chính xác", example: "" },
    { word: "Forecast", definition: "dự báo", example: "" },
    { word: "Front Desk", definition: "quầy lễ tân", example: "" },
    { word: "Expect", definition: "mong đợi", example: "" },
    { word: "Be able to V", definition: "có thể làm gì", example: "" },
    { word: "Intern", definition: "thực tập sinh", example: "" },
    { word: "Look forward to Ving", definition: "mong đợi", example: "" },
    { word: "Conduct an interview", definition: "tiến hành phỏng vấn", example: "" },
    { word: "Facility", definition: "cơ sở, tiện ích", example: "" },
    { word: "Dense", definition: "dày đặc", example: "" },
    { word: "Footwear", definition: "giày dép", example: "" },
    { word: "Campground", definition: "khu cắm trại", example: "" },
    { word: "Regulation", definition: "quy định", example: "" },
    { word: "Property", definition: "tài sản, bất động sản", example: "" },
    { word: "Place an order", definition: "đặt hàng", example: "" },
    { word: "Advertise", definition: "quảng cáo", example: "" },
    { word: "Reserve", definition: "đặt chỗ, để dành", example: "" },
    { word: "Caterer", definition: "nhà cung cấp thực phẩm", example: "" },
    { word: "Exclude", definition: "loại trừ", example: "" },
    { word: "Postpone", definition: "hoãn lại", example: "" },
    { word: "Refund", definition: "hoàn tiền", example: "" },
    { word: "Expense", definition: "chi phí", example: "" },
    { word: "Venue", definition: "địa điểm tổ chức", example: "" },
    { word: "In person", definition: "trực tiếp", example: "" },
    { word: "Navigate", definition: "điều hướng, định vị", example: "" },
    { word: "Elevator", definition: "thang máy", example: "" },
    { word: "Accommodate", definition: "đáp ứng, chứa được", example: "" },
    { word: "Wheelchair", definition: "xe lăn", example: "" },
    { word: "Faulty", definition: "bị lỗi", example: "" },
    { word: "Be eligible for", definition: "đủ điều kiện", example: "" },
    { word: "Court", definition: "tòa án", example: "" },
    { word: "Investor", definition: "nhà đầu tư", example: "" },
    { word: "Broadcast", definition: "phát sóng", example: "" },
    { word: "Rumor", definition: "tin đồn", example: "" },
    { word: "Exclusive", definition: "độc quyền, đặc biệt", example: "" },
    { word: "Bid", definition: "đấu thầu, giá thầu", example: "" },
    { word: "Reporter", definition: "phóng viên", example: "" },
    { word: "Campus", definition: "khuôn viên trường đại học", example: "" },
    { word: "Entrepreneur", definition: "doanh nhân", example: "" },
    { word: "Launch", definition: "ra mắt", example: "" },
    { word: "Take a course", definition: "tham gia khóa học", example: "" },
    { word: "Trucking company", definition: "công ty vận tải", example: "" },
    { word: "Merger", definition: "sự hợp nhất", example: "" },
    { word: "Mark", definition: "dấu, đánh dấu", example: "" },
    { word: "Get-together", definition: "buổi gặp gỡ", example: "" },
    { word: "Progress", definition: "tiến bộ, tiến trình", example: "" },
    { word: "Session", definition: "buổi họp, phiên", example: "" },
    { word: "Take care of", definition: "chăm sóc, giải quyết", example: "" },
    { word: "Patient", definition: "bệnh nhân, kiên nhẫn", example: "" },
    { word: "Clinic", definition: "phòng khám", example: "" },
    { word: "Record", definition: "hồ sơ, ghi lại", example: "" },
    { word: "Obtain", definition: "đạt được", example: "" },
    { word: "Cereal", definition: "ngũ cốc", example: "" },
    { word: "At one's convenience", definition: "khi thuận tiện", example: "" },
    { word: "Electronics", definition: "đồ điện tử", example: "" },
    { word: "Inventory", definition: "hàng tồn kho", example: "" },
    { word: "Debrief", definition: "báo cáo, tóm tắt", example: "" },
    { word: "Satellite", definition: "vệ tinh", example: "" },
    { word: "Remote", definition: "từ xa, hẻo lánh", example: "" },
    { word: "Generally", definition: "nói chung", example: "" },
    { word: "Interruption", definition: "sự gián đoạn", example: "" },
    { word: "Disrupt", definition: "làm gián đoạn", example: "" },
    { word: "Focus on", definition: "tập trung vào", example: "" },
    { word: "Brainstorm", definition: "động não, thảo luận ý tưởng", example: "" },
    { word: "Take measurements", definition: "đo lường", example: "" },
    { word: "Booklet", definition: "quyển sách nhỏ", example: "" },
    { word: "Orchestra", definition: "dàn nhạc", example: "" },
    { word: "Look for", definition: "tìm kiếm", example: "" },
    { word: "Patron", definition: "khách hàng quen", example: "" },
    { word: "Take your seat", definition: "ngồi vào chỗ của bạn", example: "" },
    { word: "Tradeshow", definition: "hội chợ thương mại", example: "" },
    { word: "Separate", definition: "riêng biệt, tách rời", example: "" },
    { word: "Sensitive", definition: "nhạy cảm", example: "" },
    { word: "Complaint", definition: "lời phàn nàn", example: "" },
    { word: "Reduce", definition: "giảm", example: "" },
    { word: "Footprint", definition: "dấu chân, tác động môi trường", example: "" },
    { word: "Indicate", definition: "chỉ ra, biểu thị", example: "" },
    { word: "Misconception", definition: "quan niệm sai lầm", example: "" },
    { word: "Refreshment", definition: "đồ ăn nhẹ", example: "" },
    { word: "Beam", definition: "dầm, chùm sáng, tỏa sáng", example: "" },
    { word: "Fasten", definition: "buộc, thắt chặt", example: "" },
    { word: "Restraint", definition: "sự kiềm chế, ràng buộc", example: "" },
    { word: "Permit", definition: "giấy phép, cho phép", example: "" },
    { word: "Parade", definition: "cuộc diễu hành", example: "" },
    { word: "Promptly", definition: "ngay lập tức", example: "" },
    { word: "Be supposed to V", definition: "được cho là, phải làm gì", example: "" },
    { word: "Avenue", definition: "đại lộ, con đường hướng tới", example: "" },
    { word: "Wonder", definition: "tự hỏi, điều kỳ diệu", example: "" },
    { word: "Commercial break", definition: "quảng cáo giữa chương trình", example: "" },
];

const listening_tong_hop_test_8: VocabItem[] = [
    { word: "Napkin", definition: "khăn ăn", example: "" },
    { word: "Trash", definition: "rác", example: "" },
    { word: "Clinic", definition: "phòng khám", example: "" },
    { word: "Cost (v)", definition: "tốn, trị giá", example: "" },
    { word: "Lobby", definition: "sảnh chờ", example: "" },
    { word: "Acquisition", definition: "sự mua lại, sự thu nhận", example: "" },
    { word: "Committee", definition: "ủy ban", example: "" },
    { word: "Look up", definition: "tra cứu, tìm kiếm", example: "" },
    { word: "Separate", definition: "tách rời, riêng biệt", example: "" },
    { word: "Drawer", definition: "ngăn kéo", example: "" },
    { word: "Pantry", definition: "phòng để đồ ăn, nhà kho", example: "" },
    { word: "Knife", definition: "con dao", example: "" },
    { word: "Lounge", definition: "phòng chờ", example: "" },
    { word: "Cartridge", definition: "hộp mực, ống chứa", example: "" },
    { word: "Be able to V", definition: "có thể làm gì", example: "" },
    { word: "Take a bus", definition: "đi xe buýt", example: "" },
    { word: "Hallway", definition: "hành lang", example: "" },
    { word: "Work on sth", definition: "làm việc trên gì đó", example: "" },
    { word: "Innovative", definition: "sáng tạo, đổi mới", example: "" },
    { word: "Postage", definition: "cước phí bưu điện", example: "" },
    { word: "Cater", definition: "phục vụ ăn uống", example: "" },
    { word: "Express mail", definition: "thư chuyển phát nhanh", example: "" },
    { word: "Air conditioner", definition: "máy điều hòa", example: "" },
    { word: "Shut off", definition: "tắt", example: "" },
    { word: "Microscope", definition: "kính hiển vi", example: "" },
    { word: "Misplace", definition: "để lạc, đặt không đúng chỗ", example: "" },
    { word: "Manual", definition: "sách hướng dẫn/ thủ công", example: "" },
    { word: "Finalize", definition: "hoàn thiện", example: "" },
    { word: "Filing cabinet", definition: "tủ đựng hồ sơ", example: "" },
    { word: "Storage room", definition: "phòng lưu trữ", example: "" },
    { word: "Replacement", definition: "sự thay thế", example: "" },
    { word: "Organization", definition: "tổ chức, sự tổ chức", example: "" },
    { word: "Renovation", definition: "cải tạo, tu sửa", example: "" },
    { word: "Lobby", definition: "hành lang", example: "" },
    { word: "Do some research", definition: "nghiên cứu", example: "" },
    { word: "Donation", definition: "sự quyên góp", example: "" },
    { word: "Harvest", definition: "thu hoạch", example: "" },
    { word: "Pair of gloves", definition: "đôi găng tay", example: "" },
    { word: "Pick", definition: "chọn, hái", example: "" },
    { word: "Straightforward", definition: "đơn giản, rõ ràng", example: "" },
    { word: "Hydrate", definition: "cung cấp nước, làm ẩm", example: "" },
    { word: "Bottle", definition: "chai, lọ", example: "" },
    { word: "Clipboard", definition: "bảng kẹp tài liệu", example: "" },
    { word: "Label (v)", definition: "dán nhãn", example: "" },
    { word: "Botanist", definition: "nhà thực vật học", example: "" },
    { word: "Hybrid", definition: "giống lai, kết hợp", example: "" },
    { word: "Bloom", definition: "nở hoa", example: "" },
    { word: "Downtown", definition: "trung tâm thành phố", example: "" },
    { word: "Bucket", definition: "xô, thùng", example: "" },
    { word: "Platform", definition: "nền tảng, bến tàu", example: "" },
    { word: "Retain", definition: "giữ lại", example: "" },
    { word: "Reasonable", definition: "hợp lý, phải chăng", example: "" },
    { word: "Look over", definition: "xem xét", example: "" },
    { word: "Be interested in", definition: "quan tâm đến", example: "" },
    { word: "Deal (n)", definition: "giao dịch", example: "" },
    { word: "Impressive", definition: "ấn tượng", example: "" },
    { word: "Bonus (n)", definition: "tiền thưởng", example: "" },
    { word: "Document", definition: "tài liệu, ghi chép", example: "" },
    { word: "Documentation", definition: "tài liệu hướng dẫn", example: "" },
    { word: "Reference", definition: "tài liệu tham khảo", example: "" },
    { word: "City council", definition: "hội đồng thành phố", example: "" },
    { word: "Implement", definition: "thực hiện, thi hành", example: "" },
    { word: "Make sure", definition: "đảm bảo", example: "" },
    { word: "Inform sb of/about sth", definition: "thông báo cho ai về cái gì", example: "" },
    { word: "Revenue", definition: "doanh thu", example: "" },
    { word: "Reduce", definition: "giảm thiểu", example: "" },
    { word: "Attract", definition: "thu hút", example: "" },
    { word: "Understaff", definition: "thiếu nhân viên", example: "" },
    { word: "Guideline", definition: "hướng dẫn", example: "" },
    { word: "Prospective", definition: "triển vọng, tiềm năng", example: "" },
    { word: "Forward (v)", definition: "chuyển tiếp, hướng về phía trước", example: "" },
    { word: "Restriction", definition: "sự hạn chế", example: "" },
    { word: "Signature", definition: "chữ ký", example: "" },
    { word: "Expense", definition: "chi phí", example: "" },
    { word: "Rental", definition: "sự cho thuê", example: "" },
    { word: "Trade show", definition: "triển lãm thương mại", example: "" },
    { word: "Stop by", definition: "ghé qua", example: "" },
    { word: "Chart", definition: "biểu đồ", example: "" },
    { word: "Look forward to Ving", definition: "mong đợi điều gì đó", example: "" },
    { word: "Asphalt", definition: "nhựa đường", example: "" },
    { word: "Alternative", definition: "sự thay thế, thay đổi", example: "" },
    { word: "Batch", definition: "mẻ (sản phẩm)", example: "" },
    { word: "Mold", definition: "khuôn, nấm mốc", example: "" },
    { word: "Output", definition: "sản lượng, đầu ra", example: "" },
    { word: "Projection", definition: "sự dự đoán, dự báo", example: "" },
    { word: "Process", definition: "quy trình, xử lý", example: "" },
    { word: "Malfunction", definition: "sự cố, trục trặc", example: "" },
    { word: "Cost estimate", definition: "ước tính chi phí", example: "" },
    { word: "Make a mistake", definition: "mắc lỗi", example: "" },
    { word: "Shortage", definition: "sự thiếu hụt", example: "" },
    { word: "Inspect", definition: "kiểm tra", example: "" },
    { word: "Determine", definition: "xác định", example: "" },
    { word: "Major", definition: "chính, lớn", example: "" },
    { word: "Storefront", definition: "mặt tiền cửa hàng", example: "" },
    { word: "Furnish", definition: "trang bị, cung cấp nội thất", example: "" },
    { word: "Unique", definition: "độc đáo", example: "" },
    { word: "Hardwood", definition: "gỗ cứng", example: "" },
    { word: "Compact", definition: "gọn nhẹ, nhỏ gọn", example: "" },
    { word: "Fold", definition: "gấp (quần áo, giấy...)", example: "" },
    { word: "Throw into", definition: "ném vào", example: "" },
    { word: "Spacious", definition: "rộng rãi", example: "" },
    { word: "Guarantee", definition: "bảo hành, đảm bảo", example: "" },
    { word: "Enter", definition: "vào, nhập", example: "" },
    { word: "Subscribe", definition: "đăng ký", example: "" },
    { word: "Newsletter", definition: "bản tin", example: "" },
    { word: "Remain", definition: "còn lại, duy trì", example: "" },
    { word: "Moderate", definition: "vừa phải, ôn hòa", example: "" },
    { word: "Head into", definition: "hướng đến", example: "" },
    { word: "Initiative", definition: "sáng kiến, sáng tạo", example: "" },
    { word: "Appropriate", definition: "thích hợp", example: "" },
    { word: "Public transportation", definition: "phương tiện công cộng", example: "" },
    { word: "Antique", definition: "cổ vật, cổ xưa", example: "" },
    { word: "Drop off", definition: "thả xuống, bỏ lại", example: "" },
    { word: "Seem to V", definition: "có vẻ như làm gì đó", example: "" },
    { word: "Maintenance", definition: "bảo trì, duy trì", example: "" },
    { word: "National holiday", definition: "ngày lễ quốc gia", example: "" },
    { word: "Cost estimate", definition: "ước tính chi phí", example: "" },
    { word: "Warranty", definition: "bảo hành", example: "" },
    { word: "Conduct an inspection", definition: "tiến hành kiểm tra", example: "" },
    { word: "Outstanding", definition: "xuất sắc, nổi bật", example: "" },
    { word: "Unfailing", definition: "không ngừng, bền vững", example: "" },
    { word: "Consistent", definition: "nhất quán", example: "" },
    { word: "Footwear", definition: "giày dép", example: "" },
    { word: "Highlight", definition: "làm nổi bật, điểm nhấn", example: "" },
    { word: "Present an award", definition: "trao giải thưởng", example: "" },
    { word: "Retirement", definition: "nghỉ hưu", example: "" },
    { word: "Defective", definition: "có khuyết điểm, lỗi", example: "" },
    { word: "Reject", definition: "từ chối", example: "" },
    { word: "Deny", definition: "từ chối, phủ nhận", example: "" },
    { word: "Grant", definition: "cấp, cho phép", example: "" },
    { word: "Restore", definition: "khôi phục", example: "" },
    { word: "Essential", definition: "thiết yếu", example: "" },
    { word: "Workstation", definition: "bàn làm việc, trạm làm việc", example: "" },
    { word: "Patient", definition: "bệnh nhân, kiên nhẫn", example: "" },
    { word: "Consult", definition: "tham khảo, tư vấn", example: "" },
    { word: "Consider", definition: "cân nhắc", example: "" },
    { word: "Significant", definition: "quan trọng", example: "" },
    { word: "Overhaul", definition: "cải tiến, sửa chữa toàn diện", example: "" },
    { word: "Consume", definition: "tiêu thụ", example: "" },
    { word: "Surprising", definition: "gây ngạc nhiên", example: "" },
    { word: "Reassure", definition: "trấn an", example: "" },
    { word: "On track", definition: "đi đúng hướng", example: "" },
    { word: "Exceed", definition: "vượt quá, vượt lên", example: "" },
    { word: "Back out", definition: "rút lui", example: "" },
    { word: "Referral", definition: "sự giới thiệu, chuyển tiếp", example: "" },
    { word: "Inventory", definition: "hàng tồn kho", example: "" },
    { word: "Vendor", definition: "nhà cung cấp", example: "" },
    { word: "Sustainable", definition: "bền vững", example: "" },
    { word: "Practice", definition: "thói quen, luyện tập", example: "" },
    { word: "Hand out", definition: "phát, phân phát", example: "" },
    { word: "Sponsor", definition: "nhà tài trợ, tài trợ", example: "" },
    { word: "Offerings", definition: "sản phẩm, dịch vụ cung cấp", example: "" },
    { word: "Keynote", definition: "bài phát biểu chính, chủ chốt", example: "" },
    { word: "Run a business", definition: "điều hành một doanh nghiệp", example: "" },
    { word: "Engaging", definition: "hấp dẫn, lôi cuốn", example: "" },
    { word: "Phenomenon", definition: "hiện tượng", example: "" },
    { word: "Refreshment", definition: "đồ ăn nhẹ, giải khát", example: "" },
];

const listening_tong_hop_test_9: VocabItem[] = [
    { word: "Cover for", definition: "làm thay, che chở", example: "" },
    { word: "Seminar", definition: "hội thảo", example: "" },
    { word: "Blouse", definition: "áo sơ mi nữ", example: "" },
    { word: "Safety goggles", definition: "kính bảo hộ", example: "" },
    { word: "Safety regulation", definition: "quy định an toàn", example: "" },
    { word: "Scarf", definition: "khăn quàng", example: "" },
    { word: "Retire", definition: "nghỉ hưu", example: "" },
    { word: "Refrigerator", definition: "tủ lạnh", example: "" },
    { word: "Bottle of water", definition: "chai nước", example: "" },
    { word: "Guidebook", definition: "sách hướng dẫn", example: "" },
    { word: "Job fair", definition: "hội chợ việc làm", example: "" },
    { word: "Folder", definition: "bìa hồ sơ", example: "" },
    { word: "Printer", definition: "máy in", example: "" },
    { word: "Take a photograph", definition: "chụp ảnh", example: "" },
    { word: "Plate", definition: "đĩa", example: "" },
    { word: "Elevator", definition: "thang máy", example: "" },
    { word: "Distribute", definition: "phân phát", example: "" },
    { word: "Flyer", definition: "tờ rơi", example: "" },
    { word: "Stuck", definition: "bị kẹt", example: "" },
    { word: "Be supposed to", definition: "được cho là", example: "" },
    { word: "Supply", definition: "cung cấp", example: "" },
    { word: "Supplies", definition: "vật tư", example: "" },
    { word: "Briefcase", definition: "cặp đựng tài liệu", example: "" },
    { word: "Briefing", definition: "buổi họp thông tin", example: "" },
    { word: "Patient", definition: "bệnh nhân", example: "" },
    { word: "Health care", definition: "chăm sóc sức khỏe", example: "" },
    { word: "Reception desk", definition: "bàn tiếp tân", example: "" },
    { word: "Role", definition: "vai trò", example: "" },
    { word: "Be responsible for", definition: "chịu trách nhiệm", example: "" },
    { word: "Shift", definition: "ca làm việc", example: "" },
    { word: "Hiking", definition: "đi bộ đường dài", example: "" },
    { word: "Look forward to Ving", definition: "mong đợi", example: "" },
    { word: "Have sth at your feet", definition: "có cơ hội kiểm soát cái gì", example: "" },
    { word: "Custodian", definition: "người trông coi, bảo vệ", example: "" },
    { word: "Demand", definition: "yêu cầu", example: "" },
    { word: "Involve", definition: "liên quan", example: "" },
    { word: "Competitive", definition: "có tính cạnh tranh", example: "" },
    { word: "Emphasize", definition: "nhấn mạnh", example: "" },
    { word: "Retail industry", definition: "ngành bán lẻ", example: "" },
    { word: "Refer", definition: "tham khảo, ám chỉ", example: "" },
    { word: "Advertise", definition: "quảng cáo", example: "" },
    { word: "Appreciate", definition: "cảm kích", example: "" },
    { word: "Dealership", definition: "đại lý", example: "" },
    { word: "Handhold", definition: "chỗ tay cầm", example: "" },
    { word: "Reclaim", definition: "tái sử dụng, đòi lại", example: "" },
    { word: "Lumber", definition: "gỗ xây dựng", example: "" },
    { word: "Incorporate sth into sth", definition: "kết hợp cái gì vào cái gì", example: "" },
    { word: "Tear down", definition: "phá dỡ", example: "" },
    { word: "Cost-effective", definition: "hiệu quả về chi phí", example: "" },
    { word: "Barn", definition: "nhà kho", example: "" },
    { word: "Reusable", definition: "tái sử dụng được", example: "" },
    { word: "Durability", definition: "độ bền", example: "" },
    { word: "Demonstration", definition: "sự minh họa, trình diễn", example: "" },
    { word: "Give sb a tour", definition: "dẫn ai đó đi tham quan", example: "" },
    { word: "Spotlight", definition: "điểm nổi bật, chiếu sáng", example: "" },
    { word: "Expand", definition: "mở rộng", example: "" },
    { word: "Journalist", definition: "nhà báo", example: "" },
    { word: "Automobile", definition: "xe hơi", example: "" },
    { word: "Justify", definition: "biện minh", example: "" },
    { word: "Assumption", definition: "giả định", example: "" },
    { word: "Employer", definition: "nhà tuyển dụng", example: "" },
    { word: "Reinforce", definition: "củng cố", example: "" },
    { word: "Pedestrian", definition: "người đi bộ", example: "" },
    { word: "Capacity", definition: "sức chứa, năng lực", example: "" },
    { word: "Significant", definition: "đáng kể, quan trọng", example: "" },
    { word: "Get back to sb", definition: "liên lạc lại với ai", example: "" },
    { word: "Take a look", definition: "xem qua, kiểm tra", example: "" },
    { word: "Revise", definition: "sửa đổi, chỉnh sửa", example: "" },
    { word: "Itinerary", definition: "lịch trình", example: "" },
    { word: "Look into", definition: "điều tra, xem xét", example: "" },
    { word: "Advocate", definition: "người ủng hộ; ủng hộ", example: "" },
    { word: "Perhaps", definition: "có lẽ", example: "" },
    { word: "Bid", definition: "đấu thầu; trả giá", example: "" },
    { word: "Replacement", definition: "sự thay thế", example: "" },
    { word: "Exceed", definition: "vượt quá", example: "" },
    { word: "Infrastructure", definition: "cơ sở hạ tầng", example: "" },
    { word: "Steel", definition: "thép", example: "" },
    { word: "Priority", definition: "sự ưu tiên", example: "" },
    { word: "Rush", definition: "vội vàng, gấp rút", example: "" },
    { word: "Initial", definition: "ban đầu", example: "" },
    { word: "Put sth ahead", definition: "ưu tiên điều gì", example: "" },
    { word: "Issue", definition: "phát hành, đưa ra", example: "" },
    { word: "Furnish", definition: "cung cấp, trang bị", example: "" },
    { word: "Unique", definition: "độc đáo, duy nhất", example: "" },
    { word: "Hardwood", definition: "gỗ cứng", example: "" },
    { word: "Compact", definition: "nhỏ gọn", example: "" },
    { word: "Fold", definition: "gấp, xếp", example: "" },
    { word: "Throw into", definition: "lao vào, bắt đầu làm gì", example: "" },
    { word: "Spacious", definition: "rộng rãi", example: "" },
    { word: "Guarantee", definition: "bảo đảm", example: "" },
    { word: "Enter", definition: "đi vào", example: "" },
    { word: "Subscribe", definition: "đăng ký", example: "" },
    { word: "Newsletter", definition: "bản tin", example: "" },
    { word: "Remain", definition: "vẫn còn, duy trì", example: "" },
    { word: "Moderate", definition: "vừa phải, điều độ", example: "" },
    { word: "Head into", definition: "đi vào", example: "" },
    { word: "Initiative", definition: "sáng kiến", example: "" },
    { word: "Appropriate", definition: "thích hợp", example: "" },
    { word: "Public transportation", definition: "phương tiện giao thông công cộng", example: "" },
    { word: "Antique", definition: "cổ điển", example: "" },
    { word: "Out of business", definition: "phá sản, ngừng kinh doanh", example: "" },
    { word: "Shut down", definition: "đóng cửa, ngừng hoạt động", example: "" },
    { word: "In person", definition: "trực tiếp", example: "" },
    { word: "Remodel", definition: "tu sửa, cải tạo", example: "" },
    { word: "Wrap up", definition: "hoàn thành, kết thúc", example: "" },
    { word: "Evaluate", definition: "đánh giá", example: "" },
    { word: "Throw a party", definition: "tổ chức tiệc", example: "" },
    { word: "Strive to V", definition: "phấn đấu để làm gì", example: "" },
    { word: "Meet the needs", definition: "đáp ứng nhu cầu", example: "" },
    { word: "Diverse", definition: "đa dạng", example: "" },
    { word: "Population", definition: "dân số", example: "" },
    { word: "Familiar", definition: "quen thuộc", example: "" },
    { word: "Investor", definition: "nhà đầu tư", example: "" },
    { word: "Adjacent", definition: "liền kề", example: "" },
    { word: "Charity", definition: "tổ chức từ thiện", example: "" },
    { word: "Awareness of", definition: "nhận thức về", example: "" },
    { word: "Interrupt", definition: "gián đoạn", example: "" },
    { word: "Portal", definition: "cổng thông tin điện tử", example: "" },
    { word: "Adjust", definition: "điều chỉnh", example: "" },
    { word: "Take over", definition: "tiếp quản", example: "" },
    { word: "Expense", definition: "chi phí", example: "" },
    { word: "Reserve", definition: "đặt trước, dự trữ", example: "" },
    { word: "Handle", definition: "xử lý, giải quyết", example: "" },
    { word: "Pottery", definition: "đồ gốm", example: "" },
    { word: "Capable", definition: "có khả năng", example: "" },
    { word: "Projector", definition: "máy chiếu", example: "" },
    { word: "Agent", definition: "đại lý, tác nhân", example: "" },
    { word: "Experience (v)", definition: "trải nghiệm", example: "" },
    { word: "Refer", definition: "tham khảo, đề cập", example: "" },
    { word: "Incentive", definition: "động lực", example: "" },
    { word: "Lounge", definition: "phòng chờ", example: "" },
    { word: "Hospitality", definition: "lòng hiếu khách", example: "" },
    { word: "Inventory", definition: "hàng tồn kho, kiểm kê", example: "" },
    { word: "Designate", definition: "chỉ định", example: "" },
    { word: "Reminder", definition: "lời nhắc", example: "" },
    { word: "Lock", definition: "ổ khóa", example: "" },
    { word: "Bonus", definition: "tiền thưởng", example: "" },
    { word: "Ingredient", definition: "nguyên liệu, thành phần", example: "" },
    { word: "Fresh", definition: "tươi", example: "" },
    { word: "Road construction", definition: "xây dựng đường", example: "" },
    { word: "Entrance", definition: "lối vào", example: "" },
    { word: "Alternate", definition: "thay thế, luân phiên", example: "" },
    { word: "Container", definition: "thùng chứa, đồ chứa", example: "" },
    { word: "Resident", definition: "cư dân", example: "" },
    { word: "In progress", definition: "đang tiến hành, đang thực hiện", example: "" },
    { word: "Election", definition: "cuộc bầu cử", example: "" },
    { word: "Elect", definition: "bầu cử, chọn lựa", example: "" },
    { word: "Approach (v, n)", definition: "tiếp cận, phương pháp", example: "" },
    { word: "Debate", definition: "cuộc tranh luận, tranh luận", example: "" },
    { word: "Congestion", definition: "sự tắc nghẽn, đông đúc", example: "" },
    { word: "Fund-raiser", definition: "buổi gây quỹ", example: "" },
];

const listening_tong_hop_test_10: VocabItem[] = [
    { word: "At the latest", definition: "muộn nhất", example: "" },
    { word: "Trailer", definition: "xe kéo, toa xe, trailer", example: "" },
    { word: "Credit card", definition: "thẻ tín dụng", example: "" },
    { word: "Speed limit", definition: "giới hạn tốc độ", example: "" },
    { word: "Instructor", definition: "giảng viên, huấn luyện viên", example: "" },
    { word: "Lobby", definition: "sảnh, hành lang", example: "" },
    { word: "Postpone", definition: "hoãn lại", example: "" },
    { word: "Outdated", definition: "lỗi thời, cổ hủ", example: "" },
    { word: "Rent", definition: "thuê, tiền thuê", example: "" },
    { word: "Projection", definition: "sự ước tính, sự dự đoán", example: "" },
    { word: "Projector", definition: "máy chiếu", example: "" },
    { word: "Reject", definition: "từ chối, bác bỏ", example: "" },
    { word: "Portable", definition: "di động, có thể mang theo", example: "" },
    { word: "Surplus", definition: "thặng dư, dư thừa", example: "" },
    { word: "Headset", definition: "tai nghe", example: "" },
    { word: "General contractor", definition: "nhà thầu chính", example: "" },
    { word: "Merge", definition: "hợp nhất", example: "" },
    { word: "Patient", definition: "bệnh nhân", example: "" },
    { word: "Cabinet", definition: "tủ, tủ đựng đồ", example: "" },
    { word: "Harvest", definition: "thu hoạch, thu gặt", example: "" },
    { word: "Flavor", definition: "hương vị", example: "" },
    { word: "Finalize", definition: "hoàn tất, kết thúc", example: "" },
    { word: "Make a reservation", definition: "đặt chỗ, đặt trước", example: "" },
    { word: "Mention", definition: "đề cập, nhắc đến", example: "" },
    { word: "Private", definition: "riêng tư, cá nhân", example: "" },
    { word: "Patio", definition: "sân hiên, sân ngoài trời", example: "" },
    { word: "Appetizer", definition: "món khai vị", example: "" },
    { word: "Seat", definition: "chỗ ngồi", example: "" },
    { word: "Quiet", definition: "yên tĩnh, im lặng", example: "" },
    { word: "Hiking", definition: "đi bộ đường dài", example: "" },
    { word: "Look forward to Ving", definition: "mong đợi làm gì", example: "" },
    { word: "Actually", definition: "thực tế, trên thực tế", example: "" },
    { word: "Reserve", definition: "đặt trước", example: "" },
    { word: "Permit", definition: "giấy phép", example: "" },
    { word: "Colleague", definition: "đồng nghiệp", example: "" },
    { word: "Waitstaff", definition: "nhân viên phục vụ", example: "" },
    { word: "Thrilled", definition: "rất vui, phấn khích", example: "" },
    { word: "Collaboration", definition: "sự hợp tác", example: "" },
    { word: "Partner", definition: "hợp tác", example: "" },
    { word: "Signature", definition: "đặc trưng, tiêu biểu", example: "" },
    { word: "Partnership", definition: "quan hệ đối tác, sự hợp tác", example: "" },
    { word: "Be proud of", definition: "tự hào về", example: "" },
    { word: "Promote", definition: "thăng chức, quảng bá", example: "" },
    { word: "Recycled materials", definition: "vật liệu tái chế", example: "" },
    { word: "Initiative", definition: "sáng kiến", example: "" },
    { word: "Relocate", definition: "di chuyển, chuyển đến", example: "" },
    { word: "Press conference", definition: "cuộc họp báo", example: "" },
    { word: "Emphasize", definition: "nhấn mạnh", example: "" },
    { word: "Customize", definition: "tùy chỉnh", example: "" },
    { word: "Durable", definition: "bền, chắc chắn", example: "" },
    { word: "Conduct an interview", definition: "tiến hành phỏng vấn", example: "" },
    { word: "Annual", definition: "hàng năm", example: "" },
    { word: "Charity", definition: "tổ chức từ thiện", example: "" },
    { word: "Sponsor", definition: "tài trợ, nhà tài trợ", example: "" },
    { word: "Donate", definition: "quyên góp, tặng", example: "" },
    { word: "Top-of-the-line", definition: "cao cấp, hàng đầu", example: "" },
    { word: "Costly", definition: "đắt đỏ", example: "" },
    { word: "Expense", definition: "chi phí", example: "" },
    { word: "Caterer", definition: "nhà cung cấp thực phẩm, dịch vụ ăn uống", example: "" },
    { word: "Badge", definition: "huy hiệu, thẻ", example: "" },
    { word: "Manufacturer", definition: "nhà sản xuất", example: "" },
    { word: "Take apart", definition: "tháo rời", example: "" },
    { word: "Knowledgeable", definition: "am hiểu, hiểu biết", example: "" },
    { word: "Security guard", definition: "bảo vệ, nhân viên an ninh", example: "" },
    { word: "Vacuum cleaner", definition: "máy hút bụi", example: "" },
    { word: "Facility", definition: "cơ sở, trang thiết bị", example: "" },
    { word: "Win", definition: "giành được, chiến thắng", example: "" },
    { word: "Rush", definition: "sự vội vã, sự khẩn trương", example: "" },
    { word: "Take over", definition: "tiếp quản, đảm nhận", example: "" },
    { word: "Supervisor", definition: "người giám sát", example: "" },
    { word: "Competition", definition: "sự cạnh tranh, cuộc thi", example: "" },
    { word: "Postpone", definition: "hoãn lại", example: "" },
    { word: "Keynote speech", definition: "bài phát biểu chính", example: "" },
    { word: "Specialist", definition: "chuyên gia", example: "" },
    { word: "Take medicine", definition: "uống thuốc", example: "" },
    { word: "Rent", definition: "thuê, tiền thuê", example: "" },
    { word: "Quite", definition: "khá, hoàn toàn", example: "" },
    { word: "Dock", definition: "bến tàu, cảng", example: "" },
    { word: "Assign", definition: "phân công", example: "" },
    { word: "Utility", definition: "tiện ích, dịch vụ tiện ích", example: "" },
    { word: "Workbook", definition: "sách bài tập, sổ tay", example: "" },
    { word: "Learn", definition: "học, biết được", example: "" },
    { word: "Insert", definition: "tờ thông tin, vật chèn vào", example: "" },
    { word: "Inform sb of/about sth", definition: "thông báo cho ai về điều gì", example: "" },
    { word: "Revise", definition: "sửa lại, ôn lại", example: "" },
    { word: "Counselor", definition: "cố vấn, tư vấn viên", example: "" },
    { word: "Programmer", definition: "lập trình viên", example: "" },
    { word: "Compliment", definition: "lời khen ngợi, khen ngợi", example: "" },
    { word: "Inventory", definition: "hàng tồn kho, kiểm kê", example: "" },
    { word: "Seaport", definition: "cảng biển", example: "" },
    { word: "Nervous", definition: "lo lắng, căng thẳng", example: "" },
    { word: "Shadow", definition: "theo dõi, bám sát", example: "" },
    { word: "Mechanics", definition: "cơ khí", example: "" },
    { word: "Make a mistake", definition: "phạm sai lầm", example: "" },
    { word: "Captain", definition: "đội trưởng, thuyền trưởng", example: "" },
    { word: "Commute", definition: "đi lại (từ nhà đến nơi làm việc)", example: "" },
    { word: "Traffic volume", definition: "lưu lượng giao thông", example: "" },
    { word: "Storage area", definition: "khu vực lưu trữ", example: "" },
    { word: "Rental facility", definition: "cơ sở cho thuê", example: "" },
    { word: "Barricade", definition: "hàng rào chắn, vật chắn", example: "" },
    { word: "Retreat", definition: "sự rút lui, kỳ nghỉ dưỡng", example: "" },
    { word: "Orchard", definition: "vườn cây ăn quả", example: "" },
    { word: "Draft", definition: "bản thảo, dự thảo", example: "" },
    { word: "Recruit", definition: "tuyển dụng, chiêu mộ", example: "" },
    { word: "Interior", definition: "nội thất, bên trong", example: "" },
    { word: "Maintenance", definition: "bảo trì, sự duy trì", example: "" },
    { word: "Laundry", definition: "giặt giũ", example: "" },
    { word: "Skip", definition: "bỏ qua", example: "" },
    { word: "Duty", definition: "nghĩa vụ, bổn phận", example: "" },
    { word: "Pantry", definition: "tủ đựng thực phẩm", example: "" },
    { word: "Sanitize", definition: "làm sạch, khử trùng", example: "" },
    { word: "Checklist", definition: "danh sách kiểm tra", example: "" },
    { word: "Up-to-date", definition: "cập nhật mới nhất", example: "" },
    { word: "Revision", definition: "sự sửa đổi, sự chỉnh sửa", example: "" },
    { word: "Resolve", definition: "giải quyết", example: "" },
    { word: "Inventory", definition: "hàng tồn kho, kiểm kê", example: "" },
    { word: "Article", definition: "bài viết", example: "" },
    { word: "Impact", definition: "tác động", example: "" },
    { word: "Regulation", definition: "quy định, điều lệ", example: "" },
    { word: "Aside from", definition: "ngoài ra", example: "" },
    { word: "Lawmaker", definition: "nhà lập pháp", example: "" },
    { word: "Statistic", definition: "số liệu thống kê", example: "" },
    { word: "Ranger", definition: "kiểm lâm, nhân viên bảo vệ", example: "" },
    { word: "Artificial intelligence", definition: "trí tuệ nhân tạo", example: "" },
    { word: "Delighted", definition: "rất vui mừng", example: "" },
    { word: "Simulate", definition: "mô phỏng", example: "" },
    { word: "Demonstration", definition: "sự biểu diễn, cuộc biểu tình", example: "" },
    { word: "Interactive", definition: "tương tác", example: "" },
    { word: "Bathtub", definition: "bồn tắm", example: "" },
    { word: "Customization", definition: "sự tùy chỉnh", example: "" },
    { word: "Designate", definition: "chỉ định, chỉ ra", example: "" },
    { word: "Run a raffle", definition: "tổ chức xổ số", example: "" },
    { word: "Trade show", definition: "hội chợ thương mại", example: "" },
    { word: "Distribute", definition: "phân phối", example: "" },
    { word: "Contest", definition: "cuộc thi", example: "" },
    { word: "Refreshment", definition: "món ăn nhẹ, nước giải khát", example: "" },
    { word: "Commercial", definition: "quảng cáo", example: "" },
    { word: "Address", definition: "giải quyết, phát biểu", example: "" },
    { word: "Adjustment", definition: "sự điều chỉnh", example: "" },
    { word: "Hospitality", definition: "sự hiếu khách", example: "" },
    { word: "Sales figures", definition: "số liệu bán hàng", example: "" },
    { word: "Leak", definition: "sự rò rỉ, chỗ thủng", example: "" },
    { word: "Liquid", definition: "chất lỏng", example: "" },
    { word: "Steer", definition: "lái (xe, tàu)", example: "" },
    { word: "Valve", definition: "van, khóa", example: "" },
    { word: "Void", definition: "khoảng trống, sự thiếu vắng", example: "" },
    { word: "Give a talk", definition: "thuyết trình, nói chuyện", example: "" },
    { word: "Stop by", definition: "ghé qua", example: "" },
    { word: "Advance", definition: "sự tiến bộ, tiến lên", example: "" },
    { word: "Clinic", definition: "phòng khám", example: "" },
    { word: "Chart", definition: "biểu đồ", example: "" },
    { word: "Take up", definition: "bắt đầu (sở thích, hoạt động)", example: "" },
    { word: "Supplier", definition: "nhà cung cấp", example: "" },
    { word: "Bring in", definition: "mang đến", example: "" },
    { word: "Affordable", definition: "phải chăng", example: "" },
    { word: "Familiar with", definition: "quen thuộc với", example: "" },
    { word: "Relocate", definition: "di chuyển đến nơi khác", example: "" },
    { word: "Backpack", definition: "ba lô", example: "" },
    { word: "Sturdy", definition: "vững chắc, bền", example: "" },
    { word: "Bulk", definition: "số lượng lớn, khối lượng lớn", example: "" },
    { word: "In bulk", definition: "với số lượng lớn", example: "" },
    { word: "Return policy", definition: "chính sách đổi trả", example: "" },
    { word: "Expedited shipping", definition: "giao hàng nhanh", example: "" },
    { word: "Fund", definition: "quỹ, nguồn tài trợ", example: "" },
    { word: "Loan", definition: "khoản vay", example: "" },
];

export const listeningComprehensiveVocabulary: VocabularyPart = {
    id: 100,
    title: "Listening tổng hợp",
    description: "Nhóm từ vựng phổ biến trong Listening Part 2,3 & 4. ",
    tests: [
        { id: 1001, title: "Test 1", words: listening_tong_hop_test_1 },
        { id: 1002, title: "Test 2", words: listening_tong_hop_test_2 },
        { id: 1003, title: "Test 3", words: listening_tong_hop_test_3 },
        { id: 1004, title: "Test 4", words: listening_tong_hop_test_4 },
        { id: 1005, title: "Test 5", words: listening_tong_hop_test_5 },
        { id: 1006, title: "Test 6", words: listening_tong_hop_test_6 },
        { id: 1007, title: "Test 7", words: listening_tong_hop_test_7 },
        { id: 1008, title: "Test 8", words: listening_tong_hop_test_8 },
        { id: 1009, title: "Test 9", words: listening_tong_hop_test_9 },
        { id: 1010, title: "Test 10", words: listening_tong_hop_test_10 },
    ]
};
