
import { VocabularyPart } from '../../types';

export const listeningBasicVocabulary: VocabularyPart = {
    id: 150,
    title: "Listening Cơ Bản",
    description: "Các từ vựng Listening cơ bản và phổ biến trong Part 2,3,4",
    tests: [
        // Part 2
        { 
            id: 15001, 
            title: "Part 2 (7-17)", 
            words: [
                { word: "building", definition: "tòa nhà", example: "How old is this building?" },
                { word: "material", definition: "vật liệu, tài liệu", example: "We need to ship some materials today." },
                { word: "office", definition: "văn phòng", example: "The manager is in his office." },
                { word: "performance", definition: "hiệu suất, buổi biểu diễn", example: "Can you come to my performance tonight?" },
                { word: "local", definition: "địa phương", example: "Most of the band members are local musicians." },
                { word: "late", definition: "muộn", example: "I'm sorry I was late for the meeting." },
                { word: "apartment", definition: "căn hộ", example: "Which apartment submitted the work order?" },
                { word: "submit", definition: "nộp, đệ trình", example: "Please submit your assignment here." },
                { word: "work order", definition: "lệnh làm việc, phiếu công việc", example: "The tenants submitted a work order." },
                { word: "assignment", definition: "nhiệm vụ, bài tập", example: "When is the assignment due?" },
                { word: "tenants", definition: "người thuê nhà", example: "The tenants are responsible for the utilities." },
                { word: "contact", definition: "liên hệ", example: "Will you contact the vendor about the delivery?" },
                { word: "vendor", definition: "nhà cung cấp, người bán", example: "We need to find a new office supply vendor." },
                { word: "delivery", definition: "sự giao hàng", example: "The delivery date has been changed." },
                { word: "date", definition: "ngày tháng", example: "What is the date of the meeting?" },
                { word: "take care of", definition: "chăm sóc, giải quyết", example: "I'll take care of that e-mail receipt." },
                { word: "receipt", definition: "hóa đơn, biên lai", example: "Please save your receipt for reimbursement." },
                { word: "maintenance", definition: "bảo trì", example: "The maintenance worker is here to fix the light." },
                { word: "worker", definition: "người lao động, công nhân", example: "The factory worker is very skilled." },
                { word: "light", definition: "đèn, ánh sáng", example: "The light in the hallway needs to be replaced." },
                { word: "fix", definition: "sửa chữa", example: "Can you help me fix the printer?" },
                { word: "management", definition: "ban quản lý", example: "Management made a hiring decision." },
                { word: "hiring", definition: "việc tuyển dụng", example: "The hiring process took three weeks." },
                { word: "decision", definition: "quyết định", example: "We need to make a final decision." },
                { word: "shelf", definition: "cái kệ, giá", example: "Put it on the highest shelf." },
                { word: "personnel", definition: "nhân sự", example: "Contact the personnel department for help." },
                { word: "department", definition: "phòng ban", example: "Which department do you work in?" },
                { word: "chose", definition: "đã chọn", example: "They chose a new office layout." },
                { word: "cafeteria", definition: "căng tin, quán ăn tự phục vụ", example: "Let's eat in the office cafeteria." },
                { word: "employment", definition: "việc làm", example: "She signed the employment contract." },
                { word: "contract", definition: "hợp đồng", example: "The contract is legally binding." },
                { word: "agree", definition: "đồng ý", example: "I would agree with that statement." },
                { word: "send", definition: "gửi", example: "I'll send the file now." },
                { word: "manual", definition: "sách hướng dẫn", example: "Check the employee manual." },
                { word: "division", definition: "bộ phận, phân khu", example: "Our division's picnic is this Saturday." },
                { word: "forecast", definition: "dự báo", example: "There's rain in the forecast." },
                { word: "corridor", definition: "hành lang", example: "Walk to the end of this corridor." },
                { word: "a few", definition: "một vài", example: "I will be there in a few minutes." },
                { word: "achieve", definition: "đạt được", example: "We achieved our sales targets." },
                { word: "target", definition: "mục tiêu", example: "Did we reach the target?" },
                { word: "sale", definition: "việc bán hàng, giảm giá", example: "The store is having a big sale." },
                { word: "excellent", definition: "xuất sắc", example: "That is excellent news!" },
                { word: "to the end", definition: "cho đến cuối", example: "We need to work until the end of April." },
                { word: "a few times", definition: "một vài lần", example: "I checked the schedule a few times." }
            ] 
        },
        { 
            id: 15002, 
            title: "Part 2 (18-31)", 
            words: [
                { word: "travel", definition: "đi lại, du hành", example: "How often do you travel for your job?" },
                { word: "job", definition: "công việc", example: "I really like working with computers." },
                { word: "turned out", definition: "hóa ra, diễn ra", example: "It turned out well." },
                { word: "find", definition: "tìm thấy", example: "Yes, I did find one." },
                { word: "once a month", definition: "mỗi tháng một lần", example: "I travel about once a month." },
                { word: "hike", definition: "đi bộ đường dài", example: "We should hike the Wildflower Trail today." },
                { word: "trail", definition: "đường mòn", example: "Which trail is the easiest?" },
                { word: "seat", definition: "chỗ ngồi", example: "This seat is available." },
                { word: "available", definition: "có sẵn, rảnh", example: "Is this seat available?" },
                { word: "bring", definition: "mang theo", example: "I didn't bring my boots." },
                { word: "boots", definition: "đôi ủng, giày cao cổ", example: "You'll need hiking boots for this trail." },
                { word: "visitor", definition: "khách thăm quan", example: "Check in at the visitors' center." },
                { word: "center", definition: "trung tâm", example: "The visitors' center is down the street." },
                { word: "book", definition: "đặt chỗ (v)", example: "You've booked a hotel in London, haven't you?" },
                { word: "hotel", definition: "khách sạn", example: "The hotel is fully booked." },
                { word: "enjoyable", definition: "thú vị", example: "The trip was very enjoyable, thanks." },
                { word: "usually", definition: "thường xuyên", example: "He usually takes the train." },
                { word: "take the train", definition: "đi tàu hỏa", example: "I usually take the train to work." },
                { word: "reservation", definition: "sự đặt chỗ", example: "Yes, I made a reservation last week." },
                { word: "ticket", definition: "vé", example: "Are there any tickets left for tonight's concert?" },
                { word: "left", definition: "còn lại", example: "Are there any tickets left?" },
                { word: "concert", definition: "buổi hòa nhạc", example: "He's a concert violinist." },
                { word: "sold out", definition: "bán hết", example: "The concert is sold out." },
                { word: "use", definition: "sử dụng", example: "Haven't you used this software before?" },
                { word: "software", definition: "phần mềm", example: "We need to update the accounting software." },
                { word: "before", definition: "trước khi", example: "Have you used it before?" },
                { word: "take your order", definition: "ghi món, nhận đơn hàng", example: "Can I take your order?" },
                { word: "chance", definition: "cơ hội", example: "I haven't had the chance to test it." },
                { word: "dollar", definition: "đô la", example: "The repair costs about 40 dollars." },
                { word: "blender", definition: "máy xay sinh tố", example: "When is the new blender going to be released?" },
                { word: "released", definition: "phát hành, ra mắt", example: "The product will be released next month." },
                { word: "fruit", definition: "trái cây", example: "Only with fruits and vegetables." },
                { word: "vegetables", definition: "rau củ", example: "Fresh vegetables are delivered daily." },
                { word: "kitchen", definition: "nhà bếp", example: "The blender is in the kitchen cabinet." },
                { word: "cabinet", definition: "tủ", example: "Put the glasses in the cabinet." },
                { word: "prototype", definition: "nguyên mẫu, mẫu thử", example: "The prototype is still being tested." },
                { word: "still", definition: "vẫn còn", example: "It is still in development." },
                { word: "tested", definition: "được thử nghiệm", example: "The system was tested yesterday." },
                { word: "picking up", definition: "đón, lấy", example: "Who's picking up our clients at the airport?" },
                { word: "client", definition: "khách hàng", example: "Our clients are arriving today." },
                { word: "airport", definition: "sân bay", example: "Meet them at terminal 2 of the airport." },
                { word: "decide", definition: "quyết định", example: "They decided to drive instead." },
                { word: "drive", definition: "lái xe", example: "Can you drive to the terminal?" },
                { word: "terminal", definition: "nhà ga (sân bay)", example: "Meet me at terminal 2." },
                { word: "marketing", definition: "tiếp thị", example: "It's a marketing position." },
                { word: "position", definition: "vị trí, chức vụ", example: "Apply for the open position." },
                { word: "roses", definition: "hoa hồng", example: "Where are the red roses?" },
                { word: "came in", definition: "vừa về, vừa tới", example: "The shipment came in this morning." },
                { word: "morning", definition: "buổi sáng", example: "The roses came in this morning." },
                { word: "liter", definition: "lít", example: "About three liters of water." },
                { word: "check out", definition: "kiểm tra, xem qua", example: "No, I didn't check out the sale." },
                { word: "large", definition: "lớn", example: "I needed some for a large bouquet." },
                { word: "bouquet", definition: "bó hoa", example: "She received a beautiful bouquet." },
                { word: "film", definition: "bộ phim", example: "This film has been nominated for several awards." },
                { word: "nominated", definition: "được đề cử", example: "The actor was nominated for an award." },
                { word: "several", definition: "một vài", example: "It has won several awards." },
                { word: "award", definition: "giải thưởng", example: "The film won several awards." },
                { word: "why don't we", definition: "tại sao chúng ta không...", example: "Why don't we go see it?" },
                { word: "see", definition: "xem, nhìn", example: "Why don't we go see the film?" },
                { word: "announcement", definition: "thông báo", example: "Wait until after the announcement." },
                { word: "great", definition: "tuyệt vời", example: "He made a great speech." },
                { word: "speech", definition: "bài phát biểu", example: "The director's speech was inspiring." },
                { word: "interested in", definition: "quan tâm đến", example: "Who's interested in starting a car pool program?" },
                { word: "car pool", definition: "đi chung xe", example: "Let's start a car pool program." },
                { word: "program", definition: "chương trình", example: "It's a very interesting program." },
                { word: "swim", definition: "bơi", example: "Thanks, but I can't swim." },
                { word: "organize", definition: "tổ chức", example: "Clara's already organizing one." },
                { word: "article", definition: "bài báo", example: "It's a very interesting article." },
                { word: "teach", definition: "dạy", example: "Where will I teach my workshop this month?" },
                { word: "workshop", definition: "hội thảo", example: "The workshop starts at ten A.M." },
                { word: "all", definition: "tất cả", example: "We just sent an e-mail to all instructors." },
                { word: "instructor", definition: "người hướng dẫn", example: "Send an e-mail to the instructors." },
                { word: "beautiful building", definition: "tòa nhà đẹp", example: "Yes, it's a beautiful building." },
                { word: "moving", definition: "dời đi, chuyển động", example: "Why are we moving these sweaters?" },
                { word: "sweaters", definition: "áo len", example: "Move the sweaters to the back of the store." },
                { word: "store", definition: "cửa hàng", example: "The store is in the new shopping mall." },
                { word: "shopping mall", definition: "trung tâm mua sắm", example: "The mall is near the station." },
                { word: "come in", definition: "hàng về", example: "Our spring merchandise is coming in soon." },
                { word: "spring", definition: "mùa xuân", example: "Spring merchandise is arriving." },
                { word: "merchandise", definition: "hàng hóa", example: "The merchandise arrived yesterday." },
                { word: "arrive", definition: "đến", example: "When will the shipment arrive?" },
                { word: "soon", definition: "sớm, chẳng bao lâu", example: "The bus should be here soon." },
                { word: "working on", definition: "đang làm việc với", example: "Would you be interested in working on some of these contracts?" },
                { word: "lens prescription", definition: "đơn kính", example: "A contact lens prescription." },
                { word: "limited time", definition: "thời gian có hạn", example: "I have very limited time." },
                { word: "type", definition: "loại", example: "What type of job are you looking for?" },
                { word: "looking for", definition: "tìm kiếm", example: "What are you looking for?" },
                { word: "working with", definition: "làm việc với", example: "I really like working with computers." },
                { word: "computer", definition: "máy tính", example: "The computer needs repair." },
                { word: "resume", definition: "sơ yếu lý lịch", example: "Just a résumé is needed." },
                { word: "needed", definition: "cần thiết", example: "More supplies are needed." }
            ] 
        },
        
        // Part 3
        { 
            id: 15003, 
            title: "Part 3 (32-34)", 
            words: [
                { word: "organize", definition: "tổ chức", example: "Thank you for organizing the annual company picnic." },
                { word: "annual", definition: "hàng năm", example: "We're organizing the annual employee retreat." },
                { word: "company picnic", definition: "buổi dã ngoại công ty", example: "Everybody seemed to enjoy the company picnic." },
                { word: "seem", definition: "dường như", example: "Everybody seemed to enjoy the event." },
                { word: "enjoy", definition: "thưởng thức, tận hưởng", example: "I hope you enjoy the conference!" },
                { word: "deserve", definition: "xuất sắc, xứng đáng", example: "We deserved it after working so hard." },
                { word: "working hard", definition: "làm việc chăm chỉ", example: "The team has been working hard all year." },
                { word: "great", definition: "tuyệt vời", example: "The food was great, by the way." },
                { word: "especially", definition: "đặc biệt là", example: "I especially liked the peach pie." },
                { word: "would you mind", definition: "bạn có phiền không", example: "Would you mind sharing the recipe?" },
                { word: "sharing", definition: "chia sẻ", example: "Thanks for sharing your thoughts with us." },
                { word: "recipe", definition: "công thức nấu ăn", example: "I found the recipe online." },
                { word: "delicious", definition: "ngon miệng", example: "The meal was absolutely delicious." },
                { word: "found", definition: "tìm thấy (quá khứ)", example: "I found your keys on the desk." },
                { word: "online", definition: "trực tuyến", example: "You can book your tickets online." },
                { word: "link", definition: "đường dẫn, liên kết", example: "I'll send you a link to the web page." },
                { word: "web page", definition: "trang web", example: "Check our web page for more details." },
                { word: "helpful", definition: "có ích", example: "The video was really helpful." },
                { word: "video", definition: "phim, đoạn video", example: "Watch the instructional video first." },
                { word: "walk you through", definition: "hướng dẫn chi tiết", example: "The video walks you through all the steps." },
                { word: "step", definition: "bước", example: "Follow each step carefully." },
                { word: "recommend", definition: "khuyên, đề xuất", example: "I recommend you watch it first." },
                { word: "watch", definition: "xem", example: "I'll watch the presentation later." },
                { word: "first", definition: "đầu tiên", example: "The first thing to do is register." },
                { word: "all right", definition: "được rồi, ổn", example: "All right, I'll send it now." }
            ] 
        },
        { 
            id: 15004, 
            title: "Part 3 (35-37)", 
            words: [
                { word: "finish", definition: "kết thúc, hoàn thành", example: "I'd like to finish the report today." },
                { word: "I'd like", definition: "tôi muốn", example: "I'd like to calculate the expenses." },
                { word: "calculate", definition: "tính toán", example: "We need to calculate the total cost." },
                { word: "expense", definition: "chi phí", example: "Keep track of all your travel expenses." },
                { word: "report", definition: "báo cáo", example: "The expense report is due tomorrow." },
                { word: "reviewing", definition: "xem xét, đánh giá", example: "I'm still reviewing the forms." },
                { word: "travel", definition: "đi lại", example: "The travel budget has been reduced." },
                { word: "reimbursement", definition: "sự hoàn tiền", example: "Submit your forms for reimbursement." },
                { word: "form", definition: "mẫu đơn", example: "Please fill out this form." },
                { word: "department", definition: "phòng ban", example: "Which department are you in?" },
                { word: "almost done", definition: "gần xong", example: "I'm almost done with the review." },
                { word: "question", definition: "câu hỏi", example: "I have a question about this receipt." },
                { word: "receipt", definition: "biên lai", example: "Do you have the receipt for lunch?" },
                { word: "one of", definition: "một trong những", example: "He is one of our best employees." },
                { word: "employees", definition: "nhân viên", example: "All employees must attend the meeting." },
                { word: "problem", definition: "vấn đề", example: "What's the problem with the order?" },
                { word: "policy", definition: "chính sách", example: "It's against company policy." },
                { word: "list", definition: "danh sách", example: "Check the list of approved hotels." },
                { word: "approve", definition: "phê duyệt", example: "The manager will approve the expense." },
                { word: "accommodation", definition: "chỗ ở", example: "The company provides accommodation." },
                { word: "submitted", definition: "đã nộp", example: "The form was submitted late." },
                { word: "representative", definition: "người đại diện", example: "Talk to a sales representative." },
                { word: "forgotten", definition: "đã quên", example: "He might have forgotten the policy." },
                { word: "supervisor", definition: "người giám sát", example: "Ask your supervisor for help." },
                { word: "one time", definition: "một lần", example: "I can approve it this one time." }
            ] 
        },
        { 
            id: 15005, 
            title: "Part 3 (38-40)", 
            words: [
                { word: "How's everything up here", definition: "mọi thứ ở đây thế nào", example: "How's everything up here on deck?" },
                { word: "deck", definition: "boong tàu", example: "He is standing on the ship's deck." },
                { word: "uneventful night", definition: "một đêm bình yên", example: "It was an uneventful night at sea." },
                { word: "cargo", definition: "hàng hóa", example: "The cargo ship is still in the harbor." },
                { word: "ship", definition: "con tàu", example: "The ship will leave tomorrow." },
                { word: "yet", definition: "vẫn chưa", example: "The fog hasn't lifted yet." },
                { word: "hope", definition: "hy vọng", example: "I hope the weather improves soon." },
                { word: "fog", definition: "sương mù", example: "The fog is very thick today." },
                { word: "harbor", definition: "cảng", example: "The ship is waiting in the harbor." },
                { word: "lift", definition: "tan biến (sương mù)", example: "The fog should lift by noon." },
                { word: "soon", definition: "sớm", example: "We hope to arrive soon." },
                { word: "won't", definition: "sẽ không", example: "The ship won't be able to leave." },
                { word: "be able to", definition: "có thể", example: "I won't be able to attend." },
                { word: "leave", definition: "rời đi", example: "When does the train leave?" },
                { word: "until", definition: "cho đến khi", example: "Wait until the weather improves." },
                { word: "weather", definition: "thời tiết", example: "The weather is looking good." },
                { word: "improve", definition: "cải thiện", example: "I hope conditions improve soon." },
                { word: "get too far", definition: "đi quá xa", example: "I hope we don't get too far behind schedule." },
                { word: "behind", definition: "phía sau", example: "We are behind schedule." },
                { word: "schedule", definition: "lịch trình", example: "Check the flight schedule." },
                { word: "port authority", definition: "cơ quan quản lý cảng", example: "Call the port authority for updates." },
                { word: "update", definition: "cập nhật", example: "I'll call for an update soon." },
                { word: "clear", definition: "thông quan, dọn dẹp", example: "We'll be cleared to leave soon." },
                { word: "sounds good", definition: "nghe có vẻ ổn", example: "That sounds good to me." }
            ] 
        },
        { 
            id: 15006, 
            title: "Part 3 (41-43)", 
            words: [
                { word: "reservation", definition: "sự đặt chỗ", example: "I've made a reservation for lunch." },
                { word: "meet with", definition: "gặp gỡ", example: "I need to meet with some clients." },
                { word: "some clients", definition: "một vài khách hàng", example: "The clients are arriving at noon." },
                { word: "lunch", definition: "bữa trưa", example: "Let's discuss this over lunch." },
                { word: "under", definition: "tên của, dưới", example: "The reservation is under Cohen." },
                { word: "welcome", definition: "chào mừng", example: "Welcome to our restaurant." },
                { word: "be seated on", definition: "được ngồi ở", example: "I asked to be seated on the terrace." },
                { word: "beautiful", definition: "đẹp", example: "It's a beautiful day today." },
                { word: "terrace", definition: "hiên, sân thượng", example: "The terrace is very hot today." },
                { word: "table", definition: "cái bàn", example: "I can seat you at table four inside." },
                { word: "inside", definition: "bên trong", example: "It's much cooler inside." },
                { word: "do you mind", definition: "bạn có phiền không", example: "Do you mind waiting a few minutes?" },
                { word: "waiting", definition: "đang chờ", example: "I don't mind waiting." },
                { word: "not at all", definition: "không sao, không có gì", example: "Not at all, I have time." },
                { word: "by the way", definition: "nhân tiện", example: "By the way, where is the parking area?" },
                { word: "parking area", definition: "khu vực đỗ xe", example: "The parking area is nearly full." },
                { word: "nearly", definition: "gần như", example: "It's nearly five o'clock." },
                { word: "full", definition: "đầy", example: "The restaurant is full tonight." },
                { word: "customers", definition: "khách hàng", example: "Our customers can park for free." },
                { word: "free", definition: "miễn phí", example: "Parking is free for customers." },
                { word: "garage", definition: "nhà để xe", example: "Use the garage across the street." },
                { word: "across", definition: "băng qua, đối diện", example: "It's just across the street." },
                { word: "street", definition: "con phố", example: "Walk down the street to the bank." },
                { word: "cashier", definition: "thu ngân", example: "The cashier will stamp your ticket." },
                { word: "stamp", definition: "đóng dấu", example: "Get your ticket stamped at the desk." },
                { word: "ticket", definition: "vé", example: "Show your parking ticket." },
                { word: "great", definition: "tuyệt vời", example: "Oh, great. Thanks." }
            ] 
        },
        { 
            id: 15007, 
            title: "Part 3 (44-46)", 
            words: [
                { word: "both", definition: "cả hai", example: "Thank you both for coming here today." },
                { word: "coming here", definition: "đến đây", example: "Thank you for coming here to demonstrate your product." },
                { word: "demonstrate", definition: "trình diễn, minh họa", example: "He will demonstrate how to use the new compact printer." },
                { word: "printer", definition: "máy in", example: "The new compact printer is perfect for students." },
                { word: "busy", definition: "bận rộn", example: "I know the store will be busy today." },
                { word: "store", definition: "cửa hàng", example: "The store is having a big sale on tablets." },
                { word: "a big sale", definition: "một đợt giảm giá lớn", example: "We're having a big sale on computers." },
                { word: "tablet", definition: "máy tính bảng", example: "We have a wide selection of tablets on sale." },
                { word: "we're", definition: "chúng tôi là/đang", example: "We're happy to be here today." },
                { word: "perfect for", definition: "hoàn hảo cho", example: "These printers are perfect for home offices." },
                { word: "students", definition: "sinh viên, học sinh", example: "Many students use our compact printers." },
                { word: "home office", definition: "văn phòng tại gia", example: "It's the ideal device for a home office." },
                { word: "limited space", definition: "không gian hạn chế", example: "Our printers are great for people with limited space." },
                { word: "partner", definition: "đối tác, cộng sự", example: "My partner will be setting up the station." },
                { word: "setting up", definition: "đang thiết lập, chuẩn bị", example: "He is setting up the demonstration table." },
                { word: "printer station", definition: "trạm máy in", example: "The printer station is at the back of the store." },
                { word: "demonstration table", definition: "bàn trưng bày/minh họa", example: "Where can I put our demonstration table?" },
                { word: "show", definition: "cho xem, chỉ cho", example: "I'll show you the area." },
                { word: "area", definition: "khu vực", example: "This area is designated for the demo." },
                { word: "brought", definition: "đã mang theo", example: "If you brought any brochures, please put them out." },
                { word: "brochures", definition: "tờ rơi quảng cáo", example: "The brochures are on the table." },
                { word: "it'll be", definition: "nó sẽ", example: "It'll be helpful to have those ready." },
                { word: "helpful", definition: "có ích", example: "The video was very helpful." },
                { word: "put out", definition: "trưng bày ra, đặt ra", example: "Please put out the materials for people to take." }
            ] 
        },
        { 
            id: 15008, 
            title: "Part 3 (47-49)", 
            words: [
                { word: "pleased with", definition: "hài lòng với", example: "I'm very pleased with the sales results." },
                { word: "brand", definition: "thương hiệu", example: "We carry many brands of cakes and cookies." },
                { word: "cakes, pies, and cookies", definition: "bánh ngọt, bánh nướng và bánh quy", example: "Our assortment of cakes, pies, and cookies sold well." },
                { word: "past", definition: "đã qua", example: "We saw high demand this past holiday season." },
                { word: "holiday", definition: "ngày lễ", example: "The holiday season was very busy." },
                { word: "season", definition: "mùa", example: "It was a successful holiday season." },
                { word: "thought", definition: "ý nghĩ, suy nghĩ", example: "Any thoughts on what we should focus on?" },
                { word: "should", definition: "nên", example: "What should we be concentrating on?" },
                { word: "concentrating on", definition: "tập trung vào", example: "We should be concentrating on sugar reduction." },
                { word: "forward", definition: "về phía trước", example: "What is our plan going forward?" },
                { word: "biggest", definition: "lớn nhất", example: "The biggest trend is the reduction of sugar." },
                { word: "trend", definition: "xu hướng", example: "We need to follow the latest trends." },
                { word: "right now", definition: "ngay bây giờ", example: "The public wants healthier products right now." },
                { word: "reduction", definition: "sự cắt giảm", example: "There is a focus on the reduction of sugar." },
                { word: "sugar", definition: "đường", example: "Too much sugar is unhealthy." },
                { word: "public", definition: "công chúng", example: "The public wants healthier options." },
                { word: "healthy", definition: "khỏe mạnh", example: "We want to provide healthy choices." },
                { word: "healthier", definition: "khỏe mạnh hơn", example: "People are looking for healthier products." },
                { word: "products", definition: "các sản phẩm", example: "Our new products have less sugar." },
                { word: "the same", definition: "giống nhau", example: "It has the same great taste." },
                { word: "great", definition: "tuyệt vời", example: "The food has a great taste." },
                { word: "taste", definition: "vị, nếm", example: "The taste is absolutely delicious." },
                { word: "challenge", definition: "thử thách", example: "That'll be our biggest challenge." },
                { word: "ingredient", definition: "nguyên liệu", example: "We use only natural ingredients." },
                { word: "supplier", definition: "nhà cung cấp", example: "Our supplier started offering a new sweetener." },
                { word: "recently", definition: "gần đây", example: "They recently changed the recipe." },
                { word: "started", definition: "đã bắt đầu", example: "We started using a different brand." },
                { word: "offering", definition: "cung cấp", example: "They are offering a discount this week." },
                { word: "sweetener", definition: "chất tạo ngọt", example: "The sweetener is made from natural ingredients." },
                { word: "made", definition: "được làm từ", example: "It is made entirely from plants." },
                { word: "entirely", definition: "hoàn toàn", example: "The building is powered entirely by solar." },
                { word: "natural", definition: "tự nhiên", example: "This product uses natural sweeteners." },
                { word: "similar", definition: "giống, tương tự", example: "Are there similar ones on the market?" },
                { word: "market", definition: "thị trường", example: "The market is very competitive right now." },
                { word: "compare", definition: "so sánh", example: "How do these two products compare?" },
                { word: "investigation", definition: "sự điều tra, nghiên cứu", example: "I'd have to do some investigation." },
                { word: "find out", definition: "tìm ra", example: "I'll find out more about it." },
                { word: "available", definition: "có sẵn", example: "I have some time available tomorrow." },
                { word: "tomorrow", definition: "ngày mai", example: "I will call you tomorrow." },
                { word: "afternoon", definition: "buổi chiều", example: "I am free tomorrow afternoon." }
            ] 
        },
        { 
            id: 15009, 
            title: "Part 3 (50-52)", 
            words: [
                { word: "calling", definition: "đang gọi điện", example: "I'm calling to see if you'd have time for a project." },
                { word: "you'd", definition: "bạn sẽ", example: "I think you'd be perfect for this role." },
                { word: "work on", definition: "làm việc về", example: "Would you like to work on this campaign?" },
                { word: "project", definition: "dự án", example: "We have an exciting new project." },
                { word: "firm", definition: "công ty", example: "Our marketing firm is expanding rapidly." },
                { word: "we've", definition: "chúng tôi đã", example: "We've expanded a lot this year." },
                { word: "expanded", definition: "đã mở rộng", example: "The company has expanded its operations." },
                { word: "a lot", definition: "nhiều", example: "They have a lot of experience." },
                { word: "past year", definition: "năm vừa qua", example: "We grew significantly this past year." },
                { word: "need some help", definition: "cần sự giúp đỡ", example: "We need some help with the campaign." },
                { word: "thinking of", definition: "đang nghĩ về", example: "Thanks for thinking of me for the job." },
                { word: "what type", definition: "loại nào", example: "What type of work would I be doing?" },
                { word: "client", definition: "khách hàng", example: "The client is based in Brazil." },
                { word: "interested in", definition: "quan tâm đến", example: "The client is interested in social media." },
                { word: "create", definition: "tạo ra", example: "We need to create a new campaign." },
                { word: "campaign", definition: "chiến dịch", example: "The marketing campaign will launch soon." },
                { word: "social media", definition: "mạng xã hội", example: "The campaign will focus on social media." },
                { word: "site", definition: "trang web, địa điểm", example: "Check the social media sites." },
                { word: "oversee", definition: "giám sát", example: "You'd be overseeing the entire campaign." },
                { word: "experience", definition: "kinh nghiệm", example: "Do you have experience with social media?" },
                { word: "detailed", definition: "chi tiết", example: "Send me a detailed description." },
                { word: "description", definition: "sự mô tả", example: "The job description is online." },
                { word: "idea", definition: "ý tưởng", example: "That'll give me an idea of the time needed." },
                { word: "how much", definition: "bao nhiêu", example: "How much time will this take?" }
            ] 
        },
        { 
            id: 15010, 
            title: "Part 3 (53-55)", 
            words: [
                { word: "be about to", definition: "sắp sửa làm gì", example: "We were about to pack the van." },
                { word: "pack", definition: "đóng gói", example: "Please pack the items carefully." },
                { word: "van", definition: "xe tải nhỏ", example: "We need to load van number five." },
                { word: "music festival", definition: "lễ hội âm nhạc", example: "The items are for the music festival." },
                { word: "notice", definition: "nhận thấy", example: "I noticed it's got a flat tire." },
                { word: "flat tire", definition: "lốp xe bị xịt", example: "The van has a flat tire." },
                { word: "supposed to", definition: "được cho là phải làm gì", example: "We're supposed to get there by eleven." },
                { word: "set up", definition: "thiết lập", example: "We need to set up lunch for the performers." },
                { word: "lunch performer", definition: "bữa trưa cho nghệ sĩ", example: "The lunch for the performers is ready." },
                { word: "let me see", definition: "để tôi xem", example: "Let me see what's available." },
                { word: "a lot of", definition: "nhiều", example: "We've got a lot of catering jobs today." },
                { word: "catering job", definition: "công việc cung cấp đồ ăn", example: "This is our third catering job." },
                { word: "loading", definition: "đang chất hàng", example: "Do you need help loading the van?" },
                { word: "already", definition: "đã rồi", example: "The food's already in coolers." },
                { word: "cooler", definition: "thùng đá, máy làm mát", example: "Put the beverages in the cooler." },
                { word: "serving", definition: "phục vụ", example: "Get the serving utensils ready." },
                { word: "utensils", definition: "dụng cụ nhà bếp", example: "Where are the serving utensils?" },
                { word: "napkin", definition: "khăn ăn", example: "Don't forget the napkins." },
                { word: "brought", definition: "đã mang theo", example: "Everything needs to be brought to the van." },
                { word: "parking area", definition: "khu vực đậu xe", example: "Meet me at the parking area." }
            ] 
        },
        { 
            id: 15011, 
            title: "Part 3 (56-58)", 
            words: [
                { word: "taking my call", definition: "nghe máy của tôi", example: "Thanks for taking my call today." },
                { word: "mention", definition: "đề cập", example: "As I mentioned in my e-mail." },
                { word: "interested in", definition: "quan tâm đến", example: "I'm interested in working in your field." },
                { word: "field", definition: "lĩnh vực", example: "Which field are you interested in?" },
                { word: "talking to", definition: "đang nói chuyện với", example: "I'm talking to some professionals." },
                { word: "professionals", definition: "những chuyên gia", example: "Meet with other professionals in the industry." },
                { word: "first", definition: "đầu tiên", example: "I'm talking to experts first." },
                { word: "find out more", definition: "tìm hiểu thêm", example: "I want to find out more about the job." },
                { word: "get your start", definition: "bắt đầu sự nghiệp", example: "So how did you get your start?" },
                { word: "family", definition: "gia đình", example: "My family always subscribed to newspapers." },
                { word: "always", definition: "luôn luôn", example: "I always thought the news was important." },
                { word: "subscribe", definition: "đăng ký (báo, tạp chí)", example: "We subscribed to three newspapers." },
                { word: "newspaper", definition: "tờ báo", example: "He worked for the local newspaper." },
                { word: "thought", definition: "đã nghĩ", example: "I thought the news was vital." },
                { word: "news", definition: "tin tức", example: "The news business is very fast-paced." },
                { word: "important", definition: "quan trọng", example: "News is important to the community." },
                { word: "university", definition: "trường đại học", example: "I joined the paper at university." },
                { word: "join", definition: "tham gia", example: "I decided to join the staff." },
                { word: "eventually", definition: "cuối cùng thì", example: "I eventually worked my way up." },
                { word: "work my way up", definition: "nỗ lực thăng tiến", example: "I worked my way up to editor." },
                { word: "editor", definition: "biên tập viên", example: "The editor reviewed the article." },
                { word: "true", definition: "đúng", example: "Is it true that you work long hours?" },
                { word: "business", definition: "kinh doanh", example: "He is in the news business." },
                { word: "long hour", definition: "giờ làm việc dài", example: "We often work very long hours." },
                { word: "schedule", definition: "lịch trình", example: "So what's your schedule like?" }
            ] 
        },
        { 
            id: 15012, 
            title: "Part 3 (59-61)", 
            words: [
                { word: "article", definition: "bài báo", example: "" },
                { word: "propose", definition: "đề xuất, đề nghị", example: "" },
                { word: "merger", definition: "sự sáp nhập", example: "" },
                { word: "corporation", definition: "tập đoàn", example: "" },
                { word: "look like", definition: "trông có vẻ, dường như", example: "" },
                { word: "a lot of", definition: "nhiều", example: "" },
                { word: "advantage", definition: "lợi thế, ưu điểm", example: "" },
                { word: "operation", definition: "hoạt động, vận hành", example: "" },
                { word: "talk about", definition: "thảo luận về", example: "" },
                { word: "last year", definition: "năm ngoái", example: "" },
                { word: "remember", definition: "nhớ, ghi nhớ", example: "" },
                { word: "details", definition: "chi tiết", example: "" },
                { word: "work out", definition: "giải quyết, xử lý (công việc)", example: "" },
                { word: "whether", definition: "liệu rằng", example: "" },
                { word: "offices", definition: "các văn phòng", example: "" },
                { word: "stay", definition: "ở lại, duy trì", example: "" },
                { word: "relocating", definition: "di chuyển chỗ, chuyển địa điểm", example: "" },
                { word: "move", definition: "chuyển, di chuyển", example: "" },
                { word: "relief", definition: "sự nhẹ nhõm, sự giảm nhẹ", example: "" }
            ] 
        },
        { 
            id: 15013, 
            title: "Part 3 (62-64)", 
            words: [
                { word: "calling", definition: "đang gọi điện", example: "" },
                { word: "company", definition: "công ty", example: "" },
                { word: "employee", definition: "nhân viên", example: "" },
                { word: "gift", definition: "quà tặng", example: "" },
                { word: "useful", definition: "hữu ích", example: "" },
                { word: "annual", definition: "hàng năm", example: "" },
                { word: "staff", definition: "đội ngũ nhân viên", example: "" },
                { word: "tournament", definition: "giải đấu", example: "" },
                { word: "thought", definition: "ý nghĩ, suy nghĩ", example: "" },
                { word: "water bottle", definition: "bình nước", example: "" },
                { word: "a few", definition: "một vài", example: "" },
                { word: "drink container", definition: "bình đựng nước", example: "" },
                { word: "pull", definition: "kéo, truy cập (thông tin)", example: "" },
                { word: "recommend", definition: "khuyên, đề xuất", example: "" },
                { word: "easier", definition: "dễ dàng hơn", example: "" },
                { word: "clean", definition: "sạch, làm sạch", example: "" },
                { word: "straw", definition: "ống hút", example: "" },
                { word: "put", definition: "đặt, để", example: "" },
                { word: "logo", definition: "biểu trưng, biểu tượng", example: "" },
                { word: "send", definition: "gửi", example: "" },
                { word: "graphic", definition: "đồ họa", example: "" },
                { word: "file", definition: "tệp tin", example: "" }
            ] 
        },
        { 
            id: 15014, 
            title: "Part 3 (65-67)", 
            words: [
                { word: "finish", definition: "hoàn thành, kết thúc", example: "" },
                { word: "recording", definition: "bản ghi âm, đang ghi", example: "" },
                { word: "audio", definition: "âm thanh", example: "" },
                { word: "guide", definition: "hướng dẫn", example: "" },
                { word: "pencil drawing", definition: "tranh vẽ chì", example: "" },
                { word: "included", definition: "bao gồm", example: "" },
                { word: "modern", definition: "hiện đại", example: "" },
                { word: "art", definition: "nghệ thuật", example: "" },
                { word: "exhibit", definition: "triển lãm, vật trưng bày", example: "" },
                { word: "next week", definition: "tuần tới", example: "" },
                { word: "be loaded", definition: "được tải lên", example: "" },
                { word: "device", definition: "thiết bị", example: "" },
                { word: "tomorrow", definition: "ngày mai", example: "" },
                { word: "unfortunately", definition: "không may", example: "" },
                { word: "make one change", definition: "thực hiện một thay đổi", example: "" },
                { word: "no longer", definition: "không còn nữa", example: "" },
                { word: "scheduling mix-up", definition: "nhầm lẫn về lịch trình", example: "" },
                { word: "promise", definition: "hứa", example: "" },
                { word: "museum", definition: "bảo tàng", example: "" },
                { word: "too bad", definition: "quá tệ, đáng tiếc", example: "" },
                { word: "one of", definition: "một trong những", example: "" },
                { word: "favorite", definition: "yêu thích", example: "" },
                { word: "pieces (art)", definition: "các tác phẩm (nghệ thuật)", example: "" },
                { word: "place", definition: "vị trí, địa điểm", example: "" },
                { word: "remove", definition: "loại bỏ, dời đi", example: "" },
                { word: "right away", definition: "ngay lập tức", example: "" }
            ] 
        },
        { 
            id: 15015, 
            title: "Part 3 (68-70)", 
            words: [
                { word: "glad", definition: "vui mừng, mừng", example: "" },
                { word: "assign", definition: "phân công, giao phó", example: "" },
                { word: "cover", definition: "đưa tin, bao phủ", example: "" },
                { word: "press conference", definition: "cuộc họp báo", example: "" },
                { word: "earlier", definition: "sớm hơn", example: "" },
                { word: "major", definition: "quan trọng, chính", example: "" },
                { word: "media network", definition: "mạng lưới truyền thông", example: "" },
                { word: "in addition to", definition: "ngoài ra, bên cạnh", example: "" },
                { word: "industry", definition: "ngành công nghiệp", example: "" },
                { word: "transform", definition: "thay đổi, biến đổi", example: "" },
                { word: "region", definition: "khu vực, vùng", example: "" },
                { word: "power", definition: "năng lượng, quyền lực", example: "" },
                { word: "compare", definition: "so sánh", example: "" },
                { word: "fact", definition: "sự thật, dữ kiện", example: "" },
                { word: "before", definition: "trước khi", example: "" },
                { word: "largest", definition: "lớn nhất", example: "" },
                { word: "wind turbine", definition: "tuabin gió", example: "" },
                { word: "built", definition: "đã xây dựng", example: "" },
                { word: "different", definition: "khác biệt", example: "" },
                { word: "stage", definition: "giai đoạn, sân khấu", example: "" },
                { word: "construction", definition: "sự xây dựng", example: "" },
                { word: "also", definition: "cũng, ngoài ra", example: "" },
                { word: "close", definition: "gần, đóng", example: "" },
                { word: "being done", definition: "đang được thực hiện", example: "" },
                { word: "think", definition: "nghĩ, suy nghĩ", example: "" },
                { word: "crucial", definition: "then chốt, cực kỳ quan trọng", example: "" },
                { word: "focus on", definition: "tập trung vào", example: "" },
                { word: "how many", definition: "bao nhiêu", example: "" },
                { word: "new jobs", definition: "các công việc mới", example: "" },
                { word: "related to", definition: "liên quan đến", example: "" },
                { word: "assembling", definition: "lắp ráp", example: "" },
                { word: "maintaining", definition: "bảo trì, duy trì", example: "" },
                { word: "opening up", definition: "mở ra", example: "" },
                { word: "area", definition: "khu vực", example: "" },
                { word: "as a result", definition: "kết quả là", example: "" }
            ] 
        },
        
        // Part 4
        { 
            id: 15016, 
            title: "Part 4 (71-73)", 
            words: [
                { word: "reach", definition: "liên hệ, đạt tới", example: "You have reached the information line." },
                { word: "information line", definition: "đường dây thông tin", example: "Please call our information line for updates." },
                { word: "apartment", definition: "căn hộ", example: "She lives in a small apartment downtown." },
                { word: "management", definition: "sự quản lý, ban quản lý", example: "Contact the management office for repairs." },
                { word: "maintenance", definition: "sự bảo trì", example: "Maintenance work will begin on Monday." },
                { word: "begin", definition: "bắt đầu", example: "The meeting will begin at ten A.M." },
                { word: "repave", definition: "lát lại (đường)", example: "The city plans to repave the main road." },
                { word: "entire", definition: "toàn bộ", example: "The entire building was renovated." },
                { word: "parking area", definition: "khu vực đỗ xe", example: "The parking area is full." },
                { word: "adjacent", definition: "liền kề, kế bên", example: "The park is adjacent to the library." },
                { word: "main entrance", definition: "lối vào chính", example: "Meet me at the main entrance." },
                { word: "resident", definition: "cư dân", example: "All residents must sign the form." },
                { word: "move", definition: "di chuyển, dời đi", example: "Please move your vehicle." },
                { word: "vehicle", definition: "phương tiện, xe cộ", example: "Park your vehicle in the designated spot." },
                { word: "designated", definition: "được chỉ định", example: "Use only the designated parking spots." },
                { word: "parking spot", definition: "chỗ đỗ xe", example: "I found a parking spot near the door." },
                { word: "towed", definition: "bị kéo đi (xe)", example: "Unauthorized vehicles will be towed." },
                { word: "owner", definition: "chủ sở hữu", example: "The car owner was notified." },
                { word: "expense", definition: "chi phí", example: "The repairs were done at the owner's expense." },
                { word: "map", definition: "bản đồ", example: "Look at the map to find the office." },
                { word: "alternate", definition: "thay thế, luân phiên", example: "A map of alternate parking sites was provided." },
                { word: "posted", definition: "được dán, được đăng", example: "The notice is posted in the lobby." },
                { word: "lobby", definition: "sảnh", example: "Wait for me in the building lobby." }
            ] 
        },
        { 
            id: 15017, 
            title: "Part 4 (74-76)", 
            words: [
                { word: "episode", definition: "tập (phim, chương trình)", example: "On today's episode, we'll discuss home repairs." },
                { word: "go over", definition: "kiểm tra, xem qua", example: "Let's go over the instructions again." },
                { word: "maintain", definition: "duy trì, bảo trì", example: "It's important to maintain your home's roof." },
                { word: "repair", definition: "sửa chữa", example: "I need to repair the broken window." },
                { word: "roof", definition: "mái nhà", example: "The roof needs a few minor repairs." },
                { word: "invest in", definition: "đầu tư vào", example: "You should invest in high-quality tools." },
                { word: "special", definition: "đặc biệt", example: "You'll need a few special tools for this job." },
                { word: "tool", definition: "công cụ", example: "Choose the right tool for the task." },
                { word: "trowel", definition: "cái bay (xây dựng)", example: "Use a trowel to apply the cement." },
                { word: "crowbar", definition: "xà beng", example: "Use a crowbar to remove loose shingles." },
                { word: "important", definition: "quan trọng", example: "Choosing quality tools is important." },
                { word: "high quality", definition: "chất lượng cao", example: "We only use high quality materials." },
                { word: "roof cement", definition: "xi măng lợp mái", example: "Apply roof cement to the cracks." },
                { word: "seal", definition: "bịt kín, niêm phong", example: "Seal any cracks to prevent leaks." },
                { word: "remove", definition: "loại bỏ, tháo dỡ", example: "Remove the damaged parts before replacing them." },
                { word: "replace", definition: "thay thế", example: "I need to replace the old shingles." },
                { word: "highly recommend", definition: "cực kỳ khuyên dùng", example: "I highly recommend taking photos of the roof." },
                { word: "take photo", definition: "chụp ảnh", example: "Take a photo of the completed work." },
                { word: "track (verb)", definition: "theo dõi", example: "You can track the condition of your roof over time." },
                { word: "overall condition", definition: "tình trạng tổng thể", example: "The overall condition of the building is good." }
            ] 
        },
        { 
            id: 15018, 
            title: "Part 4 (77-79)", 
            words: [
                { word: "join", definition: "tham gia", example: "Thank you for joining the tour today." },
                { word: "tour", definition: "chuyến tham quan", example: "Welcome to our tour of the gardens." },
                { word: "conservatory", definition: "nhà kính trồng cây", example: "The conservatory has many species of flowers." },
                { word: "hope", definition: "hy vọng", example: "I hope you enjoyed the visit." },
                { word: "learn about", definition: "tìm hiểu về", example: "We'll learn about many species of plants." },
                { word: "species", definition: "loài", example: "There are many rare species in this conservatory." },
                { word: "beginning", definition: "bắt đầu, phần đầu", example: "I mentioned this at the beginning of the tour." },
                { word: "world-renowned", definition: "nổi tiếng thế giới", example: "She is a world-renowned botanist." },
                { word: "botanist", definition: "nhà thực vật học", example: "The botanist will give a lecture later." },
                { word: "lecture", definition: "bài giảng", example: "The lecture will start at two o'clock." },
                { word: "orchid plant", definition: "cây phong lan", example: "Orchid plants require special care." },
                { word: "community", definition: "cộng đồng", example: "The talk is in the community room." },
                { word: "attending", definition: "tham dự", example: "I recommend attending the lecture." },
                { word: "be featured", definition: "được xuất hiện, được giới thiệu", example: "Her work has been featured in a film." },
                { word: "documentary", definition: "phim tài liệu", example: "I watched an interesting documentary recently." },
                { word: "film", definition: "phim, quay phim", example: "The film is called Orchid Caretakers." },
                { word: "purchase", definition: "mua, sự mua sắm", example: "You can purchase the DVD in our shop." },
                { word: "gift shop", definition: "cửa hàng lưu niệm", example: "Visit our gift shop for more items." },
                { word: "recently", definition: "gần đây", example: "I watched the movie recently." },
                { word: "right here", definition: "ngay tại đây", example: "We have these plants right here in our garden." }
            ] 
        },
        { 
            id: 15019, 
            title: "Part 4 (80-82)", 
            words: [
                { word: "benefit", definition: "lợi ích / (buổi biểu diễn) từ thiện", example: "Welcome to our benefit concert tonight." },
                { word: "concert", definition: "buổi hòa nhạc", example: "The concert will begin soon." },
                { word: "supporting", definition: "hỗ trợ", example: "Thank you all for supporting our center." },
                { word: "facilities", definition: "cơ sở vật chất", example: "Our facilities need some repairs." },
                { word: "in need of", definition: "cần cái gì đó", example: "The building is in need of repair." },
                { word: "repairs", definition: "sự sửa chữa", example: "Several minor repairs are necessary." },
                { word: "a while", definition: "một thời gian", example: "We haven't had a meeting for a while." },
                { word: "raise (money)", definition: "gây quỹ, quyên góp", example: "We've raised 5,000 dollars so far." },
                { word: "ticket sales", definition: "việc bán vé", example: "Revenue from ticket sales will go to charity." },
                { word: "dollar", definition: "đô la", example: "The total amount was over a thousand dollars." },
                { word: "reach", definition: "đạt tới", example: "We haven't quite reached our goal yet." },
                { word: "goal", definition: "mục tiêu", example: "Our goal is to raise 10,000 dollars." },
                { word: "encourage", definition: "khuyến khích", example: "I want to encourage you to buy some snacks." },
                { word: "concession stand", definition: "quầy bán đồ ăn nhẹ", example: "Food is available at the concession stand." },
                { word: "percent", definition: "phần trăm", example: "Eighty percent of the proceeds will be donated." },
                { word: "proceeds (noun)", definition: "tiền thu được (từ sự kiện)", example: "The proceeds will fund the construction." },
                { word: "construction", definition: "sự xây dựng", example: "Construction on the new wing will begin soon." }
            ] 
        },
        { 
            id: 15020, 
            title: "Part 4 (83-85)", 
            words: [
                { word: "attending", definition: "tham dự", example: "Thank you all for attending today's workshop." },
                { word: "workshop", definition: "hội thảo", example: "I hope you enjoy the workshop session." },
                { word: "conduct", definition: "thực hiện, dẫn dắt", example: "We will be conducting the session together." },
                { word: "session", definition: "phiên, buổi", example: "The training session will last for two hours." },
                { word: "focus on", definition: "tập trung vào", example: "We will be focusing on using time efficiently." },
                { word: "efficiently", definition: "một cách hiệu quả", example: "Learn how to use your time efficiently." },
                { word: "business owner", definition: "chủ doanh nghiệp", example: "Time management is key for any business owner." },
                { word: "wisely", definition: "một cách khôn ngoan", example: "Spending your time wisely is a key factor." },
                { word: "key factor", definition: "yếu tố quan trọng", example: "Discipline is a key factor to business success." },
                { word: "success", definition: "sự thành công", example: "He worked hard to achieve business success." },
                { word: "presentation", definition: "bài thuyết trình", example: "I'll be referring to documents during the presentation." },
                { word: "referring", definition: "tham khảo, nhắc tới", example: "I'll be referring to the packet you were handed." },
                { word: "documents", definition: "tài liệu", example: "Keep all your important documents in one place." },
                { word: "packet", definition: "gói tài liệu", example: "Refer to the documents in your packet." },
                { word: "be handed", definition: "được trao cho", example: "You were handed a packet as you arrived." },
                { word: "arrive", definition: "đến", example: "Please sign in when you arrive." },
                { word: "the back", definition: "phía sau", example: "Additional packets are at the back of the room." },
                { word: "start off", definition: "bắt đầu", example: "To start off, we'll do a quick exercise." },
                { word: "exercise", definition: "bài tập", example: "Let's begin with a team-building exercise." },
                { word: "get to know", definition: "tìm hiểu, làm quen", example: "Use this time to get to know one another." },
                { word: "one another", definition: "lẫn nhau", example: "It is important to support one another." },
                { word: "better", definition: "tốt hơn", example: "We want to help you perform better." }
            ] 
        },
        { 
            id: 15021, 
            title: "Part 4 (86-88)", 
            words: [
                { word: "site", definition: "địa điểm", example: "At this site, researchers uncovered ruins." },
                { word: "archaeologist", definition: "nhà khảo cổ học", example: "Archaeologists have uncovered many ancient artifacts." },
                { word: "uncover", definition: "khám phá, phát hiện", example: "They uncovered the remains of a marketplace." },
                { word: "remain", definition: "tàn tích, vật còn lại", example: "The remains of the building were discovered." },
                { word: "century", definition: "thế kỷ", example: "This marketplace dates back to the fifth century." },
                { word: "marketplace", definition: "khu chợ", example: "This was a busy fifth-century marketplace." },
                { word: "colorful", definition: "đầy màu sắc", example: "The walls are covered with colorful mosaic tiles." },
                { word: "mosaic", definition: "tranh khảm", example: "You can see intricate details in the mosaic." },
                { word: "tiles", definition: "gạch lát", example: "Be careful not to damage the tiles." },
                { word: "wall", definition: "bức tường", example: "There are paintings on the walls." },
                { word: "notice", definition: "nhận thấy", example: "You'll notice how vibrant the colors are." },
                { word: "vibrant", definition: "rực rỡ, sôi động", example: "The colors are still very vibrant." },
                { word: "ruin", definition: "đống đổ nát, tàn tích", example: "These ruins are very famous." },
                { word: "famous", definition: "nổi tiếng", example: "This site is famous for its history." },
                { word: "intricate", definition: "phức tạp, tinh xảo", example: "You can see intricate details in the art." },
                { word: "details", definition: "chi tiết", example: "The details in the picture are amazing." },
                { word: "artist", definition: "nghệ sĩ", example: "The artists used many colors." },
                { word: "picture", definition: "bức tranh, hình ảnh", example: "The pictures show scenes from daily life." },
                { word: "scene", definition: "cảnh tượng", example: "These scenes show how people lived." },
                { word: "daily life", definition: "cuộc sống hàng ngày", example: "The art depicts scenes from daily life." },
                { word: "protect", definition: "bảo vệ", example: "A roof was built to protect the area." },
                { word: "roof", definition: "mái nhà", example: "The area is covered by a new roof." },
                { word: "constructed", definition: "được xây dựng", example: "The roof was constructed last year." },
                { word: "area", definition: "khu vực", example: "Stay within the designated area." },
                { word: "light", definition: "ánh sáng", example: "The lights are dim to protect the tiles." },
                { word: "dim", definition: "lờ mờ, tối", example: "The area is dimly lit." },
                { word: "taking photos", definition: "chụp ảnh", example: "Taking photos is not allowed here." },
                { word: "allow", definition: "cho phép", example: "We do not allow cameras inside." },
                { word: "flash", definition: "đèn flash", example: "The flash would damage the art." },
                { word: "damage", definition: "gây hại, làm hỏng", example: "Water can damage the ancient structures." },
                { word: "proceed", definition: "tiếp tục, tiến hành", example: "Please be careful as we proceed." },
                { word: "hold", definition: "giữ", example: "Please hold on to the handrails." },
                { word: "handrail", definition: "tay vịn", example: "Hold the handrail on the stairs." },
                { word: "either side", definition: "hai bên", example: "There are handrails on either side." },
                { word: "path", definition: "con đường", example: "Please stay on the designated path." }
            ] 
        },
        { 
            id: 15022, 
            title: "Part 4 (89-91)", 
            words: [
                { word: "agency", definition: "đại lý, công ty quảng cáo", example: "Our agency just won an important contract." },
                { word: "won", definition: "đã thắng, giành được", example: "We won the contract after a long bidding process." },
                { word: "important", definition: "quan trọng", example: "This is an important contract for us." },
                { word: "contract", definition: "hợp đồng", example: "We need to sign the contract today." },
                { word: "developing", definition: "đang phát triển", example: "We'll be developing several ads." },
                { word: "ads", definition: "quảng cáo", example: "We're developing 30-second ads for radio." },
                { word: "second", definition: "giây / thứ hai", example: "The ad will be 30 seconds long." },
                { word: "local", definition: "địa phương", example: "The ads will run on local radio stations." },
                { word: "radio station", definition: "đài phát thanh", example: "Tune in to your local radio station." },
                { word: "release", definition: "phát hành", example: "The ads will be released next month." },
                { word: "next month", definition: "tháng tới", example: "Construction starts next month." },
                { word: "additional", definition: "bổ sung", example: "We will release additional ads later." },
                { word: "following month", definition: "tháng kế tiếp", example: "The report is due the following month." },
                { word: "tight schedule", definition: "lịch trình dày đặc", example: "We are on a very tight schedule." },
                { word: "priority", definition: "sự ưu tiên", example: "Completing this project is a priority." },
                { word: "client", definition: "khách hàng", example: "The client provided a rough draft." },
                { word: "internally", definition: "nội bộ", example: "They worked on the project internally." },
                { word: "rough", definition: "thô, sơ thảo", example: "We are editing a rough ad." },
                { word: "editing", definition: "việc chỉnh sửa", example: "We need to finish the editing process." },
                { word: "work on", definition: "làm việc về", example: "Let's work on that now." }
            ] 
        },
        { 
            id: 15023, 
            title: "Part 4 (92-94)", 
            words: [
                { word: "excuse me", definition: "xin lỗi (khi làm phiền)", example: "Excuse me, may I have your attention?" },
                { word: "nurse", definition: "y tá", example: "The nurses are busy with patients." },
                { word: "attention", definition: "sự chú ý", example: "Please give me your full attention." },
                { word: "receive", definition: "nhận", example: "I've been receiving many complaints." },
                { word: "complaint", definition: "lời phàn nàn", example: "We received a complaint about the food." },
                { word: "free snack", definition: "đồ ăn nhẹ miễn phí", example: "We provide free snacks in the break room." },
                { word: "hospital", definition: "bệnh viện", example: "He works at the city hospital." },
                { word: "break room", definition: "phòng nghỉ", example: "Snacks are available in the break room." },
                { word: "selection", definition: "sự lựa chọn, danh mục", example: "I don't like the selection of snacks." },
                { word: "shift", definition: "ca làm việc", example: "He starts his evening shift at 6 P.M." },
                { word: "spending account", definition: "tài khoản chi tiêu", example: "Money will be put into your spending account." },
                { word: "staff", definition: "nhân viên", example: "All staff members should attend." },
                { word: "cafeteria", definition: "căng tin", example: "You can buy snacks at the cafeteria." },
                { word: "require", definition: "yêu cầu", example: "This change will require approval." },
                { word: "management", definition: "ban quản lý", example: "Management will review the proposal." },
                { word: "approval", definition: "sự chấp thuận", example: "Wait for management approval." },
                { word: "keep you posted", definition: "cập nhật cho bạn", example: "I'll keep you posted on any changes." }
            ] 
        },
        { 
            id: 15024, 
            title: "Part 4 (95-97)", 
            words: [
                { word: "mayor", definition: "thị trưởng", example: "The mayor gave a speech at the park." },
                { word: "please", definition: "làm ơn / vui lòng", example: "I am pleased to welcome you today." },
                { word: "welcome", definition: "chào đón", example: "Welcome to the grand opening celebration." },
                { word: "celebration", definition: "sự ăn mừng, lễ kỷ niệm", example: "Join us for the town's celebration." },
                { word: "town", definition: "thị trấn", example: "Our town has a new public park." },
                { word: "newly", definition: "mới", example: "The newly renovated area is beautiful." },
                { word: "renovated", definition: "được cải tạo, nâng cấp", example: "The park was recently renovated." },
                { word: "a lot of", definition: "nhiều", example: "There are a lot of new areas to explore." },
                { word: "new area", definition: "khu vực mới", example: "Explore the new area near the pond." },
                { word: "explore", definition: "khám phá", example: "We've planned a hike to explore the park." },
                { word: "plan", definition: "kế hoạch / dự định", example: "We've planned a short hike for everyone." },
                { word: "short", definition: "ngắn", example: "It will be a short walk around the lake." },
                { word: "hike", definition: "đi bộ đường dài", example: "The group is going on a short hike." },
                { word: "walking around", definition: "đi dạo xung quanh", example: "We will be walking around the pond today." },
                { word: "pond", definition: "cái ao", example: "The trail goes around the central pond." },
                { word: "walking trail", definition: "đường đi bộ, đường mòn", example: "Follow the walking trail to the hill." },
                { word: "hill", definition: "ngọn đồi", example: "We will end our walk on top of the hill." },
                { word: "north side", definition: "phía bắc", example: "The snacks are on the north side of the park." },
                { word: "snack", definition: "đồ ăn nhẹ", example: "Free snacks will be provided at the end." },
                { word: "ice cream", definition: "kem", example: "Enjoy some free ice cream after the walk." },
                { word: "forget", definition: "quên", example: "Don't forget to take some photos." },
                { word: "post", definition: "đăng tải", example: "Post your photos on the city's Web site." },
                { word: "commemorate", definition: "kỷ niệm, tưởng niệm", example: "We'd like to commemorate this special day." },
                { word: "special", definition: "đặc biệt", example: "This is a special day for our community." }
            ] 
        },
        { 
            id: 15025, 
            title: "Part 4 (98-100)", 
            words: [
                { word: "attending", definition: "tham dự", example: "Thanks for attending today's lecture." },
                { word: "public", definition: "công cộng, công chúng", example: "This is a free public lecture for everyone." },
                { word: "lecture", definition: "bài giảng", example: "The lecture is about vegetable gardening." },
                { word: "sponsor", definition: "tài trợ / nhà tài trợ", example: "The event is sponsored by the association." },
                { word: "association", definition: "hiệp hội", example: "Contact the Farmers' Association for more tips." },
                { word: "receive", definition: "nhận", example: "We've received many requests for information." },
                { word: "request", definition: "yêu cầu", example: "Submit your request for soil testing." },
                { word: "information", definition: "thông tin", example: "Find more information on our Web site." },
                { word: "growing", definition: "trồng (cây), phát triển", example: "Learn about growing a healthy garden." },
                { word: "vegetable", definition: "rau củ", example: "Fresh vegetables are the best reward." },
                { word: "garden", definition: "khu vườn", example: "Start your own vegetable garden this spring." },
                { word: "healthy", definition: "khỏe mạnh", example: "Keep your garden healthy with regular testing." },
                { word: "first thing", definition: "điều đầu tiên", example: "The first thing we recommend is a soil test." },
                { word: "recommend", definition: "đề xuất, khuyên dùng", example: "I recommend regular soil testing." },
                { word: "regular", definition: "thường xuyên, đều đặn", example: "Perform regular checks on your plants." },
                { word: "soil", definition: "đất", example: "Test your garden soil for nutrients." },
                { word: "testing", definition: "kiểm tra, thử nghiệm", example: "Soil testing is essential for a good harvest." },
                { word: "sample", definition: "mẫu thử", example: "Take a soil sample from your garden." },
                { word: "the same", definition: "giống nhau", example: "Samples should be taken from the same depth." },
                { word: "depth", definition: "độ sâu", example: "Check the depth on this chart." },
                { word: "chart", definition: "biểu đồ", example: "Refer to the chart for depth measurements." },
                { word: "leave", definition: "rời đi / để lại", example: "Before you leave, sign up for our list." },
                { word: "sign up", definition: "đăng ký", example: "Sign up for our mailing list today." },
                { word: "mailing list", definition: "danh sách gửi thư", example: "Join our mailing list for future updates." },
                { word: "inform", definition: "thông báo", example: "Stay informed of future lectures." },
                { word: "future", definition: "tương lai", example: "We have more lectures planned for the future." }
            ] 
        },
    ]
};
