import { VocabItem, VocabularyPart } from '../../types';

const test1_part1_words: VocabItem[] = [
    { word: "Wipe off", definition: "lau sạch", example: "" },
    { word: "Throw away", definition: "vứt bỏ", example: "" },
    { word: "Brush off", definition: "phủi đi, phớt lờ", example: "" },
    { word: "Shovel from", definition: "xúc khỏi", example: "" },
    { word: "Hang", definition: "treo, móc", example: "" },
    { word: "Have a conversation", definition: "trò chuyện", example: "" },
    { word: "Rearrange", definition: "sắp xếp lại", example: "" },
    { word: "Cushion", definition: "gối đệm", example: "" },
    { word: "Enter", definition: "đi vào", example: "" },
    { word: "Scatter", definition: "rải, tung", example: "" },
    { word: "Rack", definition: "giá đỡ", example: "" },
    { word: "Line up", definition: "xếp hàng", example: "" },
    { word: "Tent", definition: "lều", example: "" },
    { word: "Potted plant", definition: "cây trong chậu", example: "" },
    { word: "Suspend", definition: "treo lơ lửng", example: "" },
    { word: "Stack", definition: "chất đống, chồng", example: "" },
    { word: "Entryway", definition: "lối vào", example: "" },
    { word: "Rug", definition: "thảm nhỏ", example: "" },
    { word: "Roll up", definition: "cuộn lại", example: "" },
    { word: "Sweep", definition: "quét", example: "" },
    { word: "Patio", definition: "sân nhỏ ngoài trời", example: "" },
    { word: "Light fixture", definition: "đèn cố định", example: "" },
];

const test2_part1_words: VocabItem[] = [
    { word: "Insert", definition: "chèn, đưa vào", example: "" },
    { word: "Cord", definition: "dây cáp", example: "" },
    { word: "Outlet", definition: "ổ cắm điện, đầu ra", example: "" },
    { word: "Press a button", definition: "nhấn nút", example: "" },
    { word: "Grip", definition: "cầm chặt, sự nắm chặt", example: "" },
    { word: "Handle", definition: "tay cầm", example: "" },
    { word: "Tack onto", definition: "gắn thêm vào", example: "" },
    { word: "Window shutter", definition: "cửa chớp", example: "" },
    { word: "Clear off", definition: "dọn sạch", example: "" },
    { word: "Wooden board", definition: "tấm ván gỗ", example: "" },
    { word: "Utensil", definition: "dụng cụ", example: "" },
    { word: "Discard", definition: "vứt bỏ", example: "" },
    { word: "Rolling chair", definition: "ghế xoay", example: "" },
    { word: "Counter", definition: "quầy, mặt bàn", example: "" },
    { word: "Drawer", definition: "ngăn kéo", example: "" },
    { word: "Chop", definition: "thái, chặt", example: "" },
    { word: "Scatter", definition: "rải, rắc", example: "" },
    { word: "Pile", definition: "chồng, chất đống", example: "" },
    { word: "Load into", definition: "chất vào", example: "" },
    { word: "Tent", definition: "lều", example: "" },
    { word: "Canopy", definition: "mái che, tán cây", example: "" },
    { word: "Stack", definition: "chồng, xếp chồng", example: "" },
    { word: "Escalator", definition: "thang cuốn", example: "" },
    { word: "Rack", definition: "giá đỡ", example: "" },
    { word: "Lift onto", definition: "nhấc lên", example: "" },
    { word: "Shuttle bus", definition: "xe buýt đưa đón", example: "" },
];

const test3_part1_words: VocabItem[] = [
    { word: "Oven", definition: "lò nướng", example: "" },
    { word: "Cabinet", definition: "tủ", example: "" },
    { word: "Towel", definition: "khăn", example: "" },
    { word: "Trash", definition: "rác, vứt bỏ", example: "" },
    { word: "Take off", definition: "cởi (đồ), cất cánh", example: "" },
    { word: "Face", definition: "đối mặt, quay mặt về hướng", example: "" },
    { word: "Shelving unit", definition: "giá kệ", example: "" },
    { word: "Gather", definition: "tập hợp", example: "" },
    { word: "Lay out", definition: "bố trí, trình bày", example: "" },
    { word: "Railing", definition: "lan can, tay vịn", example: "" },
    { word: "Under construction", definition: "đang xây dựng", example: "" },
    { word: "Sheet of metal", definition: "tấm kim loại", example: "" },
    { word: "Lean against", definition: "tựa vào", example: "" },
    { word: "Pile", definition: "chồng, chất đống", example: "" },
    { word: "Branch", definition: "cành cây, chi nhánh", example: "" },
    { word: "Discard", definition: "vứt bỏ", example: "" },
    { word: "Bench", definition: "ghế dài", example: "" },
    { word: "Structure", definition: "cấu trúc, công trình", example: "" },
];

const test4_part1_words: VocabItem[] = [
    { word: "Pour", definition: "rót, đổ", example: "" },
    { word: "Liquid", definition: "chất lỏng", example: "" },
    { word: "Iron", definition: "bàn là, là (quần áo)", example: "" },
    { word: "Glance", definition: "liếc nhìn", example: "" },
    { word: "Jar", definition: "lọ, hũ", example: "" },
    { word: "Monitor", definition: "màn hình, giám sát", example: "" },
    { word: "Wipe off", definition: "lau chùi", example: "" },
    { word: "Float", definition: "nổi", example: "" },
    { word: "Cargo", definition: "hàng hóa", example: "" },
    { word: "Lighthouse", definition: "ngọn hải đăng", example: "" },
    { word: "Row", definition: "hàng, chèo thuyền", example: "" },
    { word: "Fireplace", definition: "lò sưởi", example: "" },
    { word: "Cable", definition: "dây cáp", example: "" },
    { word: "Pile", definition: "đống, chồng chất", example: "" },
    { word: "Pack", definition: "đóng gói, balô", example: "" },
    { word: "Fall over", definition: "ngã, đổ", example: "" },
    { word: "Couch", definition: "ghế sofa", example: "" },
    { word: "Ceiling", definition: "trần nhà", example: "" },
    { word: "Stack", definition: "chồng, xếp chồng", example: "" },
];

const test5_part1_words: VocabItem[] = [
    { word: "Carry", definition: "mang, vác, cầm", example: "" },
    { word: "Push", definition: "đẩy", example: "" },
    { word: "Pull", definition: "kéo", example: "" },
    { word: "Bench", definition: "băng ghế", example: "" },
    { word: "Hike", definition: "đi bộ đường dài, đi leo núi", example: "" },
    { word: "Path", definition: "đường mòn", example: "" },
    { word: "Backpack", definition: "ba lô", example: "" },
    { word: "Laces", definition: "dây giày", example: "" },
    { word: "Tunnel", definition: "đường hầm", example: "" },
    { word: "Plug", definition: "phích cắm, cắm", example: "" },
    { word: "Cord", definition: "dây cáp, dây", example: "" },
    { word: "Kneel down", definition: "quỳ xuống", example: "" },
    { word: "Trim", definition: "cắt tỉa", example: "" },
    { word: "Fold", definition: "gấp, xếp", example: "" },
    { word: "Stack", definition: "xếp chồng, chồng", example: "" },
    { word: "Suspend", definition: "treo, đình chỉ", example: "" },
    { word: "Light fixture", definition: "đèn cố định", example: "" },
    { word: "Pile", definition: "đống, chất đống", example: "" },
    { word: "Roll up", definition: "cuộn lên, gấp gọn", example: "" },
    { word: "Rug", definition: "thảm", example: "" },
];

const test6_part1_words: VocabItem[] = [
    { word: "Shovel", definition: "cái xẻng; xúc", example: "" },
    { word: "Walkway", definition: "lối đi", example: "" },
    { word: "Walking stick", definition: "gậy đi bộ", example: "" },
    { word: "Food trolley", definition: "xe đẩy thức ăn", example: "" },
    { word: "Carry", definition: "mang, vác", example: "" },
    { word: "Water", definition: "tưới nước", example: "" },
    { word: "Scrub", definition: "chà, cọ", example: "" },
    { word: "Bucket", definition: "cái xô", example: "" },
    { word: "A bucket of water", definition: "một xô nước", example: "" },
    { word: "Tile", definition: "gạch, lát gạch", example: "" },
    { word: "Occupied", definition: "đang sử dụng, bận rộn", example: "" },
    { word: "Fountain", definition: "đài phun nước", example: "" },
    { word: "Gather", definition: "thu thập, tụ họp", example: "" },
    { word: "Entrance", definition: "lối vào", example: "" },
    { word: "Block", definition: "khối, chặn", example: "" },
    { word: "Pedestrian", definition: "người đi bộ", example: "" },
    { word: "Log", definition: "khúc gỗ; ghi chép", example: "" },
    { word: "Pile", definition: "chồng, đống", example: "" },
    { word: "Brick", definition: "gạch", example: "" },
];

const test7_part1_words: VocabItem[] = [
    { word: "Dig", definition: "đào, bới", example: "" },
    { word: "Stack", definition: "xếp chồng, đống", example: "" },
    { word: "Empty", definition: "làm trống, đổ ra", example: "" },
    { word: "Soil", definition: "đất", example: "" },
    { word: "Pot", definition: "chậu", example: "" },
    { word: "Cart", definition: "xe đẩy", example: "" },
    { word: "Hang", definition: "treo", example: "" },
    { word: "Hook", definition: "cái móc, móc", example: "" },
    { word: "Shelve", definition: "xếp lên kệ, đặt sang một bên", example: "" },
    { word: "Restock", definition: "bổ sung hàng", example: "" },
    { word: "Grocery", definition: "cửa hàng tạp hóa", example: "" },
    { word: "Rest", definition: "nghỉ ngơi, phần còn lại", example: "" },
    { word: "Counter", definition: "quầy", example: "" },
    { word: "Fold", definition: "gấp", example: "" },
    { word: "Wipe down", definition: "lau sạch", example: "" },
    { word: "Stool", definition: "ghế đẩu", example: "" },
    { word: "Banner", definition: "biểu ngữ", example: "" },
    { word: "Lawn", definition: "bãi cỏ", example: "" },
    { word: "Sidewalk", definition: "vỉa hè", example: "" },
    { word: "Square", definition: "quảng trường", example: "" },
    { word: "Gather", definition: "tụ họp, thu thập", example: "" },
    { word: "Patio", definition: "hiên, sân", example: "" },
    { word: "Block", definition: "tảng, chặn", example: "" },
    { word: "Curtain", definition: "rèm cửa", example: "" },
];

const test8_part1_words: VocabItem[] = [
    { word: "Take off", definition: "cất cánh, tháo (đồ)", example: "" },
    { word: "Badge", definition: "huy hiệu, phù hiệu", example: "" },
    { word: "Lean over", definition: "nghiêng người qua", example: "" },
    { word: "Lock", definition: "ổ khóa, khóa", example: "" },
    { word: "Lift", definition: "nâng lên, thang máy", example: "" },
    { word: "Bin", definition: "thùng chứa", example: "" },
    { word: "Railing", definition: "lan can", example: "" },
    { word: "Climbing", definition: "leo trèo", example: "" },
    { word: "Carry", definition: "mang, vác, chở", example: "" },
    { word: "Ladder", definition: "thang", example: "" },
    { word: "Post a sign", definition: "dán bảng hiệu", example: "" },
    { word: "Rest", definition: "nghỉ ngơi, phần còn lại", example: "" },
    { word: "Pole", definition: "cột", example: "" },
    { word: "Row a boat", definition: "chèo thuyền", example: "" },
    { word: "Display case", definition: "tủ trưng bày", example: "" },
    { word: "Tie a necktie", definition: "thắt cà vạt", example: "" },
    { word: "Counter", definition: "quầy, mặt phẳng", example: "" },
    { word: "Wire", definition: "dây điện", example: "" },
    { word: "Suspend", definition: "treo, đình chỉ", example: "" },
    { word: "Wheelbarrow", definition: "xe cút kít", example: "" },
    { word: "Bench", definition: "ghế dài", example: "" },
    { word: "Occupied", definition: "bị chiếm, có người sử dụng", example: "" },
    { word: "Shade (v)", definition: "che bóng, làm mát", example: "" },
    { word: "Prop against", definition: "dựa vào", example: "" },
    { word: "Bulletin board", definition: "bảng thông báo", example: "" },
    { word: "Pin", definition: "ghim, cái ghim", example: "" },
];

const test9_part1_words: VocabItem[] = [
    { word: "Rug", definition: "thảm", example: "" },
    { word: "Doorknob", definition: "tay nắm cửa", example: "" },
    { word: "Turn a doorknob", definition: "xoay tay nắm cửa", example: "" },
    { word: "Climb", definition: "leo, trèo", example: "" },
    { word: "Ladder", definition: "thang", example: "" },
    { word: "Hang", definition: "treo, mắc", example: "" },
    { word: "Light fixture", definition: "đèn chiếu sáng", example: "" },
    { word: "Attach", definition: "gắn, đính", example: "" },
    { word: "File folder", definition: "bìa hồ sơ", example: "" },
    { word: "Carry", definition: "mang, vác", example: "" },
    { word: "Shopping cart", definition: "xe đẩy hàng", example: "" },
    { word: "Line up", definition: "xếp hàng", example: "" },
    { word: "In a row", definition: "liên tiếp", example: "" },
    { word: "Clear away", definition: "dọn đi", example: "" },
    { word: "Walkway", definition: "lối đi", example: "" },
    { word: "Brick", definition: "gạch", example: "" },
    { word: "Branch", definition: "nhánh cây", example: "" },
    { word: "Trim", definition: "tỉa, cắt bớt", example: "" },
    { word: "Flowerpot", definition: "chậu hoa", example: "" },
    { word: "Shovel", definition: "xẻng", example: "" },
    { word: "Lean against", definition: "dựa vào", example: "" },
    { word: "Pile", definition: "chồng, đống", example: "" },
    { word: "Patio", definition: "sân hiên", example: "" },
    { word: "Lamppost", definition: "cột đèn đường", example: "" },
];

const test10_part1_words: VocabItem[] = [
    { word: "Reach", definition: "với tới, chạm tới", example: "" },
    { word: "Adjust", definition: "điều chỉnh, sửa đổi", example: "" },
    { word: "Try on", definition: "thử (quần áo, giày dép)", example: "" },
    { word: "Gloves", definition: "găng tay", example: "" },
    { word: "Dining area", definition: "khu vực ăn uống", example: "" },
    { word: "Took", definition: "đã lấy", example: "" },
    { word: "Cupboard", definition: "tủ chén, tủ đựng đồ", example: "" },
    { word: "Storage", definition: "sự lưu trữ", example: "" },
    { word: "Cushion", definition: "gối, đệm", example: "" },
    { word: "Pick up", definition: "nhặt lên, đón", example: "" },
    { word: "Rake", definition: "cái cào, cào lá", example: "" },
    { word: "Leaves", definition: "lá cây", example: "" },
    { word: "Shovel", definition: "xẻng, xúc đất", example: "" },
    { word: "Soil", definition: "đất, bùn", example: "" },
    { word: "Water", definition: "tưới nước", example: "" },
    { word: "Dinner plate", definition: "đĩa ăn tối", example: "" },
    { word: "Sink", definition: "bồn rửa", example: "" },
    { word: "Floor tile", definition: "gạch lát sàn", example: "" },
    { word: "Line up", definition: "xếp hàng", example: "" },
    { word: "Platter", definition: "khay, đĩa lớn", example: "" },
    { word: "Crouch down", definition: "ngồi xổm, cúi xuống", example: "" },
    { word: "Counter", definition: "quầy, mặt bàn", example: "" },
    { word: "Hand", definition: "đưa tay, trao tay", example: "" },
    { word: "Lightbulb", definition: "bóng đèn", example: "" },
    { word: "Potted plant", definition: "cây cảnh trong chậu", example: "" },
    { word: "Entrance", definition: "lối vào", example: "" },
    { word: "Awning", definition: "mái hiên", example: "" },
    { word: "Shade", definition: "che bóng", example: "" },
    { word: "Prop", definition: "chống đỡ, vật chống đỡ", example: "" },
];

export const listeningPart1Vocabulary: VocabularyPart = {
    id: 1,
    title: "Listening Part 1",
    description: "Lưu ý: Đây là từ vựng Listening, bạn nên sử dụng hoạt động Nghe điền từ nhiều hơn nhé.",
    tests: [
        { id: 101, title: "Test 1", words: test1_part1_words },
        { id: 102, title: "Test 2", words: test2_part1_words },
        { id: 103, title: "Test 3", words: test3_part1_words },
        { id: 104, title: "Test 4", words: test4_part1_words },
        { id: 105, title: "Test 5", words: test5_part1_words },
        { id: 106, title: "Test 6", words: test6_part1_words },
        { id: 107, title: "Test 7", words: test7_part1_words },
        { id: 108, title: "Test 8", words: test8_part1_words },
        { id: 109, title: "Test 9", words: test9_part1_words },
        { id: 110, title: "Test 10", words: test10_part1_words },
    ]
};
