import { VocabularyPart } from '../../types';

export const medicalEnglishVocabulary: VocabularyPart = {
    id: 11, // Assigning a unique ID
    title: 'Medical English',
    description: 'Vocabulary for Medical Contexts',
    isNew: true,
    tests: [
        {
            id: 1,
            title: 'Set 1 - Health & illness',
            words: [
                { word: 'nausea', ipa: '/ˈnɔː.zi.ə/', definition: 'buồn nôn' },
                { word: 'vomit', ipa: '/ˈvɒm.ɪt/', definition: 'nôn mửa' },
                { word: 'deteriorate', ipa: '/dɪˈtɪə.ri.ə.reɪt/', definition: 'xấu đi/ tệ đi' },
                { word: 'remission', ipa: '/rɪˈmɪʃ.ən/', definition: 'thuyên giảm' },
                { word: 'relapse', ipa: '/rɪˈlæps/', definition: 'tái phát' }
            ]
        },
        {
            id: 2,
            title: 'Set 2 - Parts of the body 1',
            words: [
                { word: 'jaw (mandible)', ipa: '/dʒɔː/ (/ˈmæn.dɪ.bəl/)', definition: 'Hàm dưới' },
                { word: 'axilla', ipa: '/ækˈsɪl.ə/', definition: 'armpit, nách' },
                { word: 'armpit', ipa: '/ˈɑːm.pɪt/', definition: 'nách' },
                { word: 'upper arm', ipa: '/ˈʌp.ər ɑːm/', definition: 'cánh tay trên' },
                { word: 'nates', ipa: '/ˈneɪ.tiːz/', definition: 'mông' },
                { word: 'buttock', ipa: '/ˈbʌt.ək/', definition: 'mông' },
                { word: 'thigh', ipa: '/θaɪ/', definition: 'đùi' },
                { word: 'calf', ipa: '/kɑːf/', definition: 'bắp chân' },
                { word: 'chest (thorax)', ipa: '/tʃest/ (/ˈθɔː.ræks/)', definition: 'toàn bộ lồng ngực' },
                { word: 'thorax', ipa: '/ˈθɔː.ræks/', definition: 'toàn bộ lồng ngực' },
                { word: 'breast (mamma)', ipa: '/brest/ (/ˈmæm.ə/)', definition: 'ngực tuyến vú' },
                { word: 'tummy', ipa: '/ˈtʌm.i/', definition: 'bụng' },
                { word: 'abdomen', ipa: '/ˈæb.də.mən/', definition: 'bụng' },
                { word: 'navel', ipa: '/ˈneɪ.vəl/', definition: 'rốn' },
                { word: 'umbilicus', ipa: '/ʌmˈbɪl.ɪ.kəs/', definition: 'rốn' },
                { word: 'hip', ipa: '/hɪp/', definition: 'hông' },
                { word: 'coxa', ipa: '/ˈkɒk.sə/', definition: 'hông' },
                { word: 'groin (inguinal region)', ipa: '/ɡrɔɪn/ (/ˈɪŋ.ɡwɪ.nəl ˈriː.dʒən/)', definition: 'háng' },
                { word: 'knee', ipa: '/niː/', definition: 'gối, đầu gối' },
                { word: 'patella', ipa: '/pəˈtel.ə/', definition: 'xương bánh chè' },
                { word: 'kneecap', ipa: '/ˈniː.kæp/', definition: 'xương bánh chè' },
                { word: 'shin', ipa: '/ʃɪn/', definition: 'ống chân' },
                { word: 'limb', ipa: '/lɪm/', definition: 'chi' },
                { word: 'upper limb', ipa: '/ˈʌp.ər lɪm/', definition: 'arm' },
                { word: 'lower limb', ipa: '/ˈləʊ.ər lɪm/', definition: 'leg' },
                { word: 'trunk', ipa: '/trʌŋk/', definition: 'body exclude head & limb' },
                { word: 'radiate', ipa: '/ˈreɪ.di.eɪt/', definition: 'lan ra/ tỏa ra' },
                { word: 'cubitus', ipa: '/ˈkjuː.bɪ.təs/', definition: 'elbow' },
                { word: 'carpus', ipa: '/ˈkɑː.pəs/', definition: 'wrist' },
                { word: 'testicle', ipa: '/ˈtes.tɪ.kəl/', definition: 'tinh hoàn' },
                { word: 'loin', ipa: '/lɔɪn/', definition: 'phần lưng dưới' }
            ]
        },
        {
            id: 3,
            title: 'Set 3 - The abdomen',
            words: [
                { word: 'stomach', ipa: '/ˈstʌm.ək/', definition: 'dạ dày' },
                { word: 'pancreas', ipa: '/ˈpæŋ.kri.əs/', definition: 'tuyến tụy' },
                { word: 'duodenum', ipa: '/ˌdʒuː.əˈdiː.nəm/', definition: 'tá tràng' },
                { word: 'gall bladder', ipa: '/ˈɡɔːl ˌblæd.ər/', definition: 'túi mật' },
                { word: 'liver', ipa: '/ˈlɪv.ər/', definition: 'gan' },
                { word: 'kidney', ipa: '/ˈkɪd.ni/', definition: 'thận' },
                { word: 'spleen', ipa: '/spliːn/', definition: 'lá lách' },
                { word: 'intestine', ipa: '/ɪnˈtes.tɪn/', definition: 'ruột' },
                { word: 'bowel', ipa: '/baʊəl/', definition: 'ruột' },
                { word: 'small intestine', ipa: '/ˌsmɔːl ɪnˈtes.tɪn/', definition: 'ruột non' },
                { word: 'small bowel', ipa: '/ˌsmɔːl ˈbaʊ.əl/', definition: 'ruột non' },
                { word: 'large bowel', ipa: '/ˌlɑːdʒ ˈbaʊ.əl/', definition: 'ruột già' },
                { word: 'large intestune', ipa: '/ˌlɑːdʒ ɪnˈtes.tɪn/', definition: 'ruột già' },
                { word: 'anus', ipa: '/ˈeɪ.nəs/', definition: 'hậu môn' },
                { word: 'rectrum', ipa: '/ˈrek.təm/', definition: 'trực tràng' },
                { word: 'back passage', ipa: '/ˌbæk ˈpæs.ɪdʒ/', definition: 'anus/ rectrum' }
            ]
        },
        {
            id: 4,
            title: 'Set 4 - The chest',
            words: [
                { word: 'respiration', ipa: '/ˌres.pɪˈreɪ.ʃən/', definition: 'hô hấp' },
                { word: 'airway', ipa: '/ˈeə.weɪ/', definition: 'đường thở' },
                { word: 'lobe', ipa: '/ləʊb/', definition: 'thùy phổi' },
                { word: 'larynx', ipa: '/ˈlær.ɪŋks/', definition: 'thanh quản' },
                { word: 'trachea', ipa: '/trəˈkiː.ə/', definition: 'khí quản' },
                { word: 'windpipe', ipa: '/ˈwɪnd.paɪp/', definition: 'khí quản' },
                { word: 'bronchus', ipa: '/ˈbrɒŋ.kəs/', definition: 'phế quản' },
                { word: 'bronchioles', ipa: '/ˈbrɒŋ.ki.əʊlz/', definition: 'tiểu phế quản' },
                { word: 'diaphragm', ipa: '/ˈdaɪ.ə.fræm/', definition: 'màn ngăn, cơ hoành' }
            ]
        },
        {
            id: 5,
            title: 'Set 5 - The pelvis',
            words: [
                { word: 'pelvis', ipa: '/ˈpel.vɪs/', definition: 'xương chậu' },
                { word: 'ureter', ipa: '/jʊəˈriː.tər/', definition: 'niệu quản' },
                { word: 'urine', ipa: '/ˈjʊə.rɪn/', definition: 'nước tiểu' },
                { word: 'bladder', ipa: '/ˈblæd.ər/', definition: 'bàng quang' },
                { word: 'urethra', ipa: '/jʊˈriː.θrə/', definition: 'niệu đạo' }
            ]
        },
        {
            id: 6,
            title: 'Set 6 - Diseases 1',
            words: [
                { word: 'angina pectoris', ipa: '/ænˌdʒaɪ.nə ˈpek.tər.ɪs/', definition: 'đau thắt ngực' },
                { word: 'renal colic', ipa: '/ˌriː.nəl ˈkɒl.ɪk/', definition: 'đau quặn thận' },
                { word: 'inguinal swelling', ipa: '/ˈɪŋ.ɡwɪ.nəl ˈswel.ɪŋ/', definition: 'sưng bẹn' },
                { word: 'abdominal pain', ipa: '/æbˈdɒm.ɪ.nəl peɪn/', definition: 'đau bụng' },
                { word: 'periumbilical rash', ipa: '/ˌper.i.ʌmˈbɪl.ɪ.kəl ræʃ/', definition: 'phát ban quanh rốn' },
                { word: 'thoracic pain', ipa: '/θɔːˈræs.ɪk peɪn/', definition: 'đau lồng ngực' },
                { word: 'enlarged axillary node', ipa: '/ɪnˈlɑːdʒd ækˈsɪl.ər.i nəʊd/', definition: 'hạch nách to' },
                { word: 'mandibular pain', ipa: '/mænˈdɪb.jə.lər peɪn/', definition: 'đau hàm dưới' }
            ]
        },
        {
            id: 7,
            title: 'Set 7 - Diseases 2',
            words: [
                { word: 'hepatitis a, b', ipa: '/ˌhep.əˈtaɪ.tɪs eɪ, biː/', definition: 'viêm gan' },
                { word: 'pneumonia', ipa: '/njuːˈməʊ.ni.ə/', definition: 'viêm phổi' },
                { word: 'nephritis', ipa: '/nəˈfraɪ.tɪs/', definition: 'viêm thận' },
                { word: 'gastric ulcer', ipa: '/ˌɡæs.trɪk ˈʌl.sər/', definition: 'loét dạ dày' },
                { word: 'cystitis', ipa: '/sɪˈstaɪ.tɪs/', definition: 'viêm bàng quang' },
                { word: 'angina pectoris', ipa: '/ænˌdʒaɪ.nə ˈpek.tər.ɪs/', definition: 'đau thắt vùng ngực' },
                { word: 'cholecystitis', ipa: '/ˌkɒl.ɪ.sɪˈstaɪ.tɪs/', definition: 'viêm túi mật' },
                { word: 'ulcerative colitis', ipa: '/ˌʌl.sər.ə.tɪv kəˈlaɪ.tɪs/', definition: 'viêm loét đại tràng' }
            ]
        },
        {
            id: 8,
            title: 'Set 8 - Body functions',
            words: [
                { word: 'sensation', ipa: '/senˈseɪ.ʃən/', definition: 'feeling' },
                { word: 'gait', ipa: '/ɡeɪt/', definition: 'dáng đi' },
                { word: 'inhale', ipa: '/ɪnˈheɪl/', definition: 'breathe in/ take a breath in' },
                { word: 'exhale', ipa: '/eksˈheɪl/', definition: 'breathe out' },
                { word: 'urinate', ipa: '/ˈjʊə.rɪ.neɪt/', definition: 'đi tiểu' },
                { word: 'micturate', ipa: '/ˈmɪk.tʃə.reɪt/', definition: 'đi tiểu' },
                { word: 'pass urine, pass water', ipa: '/pɑːs ˈjʊə.rɪn/ - /pɑːs ˈwɔː.tər/', definition: 'đi tiểu' },
                { word: 'urine', ipa: '/ˈjʊə.rɪn/', definition: 'nước tiểu' },
                { word: 'defecate', ipa: '/ˈdef.ə.keɪt/', definition: 'đại tiện' },
                { word: 'pass faeces', ipa: '/pɑːs ˈfiː.siːz/', definition: 'đi ngoài, đi phân' },
                { word: 'pass stools', ipa: '/pɑːs stuːlz/', definition: 'đi ngoài, đi phân' },
                { word: 'faeces', ipa: '/ˈfiː.siːz/', definition: 'phân, cứt' },
                { word: 'stools', ipa: '/stuːlz/', definition: 'phân, cứt' },
                { word: 'menstruate', ipa: '/ˈmen.stru.eɪt/', definition: 'hành kinh, có kinh' },
                { word: 'have a period', ipa: '/hæv ə ˈpɪə.ri.əd/', definition: 'hành kinh, có kinh' },
                { word: 'menstrual period', ipa: '/ˈmen.stru.əl ˈpɪə.ri.əd/', definition: 'kỳ kinh nguyệt' },
                { word: 'monthly period', ipa: '/ˈmʌnθ.li ˈpɪə.ri.əd/', definition: 'kỳ kinh nguyệt' },
                { word: 'shake', ipa: '/ʃeɪk/', definition: 'run' },
                { word: 'sweat', ipa: '/swet/', definition: 'đổ mồ hôi' }
            ]
        },
        {
            id: 9,
            title: 'Set 9 - Diseases 3',
            words: [
                { word: 'dysuria', ipa: '/dɪsˈjʊə.ri.ə/', definition: 'tiểu buốt/ rát' },
                { word: 'dysphagia', ipa: '/dɪsˈfeɪ.dʒi.ə/', definition: 'khó nuốt' },
                { word: 'diplopia', ipa: '/dɪˈpləʊ.pi.ə/', definition: 'nhìn đôi/ song thị' },
                { word: 'dysphasia', ipa: '/dɪsˈfeɪ.zi.ə/', definition: 'khó nói/ loạn ngôn' },
                { word: 'dyspnoea', ipa: '/dɪspˈniː.ə/', definition: 'khó thở' },
                { word: 'numbness', ipa: '/ˈnʌm.nəs/', definition: 'tê bì' },
                { word: 'tingling', ipa: '/ˈtɪŋ.ɡlɪŋ/', definition: 'tê bì' },
                { word: 'peripheral neuropathy', ipa: '/pəˈrɪf.ər.əl njʊəˈrɒp.ə.θi/', definition: 'Bệnh thần kinh ngoại biên.' },
                { word: 'oesophageal stricture', ipa: '/ɪˌsɒf.əˈdʒiː.əl ˈstrɪk.tʃər/', definition: 'Hẹp thực quản.' },
                { word: 'prostatic hypertrophy', ipa: '/prɒsˈtæt.ɪk haɪˈpɜː.trə.fi/', definition: 'Phì đại tuyến tiền liệt' },
                { word: 'hyperthyroidism', ipa: '/ˌhaɪ.pəˈθaɪ.rɔɪ.dɪ.zəm/', definition: 'Cường giáp' },
                { word: 'Parkinsonism', ipa: '/ˈpɑː.kɪn.sən.ɪ.zəm/', definition: 'Hội chứng Parkinson (tay run)' },
                { word: 'left heart failure', ipa: '/left hɑːt ˈfeɪ.ljər/', definition: 'Suy tim trái' }
            ]
        },
        {
            id: 10,
            title: 'L2 - Set 1',
            words: [
                { word: 'adjuster', definition: 'thẩm định viên, người của công ty bảo hiểm xác định sự tổn thất' },
                { word: 'address', definition: 'địa chỉ' },
                { word: 'advice nurse', definition: 'y tá tư vấn' },
                { word: 'ambulance', definition: 'xe cứu thương, xe cấp cứu' },
                { word: 'amount', definition: 'lượng, số lượng' },
                { word: 'appliances', definition: 'dụng cụ, thiết bị' },
                { word: 'application', definition: 'đơn' },
                { word: 'appointment', definition: 'cuộc hẹn' },
                { word: 'appraiser', definition: 'giám định viên, người định giá' },
                { word: 'approved', definition: 'phê duyệt, chấp thuận' },
                { word: 'APR-Annual Percentage Rate', definition: 'Lãi suất phần trăm bình quân hàng năm' },
                { word: 'arrest', definition: 'sự bắt giữ' },
                { word: 'arrival', definition: 'sự đến, sự tới nơi' },
                { word: 'assault', definition: 'sự hành hung' },
                { word: 'ATM-Automated Teller Machine', definition: 'Máy Rút Tiền Tự Động' },
                { word: 'baby formula', definition: 'sữa công thức' },
                { word: 'bail', definition: 'tiền bảo lãnh' },
                { word: 'balance transfer', definition: 'Chuyển đổi số dư (từ tài khoản này sang tài khoản khoản khác)' },
                { word: 'beneficiary', definition: 'người thụ hưởng' },
                { word: 'benefits', definition: 'những tiền trợ cấp, phúc lợi, lợi ích' },
                { word: 'bill', definition: 'hoá đơn' },
                { word: 'birth certificate', definition: 'giấy khai sinh' },
                { word: 'bodily injury', definition: 'thương tích cơ thể' },
                { word: 'body shop', definition: 'tiệm làm đồng xe, sửa xe' },
                { word: 'booster shot', definition: 'tiêm chủng hỗ trợ, tiêm nhắc, tiêm chủng hỗ trợ sau lần chủng ngừa trước đó' },
                { word: 'brand', definition: 'nhãn, loại hàng, chính hiệu' },
                { word: 'brand name medication', definition: 'thuốc chính hiệu' },
                { word: 'breathing', definition: 'sự thở' },
                { word: 'brief', definition: 'ngắn' },
                { word: 'budget billing', definition: 'ngân sách thanh toán' }
            ]
        },
        {
            id: 11,
            title: 'L2 - Set 2',
            words: [
                { word: 'bumper', definition: 'cản xe' },
                { word: 'bundled services', definition: 'dịch vụ trọn gói' },
                { word: 'burglary', definition: 'nạn ăn trộm, tội trộm' },
                { word: 'business days', definition: 'những ngày làm việc' },
                { word: 'chest', definition: 'ngực' },
                { word: 'chicken Pox', definition: 'bệnh thuỷ đậu' },
                { word: 'claim', definition: 'hồ sơ bồi thường, Yêu cầu giải quyết quyền lợi bảo hiểm' },
                { word: 'clinic', definition: 'phòng khám chữa bệnh, bệnh xá' },
                { word: 'collections (collections department)', definition: 'Thu hồi (bộ phận thu hồi (nợ))' },
                { word: 'collision', definition: 'sự đụng' },
                { word: 'collision coverage', definition: 'khoản bồi thường cho xe khi đụng xe' },
                { word: 'compact', definition: 'nhỏ, gọn' },
                { word: 'comprehensive coverage', definition: 'khoản bồi thường không do xe đụng, khoản bồi thường thiệt hại cho xe trong những trường hợp khác ngoài sự đụng xe,' },
                { word: 'co-pay', definition: 'chi phí cùng trả, cùng trả tiền' },
                { word: 'cough', definition: 'ho' },
                { word: 'CPR (Cardio pulmonary resuscitation)', definition: 'hồi sức tim-phổi' },
                { word: 'crashed', definition: 'đâm sầm vào, tông vào' },
                { word: 'credit report', definition: 'bản báo cáo tín dụng' },
                { word: 'CT (Computerized Tomography) scan', definition: 'chụp cắt lớp điện toán' },
                { word: 'damages', definition: 'những thiệt hại, hư hại' },
                { word: 'deadline', definition: 'hạn chót, hạn cuối cùng' },
                { word: 'debris', definition: 'mảnh vỡ, mảnh vụn' },
                { word: 'deductible', definition: 'tiền khấu trừ' },
                { word: 'default', definition: 'Việc không trả được nợ' },
                { word: 'delivery', definition: 'sự sanh đẻ' },
                { word: 'departure', definition: 'sự rời khỏi, sự ra đi, sự khởi hành' },
                { word: 'diabetes', definition: 'bệnh tiểu đường' },
                { word: 'diarrhea', definition: 'tiêu chảy' },
                { word: 'disability', definition: 'sự tàn phế, sự ốm yếu tàn tật' },
                { word: 'DMV (Department of Motor Vehicles)', definition: 'Cơ Quan Lộ Vận, Cơ Quan Quản Lý Các Phương Tiện Cơ Giới' },
                { word: 'dosage', definition: 'sự phân liều lượng' }
            ]
        },
        {
            id: 12,
            title: 'L2 - Set 3',
            words: [
                { word: 'down payment', definition: 'Khoản tiền trả trước' },
                { word: 'down, weak', definition: 'cảm giác yếu, đau ốm' },
                { word: 'drivable', definition: 'có thể chạy' },
                { word: 'drive in facilities', definition: 'những nơi kiểm tra và định giá tiền bồi thường cho các thiệt hại/ hư hại của xe từ công ty bảo hiểm' },
                { word: 'drive through', definition: 'sự phục vụ kiểu tạt xe qua' },
                { word: 'DUI', definition: 'lái xe dưới sự ảnh hưởng của rượu bia/thuốc' },
                { word: 'dull pain', definition: 'đau ngầm, đau âm ỉ, đau lâm râm' },
                { word: 'effective date', definition: 'ngày có hiệu lực' },
                { word: 'emergency', definition: 'sự khẩn cấp, tình trạng khẩn cấp' },
                { word: 'employer', definition: 'chủ, người sử dụng lao động' },
                { word: 'enrolled', definition: 'đã đăng ký' },
                { word: 'entrance', definition: 'lối vào, cửa vào' },
                { word: 'equity', definition: 'giá trị tài sản thế chấp' },
                { word: 'ER (Emergency Room)', definition: 'phòng cấp cứu' },
                { word: 'escrow account', definition: 'Tài khoản bảo chứng; tài khoản lưu giữ uỷ thác' },
                { word: 'estimate', definition: 'sự đánh giá, sự ước lượng' },
                { word: 'expiration date', definition: 'ngày hết hiệu lực, ngày hết hạn' },
                { word: 'expire', definition: 'hết hạn, hết hiệu lực, kết thúc' },
                { word: 'felony', definition: 'trọng tội, tội nghiêm trọng, tội ác, tội nặng' },
                { word: 'fender', definition: 'cản sốc (vè xe)' },
                { word: 'field sobriety test', definition: 'kiểm tra vể sự tỉnh táo tại hiện trường' },
                { word: 'fine', definition: 'tiền phạt' },
                { word: 'fingerprints', definition: 'dấu lăn ngón tay, dấu điểm chỉ, dấu tay' },
                { word: 'fixed interest rate', definition: 'Lãi suất cố định' },
                { word: 'flight', definition: 'sự bay, chuyến bay' },
                { word: 'food stamps', definition: 'tem phiếu thực phẩm,' },
                { word: 'foreclosure', definition: 'tịch thu tài sản thế chấp' },
                { word: 'forms', definition: 'mẫu (đơn...) có chỗ trống (để điền vào)' },
                { word: 'formulary medication', definition: 'danh sách thuốc' },
                { word: 'full coverage', definition: 'bảo hiểm toàn diện, bảo hiểm hai chiều, các tổn thất bảo hiểm đã được bồi thường đầy đủ' },
                { word: 'furnace', definition: 'lò sưởi' }
            ]
        },
        {
            id: 13,
            title: 'L2 - Set 4',
            words: [
                { word: 'gas leak', definition: 'rò rỉ khí đốt, bị xì gas' },
                { word: 'generic', definition: 'thuốc gốc, thuộc những sản phẩm được phân phối mà không có tên nhãn hiệu' },
                { word: 'German measles (rubella)', definition: 'bệnh sởi Đức' },
                { word: 'grace period', definition: 'Thời gian ân hạn' },
                { word: 'gross monthly income', definition: 'Tổng thu nhập hàng tháng' },
                { word: 'guest', definition: 'khách' },
                { word: 'health plan', definition: 'chương trình sức khoẻ' },
                { word: 'heart', definition: 'tim' },
                { word: 'heart attack', definition: 'nhồi máu cơ tim' },
                { word: 'high blood pressure', definition: 'áp huyết cao' },
                { word: 'hit and run', definition: 'gây tai nạn rồi chạy luôn' },
                { word: 'HMO (Health Maintenance Organization)', definition: 'tổ chức duy trì sức khỏe' },
                { word: 'home equity line', definition: 'định mức tín dụng theo giá trị thế chấp nhà' },
                { word: 'home equity loan', definition: 'khoản vay theo giá trị thế chấp nhà' },
                { word: 'homeowner', definition: 'chủ nhà' },
                { word: 'homeowners insurance', definition: 'bảo hiểm chủ sở hữu nhà' },
                { word: 'horn, to honk', definition: 'bóp còi' },
                { word: 'ICU (Intensive Care Unit)', definition: 'Đơn vị đIều trị tăng cường' },
                { word: 'immunization record', definition: 'hồ sơ tiêm chủng' },
                { word: 'inspect (to)', definition: 'kiểm tra, xem xét' },
                { word: 'insurance', definition: 'bảo hiểm' },
                { word: 'insured', definition: 'được bảo hiểm, có bảo hiểm' },
                { word: 'interest rate', definition: 'Lãi suất' },
                { word: 'itching', definition: 'sự ngứa' },
                { word: 'landlord', definition: 'chủ nhà, chủ quán trọ, địa chủ' },
                { word: 'late fee', definition: 'lệ phí quá hạn, lệ phí trễ hạn' },
                { word: 'layoff', definition: 'sự sa thải, sự cho nghỉ việc' },
                { word: 'layover', definition: 'điểm dừng, vị trí chuyển chuyến bay' },
                { word: 'liability insurance', definition: 'bảo hiểm trách nhiệm' },
                { word: 'license plate number', definition: 'số biển xe' },
                { word: 'lobby', definition: 'hành lang, phòng đợi, phòng trước' }
            ]
        },
        {
            id: 14,
            title: 'L2 - Set 5',
            words: [
                { word: 'mailing address', definition: 'địa chỉ thư' },
                { word: 'measles (rubeola)', definition: 'bệnh sởi' },
                { word: 'member ID', definition: 'số nhận dạng thành viên' },
                { word: 'meter reading', definition: 'đọc số lượng trên máy đo' },
                { word: 'misdemeanor', definition: 'phi pháp, khinh tội, một tội nhỏ' },
                { word: 'money order', definition: 'Phiếu tiền' },
                { word: 'MRI (Magnetic Resonance Imaging)', definition: 'chụp cộng hưởng từ' },
                { word: 'mumps', definition: 'bệnh quai bị' },
                { word: 'nape (of the neck)', definition: 'gáy, ót' },
                { word: 'net monthly income', definition: 'Thu nhập ròng hàng tháng' },
                { word: 'neurologist', definition: 'bác sỹ chuyên về thần kinh' },
                { word: 'niece', definition: 'cháu gái (con của anh, chị, em)' },
                { word: 'no fault laws', definition: 'những luật quy định được quyền bồi thường không kể lỗi do ai; những luật quy định rằng khi tai nạn xảy ra mỗi bên tự báo bảo hiểm của mình để đòi bồi thường, không cần biết nguyên nhân tai nạn do ai gây ra' },
                { word: 'non-payment', definition: 'sự không trả tiền, sự không thanh toán' },
                { word: 'numbness', definition: 'sự tê' },
                { word: 'obstetrician', definition: 'bác sỹ sản khoa' },
                { word: 'on demand', definition: 'theo yêu cầu, khi yêu cầu' },
                { word: 'OTC (over-the-counter)', definition: 'thuốc có thể mua không cần đơn bác sĩ' },
                { word: 'overdraft fee', definition: 'Phí thấu chi' },
                { word: 'P.O. Box', definition: 'hộp thư bưu điện' },
                { word: 'paperwork', definition: 'giấy tờ, giấy má sổ sách' },
                { word: 'participates', definition: 'tham gia, tham dự' },
                { word: 'pass out', definition: 'ngất đi, xỉu đi' },
                { word: 'password', definition: 'Khẩu lệnh, mật khẩu, mật hiệu' },
                { word: 'pay per view', definition: 'trả tiền cho mỗi lần xem' },
                { word: 'paychecks', definition: 'những chi phiếu (để) trả lương' },
                { word: 'payroll', definition: 'bảng lương nhân công, sổ lương' },
                { word: 'paystubs', definition: 'những phiếu trả lương, cuống lương' },
                { word: 'pharmacy', definition: 'phòng dược, nhà thuốc' },
                { word: 'PIP (Personal Injury Protection)', definition: 'bảo hiểm chấn thương cá nhân' },
                { word: 'point of impact', definition: 'điểm vai chạm, nơi đụng' }
            ]
        },
        {
            id: 15,
            title: 'L2 - Set 6',
            words: [
                { word: 'policy', definition: 'đơn bảo hiểm, hợp đồng bảo hiểm' },
                { word: 'PPO (Preferred Provider Organization)', definition: 'tổ chức nhóm cung cấp ưu tiên' },
                { word: 'premium', definition: 'bảo phí, phí bảo hiểm,' },
                { word: 'primary care physician (pcp)', definition: 'bác sỹ chính săn sóc' },
                { word: 'quote', definition: 'định giá, báo giá, giá tham khảo' },
                { word: 'recorded', definition: 'được thu băng, ghi âm, thu âm' },
                { word: 'recorded statement', definition: 'lời khai được thu âm' },
                { word: 'records', definition: 'những hồ sơ, biên bản, sổ sách ghi sổ' },
                { word: 'refer', definition: 'chuyển đến, giới thiệu đến' },
                { word: 'refill', definition: 'lấy thêm thuốc theo toa/ lấy thuốc lại theo toa' },
                { word: 'registered', definition: 'đã đăng ký, đã vào sổ' },
                { word: 'relationship', definition: 'Mối quan hệ, mối liên hệ, sự giao thiệp' },
                { word: 'renewal', definition: 'sự gia hạn, sự làm lại, sự tái tục' },
                { word: 'rent', definition: 'thuê mướn, thuê' },
                { word: 'repairs', definition: 'sự sửa chữa, sự tu sửa' },
                { word: 'requirements', definition: 'những yêu cầu, điều kiện cần thiết, nhu cầu' },
                { word: 'reservation', definition: 'sự giữ trước, sự đặt chỗ trước' },
                { word: 'residing', definition: 'ở tại, trú ngụ tại, cư trú, sinh sống' },
                { word: 'reverse', definition: 'chạy lui' },
                { word: 'right of way', definition: 'quyền đi trước, quyền ưu tiên' },
                { word: 'roadside assistance', definition: 'hỗ trợ trên đường' },
                { word: 'robbery', definition: 'sự ăn cướp, vụ ăn cướp' },
                { word: 'round-trip', definition: 'khứ hồi, cuộc du hành vừa đi vừa về' },
                { word: 'routing number', definition: 'Số định tuyến' },
                { word: 'salvage value', definition: 'giá trị thu hồi, giá trị còn lại của thiết bị' },
                { word: 'schedule', definition: 'lịch trình, bảng giờ giấc, thời gian biểu' },
                { word: 'security deposit', definition: 'tiền đặt cọc, tiền bảo chứng' },
                { word: 'service fee', definition: 'phí phục vụ, phí dịch vụ' },
                { word: 'sewage', definition: 'chất thải, nước cống, rác cống' },
                { word: 'sharp pain', definition: 'đau nhói' },
                { word: 'side effects', definition: 'các tác dụng phụ' }
            ]
        },
        {
            id: 16,
            title: 'L2 - Set 7',
            words: [
                { word: 'social security', definition: 'phúc lợi xã hội, an sinh xã hội' },
                { word: 'social security number', definition: 'số an sinh xã hội' },
                { word: 'social worker', definition: 'nhân viên xã hội' },
                { word: 'STD (Sexually Transmitted Disease)', definition: 'bệnh truyền nhiễm qua đường sinh dục' },
                { word: 'stroke (cva)', definition: 'đột quỵ , tai biến mạch máu não' },
                { word: 'subscriber', definition: 'người đăng ký' },
                { word: 'TB (Tuberculosis)', definition: 'bệnh lao' },
                { word: 'temporary repairs', definition: 'những sự sửa chữa tạm thời' },
                { word: 'tenant', definition: 'người thuê, người mướn' },
                { word: 'tetanus', definition: 'bệnh phong đòn gánh, bệnh uốn ván' },
                { word: 'theft', definition: 'sự ăn trộm, sự trộm cắp' },
                { word: 'throbbing pain', definition: 'sự đau buốt, đau nhoi nhói' },
                { word: 'tingling', definition: 'cảm giác châm chích' },
                { word: 'to enroll', definition: 'đăng ký' },
                { word: 'to fill (Med)', definition: 'lấy thuốc theo toa' },
                { word: 'to fill a prescription', definition: 'lấy thuốc theo toa của bác sỹ' },
                { word: 'to renew', definition: 'gia hạn, làm lại, tái tục' },
                { word: 'to waive', definition: 'Miễn (phí)' },
                { word: 'total loss', definition: 'tổn tất toàn bộ' },
                { word: 'tow yard', definition: 'bãi giữ xe' },
                { word: 'transportation', definition: 'Phương tiện đi lại, phương tiện vận chuyển, xe cộ' },
                { word: 'triage nurse', definition: 'y tá phân loại bệnh' },
                { word: 'troubleshooting', definition: 'việc sửa hỏng hóc, việc xử lý sự cố' },
                { word: 'twins', definition: 'sinh đôi' },
                { word: 'underwriter (underwriting)', definition: 'người thẩm định hợp đồng bảo hiểm' },
                { word: 'unemployment benefits', definition: 'những trợ cấp thất nghiệp' },
                { word: 'update', definition: 'cập nhật, hiện đại hoá' },
                { word: 'upgrade services', definition: 'nâng cấp các dịch vụ' },
                { word: 'utility bill', definition: 'hóa đơn điện nước' },
                { word: 'vomiting', definition: 'sự ói ra' },
                { word: 'water heater', definition: 'bộ đun nước' },
                { word: 'year/make/model', definition: 'đời/hiệu/mẫu' }
            ]
        },
        {
            id: 17,
            title: 'L3 - Set 1',
            words: [
                { word: 'account', definition: 'tài khoản, trương mục' },
                { word: 'aches and pains', definition: 'đau nhức' },
                { word: 'acid reflux', definition: 'chứng axít trào ngược' },
                { word: 'airway', definition: 'đường khí, đường thở' },
                { word: 'alley', definition: 'ngõ, ngõ hẻm' },
                { word: 'annual out-of-pocket maximum', definition: 'số tiền tối đa phải trả trong năm' },
                { word: 'antibiotics', definition: 'những thuốc kháng sinh, thuốc trụ sinh' },
                { word: 'antifreeze', definition: 'hoá chất chống đông' },
                { word: 'antitheft device', definition: 'thiết bị chống trộm' },
                { word: 'artery', definition: 'động mạch' },
                { word: 'backfire', definition: 'hiện tượng cháy nổ không tiếp diễn liên tục' },
                { word: 'backrest', definition: 'lưng ghế' },
                { word: 'billing department', definition: 'sở tính tiền' },
                { word: 'birthmarks', definition: 'vết chàm, vết bớt' },
                { word: 'bladder', definition: 'bàng quang, bọng đái' },
                { word: 'bleeding', definition: 'chảy máu, xuất huyết' },
                { word: 'blind curve', definition: 'Khúc quanh mà cả hai bên đều không thấy nhau' },
                { word: 'blind spot', definition: 'điểm mù' },
                { word: 'blinkers', definition: 'những đèn tín hiệu' },
                { word: 'blood alcohol level', definition: 'nồng độ rượu trong máu' },
                { word: 'blood pressure cuff', definition: 'dụng cụ đo huyết áp, bao quấn quanh vùng cánh tay trên để đo huyết áp' },
                { word: 'bloody stool', definition: 'máu trong phân' },
                { word: 'bowel movement', definition: 'đi tiêu, đại tiện' },
                { word: 'breast self- examination', definition: 'tự kiểm tra vú' },
                { word: 'breast-feeding clinic', definition: 'bệnh xá chuyên về sự nuôi bàng sữa mẹ' },
                { word: 'breathing tube', definition: 'ống thở' },
                { word: 'broadside collision', definition: 'sự va chạm phía bên (theo hình chữ T)' },
                { word: 'broken down', definition: 'bị hỏng, chết máy' },
                { word: 'bronchi', definition: 'phế quản, cuống phổi' },
                { word: 'burning', definition: 'đau rát' },
                { word: 'burning sensation', definition: 'cảm giác bỏng rát' }
            ]
        },
        {
            id: 18,
            title: 'L3 - Set 2',
            words: [
                { word: 'buttock', definition: 'mông' },
                { word: 'cardiac arrest', definition: 'ngừng tim, ngừng tuần hoàn' },
                { word: 'cavity', definition: 'sâu răng' },
                { word: 'change lane (noun)', definition: 'làn quẹo' },
                { word: 'chart', definition: 'giấy bệnh án' },
                { word: 'checking account', definition: 'trương mục/tài khoản vãng lai, trương mục/tài khoản ngân phiếu' },
                { word: 'check-point', definition: 'trạm kiểm soát' },
                { word: 'chills', definition: 'ớn lạnh' },
                { word: 'chiropractor', definition: 'Người chuyên nắn bóp cột sống' },
                { word: 'chlamydia', definition: 'chlamydia' },
                { word: 'choke, to', definition: 'nghẹt thở' },
                { word: 'chronic', definition: 'mạn tính, kinh niên' },
                { word: 'claims', definition: 'những hồ sơ bồi thường' },
                { word: 'clutch', definition: 'bộ ly hợp, côn ly hợp' },
                { word: 'collections', definition: 'Thu hồi (nợ)' },
                { word: 'come to rest ( a car after an accident)', definition: 'ngừng lại' },
                { word: 'communicable disease', definition: 'bệnh truyền nhiễm' },
                { word: 'complications', definition: 'những biến chứng' },
                { word: 'comply, (to)', definition: 'Tuân thủ' },
                { word: 'congested', definition: 'bị tắt nghẽn, bị sung huyết' },
                { word: 'constipated', definition: 'bị táo bón' },
                { word: 'constipation', definition: 'sự táo bón' },
                { word: 'contagious', definition: 'lây, truyền nhiễm' },
                { word: 'co-pay, co-payment', definition: 'chi phí cùng trả, cùng trả tiền' },
                { word: 'co-signer', definition: 'Người đồng ký tên' },
                { word: 'cough up', definition: 'ho ra, ho lên' },
                { word: 'coverage', definition: 'bao trả' },
                { word: 'cramps', definition: 'cơn đau thắt' },
                { word: 'credit check', definition: 'Việc kiểm tra tín dụng' },
                { word: 'cruise control', definition: 'hệ thống ga tự động, hệ thống điều khiển hành trình' },
                { word: 'dealer', definition: 'Người buôn bán (hoặc là đại lý)' }
            ]
        },
        {
            id: 19,
            title: 'L3 - Set 3',
            words: [
                { word: 'defroster', definition: 'thiết bị làm tan đông' },
                { word: 'dent', definition: 'vết lõm, vết thụn, vết móp' },
                { word: 'deposit', definition: 'Gửi (tiền)' },
                { word: 'De-Seg: Disciplinary Segregation', definition: 'cách ly vì vi phạm kỷ luật' },
                { word: 'detour', definition: 'đường vòng, chỗ quanh co, khúc ngoặt' },
                { word: 'diabetic', definition: 'người mắc bệnh tiểu đường' },
                { word: 'digits', definition: 'những con số' },
                { word: 'diphtheria-tetanus- pertussis vaccine (DPT, DT, DtaP, DTP)', definition: 'vắc-xin ngừa bệnh bạch hầu, uốn ván, và ho gà' },
                { word: 'discomfort', definition: 'cảm giác khó chịu' },
                { word: 'ditch', definition: 'rãnh, mương' },
                { word: 'dizzy, light headed', definition: 'hoa mắt, choáng váng, chóng mặt' },
                { word: 'doing the Dutch/ the "Dutch Act"', definition: 'tự tử, tự vẫn' },
                { word: 'double park', definition: 'đậu cập bên hông một chiếc xe đang đậu bên lề đường' },
                { word: 'drizzling', definition: 'mưa phùn, mưa bụi' },
                { word: 'durable medical equipment', definition: 'thiết bị y tế lâu bền' },
                { word: 'eastbound', definition: 'về hướng đông' },
                { word: 'exit ramp', definition: 'đường ra khỏi quốc lộ' },
                { word: 'feces', definition: 'phân' },
                { word: 'fender', definition: 'cản sốc (vè xe)' },
                { word: 'fender bender', definition: 'tai nạn nhẹ' },
                { word: 'fishtail', definition: 'hiện tượng bánh sau lắc qua hai bên' },
                { word: 'flip over', definition: 'lật qua' },
                { word: 'follow-up', definition: 'sự theo dõi bệnh nhân' },
                { word: 'four wheel drive', definition: 'bốn bánh chủ động' },
                { word: 'freeway', definition: 'sa lộ' },
                { word: 'gear shift', definition: 'sang số' },
                { word: 'goosebumps', definition: 'nổi da gà' },
                { word: 'groin', definition: 'háng' },
                { word: 'hacking cough', definition: 'ho khan' },
                { word: 'headlights', definition: 'đèn đầu xe, đèn lái' },
                { word: 'heal, (to)', definition: 'chữa khỏi bệnh, làm lành' }
            ]
        },
        {
            id: 20,
            title: 'L3 - Set 4',
            words: [
                { word: 'Health Maintenance Organization (HMO)', definition: 'tổ chức duy trì sức khỏe' },
                { word: 'heart murmur', definition: 'Tiếng thổi tim' },
                { word: 'highway patrol', definition: 'đội tuần tra xa lộ' },
                { word: 'hinged side door (in a van)', definition: 'cửa trượt, cửa kéo (xe van)' },
                { word: 'hives', definition: 'chứng nổi mề đay (vùng da sẩn đỏ, ngứa)' },
                { word: 'hoarseness', definition: 'giọng khản, khàn khàn' },
                { word: 'hospice care', definition: 'chăm sóc cận tử, sự chăm sóc từ cơ sở điều dưỡng bệnh nan y' },
                { word: 'hubcap', definition: 'Nắp tròn đậy trục bánh xe' },
                { word: 'I.K. : Inmate Kitchen', definition: 'phòng bếp của tù nhân' },
                { word: 'impounded', definition: 'giam xe' },
                { word: 'infection', definition: 'nhiễm trùng' },
                { word: 'in-network', definition: 'trong mạng lưới' },
                { word: 'inpatient', definition: 'bệnh nhân nội trú' },
                { word: 'installments', definition: 'những khoản trả góp mỗi lần' },
                { word: 'insufficient funds', definition: 'không đủ ngân quỹ' },
                { word: 'laxative', definition: 'thuốc nhuận tràng, nhuận tràng' },
                { word: 'limb', definition: 'chân, tay' },
                { word: 'listlessness', definition: 'sự thiếu sinh lực, sự thiếu sức sống' },
                { word: 'loss of appetite', definition: 'mất sự ngon miệng, chán ăn' },
                { word: 'lozenge, cough drop', definition: 'viên ho, kẹo ho' },
                { word: 'make', definition: 'hiệu xe' },
                { word: 'marital status', definition: 'tình trạng hôn nhân' },
                { word: 'market price, market value', definition: 'Giá thị trường, Giá trị thị trường' },
                { word: 'median (strip)', definition: 'dải phân cách' },
                { word: 'medical record number', definition: 'số hồ sơ y tế' },
                { word: 'medication', definition: 'thuốc, dược phẩm' },
                { word: 'mess hall', definition: 'phòng ăn tập thể' },
                { word: 'moving violation', definition: 'vi phạm luật giao thông khi xe đang chuyển động' },
                { word: 'mud flap', definition: 'tấm chắn bùn' },
                { word: 'mudguard', definition: 'cái chắn bùn' },
                { word: 'multi-car', definition: 'tai nạn liên hoàn' }
            ]
        },
        {
            id: 21,
            title: 'L3 - Set 5',
            words: [
                { word: 'mumps', definition: 'bệnh quai bị' },
                { word: 'nauseated', definition: 'buồn nôn' },
                { word: 'no (left/right) turn sign', definition: 'bảng cấm quẹo trái/phải' },
                { word: 'no outlet sign', definition: 'biển báo không có lối ra' },
                { word: 'nosebleed', definition: 'chảy máu mũi, máu cam' },
                { word: 'numbness', definition: 'sự tê' },
                { word: 'nurse practitioner', definition: 'y tá thực hành, y tá cao cấp, y tá có ghi trong danh bộ được huấn luyện thêm về số kỷ thuật y-khoa' },
                { word: 'odometer', definition: 'Đồng hồ đo quãng đường đã đi của xe' },
                { word: 'off ramp', definition: 'đường ra khỏi đường sa lộ' },
                { word: 'on ramp', definition: 'đường vào sa lộ' },
                { word: 'one way street', definition: 'đường một chiều' },
                { word: 'out of network', definition: 'ngoài mạng lưới' },
                { word: 'overdraft', definition: 'Khoản thấu chi' },
                { word: 'overpass', definition: 'cầu vượt' },
                { word: 'overturned', definition: 'bị lật ngược' },
                { word: 'pale', definition: 'xanh xao, nhợt nhạt' },
                { word: 'pap smear', definition: 'xét nghiệm ung thư cổ tử cung, trắc nghiệm bôi phét chất nhờn ở cổ tử cung để chẩn bệnh ung thư' },
                { word: 'pass out', definition: 'ngất đi, xỉu đi' },
                { word: 'payoff', definition: 'Sự tất toán' },
                { word: 'pedestrian crossing', definition: 'lối qua đường cho khách bộ hành' },
                { word: 'pediatrician', definition: 'bác sỹ khoa nhi' },
                { word: 'Pertussis', definition: 'ho gà' },
                { word: 'phlegm', definition: 'đàm, đờm dãi' },
                { word: 'pickup truck', definition: 'xe bánh tải' },
                { word: 'pins and needles', definition: 'cảm giác châm chích' },
                { word: 'policyholder', definition: 'người có hợp đồng bảo hiểm' },
                { word: 'power brakes', definition: 'phanh động lực' },
                { word: 'power locks', definition: 'khóa cửa điện' },
                { word: 'power trunk', definition: 'khoang động cơ điện' },
                { word: 'prescribed', definition: 'đã được bác sỹ kê toa, kê đơn' },
                { word: 'Primary Care Physician (PCP)', definition: 'bác sỹ chính săn sóc' }
            ]
        },
        {
            id: 22,
            title: 'L3 - Set 6',
            words: [
                { word: 'quarter panel (rear/front/or right/left)', definition: 'tấm góc, tấm khung trên lốp trước và sau' },
                { word: 'rash', definition: 'chứng ban chẩm, chứng phát ban' },
                { word: 'rear view mirror', definition: 'kính chiếu hậu, gương nhìn sau' },
                { word: 'recorded statement', definition: 'lời khai được thu âm' },
                { word: 'refer to', definition: 'giới thiệu (của bác sỹ/cơ sở điều trị)' },
                { word: 'refer, (to)', definition: 'giới thiệu, chuyến đến, được chuyển đến' },
                { word: 'referral', definition: 'sự giới thiệu (từ bác sỹ), sự được chuyển đến' },
                { word: 'right of way', definition: 'quyền đi trước, quyền ưu tiên' },
                { word: 'road conditions', definition: 'những tình trạng mặt đường' },
                { word: 'running boards', definition: 'những bậc lên xuống ô tô' },
                { word: 'scratch', definition: 'vết trầy, vết xước' },
                { word: 'screening', definition: 'thử nghiệm sàng lọc' },
                { word: 'seizure', definition: 'động kinh' },
                { word: 'shackles', definition: 'cái còng, đồ xích lại' },
                { word: 'shaking, trembling', definition: 'run, rùng mình (do lạnh, sợ hãi)' },
                { word: 'shortage', definition: 'Sự thiếu hụt' },
                { word: 'shortness of breath', definition: 'hụt hơi, thiếu hơi thở' },
                { word: 'shoulder (road)', definition: 'lề đường' },
                { word: 'sick bay', definition: 'bệnh xá trên tàu thủy hay nhà tù' },
                { word: 'side mirrors', definition: 'những kính bên hông' },
                { word: 'sidewalk', definition: 'đường bộ hành, hè phố, vỉa hè' },
                { word: 'skid , to', definition: 'trượt (xe, bánh xe)' },
                { word: 'skid marks', definition: 'vết trượt bánh xe' },
                { word: 'skidded', definition: 'đã bị trượt bánh xe' },
                { word: 'slam (to)', definition: 'đóng sầm, rập mạnh' },
                { word: 'sling', definition: 'băng đeo (cánh tay đau)' },
                { word: 'sole (of the foot)', definition: 'gang bàn chân, lòng bàn chân' },
                { word: 'spell', definition: 'cơn, đoạn thời gian' },
                { word: 'spinal column', definition: 'cột sống' },
                { word: 'spine', definition: 'xương sống' },
                { word: 'spleen', definition: 'lá lách, tì' }
            ]
        },
        {
            id: 23,
            title: 'L3 - Set 7',
            words: [
                { word: 'sprain', definition: 'trặc gân, bong gân' },
                { word: 'statement', definition: 'Bảng sao kê' },
                { word: 'Primary Care Physician (PCP)', definition: 'bác sỹ chính săn sóc' },
                { word: 'quarter panel (rear/front/or right/left)', definition: 'tấm góc, tấm khung trên lốp trước và sau' },
                { word: 'rash', definition: 'chứng ban chẩm, chứng phát ban' },
                { word: 'rear view mirror', definition: 'kính chiếu hậu, gương nhìn sau' },
                { word: 'recorded statement', definition: 'lời khai được thu âm' },
                { word: 'refer to', definition: 'giới thiệu (của bác sỹ/cơ sở điều trị)' },
                { word: 'refer, (to)', definition: 'giới thiệu, chuyến đến, được chuyển đến' },
                { word: 'referral', definition: 'sự giới thiệu (từ bác sỹ), sự được chuyển đến' },
                { word: 'right of way', definition: 'quyền đi trước, quyền ưu tiên' },
                { word: 'road conditions', definition: 'những tình trạng mặt đường' },
                { word: 'running boards', definition: 'những bậc lên xuống ô tô' },
                { word: 'scratch', definition: 'vết trầy, vết xước' },
                { word: 'screening', definition: 'thử nghiệm sàng lọc' },
                { word: 'seizure', definition: 'động kinh' },
                { word: 'shackles', definition: 'cái còng, đồ xích lại' },
                { word: 'shaking, trembling', definition: 'run, rùng mình (do lạnh, sợ hãi)' },
                { word: 'shortage', definition: 'Sự thiếu hụt' },
                { word: 'shortness of breath', definition: 'hụt hơi, thiếu hơi thở' },
                { word: 'shoulder (road)', definition: 'lề đường' },
                { word: 'sick bay', definition: 'bệnh xá trên tàu thủy hay nhà tù' },
                { word: 'side mirrors', definition: 'những kính bên hông' },
                { word: 'sidewalk', definition: 'đường bộ hành, hè phố, vỉa hè' },
                { word: 'skid , to', definition: 'trượt (xe, bánh xe)' },
                { word: 'skid marks', definition: 'vết trượt bánh xe' },
                { word: 'skidded', definition: 'đã bị trượt bánh xe' },
                { word: 'slam (to)', definition: 'đóng sầm, rập mạnh' },
                { word: 'sling', definition: 'băng đeo (cánh tay đau)' },
                { word: 'sole (of the foot)', definition: 'gang bàn chân, lòng bàn chân' },
                { word: 'spell', definition: 'cơn, đoạn thời gian' }
            ]
        },
        {
            id: 24,
            title: 'L3 - Set 8',
            words: [
                { word: 'spinal column', definition: 'cột sống' },
                { word: 'spine', definition: 'xương sống' },
                { word: 'spleen', definition: 'lá lách, tì' },
                { word: 'sprain', definition: 'trặc gân, bong gân' },
                { word: 'statement', definition: 'Bảng sao kê' },
                { word: 'steering wheel', definition: 'bánh lái, tay lái, vô lăng' },
                { word: 'strain', definition: 'căng cơ quá mức' },
                { word: 'strep throat', definition: 'nhiễm trùng họng do vi trùng streptococcus' },
                { word: 'stretcher', definition: 'cái cáng, cái băng ca (để khiêng người ốm, người bị thương ở tư thế nằm)' },
                { word: 'stuffed up', definition: 'tình trạng bị nghẹt' },
                { word: 'surrender', definition: 'Giao lại' },
                { word: 'suspended', definition: 'tình trạng bằng lái xe bị treo' },
                { word: 'swerve (to)', definition: 'đi lệch hướng, lạng lách' },
                { word: 'swollen', definition: 'bị sưng lên' },
                { word: 'tailgate (to)', definition: 'chạy sát đằng sau một xe khác' },
                { word: 'taillight', definition: 'đèn sau xe, đèn đuôi xe' },
                { word: 'tetanus', definition: 'bệnh phong đòn gánh, bệnh uốn ván' },
                { word: 'The Monster/ The Ninja', definition: 'bị nhiễm HIV, siêu vi trùng gây nên hội chứng suy giảm miễn dịch mắc phải' },
                { word: 'thermometer', definition: 'nhiệt kế (dụng cụ đo nhiệt độ), hàn thử biểu' },
                { word: 'throbbing (pain)', definition: 'sự đau buốt, đau nhoi nhói' },
                { word: 'to brake', definition: 'thắng lại, phanh lại' },
                { word: 'tonsillitis', definition: 'viêm a-mi-đan' },
                { word: 'tonsils', definition: 'a-mi-đan, thịt dư hai bên cuống họng' },
                { word: 'towed', definition: 'trình trạng xe phải được kéo đi' },
                { word: 'traffic sign', definition: 'bảng báo hiệu giao thông' },
                { word: 'trailer', definition: 'xe moóc, toa moóc' },
                { word: 'trailer hitch', definition: 'cái móc để kéo xe' },
                { word: 'transaction', definition: 'Giao dịch' },
                { word: 'treatment', definition: 'sự chữa bệnh, điều trị' },
                { word: 'trunk', definition: 'thùng xe, cốp xe' },
                { word: 'turn arrow', definition: 'đèn quẹo có mũi tên' }
            ]
        },
        {
            id: 25,
            title: 'L3 - Set 9',
            words: [
                { word: 'turn signal', definition: 'đèn báo rẽ, đèn xi-nhan' },
                { word: 'urinalysis', definition: 'xét nghiệm nước tiểu' },
                { word: 'urinary incontinence', definition: 'đái dầm,' },
                { word: 'vaccines, immunizations', definition: 'sự chủng ngừa, sự tạo miễn dịch' },
                { word: 'vaginal discharge', definition: 'khí hư, dịch âm đạo, dịch tiết âm đạo' },
                { word: 'vaginal yeast infection', definition: 'nấm men âm đạo, sự viêm ngứa do nấm trong âm hộ' },
                { word: 'visibility', definition: 'tầm nhìn, độ nhìn thấy, tầm nhìn xa' },
                { word: 'vital signs', definition: 'những dấu hiệu sinh tồn' },
                { word: 'void', definition: 'bài tiết' },
                { word: 'vomiting', definition: 'sự nôn, sự ói mửa' },
                { word: 'waive, (to)', definition: 'miễn, miễn trừ' },
                { word: 'walker', definition: 'dụng cụ giúp cho người đi bộ' },
                { word: 'walk-in clinic', definition: 'phòng khám không cần hẹn trước' },
                { word: 'watery stool', definition: 'phân lỏng, phân loãng' },
                { word: 'wheezing', definition: 'thở khò khè' },
                { word: 'whiplash', definition: 'chấn thương do giật cổ' },
                { word: 'windpipe, trachea', definition: 'khí quản' },
                { word: 'windshield', definition: 'kính chắn gió xe hơi' },
                { word: 'wipers', definition: 'những thanh gạt nước kính' },
                { word: 'withdrawal', definition: 'Sự rút (tiền)' },
                { word: 'womb', definition: 'dạ con, tử cung' },
                { word: 'wound', definition: 'vết thương' },
                { word: 'yield sign', definition: 'biển báo nhường đường' }
            ]
        },
        {
            id: 26,
            title: 'L4 - Set 1',
            words: [
                { word: 'Acquired Immune Deficiency Syndrome (AIDS)', definition: 'hội chứng thiếu miễn nhiễm' },
                { word: 'acute pain', definition: 'đau cấp tính, đau nghiêm trọng' },
                { word: 'admissions desk', definition: 'bàn nhập-viện' },
                { word: 'advance directive', definition: 'chỉ thị trước về chăm sóc sức khoẻ' },
                { word: 'allergic', definition: 'dị ứng với, do dị ứng gây ra' },
                { word: 'alleviate', definition: 'làm giảm bớt, làm đỡ, làm dịu' },
                { word: 'amniocentesis', definition: 'sự chọc ối, chọc màng ối qua bụng, phương pháp khám thai bằng cách lấy một số dung dịch từ màng ối bao quanh thai nhi' },
                { word: 'amputation', definition: 'thủ thuật cắt cụt' },
                { word: 'anesthesia', definition: 'sự gây tê, sự gây mê' },
                { word: 'anesthesiologist', definition: 'bác sỹ gây mê' },
                { word: 'aneurysm', definition: 'chứng phình mạch' },
                { word: 'angina pectoris', definition: 'chứng đau thắt ngực' },
                { word: 'anti-inflammatory', definition: 'thuốc chống viêm' },
                { word: 'armband', definition: 'băng tay' },
                { word: 'arrhythmia', definition: 'chứng loạn nhịp tim, tim đập không đều nhịp' },
                { word: 'arteriosclerosis', definition: 'chứng xơ cứng động mạch' },
                { word: 'arthritis', definition: 'chứng viêm khớp' },
                { word: 'asthma', definition: 'bệnh suyễn' },
                { word: 'bed sore', definition: 'chứng thối loét vì nằm liệt giường' },
                { word: 'bedridden', definition: 'Nằm liệt giường' },
                { word: 'bilirubin', definition: 'bilirubin- một chất nhuộm màu vàng cam trong máu' },
                { word: 'biopsy', definition: 'sinh thiết' },
                { word: 'birth control pill', definition: 'thuốc ngừa thai' },
                { word: 'bladder', definition: 'bọng đái, bàng quang' },
                { word: 'blister', definition: 'mụn nước, chỗ phồng da' },
                { word: 'blistering', definition: 'làm rộp da, làm phồng da' },
                { word: 'blood clots', definition: 'cục máu đông' },
                { word: 'blood donor', definition: 'người cho máu, người hiến máu' },
                { word: 'blood glucose', definition: 'chất glucoza (đường ) trong máu' },
                { word: 'blood in the stools', definition: 'có máu trong phân' },
                { word: 'blood sample / test / specimen', definition: 'mẫu máu/thử máu/mẫu xét nghiệm máu' }
            ]
        },
        {
            id: 27,
            title: 'L4 - Set 2',
            words: [
                { word: 'blood sugar (blood glucose)', definition: 'lượng đường huyết' },
                { word: 'blood thinner / anticoagulant', definition: 'chất làm loãng máu / chất kháng đông' },
                { word: 'blood work', definition: 'sự thử máu' },
                { word: 'blood-poisoning (sepsis)', definition: 'nhiễm khuẩn huyết' },
                { word: 'blood-sugar reading', definition: 'số lượng đường trong máu hay độ đường trong máu' },
                { word: 'blue (to feel)', definition: 'buồn, chán nản' },
                { word: 'borderline', definition: 'ở mức ranh giới' },
                { word: 'braces (dental)', definition: 'dụng cụ niềng răng, chỉnh nha' },
                { word: 'breastfeed, to', definition: 'cho bú sữa mẹ' },
                { word: 'breathing problems', definition: 'những vấn-đề về hơi thở' },
                { word: 'breech Delivery', definition: 'đẻ ngôi mông, sự đẻ ngược (chân hoặc mông đứa bé ra trước, chứ không phải đầu)' },
                { word: 'bronchitis', definition: 'bệnh viêm cuống phổi' },
                { word: 'bruises', definition: 'những vết tím bầm' },
                { word: 'bulb syringe', definition: 'đồ hút mũi' },
                { word: 'callus', definition: 'chỗ chai của da' },
                { word: 'carbohydrates', definition: 'thực phẩm có chất bột đường; thực phẩm cacbohidrat' },
                { word: 'cardiac arrest', definition: 'ngừng tim, ngừng tuần hoàn' },
                { word: 'catheter', definition: 'ống thông' },
                { word: 'cervix', definition: 'cổ tử cung' },
                { word: 'chapped lips', definition: 'khô và nứt môi' },
                { word: 'cheek', definition: 'má' },
                { word: 'chemotherapy', definition: 'hoá chất trị liệu, hoá trị liệu' },
                { word: 'chest pain', definition: 'đau ngực' },
                { word: 'child safety seat', definition: 'ghế an toàn trẻ em' },
                { word: 'childbirth', definition: 'sanh con' },
                { word: 'choking', definition: 'nghẹt (hơi thở)' },
                { word: 'cholesterol', definition: 'chất mỡ trong cơ thể' },
                { word: 'chronic conditions', definition: 'tình trạng hay bệnh kinh niên, mạn tính' },
                { word: 'circulatory disease', definition: 'bệnh tuần hoàn máu' },
                { word: 'circumcision', definition: 'cắt bao quy đầu' },
                { word: 'clavicle, collar bone', definition: 'xương bả vai, xương đòn gánh' }
            ]
        },
        {
            id: 28,
            title: 'L4 - Set 3',
            words: [
                { word: 'cold symptoms', definition: 'những triệu-chứng cảm lạnh' },
                { word: 'colic, cramps', definition: 'cơn đau bụng, co thắt làm đau quặn' },
                { word: 'Collodion', definition: 'thuốc dán, màng keo' },
                { word: 'colonoscopy', definition: 'Soi ruột kết (kết tràng), nội soi đường ruột' },
                { word: 'colostrum', definition: 'sữa non' },
                { word: 'colposcopy', definition: 'sự soi âm đạo' },
                { word: 'compression stockings', definition: 'vớ đàn hồi' },
                { word: 'condom', definition: 'bao dương vật, bao cao su' },
                { word: 'consent form', definition: 'đơn ưng thuận' },
                { word: 'constipation', definition: 'sự táo bón' },
                { word: 'contraception/birth control', definition: 'tránh thụ thai, ngừa thai' },
                { word: 'contractions', definition: 'những sự co thắt cơ bắp' },
                { word: 'contrast dye', definition: 'Dung dịch tương phản' },
                { word: 'cough syrup', definition: 'thuốc ho' },
                { word: 'cracked', definition: 'bị rạn, nứt' },
                { word: 'cramp (muscle)', definition: 'co cứng cơ, chuột rút, vọp bẻ' },
                { word: 'cramps (stomach)', definition: 'đau co thắt (ở vùng dạ dày)' },
                { word: 'crawling sensation', definition: 'cảm giác như có gì đang bò (trên cơ thể)' },
                { word: 'crib death', definition: 'đột tử ở trẻ sơ sinh' },
                { word: 'C-section', definition: 'sinh mổ' },
                { word: 'cubic centimeters (“cc’s)', definition: 'centimét khối' },
                { word: 'cystitis', definition: 'viêm bàng quang, viêm bọng đái' },
                { word: 'dehydrated', definition: 'thiếu nước' },
                { word: 'deoxyribonucleic acid (DNA)', definition: 'cấu tử cơ bản của tế bào di truyền ( axit deoxiribonucleic)' },
                { word: 'diagnosed', definition: 'chẩn-đoán' },
                { word: 'diagnosis', definition: 'sự chẩn đoán, phép chẩn đoán bệnh' },
                { word: 'dialysis', definition: 'thẩm tách máu' },
                { word: 'dietitian', definition: 'chuyên viên về ăn uống' },
                { word: 'digestive system', definition: 'hệ tiêu hoá' },
                { word: 'dilation and curettage (D & C)', definition: 'nong và nạo' },
                { word: 'discharge instructions', definition: 'những hướng dẫn xuất viện' }
            ]
        },
        {
            id: 29,
            title: 'L4 - Set 4',
            words: [
                { word: 'discharge (from hospital)', definition: 'xuất viện' },
                { word: 'disorder', definition: 'sự rối loạn' },
                { word: 'distracted', definition: 'bị lơ đãng, phân tâm' },
                { word: 'diverticulitis', definition: 'viêm túi thừa, viêm chi nang' },
                { word: 'Do Not Resuscitate (DNR)', definition: 'không hô hấp nhân tạo' },
                { word: 'dosage button', definition: 'nút dùng để truyền vào cơ thể một liều thuốc cố định' },
                { word: 'douching', definition: 'thụt rửa âm đạo, việc bơm nước vào cơ để tẩy uể' },
                { word: 'drain', definition: 'dẫn lưu' },
                { word: 'drainage, discharge', definition: 'sự dẫn lưu; sự ra mủ, huyết trắng, máu, ra dịch' },
                { word: 'Durable Power of Attorney for Healthcare', definition: 'giấy ủy quyền dài hạn về chăm sóc sức khoẻ' },
                { word: 'ear, nose and throat doctor (ENT) otorhinolaryngologist', definition: 'bác sỹ chuyên về tai, mũi, họng' },
                { word: 'earache', definition: 'nhức lổ-tai' },
                { word: 'ectopic', definition: 'thai nghén ngoài tử cung' },
                { word: 'effects of the anesthesia', definition: 'những hiệu-nghiệm của thuốc tê mê' },
                { word: 'electrocardiogram (ECG/EKG)', definition: 'điện tâm đồ' },
                { word: 'electrocardiogram, EKG', definition: 'biểu đồ điện tim' },
                { word: 'electroencephalogram (EEG)', definition: 'điện não đồ' },
                { word: 'electroencephalography', definition: 'phép ghi điện não' },
                { word: 'electrolyte replacement solution - An oral or IV solution', definition: 'dung dịch thay chất điện phân' },
                { word: 'electromyogram (EMG)', definition: 'Cơ điện đồ' },
                { word: 'embolism', definition: 'sự nghẽn mạch' },
                { word: 'emergency room (ER)', definition: 'phòng cấp cứu' },
                { word: 'emphysema', definition: 'tràn khí, khí thủng' },
                { word: 'encephalitis', definition: 'viêm não' },
                { word: 'endoscopy', definition: 'nội soi, soi trong' },
                { word: 'engorgement', definition: 'sung huyết, ứ, căng' },
                { word: 'epidural', definition: 'gây tê dưới màng cứng' },
                { word: 'esophagus', definition: 'thực quản' },
                { word: 'excrement, feces', definition: 'phân' },
                { word: 'eye specialist', definition: 'bác sỹ chuyên về mắt' },
                { word: 'fainting spell', definition: 'cơn ngất (xỉu)' }
            ]
        },
        {
            id: 30,
            title: 'L4 - Set 5',
            words: [
                { word: 'false labor', definition: 'sự chuyển bụng đẻ giả' },
                { word: 'family counselor', definition: 'nhà tư vấn gia đình' },
                { word: 'fast (to)', definition: 'nhịn đói, nhịn ăn' },
                { word: 'flu shot', definition: 'tiêm phòng cúm' },
                { word: 'flu, influenza', definition: 'bệnh cúm' },
                { word: 'follow-up', definition: 'sự theo dõi bệnh nhân' },
                { word: 'formulary medication', definition: 'danh sách thuốc' },
                { word: 'foul-smelling', definition: 'mùi hôi thối, mùi khó chịu' },
                { word: 'fracture an ankle', definition: 'gãy hoặc nứt xương mắt cá' },
                { word: 'frequent urination', definition: 'chứng đi tiểu thường xuyên' },
                { word: 'gagging', definition: 'nôn khan, oẹ' },
                { word: 'gait', definition: 'dáng đi' },
                { word: 'gall bladder', definition: 'túi mật' },
                { word: 'gangrene', definition: 'bệnh thối hoại' },
                { word: 'gastroenterologist', definition: 'bác sỹ chuyên khoa dạ dày-ruột' },
                { word: 'gastroenterology', definition: 'vị tràng học' },
                { word: 'gastrologist', definition: 'bác sĩ chuyên khoa dạ dày' },
                { word: 'germs', definition: 'các vi trùng' },
                { word: 'gestational diabetes', definition: 'chứng tiểu đường trong thời kỳ thai nghén' },
                { word: 'gingivitis', definition: 'viêm lợi' },
                { word: 'glaucoma', definition: 'chứng tăng nhãn áp' },
                { word: 'glucose readings', definition: 'những chỉ số đường huyết' },
                { word: 'groggy', definition: 'say lảo đảo, đứng không vững' },
                { word: 'groin', definition: 'háng' },
                { word: 'hearing aids', definition: 'máy trợ thính' },
                { word: 'hearing loss', definition: 'mất thính lực' },
                { word: 'Heart attack', definition: 'nhồi máu cơ tim' },
                { word: 'heart failure', definition: 'suy tim' },
                { word: 'heartburn', definition: 'chứng ợ nóng (ợ chua)' },
                { word: 'heel prick', definition: 'kỹ thuật lấy máu gót chân trẻ sơ sinh' },
                { word: 'hemorrhoids', definition: 'bệnh trĩ' }
            ]
        },
        {
            id: 31,
            title: 'L4 - Set 6',
            words: [
                { word: 'Hepatitis B (vaccine)', definition: 'tiêm phòng viêm gan B' },
                { word: 'hernia', definition: 'thoát-vị' },
                { word: 'High Density Lipoproteins (HDL) (good cholesterol)', definition: 'Lipoprotein tỉ trọng cao' },
                { word: 'hives', definition: 'chứng nổi mề đay (vùng da sẩn đỏ, ngứa)' },
                { word: 'home care', definition: 'chăm sóc điều dưỡng tại nhà' },
                { word: 'hormonal', definition: 'thuộc kích thích tố' },
                { word: 'hospital gown', definition: 'cái áo choàng của bệnh- viện' },
                { word: 'hot flashes', definition: 'những cơn nóng bất chợt' },
                { word: 'Human Immunodeficiency Virus (HIV)', definition: 'HIV, siêu vi trùng gây nên hội chứng suy giảm miễn dịch mắc phải' },
                { word: 'Human Papilloma Virus (HPV)', definition: 'Siêu vi papilon ở người' },
                { word: 'hyperglycemia', definition: 'sự tăng đường huyết' },
                { word: 'hyperventilation', definition: 'tăng thông khí' },
                { word: 'hypoglycemia', definition: 'sự giảm đường huyết' },
                { word: 'immediate family', definition: 'gia đình trực hệ, gia đình ruột thịt' },
                { word: 'immunization', definition: 'sự tạo miễn dịch' },
                { word: 'implants', definition: 'cấy dưới da' },
                { word: 'incision', definition: 'vết mổ' },
                { word: 'incontinence', definition: '(sự) không kiềm chế được, không kìm lại, đái dầm' },
                { word: 'infected', definition: 'bị nhiễm-độc, bị nhiễm trùng' },
                { word: 'infection', definition: 'sự nhiễm-trùng' },
                { word: 'inflamed', definition: 'viêm' },
                { word: 'inhaler', definition: 'ống xịt thuốc' },
                { word: 'insulin injection/shot', definition: 'mũi tiêm insulin' },
                { word: 'Intensive Care Unit (ICU)', definition: 'Đơn vị đIều trị tăng cường' },
                { word: 'interact', definition: 'ảnh hưởng lẫn nhau, tác động qua lại' },
                { word: 'Intrauterine Device (IUD)', definition: 'vòng tránh thai' },
                { word: 'Intravenous (IV)', definition: 'truyền vào tĩnh mạch' },
                { word: 'itching', definition: 'chứng ngứa' },
                { word: 'IV', definition: 'trong tĩnh mạch' },
                { word: 'jaundice', definition: 'chứng vàng da' },
                { word: 'joints', definition: 'những khớp xương' }
            ]
        },
        {
            id: 32,
            title: 'L4 - Set 7',
            words: [
                { word: 'kidney failure', definition: 'suy thận' },
                { word: 'kidney stones', definition: 'những sạn thận' },
                { word: 'Kidney stones (renal calculi)', definition: 'những sạn thận' },
                { word: 'lactation consultant', definition: 'chuyên viên về sữa mẹ' },
                { word: 'lice', definition: 'con chấy' },
                { word: 'listless', definition: 'thiếu sinh lực, thiếu sức sống' },
                { word: 'Living Will', definition: 'di chúc sống' },
                { word: 'loose', definition: 'lỏng' },
                { word: 'Low Density Lipoproteins (LDL) (bad cholesterol)', definition: 'lipoprotein tỷ trọng thấp' },
                { word: 'low- sodium', definition: 'ít loại muối Natri' },
                { word: 'mammogram', definition: 'phim chụp tia X vú; ảnh của những khối u ở vú qua tia X;' },
                { word: 'mastectomy', definition: 'thủ thuật cắt bỏ vú, thuật mổ vú (để chữa ung thư)' },
                { word: 'mastitis', definition: 'viêm vú' },
                { word: 'measles', definition: 'bệnh sởi' },
                { word: 'Measles, Mumps and Rubella (MMR)', definition: 'thuốc chủng ngừa bệnh sởi, bệnh quai bị và bệnh sởi Đức' },
                { word: 'medical history', definition: 'tiểu sử y tế' },
                { word: 'medical procedures', definition: 'những thủ thuật y khoa' },
                { word: 'medication', definition: 'thuốc' },
                { word: 'menstrual cramps', definition: 'đau bụng kinh' },
                { word: 'menstrual period', definition: 'kinh nguyệt' },
                { word: 'Metastasis', definition: 'di căn' },
                { word: 'micrograms', definition: 'một phần triệu gam' },
                { word: 'midwife', definition: 'nữ hộ sinh, cô mụ, người đỡ đẻ' },
                { word: 'migraine', definition: 'chứng đau nửa đầu' },
                { word: 'milk pump (breast)', definition: 'đồ bơm sữa' },
                { word: 'miscarriage', definition: 'sự sẩy thai, sự hư thai' },
                { word: 'mucous', definition: 'niêm dịch, dịch nhầy , tiết niêm dịch, tiết dịch nhầy' },
                { word: 'mumps', definition: 'bệnh quai bị' },
                { word: 'murmur (heart)', definition: 'tiếng thì thầm của tim, tiếng thổi tim' },
                { word: 'myocardial infarction', definition: 'nhồi máu cơ tim' },
                { word: 'navel, belly button', definition: 'rốn' }
            ]
        },
        {
            id: 33,
            title: 'L4 - Set 8',
            words: [
                { word: 'Nervous System', definition: 'hệ thần kinh' },
                { word: 'Neurological System', definition: 'hệ thần kinh' },
                { word: 'Non Formulary', definition: 'thuốc ngoài danh sách' },
                { word: 'normal delivery/birth', definition: 'sự sanh đẻ bình thường/ tự nhiên' },
                { word: 'numb', definition: 'tê, không có cảm giác' },
                { word: 'numbing pain', definition: 'cơn đau tê' },
                { word: 'nursery (baby)', definition: 'khoa sơ sinh' },
                { word: 'nutrients', definition: 'chất dinh dưỡng' },
                { word: 'nutritionist', definition: 'chuyên viên dinh dưỡng' },
                { word: 'ob-gyn', definition: 'sản phụ khoa' },
                { word: 'obstruction', definition: 'nghẹn, tắc' },
                { word: 'oedema, edema', definition: 'chứng phù' },
                { word: 'ointment', definition: 'thuốc mỡ' },
                { word: 'oncology', definition: 'khoa ung bướu' },
                { word: 'ophthalmologist', definition: 'bác sỹ nhãn khoa' },
                { word: 'oral', definition: '(thuộc) miệng' },
                { word: 'outgrow', definition: 'lớn hơn, phát triển nhanh hơn' },
                { word: 'outlet', definition: 'chỗ thoát, lối thoát' },
                { word: 'outpatient', definition: 'bệnh nhân ngoại trú' },
                { word: 'over the counter medication (OTC)', definition: 'thuốc có thể mua không cần đơn bác sĩ' },
                { word: 'oxygen tube', definition: 'ống khí oxy' },
                { word: 'pacemaker', definition: 'máy điều hoà nhịp tim' },
                { word: 'pain medication, analgesic', definition: 'thuốc giảm đau' },
                { word: 'pap smear test', definition: 'xét nghiệm ung thư cổ tử cung, trắc nghiệm bôi phét chất nhờn ở cổ tử cung để chẩn bệnh ung thư' },
                { word: 'PCP', definition: 'bác sỹ chính săn sóc' },
                { word: 'peak flow meter', definition: 'lưu lượng đỉnh kế' },
                { word: 'pediatrician', definition: 'bác sỹ khoa nhi' },
                { word: 'perineal', definition: '(thuộc) đáy chậu' },
                { word: 'periodic limb movement disorder (PLMD)', definition: 'sự rối loạn của cử động chân tay được lập lại trong lúc ngủ' },
                { word: 'perspiration', definition: 'thoát mồ hôi, ra mồ hôi' },
                { word: 'pharyngitis', definition: 'viêm họng, viêm hầu' }
            ]
        },
        {
            id: 34,
            title: 'L4 - Set 9',
            words: [
                { word: 'pills', definition: 'thuốc viên' },
                { word: 'pinched nerve', definition: 'chèn ép dây thần kinh' },
                { word: 'PKU test', definition: 'Bệnh phenylceton niệu' },
                { word: 'pneumonia', definition: 'viêm phổi' },
                { word: 'podiatrist', definition: 'bác sỹ chuyên khoa bàn chân' },
                { word: 'Polio', definition: 'bệnh bại liệt' },
                { word: 'portions', definition: 'những khẩu phần ăn' },
                { word: 'Positron Emission Tomography (PET scan)', definition: 'chụp xạ hình cắt lớp Positron, chụp cắt lớp phát xạ' },
                { word: 'post-partum', definition: 'hậu sản' },
                { word: 'pregnancy', definition: 'sự thai nghén' },
                { word: 'prenatal Care', definition: 'chăm sóc tiền sản' },
                { word: 'preoperative', definition: 'tiền/trước giải-phẫu' },
                { word: 'procedure', definition: 'thủ thuật' },
                { word: 'prognosis', definition: 'tiên lượng, sự dự báo' },
                { word: 'prostate (gland)', definition: 'tuyến tiền liệt' },
                { word: 'pump', definition: 'đồ bơm' },
                { word: 'Radiology', definition: 'khoa về quang tuyến' },
                { word: 'Rapid eye movement (REM)', definition: 'ngủ mắt chuyển động nhanh, sự chuyển động nhanh của mắt trong lúc ngủ' },
                { word: 'recovery (room)', definition: 'phòng hồi sức' },
                { word: 'redness', definition: 'tình trạng đỏ da' },
                { word: 'regular', definition: 'đi tiêu đều đặn' },
                { word: 'release (from hospital)', definition: 'xuất viện, cho phép rời khỏi bệnh viện' },
                { word: 'respiration', definition: 'sự hô hấp' },
                { word: 'respiratory system', definition: 'hệ hô hấp' },
                { word: 'Salpingectomy', definition: 'thủ thuật cắt bỏ vòi tử cung' },
                { word: 'scar', definition: 'sẹo, vết sẹo' },
                { word: 'screening test', definition: 'xét nghiệm sàng lọc' },
                { word: 'seasonal allergies', definition: 'dị ứng theo mùa' },
                { word: 'shake', definition: 'sự rung, sự lắc' },
                { word: 'shooting pain', definition: 'đau chói' },
                { word: 'sight', definition: 'thị giác, thị lực' }
            ]
        },
        {
            id: 35,
            title: 'L4 - Set 10',
            words: [
                { word: 'Sleep apnea', definition: 'chứng ngưng thở khi ngủ' },
                { word: 'sonogram', definition: 'siêu âm thanh đồ' },
                { word: 'sore throat', definition: 'đau cổ họng' },
                { word: 'spit out', definition: 'phun ra' },
                { word: 'splint', definition: 'cái nẹp' },
                { word: 'sprain', definition: 'trặc gân, bong gân' },
                { word: 'stabbing/shooting pain', definition: 'đau thấu xương' },
                { word: 'staples', definition: 'đinh ghim' },
                { word: 'stiffness', definition: 'sự cứng, đơ cứng' },
                { word: 'stomach', definition: 'bao-tử / dạ-dày' },
                { word: 'stool softener', definition: 'thuốc làm mềm phân' },
                { word: 'Strep throat', definition: 'nhiễm trùng họng do vi trùng streptococcus' },
                { word: 'strict regimen', definition: 'chế độ ân uống nghiêm khắc' },
                { word: 'Stroke, or cerebrovascular accident (CVA)', definition: 'đột quỵ , tai biến mạch máu não' },
                { word: 'stuffed up', definition: 'tình trạng bị nghẹt' },
                { word: 'sty', definition: 'cái chắp, chỗ sưng tấy ở bờ mi mắt' },
                { word: 'suction', definition: 'sự hút' },
                { word: 'supplements', definition: 'những chất bổ sung dinh dưỡng' },
                { word: 'surgical wound', definition: 'vết thương rạch, vết thương mổ' },
                { word: 'swab, cotton swab', definition: 'bông ngoáy tai, tăm bông' },
                { word: 'swelling', definition: 'sưng, phồng' },
                { word: 'syringes', definition: 'ống tiêm' },
                { word: 'tablet', definition: 'thuốc viên dẹp' },
                { word: 'taking any medication', definition: 'đang uống bất-cứ thuốc' },
                { word: 'TB skin test', definition: 'xét nghiệm bệnh lao qua da' },
                { word: 'tearing', definition: 'tình trạng bị rách' },
                { word: 'tenderness', definition: 'đau rêm (đụng vào mới đau)' },
                { word: 'throbbing pain', definition: 'đau buốt, sự đau nhoi nhói' },
                { word: 'thyroid', definition: 'tuyến giáp trạng' },
                { word: 'thyroid gland', definition: 'tuyến giáp trạng' },
                { word: 'thyroid problems', definition: 'những vấn-đề về tuyến giáp trạng' }
            ]
        },
        {
            id: 36,
            title: 'L4 - Set 11',
            words: [
                { word: 'tiptoes, toes', definition: 'ngón chân' },
                { word: 'tissue', definition: 'mô' },
                { word: 'to admit (hospital)', definition: 'nhập viện' },
                { word: 'tonsillitis', definition: 'viêm a-mi-đan' },
                { word: 'tonsils', definition: 'a-mi-đan (hạch hạnh nhân), thịt dư hai bên cuống họng' },
                { word: 'tracheostomy', definition: 'thủ thuật mở khí quản' },
                { word: 'triage nurse', definition: 'y tá phân loại bệnh' },
                { word: 'triglycerides.', definition: 'chất béo trung tính' },
                { word: 'Tuberculosis (TB)', definition: 'bệnh lao' },
                { word: 'ulceration', definition: 'sự loét' },
                { word: 'umbilical cord', definition: 'dây rốn' },
                { word: 'uneasy, fussy', definition: 'quấy khóc; hay om sòm, hay rối rít; hay nhắng nhít, hay nhặng xị; hay quan trọng hóa' },
                { word: 'Upper Respiratory Tract Infection (URI)', definition: 'nhiễm trùng đường hô hấp trên' },
                { word: 'urinary problems', definition: 'các vấn đề tiết niệu' },
                { word: 'Urinary Tract Infection (UTI)', definition: 'nhiễm trùng đường tiết niệu, nhiễm trùng đường tiểu' },
                { word: 'urinating', definition: 'tiểu' },
                { word: 'urine culture', definition: 'nuôi cấy nước tiểu' },
                { word: 'uterus', definition: 'tử cung' },
                { word: 'vaccination/vaccine', definition: 'sự chủng ngừa, sự tiêm chủng' },
                { word: 'vaginal delivery', definition: 'sinh đẻ bằng đường âm đạo' },
                { word: 'vaginal spotting', definition: 'chảy máu tối thiểu âm đạo' },
                { word: 'varicose veins', definition: 'giãn tĩnh mạch' },
                { word: 'wart', definition: 'mụn cóc, hột cơm' },
                { word: 'wellness check-up', definition: 'kiểm tra sức khoẻ để ngăn ngừa bệnh' },
                { word: 'Whooping cough / pertussis', definition: 'bệnh ho gà' },
                { word: 'yeast infection', definition: 'nhiễm trùng nấm men âm đạo' }
            ]
        }
    ]
};

