import { VocabularyPart } from '../../types';

export const reading2026Vocabulary: VocabularyPart = {
    id: 2026,
    title: "Reading 2026",
    description: "Từ vựng Reading TRỌNG ĐIỂM trong năm 2026",
    tests: [
        {
            id: 202601,
            title: "Test 1",
            words: [
                { word: "Take place", definition: "Diễn ra", example: "" },
                { word: "Attendee", definition: "Người tham dự", example: "" },
                { word: "Antique", definition: "Đồ cổ, cổ xưa", example: "" },
                { word: "Organization", definition: "Tổ chức, cơ quan", example: "" },
                { word: "Suspicious", definition: "Đáng ngờ, nghi ngờ", example: "" },
                { word: "Vary", definition: "Thay đổi, biến đổi", example: "" },
                { word: "Inventory", definition: "Hàng tồn kho, sự kiểm kê", example: "" },
                { word: "Expand", definition: "Mở rộng, phát triển", example: "" },
                { word: "Solicit", definition: "Kêu gọi, thu hút", example: "" },
                { word: "Intend", definition: "Dự định, có ý định", example: "" },
                { word: "Prevent", definition: "Ngăn chặn", example: "" },
                { word: "Aim", definition: "Mục tiêu, nhắm vào", example: "" },
                { word: "Qualified", definition: "Đủ điều kiện, có năng lực", example: "" },
                { word: "Resident", definition: "Cư dân", example: "" },
                { word: "Agreement", definition: "Thỏa thuận, hợp đồng", example: "" },
                { word: "Opposition", definition: "Sự đối lập, phe đối lập", example: "" },
                { word: "Extensive", definition: "Rộng rãi, bao quát", example: "" },
                { word: "Guarantee", definition: "Đảm bảo, bảo hành", example: "" },
                { word: "Supplier", definition: "Nhà cung cấp", example: "" },
                { word: "Landscaping", definition: "Quy hoạch cảnh quan", example: "" },
                { word: "Suggestion", definition: "Lời gợi ý, đề xuất", example: "" },
                { word: "Expertise", definition: "Chuyên môn, sự thành thạo", example: "" },
                { word: "Competitor", definition: "Đối thủ cạnh tranh", example: "" },
                { word: "Anniversary", definition: "Lễ kỷ niệm", example: "" },
                { word: "Dedication", definition: "Sự cống hiến", example: "" },
                { word: "Loyalty", definition: "Lòng trung thành", example: "" },
                { word: "Contribute", definition: "Đóng góp", example: "" },
                { word: "Gratitude", definition: "Lòng biết ơn", example: "" },
                { word: "Refine", definition: "Tinh chỉnh, làm cho tốt hơn", example: "" },
                { word: "Spacious", definition: "Rộng rãi", example: "" },
                { word: "Go through", definition: "Kiểm tra kỹ, trải qua", example: "" },
                { word: "Various", definition: "Đa dạng, nhiều", example: "" },
                { word: "Secure", definition: "Bảo đảm, an toàn", example: "" },
                { word: "Remove", definition: "Loại bỏ, dời đi", example: "" },
                { word: "Previous", definition: "Trước đó", example: "" },
                { word: "Cooperation", definition: "Sự hợp tác", example: "" },
                { word: "Upcoming", definition: "Sắp tới", example: "" },
                { word: "Charge", definition: "Tính phí, phụ trách", example: "" },
                { word: "Assign", definition: "Phân công, chỉ định", example: "" },
                { word: "Administrator", definition: "Người quản lý, quản trị viên", example: "" },
                { word: "New hire", definition: "Nhân viên mới", example: "" },
                { word: "Promote", definition: "Thăng chức, quảng bá", example: "" },
                { word: "Advertise", definition: "Quảng cáo", example: "" },
                { word: "Coordinator", definition: "Điều phối viên", example: "" },
                { word: "Telescope", definition: "Kính thiên văn", example: "" },
                { word: "Revise", definition: "Chỉnh sửa, ôn lại", example: "" },
                { word: "Representative", definition: "Người đại diện", example: "" },
                { word: "Inquiry", definition: "Câu hỏi, sự điều tra", example: "" },
                { word: "General", definition: "Chung, tổng quát", example: "" },
                { word: "Release", definition: "Phát hành, thả ra", example: "" },
                { word: "Indicate", definition: "Chỉ ra, biểu thị", example: "" },
                { word: "Retain", definition: "Giữ lại", example: "" },
                { word: "Flavour", definition: "Hương vị", example: "" },
                { word: "Sacrifice", definition: "Hy sinh", example: "" },
                { word: "Obtain", definition: "Đạt được, lấy được", example: "" },
                { word: "Merger", definition: "Sự sáp nhập", example: "" },
                { word: "Nutritious", definition: "Bổ dưỡng", example: "" },
                { word: "Individual", definition: "Cá nhân", example: "" },
                { word: "Opportunity", definition: "Cơ hội", example: "" },
                { word: "Substitute", definition: "Người/vật thay thế", example: "" },
                { word: "Critical", definition: "Then chốt, phê bình", example: "" },
                { word: "Colleague", definition: "Đồng nghiệp", example: "" },
                { word: "Courtesy", definition: "Sự lịch sự, nhã nhặn", example: "" },
                { word: "Get the word out", definition: "Loan tin, quảng bá", example: "" },
                { word: "Install", definition: "Lắp đặt, cài đặt", example: "" },
                { word: "Significant", definition: "Đáng kể, quan trọng", example: "" },
                { word: "Estimate", definition: "Ước tính", example: "" },
                { word: "Liaison", definition: "Sự liên lạc, người liên lạc", example: "" },
                { word: "Successive", definition: "Liên tiếp", example: "" },
                { word: "Expert", definition: "Chuyên gia", example: "" },
                { word: "Diagnose", definition: "Chẩn đoán", example: "" },
                { word: "Replace", definition: "Thay thế", example: "" },
                { word: "Resemble", definition: "Giống với", example: "" },
                { word: "Approve", definition: "Chấp thuận, phê duyệt", example: "" },
                { word: "Inspection", definition: "Sự thanh tra, kiểm tra", example: "" },
                { word: "Proactive", definition: "Chủ động", example: "" },
                { word: "Procedure", definition: "Quy trình, thủ tục", example: "" },
                { word: "Compete", definition: "Cạnh tranh, thi đấu", example: "" },
                { word: "Instrumental", definition: "Góp phần quan trọng", example: "" },
                { word: "Combine", definition: "Kết hợp", example: "" },
            ]
        },
        {
            id: 202602,
            title: "Test 2",
            words: [
                { word: "Reliability", definition: "Sự đáng tin cậy", example: "" },
                { word: "Reimbursement", definition: "Sự hoàn tiền/chi phí", example: "" },
                { word: "Accept", definition: "Chấp nhận", example: "" },
                { word: "Candidate", definition: "Ứng cử viên", example: "" },
                { word: "Master", definition: "Bậc thầy / Tinh thông", example: "" },
                { word: "Power failure", definition: "Cúp điện / Mất điện", example: "" },
                { word: "Property", definition: "Tài sản, bất động sản", example: "" },
                { word: "Strategy", definition: "Chiến lược", example: "" },
                { word: "Name", definition: "Tên / Đặt tên", example: "" },
                { word: "Warranty", definition: "Bảo hành", example: "" },
                { word: "Workplace", definition: "Nơi làm việc", example: "" },
                { word: "Postpone", definition: "Hoãn lại", example: "" },
                { word: "Struggle", definition: "Đấu tranh / Gặp khó khăn", example: "" },
                { word: "Ingredient", definition: "Nguyên liệu / Thành phần", example: "" },
                { word: "Savory", definition: "Mặn (ngon), đậm đà", example: "" },
                { word: "Eager", definition: "Háo hức", example: "" },
                { word: "Artificial", definition: "Nhân tạo", example: "" },
                { word: "Substance", definition: "Chất / Vật chất", example: "" },
                { word: "Handy", definition: "Tiện dụng / Khéo tay", example: "" },
                { word: "Effective", definition: "Hiệu quả", example: "" },
                { word: "Sustainable", definition: "Bền vững", example: "" },
                { word: "Address", definition: "Giải quyết / Địa chỉ", example: "" },
                { word: "Porous", definition: "Xốp / Có lỗ rỗng", example: "" },
                { word: "Subscription", definition: "Sự đăng ký (báo, dịch vụ)", example: "" },
                { word: "Access", definition: "Quyền truy cập / Tiếp cận", example: "" },
                { word: "Valid", definition: "Hợp lệ", example: "" },
                { word: "Expire", definition: "Hết hạn", example: "" },
                { word: "Activate", definition: "Kích hoạt", example: "" },
                { word: "Distribute", definition: "Phân phát / Phân phối", example: "" },
                { word: "Feature", definition: "Đặc điểm / Có sự tham gia", example: "" },
                { word: "Reveal", definition: "Tiết lộ", example: "" },
                { word: "Extension", definition: "Sự gia hạn / Máy nhánh", example: "" },
                { word: "Complaint", definition: "Lời phàn nàn", example: "" },
                { word: "Issue", definition: "Vấn đề / Phát hành", example: "" },
                { word: "Maintenance", definition: "Bảo trì", example: "" },
                { word: "Summarize", definition: "Tóm tắt", example: "" },
                { word: "Notify", definition: "Thông báo", example: "" },
                { word: "Requirement", definition: "Yêu cầu", example: "" },
                { word: "Freight", definition: "Hàng hóa (vận chuyển)", example: "" },
                { word: "Vehicle", definition: "Phương tiện giao thông", example: "" },
                { word: "Transport", definition: "Vận chuyển / Giao thông", example: "" },
                { word: "Nationwide", definition: "Toàn quốc", example: "" },
                { word: "Executive", definition: "Người điều hành / Cấp cao", example: "" },
                { word: "Commercial", definition: "Thương mại / Quảng cáo", example: "" },
                { word: "Demand", definition: "Nhu cầu / Yêu cầu", example: "" },
                { word: "Specialty", definition: "Đặc sản / Chuyên môn", example: "" },
                { word: "Convert", definition: "Chuyển đổi", example: "" },
                { word: "Virtual", definition: "Ảo (trên máy tính)", example: "" },
                { word: "Visualization", definition: "Sự hình dung / Trực quan hóa", example: "" },
                { word: "Suggest", definition: "Gợi ý / Đề nghị", example: "" },
                { word: "Curate", definition: "Phụ trách / Tuyển chọn", example: "" },
                { word: "Highlight", definition: "Làm nổi bật / Điểm nhấn", example: "" },
                { word: "Process", definition: "Quá trình / Xử lý", example: "" },
                { word: "Sleek", definition: "Bóng mượt / Kiểu dáng đẹp", example: "" },
                { word: "Stabilization", definition: "Sự ổn định", example: "" },
                { word: "Rough", definition: "Thô ráp / Gồ ghề", example: "" },
                { word: "Surface", definition: "Bề mặt", example: "" },
                { word: "Discontinue", definition: "Ngừng / Gián đoạn", example: "" },
                { word: "Instruction", definition: "Hướng dẫn", example: "" },
                { word: "Residence", definition: "Nơi cư trú", example: "" },
                { word: "Complimentary", definition: "Miễn phí / Ca ngợi", example: "" },
                { word: "Accommodate", definition: "Cung cấp chỗ ở / Đáp ứng", example: "" },
                { word: "Catch up", definition: "Bắt kịp / Làm bù", example: "" },
                { word: "Customized", definition: "Được tùy chỉnh", example: "" },
                { word: "Express", definition: "Bày tỏ / Tốc hành", example: "" },
                { word: "Preserve", definition: "Bảo tồn / Giữ gìn", example: "" },
                { word: "Auction", definition: "Buổi đấu giá", example: "" },
                { word: "Donate", definition: "Quyên góp", example: "" },
                { word: "Operation", definition: "Hoạt động / Phẫu thuật", example: "" },
                { word: "Thrilled", definition: "Hồi hộp (thích thú)", example: "" },
                { word: "In advance", definition: "Trước (thời gian)", example: "" },
                { word: "Indeed", definition: "Thực sự / Quả thực", example: "" },
                { word: "Typically", definition: "Điển hình / Thông thường", example: "" },
                { word: "Smudge", definition: "Vết bẩn / Làm nhòe", example: "" },
                { word: "Found", definition: "Thành lập / Sáng lập", example: "" },
                { word: "Emphasize", definition: "Nhấn mạnh", example: "" },
                { word: "Immediately", definition: "Ngay lập tức", example: "" },
                { word: "Average", definition: "Trung bình", example: "" },
                { word: "Navigate", definition: "Điều hướng / Định vị", example: "" },
                { word: "Ultimately", definition: "Cuối cùng / Sau cùng", example: "" },
            ]
        },
        {
            id: 202603,
            title: "Test 3",
            words: [
                { word: "Youth", definition: "Tuổi trẻ, thanh niên", example: "" },
                { word: "Conduct", definition: "Tiến hành, thực hiện", example: "" },
                { word: "Regular", definition: "Thường xuyên, định kỳ", example: "" },
                { word: "A majority of", definition: "Đa số, phần lớn", example: "" },
                { word: "Represent", definition: "Đại diện", example: "" },
                { word: "Measure", definition: "Biện pháp / Đo lường", example: "" },
                { word: "Submit", definition: "Nộp, đệ trình", example: "" },
                { word: "Track", definition: "Theo dõi", example: "" },
                { word: "Rapidly", definition: "Một cách nhanh chóng", example: "" },
                { word: "Committee", definition: "Ủy ban, hội đồng", example: "" },
                { word: "Appendix", definition: "Phụ lục", example: "" },
                { word: "Insight", definition: "Cái nhìn sâu sắc, sự thấu hiểu", example: "" },
                { word: "Investment", definition: "Sự đầu tư", example: "" },
                { word: "Result", definition: "Kết quả", example: "" },
                { word: "Improve", definition: "Cải thiện", example: "" },
                { word: "Appoint", definition: "Bổ nhiệm", example: "" },
                { word: "Simultaneously", definition: "Đồng thời, cùng lúc", example: "" },
                { word: "Revenue", definition: "Doanh thu", example: "" },
                { word: "Undergo", definition: "Trải qua", example: "" },
                { word: "Take advantage of", definition: "Tận dụng, lợi dụng", example: "" },
                { word: "Transaction", definition: "Giao dịch", example: "" },
                { word: "Potential", definition: "Tiềm năng", example: "" },
                { word: "Attention", definition: "Sự chú ý", example: "" },
                { word: "Dynamic", definition: "Năng động", example: "" },
                { word: "Valuable", definition: "Có giá trị, quý giá", example: "" },
                { word: "Convince", definition: "Thuyết phục", example: "" },
                { word: "Audience", definition: "Khán giả", example: "" },
                { word: "Acquire", definition: "Đạt được, thâu tóm", example: "" },
                { word: "Share", definition: "Cổ phần / Phần chia", example: "" },
                { word: "Strength", definition: "Điểm mạnh, sức mạnh", example: "" },
                { word: "Quote", definition: "Báo giá / Trích dẫn", example: "" },
                { word: "Infusion", definition: "Sự truyền vào, sự rót (vốn)", example: "" },
                { word: "Refrain", definition: "Kiềm chế, tránh", example: "" },
                { word: "Preference", definition: "Sự ưu tiên, sở thích", example: "" },
                { word: "Function", definition: "Chức năng / Hoạt động", example: "" },
                { word: "Gathering", definition: "Buổi tụ tập, hội họp", example: "" },
                { word: "Innovation", definition: "Sự đổi mới, sáng tạo", example: "" },
                { word: "Shareholder", definition: "Cổ đông", example: "" },
                { word: "Productivity", definition: "Năng suất", example: "" },
                { word: "Occur", definition: "Xảy ra", example: "" },
                { word: "Optimize", definition: "Tối ưu hóa", example: "" },
                { word: "Conventional", definition: "Theo tập quán, thông thường", example: "" },
                { word: "Commuter", definition: "Người đi làm xa (đi về trong ngày)", example: "" },
                { word: "Relieved", definition: "Nhẹ nhõm", example: "" },
                { word: "Desperate", definition: "Tuyệt vọng, liều lĩnh", example: "" },
                { word: "Municipal", definition: "Thuộc thành phố, đô thị", example: "" },
                { word: "Entrance", definition: "Lối vào", example: "" },
                { word: "Mural", definition: "Tranh tường", example: "" },
                { word: "Commission", definition: "Tiền hoa hồng / Ủy ban", example: "" },
                { word: "Approximately", definition: "Xấp xỉ, khoảng chừng", example: "" },
                { word: "Publicize", definition: "Công khai, quảng bá", example: "" },
                { word: "Significance", definition: "Tầm quan trọng, ý nghĩa", example: "" },
                { word: "Official", definition: "Chính thức", example: "" },
                { word: "Mingle", definition: "Hòa nhập, trộn lẫn", example: "" },
                { word: "Invaluable", definition: "Vô giá", example: "" },
                { word: "Accurate", definition: "Chính xác", example: "" },
                { word: "Recruit", definition: "Tuyển dụng", example: "" },
                { word: "Celebrity", definition: "Người nổi tiếng", example: "" },
                { word: "Cater", definition: "Cung cấp thực phẩm/dịch vụ", example: "" },
                { word: "Equipment", definition: "Thiết bị, dụng cụ", example: "" },
                { word: "Distributor", definition: "Nhà phân phối", example: "" },
                { word: "Component", definition: "Thành phần, linh kiện", example: "" },
                { word: "Facility", definition: "Cơ sở vật chất, tiện nghi", example: "" },
                { word: "Assembly", definition: "Sự lắp ráp / Hội đồng", example: "" },
                { word: "Launch", definition: "Ra mắt, khai trương", example: "" },
                { word: "Financial", definition: "Thuộc về tài chính", example: "" },
                { word: "Oversee", definition: "Giám sát", example: "" },
                { word: "Permanently", definition: "Vĩnh viễn", example: "" },
                { word: "Relocate", definition: "Di dời, chuyển chỗ", example: "" },
                { word: "Appreciate", definition: "Cảm kích / Đánh giá cao", example: "" },
                { word: "Perspective", definition: "Góc nhìn, quan điểm", example: "" },
                { word: "Intrigue", definition: "Gây tò mò, hấp dẫn", example: "" },
                { word: "Government", definition: "Chính phủ", example: "" },
                { word: "Collaborate", definition: "Hợp tác", example: "" },
                { word: "Commensurate", definition: "Tương xứng", example: "" },
                { word: "Comply with", definition: "Tuân thủ", example: "" },
                { word: "Essential", definition: "Thiết yếu, cốt yếu", example: "" },
                { word: "Relevant", definition: "Có liên quan, thích hợp", example: "" },
                { word: "Formal", definition: "Trang trọng, chính thức", example: "" },
                { word: "Remote", definition: "Xa xôi / Từ xa", example: "" },
            ]
        },
        {
            id: 202604,
            title: "Test 4",
            words: [
                { word: "Retire", definition: "Withdraw, step down", example: "" },
                { word: "Applicant", definition: "Candidate, seeker", example: "" },
                { word: "Contract", definition: "Agreement, deal", example: "" },
                { word: "Liquid", definition: "Fluid, solution", example: "" },
                { word: "Praise", definition: "Compliment, commend", example: "" },
                { word: "Aesthetic", definition: "Artistic, beautiful", example: "" },
                { word: "Maintain", definition: "Preserve, sustain", example: "" },
                { word: "Confidentiality", definition: "Privacy, secrecy", example: "" },
                { word: "Architecture", definition: "Design, structure", example: "" },
                { word: "Thermostat", definition: "Temperature regulator", example: "" },
                { word: "Reflect", definition: "Mirror, show", example: "" },
                { word: "Retreat", definition: "Haven, withdrawal", example: "" },
                { word: "In celebration of", definition: "In honor of", example: "" },
                { word: "Outline", definition: "Draft, summarize", example: "" },
                { word: "Procurement", definition: "Acquisition, purchasing", example: "" },
                { word: "Pediatric", definition: "Child-related (medical)", example: "" },
                { word: "Accurately", definition: "Correctly, precisely", example: "" },
                { word: "Authentic", definition: "Genuine, real", example: "" },
                { word: "Cuisine", definition: "Food, cooking style", example: "" },
                { word: "Occupy", definition: "Inhabit, take up", example: "" },
                { word: "Enthusiasm", definition: "Passion, eagerness", example: "" },
                { word: "Validate", definition: "Confirm, verify", example: "" },
                { word: "At no charge", definition: "For free, gratis", example: "" },
                { word: "Memoir", definition: "Autobiography, account", example: "" },
                { word: "In person", definition: "Physically, personally", example: "" },
                { word: "Specialize in", definition: "Focus on, major in", example: "" },
                { word: "Bold", definition: "Daring, striking", example: "" },
                { word: "Reciprocate", definition: "Return, repay", example: "" },
                { word: "Competitive", definition: "Aggressive, ambitious", example: "" },
                { word: "Knowledge", definition: "Understanding, wisdom", example: "" },
                { word: "Regulation", definition: "Rule, law", example: "" },
                { word: "Fluency", definition: "Eloquence, flow", example: "" },
                { word: "Satellite", definition: "Orbiter, spacecraft", example: "" },
                { word: "Grant", definition: "Award, allow", example: "" },
                { word: "Calculate", definition: "Compute, estimate", example: "" },
                { word: "Snowpack", definition: "Snow cover", example: "" },
                { word: "Prototype", definition: "Model, sample", example: "" },
                { word: "Fluctuation", definition: "Variation, shift", example: "" },
                { word: "Enhance", definition: "Improve, boost", example: "" },
                { word: "Domestic", definition: "Local, national", example: "" },
                { word: "Prestigious", definition: "Reputable, esteemed", example: "" },
                { word: "Commitment", definition: "Dedication, pledge", example: "" },
                { word: "Tremendous", definition: "Huge, massive", example: "" },
                { word: "Headquarter", definition: "Base, situate", example: "" },
                { word: "Facilitate", definition: "Ease, assist", example: "" },
                { word: "Ergonomic", definition: "Comfortable, user-friendly", example: "" },
                { word: "Frequently", definition: "Often, regularly", example: "" },
                { word: "Initiate", definition: "Start, launch", example: "" },
                { word: "Appearance", definition: "Look, arrival", example: "" },
                { word: "Enclose", definition: "Attach, surround", example: "" },
                { word: "Commence", definition: "Begin, start", example: "" },
                { word: "Elaborate", definition: "Detailed, explain", example: "" },
                { word: "Insightful", definition: "Perceptive, astute", example: "" },
                { word: "Biography", definition: "Life story, profile", example: "" },
                { word: "Admire", definition: "Respect, appreciate", example: "" },
                { word: "Backdrop", definition: "Background, setting", example: "" },
                { word: "Refurbish", definition: "Renovate, restore", example: "" },
                { word: "Prompt", definition: "Quick, immediate", example: "" },
                { word: "Engaging", definition: "Captivating, interesting", example: "" },
                { word: "Functionality", definition: "Utility, capability", example: "" },
                { word: "Spectacular", definition: "Stunning, impressive", example: "" },
                { word: "Secluded", definition: "Isolated, private", example: "" },
                { word: "Enchanted", definition: "Charmed, magical", example: "" },
                { word: "Eclectic", definition: "Diverse, varied", example: "" },
                { word: "Audiovisual", definition: "Auditory and visual", example: "" },
                { word: "Durability", definition: "Sturdiness, longevity", example: "" },
                { word: "Versatile", definition: "Adaptable, flexible", example: "" },
                { word: "Persist", definition: "Continue, endure", example: "" },
                { word: "Commissioner", definition: "Official, representative", example: "" },
                { word: "Predecessor", definition: "Forerunner, ancestor", example: "" },
                { word: "Step down", definition: "Resign, quit", example: "" },
                { word: "Suspension", definition: "Interruption, delay", example: "" },
                { word: "Inaugural", definition: "First, opening", example: "" },
                { word: "Proceeds", definition: "Earnings, profits", example: "" },
                { word: "Submission", definition: "Handing in, entry", example: "" },
                { word: "Administration", definition: "Management, government", example: "" },
                { word: "Excel", definition: "Shine, surpass", example: "" },
                { word: "Aspect", definition: "Feature, facet", example: "" },
                { word: "Verify", definition: "Check, confirm", example: "" },
                { word: "Convenient", definition: "Handy, suitable", example: "" },
            ]
        },
        {
            id: 202605,
            title: "Test 5",
            words: [
                { word: "Accountant", definition: "Kế toán viên", example: "" },
                { word: "Agenda", definition: "Chương trình nghị sự", example: "" },
                { word: "Sudden", definition: "Đột ngột", example: "" },
                { word: "Proofread", definition: "Hiệu đính (đọc sửa)", example: "" },
                { word: "Experiment", definition: "Thí nghiệm / Thử nghiệm", example: "" },
                { word: "Initial", definition: "Ban đầu", example: "" },
                { word: "Sealant", definition: "Chất trám, keo bịt kín", example: "" },
                { word: "Refined", definition: "Tinh chế / Tao nhã", example: "" },
                { word: "Soundproof", definition: "Cách âm", example: "" },
                { word: "Entrepreneur", definition: "Doanh nhân (khởi nghiệp)", example: "" },
                { word: "Tenure", definition: "Nhiệm kỳ / Biên chế", example: "" },
                { word: "Achievement", definition: "Thành tựu", example: "" },
                { word: "Forthcoming", definition: "Sắp tới / Sẵn sàng giúp đỡ", example: "" },
                { word: "Consistently", definition: "Một cách nhất quán", example: "" },
                { word: "Implement", definition: "Thi hành, thực hiện", example: "" },
                { word: "Accordingly", definition: "Phù hợp / Do đó", example: "" },
                { word: "Align", definition: "Căn chỉnh / Sắp hàng", example: "" },
                { word: "Tardiness", definition: "Sự chậm trễ", example: "" },
                { word: "On behalf of", definition: "Thay mặt cho", example: "" },
                { word: "Physiotherapy", definition: "Vật lý trị liệu", example: "" },
                { word: "Inviting", definition: "Lôi cuốn, hấp dẫn", example: "" },
                { word: "Objective", definition: "Mục tiêu / Khách quan", example: "" },
                { word: "Resource", definition: "Tài nguyên / Nguồn lực", example: "" },
                { word: "Informative", definition: "Cung cấp nhiều tin tức", example: "" },
                { word: "Previously", definition: "Trước đây", example: "" },
                { word: "Editorial", definition: "Bài xã luận / Thuộc biên tập", example: "" },
                { word: "Prime", definition: "Chủ yếu / Hảo hạng", example: "" },
                { word: "Spread", definition: "Lan truyền / Trải ra", example: "" },
                { word: "Overall", definition: "Tổng thể", example: "" },
                { word: "Determine", definition: "Xác định / Quyết định", example: "" },
                { word: "Avoid", definition: "Tránh", example: "" },
                { word: "Sanctuary", definition: "Khu bảo tồn / Nơi ẩn náu", example: "" },
                { word: "Hectic", definition: "Bận rộn, cuồng nhiệt", example: "" },
                { word: "Bustle", definition: "Sự hối hả / Nhộn nhịp", example: "" },
                { word: "Excursion", definition: "Chuyến tham quan ngắn", example: "" },
                { word: "Cover letter", definition: "Thư xin việc", example: "" },
                { word: "Shortage", definition: "Sự thiếu hụt", example: "" },
                { word: "Extract", definition: "Chiết xuất / Đoạn trích", example: "" },
                { word: "Favorable", definition: "Thuận lợi", example: "" },
                { word: "Crash", definition: "Va chạm / Sự cố (máy tính)", example: "" },
                { word: "Compatible", definition: "Tương thích", example: "" },
                { word: "Thrive", definition: "Phát triển mạnh", example: "" },
                { word: "Figure out", definition: "Hiểu ra / Tìm ra", example: "" },
                { word: "Asset", definition: "Tài sản", example: "" },
                { word: "Supportive", definition: "Hỗ trợ / Cổ vũ", example: "" },
                { word: "Presence", definition: "Sự hiện diện", example: "" },
                { word: "Persevere", definition: "Kiên trì", example: "" },
                { word: "Explore", definition: "Khám phá / Thăm dò", example: "" },
                { word: "Primarily", definition: "Chủ yếu", example: "" },
                { word: "Breach", definition: "Sự vi phạm / Vi phạm", example: "" },
                { word: "First aid", definition: "Sơ cứu", example: "" },
                { word: "Specific", definition: "Cụ thể", example: "" },
                { word: "Administrative", definition: "Thuộc quản lý/hành chính", example: "" },
                { word: "Possess", definition: "Sở hữu", example: "" },
                { word: "Subordinate", definition: "Cấp dưới", example: "" },
                { word: "Crucially", definition: "Một cách quan trọng", example: "" },
                { word: "Proficiency", definition: "Sự thành thạo", example: "" },
                { word: "Expenditure", definition: "Chi phí / Sự tiêu dùng", example: "" },
                { word: "Statistical", definition: "Thuộc thống kê", example: "" },
                { word: "Industrial", definition: "Thuộc công nghiệp", example: "" },
                { word: "Description", definition: "Sự mô tả", example: "" },
                { word: "Dependent", definition: "Phụ thuộc", example: "" },
                { word: "In stock", definition: "Còn hàng", example: "" },
                { word: "Unfamiliar", definition: "Không quen thuộc", example: "" },
                { word: "Questionnaire", definition: "Bảng câu hỏi", example: "" },
                { word: "Introductory", definition: "Mang tính giới thiệu", example: "" },
                { word: "Subsequent", definition: "Theo sau / Đến sau", example: "" },
                { word: "Waive", definition: "Từ bỏ / Miễn", example: "" },
                { word: "Prospective", definition: "Tiềm năng / Tương lai", example: "" },
                { word: "Confidential", definition: "Bảo mật / Tuyệt mật", example: "" },
                { word: "Certified", definition: "Được chứng nhận", example: "" },
                { word: "Withdraw", definition: "Rút tiền / Rút lui", example: "" },
                { word: "Owed", definition: "Nợ", example: "" },
                { word: "Participant", definition: "Người tham gia", example: "" },
                { word: "Steady", definition: "Ổn định", example: "" },
                { word: "Acceptable", definition: "Chấp nhận được", example: "" },
                { word: "Capacity", definition: "Sức chứa / Khả năng", example: "" },
                { word: "Authorize", definition: "Ủy quyền / Cho phép", example: "" },
                { word: "Faulty", definition: "Bị lỗi / Hỏng", example: "" },
                { word: "Personnel", definition: "Nhân sự", example: "" },
            ]
        },
        {
            id: 202606,
            title: "Test 6",
            words: [
                { word: "Composer", definition: "Songwriter, author", example: "" },
                { word: "Politeness", definition: "Courtesy, civility", example: "" },
                { word: "Practical", definition: "Pragmatic, useful", example: "" },
                { word: "Workstation", definition: "Desk, workspace", example: "" },
                { word: "Latest", definition: "Newest, current", example: "" },
                { word: "Quarterly", definition: "Every 3 months", example: "" },
                { word: "Stakeholder", definition: "Investor, partner", example: "" },
                { word: "Biographer", definition: "Chronicler, author", example: "" },
                { word: "Distinctive", definition: "Unique, characteristic", example: "" },
                { word: "Stationery", definition: "Writing supplies", example: "" },
                { word: "Insurance", definition: "Protection, coverage", example: "" },
                { word: "Associated", definition: "Related, connected", example: "" },
                { word: "Ensure", definition: "Guarantee, make sure", example: "" },
                { word: "Exterior", definition: "Outside, surface", example: "" },
                { word: "Incorporate", definition: "Include, integrate", example: "" },
                { word: "Pleasure", definition: "Enjoyment, delight", example: "" },
                { word: "Corporate", definition: "Business, commercial", example: "" },
                { word: "Appliance", definition: "Device, machine", example: "" },
                { word: "Innovative", definition: "Creative, inventive", example: "" },
                { word: "Geographic", definition: "Geographical", example: "" },
                { word: "Electronics", definition: "Electronic devices", example: "" },
                { word: "Patience", definition: "Tolerance, endurance", example: "" },
                { word: "Uneven", definition: "Irregular, rough", example: "" },
                { word: "Pavement", definition: "Sidewalk, walkway", example: "" },
                { word: "Hygienist", definition: "Cleaner (specialist)", example: "" },
                { word: "Handle", definition: "Manage, deal with", example: "" },
                { word: "Benefit", definition: "Advantage, profit", example: "" },
                { word: "Streamline", definition: "Simplify, optimize", example: "" },
                { word: "Unusually", definition: "Exceptionally, remarkably", example: "" },
                { word: "Moderation", definition: "Restraint, balance", example: "" },
                { word: "Regularly", definition: "Frequently, routinely", example: "" },
                { word: "Landscape", definition: "Scenery, view", example: "" },
                { word: "Optimal", definition: "Best, ideal", example: "" },
                { word: "Reasonable", definition: "Fair, sensible", example: "" },
                { word: "Pathway", definition: "Path, trail", example: "" },
                { word: "Rustic", definition: "Rural, simple", example: "" },
                { word: "Constitute", definition: "Form, compose", example: "" },
                { word: "Fulfill", definition: "Satisfy, complete", example: "" },
                { word: "Specification", definition: "Requirement, detail", example: "" },
                { word: "Paperwork", definition: "Documents, admin work", example: "" },
                { word: "Security", definition: "Safety, protection", example: "" },
                { word: "Intricate", definition: "Complex, detailed", example: "" },
                { word: "Unprecedented", definition: "Unparalleled, unique", example: "" },
                { word: "Tactile", definition: "Tangible, touchable", example: "" },
                { word: "Exploit", definition: "Utilize, take advantage of", example: "" },
                { word: "Layover", definition: "Stopover, break", example: "" },
                { word: "Amenity", definition: "Facility, convenience", example: "" },
                { word: "Awareness", definition: "Consciousness, knowledge", example: "" },
                { word: "Conserve", definition: "Save, preserve", example: "" },
                { word: "Fundamental", definition: "Basic, essential", example: "" },
                { word: "Specified", definition: "Designated, stated", example: "" },
                { word: "Eliminate", definition: "Remove, get rid of", example: "" },
                { word: "Reduction", definition: "Decrease, cut", example: "" },
                { word: "Contribution", definition: "Donation, input", example: "" },
                { word: "Alternate", definition: "Rotate, switch", example: "" },
                { word: "Confident", definition: "Assured, self-reliant", example: "" },
                { word: "Incur", definition: "Suffer, acquire", example: "" },
                { word: "Offset", definition: "Counteract, balance", example: "" },
                { word: "Placement", definition: "Positioning, arrangement", example: "" },
                { word: "Integral", definition: "Essential, vital", example: "" },
                { word: "Guidance", definition: "Advice, direction", example: "" },
                { word: "Botanical", definition: "Floral, plant-based", example: "" },
                { word: "Society", definition: "Community, public", example: "" },
                { word: "Theme", definition: "Subject, topic", example: "" },
                { word: "Paradise", definition: "Heaven, utopia", example: "" },
                { word: "Ambitious", definition: "Aspiring, determined", example: "" },
                { word: "Cultivate", definition: "Grow, develop", example: "" },
                { word: "Privilege", definition: "Advantage, right", example: "" },
                { word: "Wildlife", definition: "Fauna, animals", example: "" },
                { word: "Cordially", definition: "Warmly, sincerely", example: "" },
                { word: "Nourish", definition: "Feed, nurture", example: "" },
                { word: "Deterrence", definition: "Prevention, discouragement", example: "" },
                { word: "Harmful", definition: "Damaging, dangerous", example: "" },
                { word: "Recreation", definition: "Leisure, fun", example: "" },
                { word: "Athletic", definition: "Sporty, fit", example: "" },
                { word: "Adequate", definition: "Sufficient, enough", example: "" },
                { word: "Suitable", definition: "Appropriate, fitting", example: "" },
                { word: "Promptly", definition: "Immediately, punctually", example: "" },
                { word: "Joint", definition: "Shared, collective", example: "" },
                { word: "Profitable", definition: "Lucrative, gainful", example: "" },
            ]
        },
        {
            id: 202607,
            title: "Test 7",
            words: [
                { word: "Commute", definition: "Travel (daily)", example: "" },
                { word: "Understaffed", definition: "Short-handed", example: "" },
                { word: "Keep fit", definition: "Stay healthy", example: "" },
                { word: "Completion", definition: "Conclusion", example: "" },
                { word: "Concern", definition: "Worry / Issue", example: "" },
                { word: "Tuition", definition: "School fees", example: "" },
                { word: "Enroll in", definition: "Register for", example: "" },
                { word: "Evaluate", definition: "Assess", example: "" },
                { word: "Milestone", definition: "Landmark", example: "" },
                { word: "Responsive", definition: "Reactive / Quick", example: "" },
                { word: "Chemistry", definition: "Interaction / Rapport", example: "" },
                { word: "Rapid", definition: "Fast / Swift", example: "" },
                { word: "Hospitality", definition: "Warmth / Welcome", example: "" },
                { word: "Payroll", definition: "Salary list", example: "" },
                { word: "Time sheet", definition: "Attendance record", example: "" },
                { word: "Container", definition: "Receptacle / Box", example: "" },
                { word: "Fancy", definition: "Elaborate / Posh", example: "" },
                { word: "Savour", definition: "Enjoy / Relish", example: "" },
                { word: "Socialise", definition: "Mingle / Interact", example: "" },
                { word: "Reserve", definition: "Book / Save", example: "" },
                { word: "Opening", definition: "Launch / Vacancy", example: "" },
                { word: "Renewal", definition: "Extension", example: "" },
                { word: "Assume", definition: "Presume / Undertake", example: "" },
                { word: "Tenant", definition: "Renter / Occupant", example: "" },
                { word: "Realty", definition: "Real estate", example: "" },
                { word: "Peninsula", definition: "Cape", example: "" },
                { word: "Moderately", definition: "Reasonably", example: "" },
                { word: "Scatter", definition: "Disperse / Spread", example: "" },
                { word: "Inexpensive", definition: "Cheap / Affordable", example: "" },
                { word: "Flock to", definition: "Crowd / Gather", example: "" },
                { word: "Alert", definition: "Watchful / Warn", example: "" },
                { word: "Electronically", definition: "Digitally", example: "" },
                { word: "Exclusively", definition: "Solely / Only", example: "" },
                { word: "Creamery", definition: "Dairy plant", example: "" },
                { word: "Physician", definition: "Doctor", example: "" },
                { word: "Remind", definition: "Prompt", example: "" },
                { word: "Time off", definition: "Leave / Break", example: "" },
                { word: "Adjust", definition: "Adapt / Alter", example: "" },
                { word: "Custodian", definition: "Caretaker / Janitor", example: "" },
                { word: "Testimonial", definition: "Recommendation", example: "" },
                { word: "Satisfaction", definition: "Contentment", example: "" },
                { word: "Detailed", definition: "Thorough", example: "" },
                { word: "Reputation", definition: "Fame / Standing", example: "" },
                { word: "Identify", definition: "Recognize", example: "" },
                { word: "Persuade", definition: "Convince", example: "" },
                { word: "Imminent", definition: "Impending", example: "" },
                { word: "Undoubtedly", definition: "Certainly", example: "" },
                { word: "Visible", definition: "Noticeable", example: "" },
                { word: "Collaboration", definition: "Cooperation", example: "" },
                { word: "Corporation", definition: "Company / Firm", example: "" },
                { word: "Nonprofit", definition: "Charitable", example: "" },
                { word: "Participation", definition: "Involvement", example: "" },
                { word: "Involve", definition: "Entail / Include", example: "" },
                { word: "Dedicate", definition: "Devote", example: "" },
                { word: "Spearhead", definition: "Lead / Initiate", example: "" },
                { word: "Subcompact", definition: "Small car", example: "" },
                { word: "Stunning", definition: "Spectacular", example: "" },
                { word: "Abundant", definition: "Plentiful", example: "" },
                { word: "Secondhand", definition: "Used", example: "" },
                { word: "Credential", definition: "Qualification", example: "" },
                { word: "Reliable", definition: "Dependable", example: "" },
                { word: "Unsightly", definition: "Ugly", example: "" },
                { word: "Merchandise", definition: "Goods / Products", example: "" },
                { word: "Possession", definition: "Belonging", example: "" },
                { word: "Drastically", definition: "Radically", example: "" },
                { word: "Informed", definition: "Knowledgeable", example: "" },
                { word: "Vast", definition: "Huge / Enormous", example: "" },
                { word: "Bypass", definition: "Avoid / Skip", example: "" },
                { word: "Deboard", definition: "Disembark", example: "" },
                { word: "Voucher", definition: "Coupon", example: "" },
                { word: "Demonstration", definition: "Display / Protest", example: "" },
                { word: "Unintentionally", definition: "Accidentally", example: "" },
                { word: "Discard", definition: "Throw away", example: "" },
                { word: "Lightweight", definition: "Airy / Light", example: "" },
                { word: "Disposable", definition: "Throwaway", example: "" },
                { word: "Receptacle", definition: "Container / Bin", example: "" },
                { word: "Overdue", definition: "Late", example: "" },
                { word: "Withhold", definition: "Retain / Hide", example: "" },
                { word: "Malfunction", definition: "Defect / Failure", example: "" },
                { word: "Expedite", definition: "Accelerate", example: "" },
            ]
        },
        {
            id: 202608,
            title: "Test 8",
            words: [
                { word: "Significantly", definition: "Đáng kể", example: "" },
                { word: "Sturdy", definition: "Cứng cáp, bền", example: "" },
                { word: "Brief", definition: "Ngắn gọn", example: "" },
                { word: "Functional", definition: "Thiết thực, hữu dụng", example: "" },
                { word: "Generate", definition: "Tạo ra, phát sinh", example: "" },
                { word: "Extensively", definition: "Rộng rãi, bao quát", example: "" },
                { word: "Proceed", definition: "Tiếp tục, tiến hành", example: "" },
                { word: "Territory", definition: "Lãnh thổ", example: "" },
                { word: "Protocol", definition: "Giao thức, quy định", example: "" },
                { word: "Simplify", definition: "Đơn giản hóa", example: "" },
                { word: "Directions", definition: "Chỉ dẫn, hướng đi", example: "" },
                { word: "Laboratory", definition: "Phòng thí nghiệm", example: "" },
                { word: "Undergraduate", definition: "Sinh viên chưa tốt nghiệp", example: "" },
                { word: "Admission", definition: "Sự nhận vào, phí vào cửa", example: "" },
                { word: "Semester", definition: "Học kỳ", example: "" },
                { word: "Transcript", definition: "Bảng điểm, bản sao", example: "" },
                { word: "Delighted", definition: "Vui mừng, hài lòng", example: "" },
                { word: "Tendency", definition: "Khuynh hướng", example: "" },
                { word: "Disclose", definition: "Tiết lộ, phơi bày", example: "" },
                { word: "Hesitate", definition: "Do dự, ngập ngừng", example: "" },
                { word: "Candid", definition: "Thẳng thắn, thật thà", example: "" },
                { word: "Unsuitable", definition: "Không phù hợp", example: "" },
                { word: "Compact", definition: "Nhỏ gọn", example: "" },
                { word: "Beautify", definition: "Làm đẹp, tô điểm", example: "" },
                { word: "Integrity", definition: "Chính trực, toàn vẹn", example: "" },
                { word: "Extra", definition: "Thêm, phụ", example: "" },
                { word: "Residential", definition: "Thuộc về cư trú/dân cư", example: "" },
                { word: "Paved", definition: "Được lát đường", example: "" },
                { word: "Border", definition: "Biên giới, viền", example: "" },
                { word: "Subsidiary", definition: "Công ty con", example: "" },
                { word: "Budget", definition: "Ngân sách", example: "" },
                { word: "Distribution", definition: "Sự phân phối", example: "" },
                { word: "Researcher", definition: "Nhà nghiên cứu", example: "" },
                { word: "Capability", definition: "Khả năng, năng lực", example: "" },
                { word: "Vacancy", definition: "Vị trí trống", example: "" },
                { word: "Cabin", definition: "Khoang (máy bay), nhà gỗ", example: "" },
                { word: "Compartment", definition: "Ngăn, buồng", example: "" },
                { word: "Dimension", definition: "Kích thước, chiều", example: "" },
                { word: "Permission", definition: "Sự cho phép", example: "" },
                { word: "Foster", definition: "Nuôi dưỡng, thúc đẩy", example: "" },
                { word: "Roughly", definition: "Khoảng chừng, thô bạo", example: "" },
                { word: "Unexpected", definition: "Bất ngờ", example: "" },
                { word: "Fulfillment", definition: "Sự hoàn thành, thỏa mãn", example: "" },
                { word: "Lodging", definition: "Nơi ở tạm thời", example: "" },
                { word: "Intent", definition: "Ý định, mục đích", example: "" },
                { word: "Directly", definition: "Trực tiếp, ngay lập tức", example: "" },
                { word: "Instructions", definition: "Hướng dẫn", example: "" },
                { word: "Go over", definition: "Kiểm tra, xem xét kỹ", example: "" },
                { word: "Convinced", definition: "Tin chắc", example: "" },
                { word: "Personality", definition: "Tính cách", example: "" },
                { word: "Structure", definition: "Cấu trúc", example: "" },
                { word: "Memorable", definition: "Đáng nhớ", example: "" },
                { word: "Politician", definition: "Chính trị gia", example: "" },
                { word: "Numerous", definition: "Nhiều, đông đảo", example: "" },
                { word: "Straightforward", definition: "Đơn giản, thẳng thắn", example: "" },
                { word: "Fascinating", definition: "Hấp dẫn, lôi cuốn", example: "" },
                { word: "Portrait", definition: "Chân dung", example: "" },
                { word: "Enigmatic", definition: "Bí ẩn, khó hiểu", example: "" },
                { word: "Anecdote", definition: "Giai thoại, chuyện vặt", example: "" },
                { word: "Shortcoming", definition: "Khiếm khuyết", example: "" },
                { word: "Credible", definition: "Đáng tin cậy", example: "" },
                { word: "Fictional", definition: "Hư cấu", example: "" },
                { word: "Quaint", definition: "Độc đáo, cổ kính", example: "" },
                { word: "Criticism", definition: "Sự chỉ trích", example: "" },
                { word: "Surrounding", definition: "Bao quanh, phụ cận", example: "" },
                { word: "Minutes", definition: "Biên bản (cuộc họp)", example: "" },
                { word: "Earmark", definition: "Dành riêng (cho mục đích)", example: "" },
                { word: "Adjustment", definition: "Sự điều chỉnh", example: "" },
                { word: "Recruitment", definition: "Sự tuyển dụng", example: "" },
                { word: "Boulevard", definition: "Đại lộ", example: "" },
                { word: "Adjournment", definition: "Sự hoãn lại (cuộc họp)", example: "" },
                { word: "Utilities", definition: "Tiện ích (điện, nước...)", example: "" },
                { word: "Easygoing", definition: "Dễ tính, thoải mái", example: "" },
                { word: "Reasonably", definition: "Hợp lý, vừa phải", example: "" },
                { word: "Satisfy", definition: "Làm hài lòng, thỏa mãn", example: "" },
                { word: "Attune", definition: "Làm cho hòa hợp", example: "" },
                { word: "Resist", definition: "Kháng cự, chống lại", example: "" },
                { word: "Adhere", definition: "Tuân thủ, dính chặt", example: "" },
                { word: "Striped", definition: "Có sọc, vằn", example: "" },
                { word: "Outstanding", definition: "Xuất sắc / Chưa thanh toán", example: "" },
            ]
        },
        {
            id: 202609,
            title: "Test 9",
            words: [
                { word: "Vacant", definition: "Trống, còn bỏ không", example: "" },
                { word: "Promotion", definition: "Sự thăng chức, sự khuyến mãi", example: "" },
                { word: "Consumption", definition: "Sự tiêu thụ", example: "" },
                { word: "Superintendent", definition: "Người giám sát, quản lý", example: "" },
                { word: "Renovation", definition: "Sự cải tạo, nâng cấp", example: "" },
                { word: "Manufacturer", definition: "Nhà sản xuất", example: "" },
                { word: "Consideration", definition: "Sự cân nhắc, xem xét", example: "" },
                { word: "Critic", definition: "Nhà phê bình", example: "" },
                { word: "Impressive", definition: "Ấn tượng", example: "" },
                { word: "Choreography", definition: "Biên đạo múa", example: "" },
                { word: "Ongoing", definition: "Đang diễn ra", example: "" },
                { word: "Household", definition: "Hộ gia đình", example: "" },
                { word: "Automotive", definition: "Thuộc ô tô", example: "" },
                { word: "Eligible", definition: "Đủ tư cách, đủ điều kiện", example: "" },
                { word: "Vendor", definition: "Nhà cung cấp, người bán hàng", example: "" },
                { word: "Variation", definition: "Sự biến đổi, sự thay đổi", example: "" },
                { word: "Imperfection", definition: "Khiếm khuyết, sự không hoàn hảo", example: "" },
                { word: "Narrow", definition: "Hẹp", example: "" },
                { word: "Detach", definition: "Tháo gỡ, tách ra", example: "" },
                { word: "Abrasive", definition: "Có tính mài mòn, thô ráp", example: "" },
                { word: "Residue", definition: "Cặn dư, phần còn lại", example: "" },
                { word: "Submerge", definition: "Nhấn chìm", example: "" },
                { word: "Utensil", definition: "Dụng cụ (thường là bếp)", example: "" },
                { word: "Separately", definition: "Một cách riêng biệt", example: "" },
                { word: "Entrust", definition: "Giao phó", example: "" },
                { word: "Convey", definition: "Truyền đạt, vận chuyển", example: "" },
                { word: "Timeless", definition: "Vĩnh cửu, không lỗi thời", example: "" },
                { word: "Precision", definition: "Độ chính xác", example: "" },
                { word: "Costly", definition: "Đắt đỏ, tốn kém", example: "" },
                { word: "Initially", definition: "Ban đầu", example: "" },
                { word: "Acquisition", definition: "Sự mua lại, sự thâu tóm", example: "" },
                { word: "Insider", definition: "Người trong cuộc", example: "" },
                { word: "Speculate", definition: "Suy đoán, đầu cơ", example: "" },
                { word: "Iconic", definition: "Mang tính biểu tượng", example: "" },
                { word: "Reliably", definition: "Một cách đáng tin cậy", example: "" },
                { word: "Fate", definition: "Định mệnh, số phận", example: "" },
                { word: "Retirement", definition: "Sự nghỉ hưu", example: "" },
                { word: "Deactivation", definition: "Sự vô hiệu hóa", example: "" },
                { word: "Renew", definition: "Gia hạn, làm mới", example: "" },
                { word: "Displeasure", definition: "Sự không hài lòng", example: "" },
                { word: "Promise", definition: "Lời hứa / Hứa", example: "" },
                { word: "Sufficient", definition: "Đủ", example: "" },
                { word: "Regard", definition: "Coi như / Sự quan tâm", example: "" },
                { word: "Assistance", definition: "Sự hỗ trợ", example: "" },
                { word: "Unveil", definition: "Tiết lộ, khánh thành", example: "" },
                { word: "Advancement", definition: "Sự tiến bộ, thăng tiến", example: "" },
                { word: "Glimpse", definition: "Cái nhìn thoáng qua", example: "" },
                { word: "Decay", definition: "Sự phân hủy, sâu răng", example: "" },
                { word: "Architectural", definition: "Thuộc kiến trúc", example: "" },
                { word: "Transition", definition: "Sự chuyển tiếp", example: "" },
                { word: "Constructive", definition: "Mang tính xây dựng", example: "" },
                { word: "Showcase", definition: "Trưng bày, phô diễn", example: "" },
                { word: "Notable", definition: "Đáng chú ý", example: "" },
                { word: "Concrete", definition: "Cụ thể / Bê tông", example: "" },
                { word: "Overcome", definition: "Vượt qua", example: "" },
                { word: "Preventive", definition: "Phòng ngừa", example: "" },
                { word: "Gauge", definition: "Đo lường, đánh giá", example: "" },
                { word: "Respective", definition: "Tương ứng", example: "" },
                { word: "Compensate", definition: "Bồi thường, đền bù", example: "" },
                { word: "Persistent", definition: "Kiên trì, dai dẳng", example: "" },
                { word: "Narrative", definition: "Câu chuyện, tường thuật", example: "" },
                { word: "Adjoining", definition: "Liền kề, kế bên", example: "" },
                { word: "Heritage", definition: "Di sản", example: "" },
                { word: "Vintage", definition: "Cổ điển", example: "" },
                { word: "Purified", definition: "Được làm sạch, tinh chế", example: "" },
                { word: "Whimsical", definition: "Bất thường, kỳ lạ, vui", example: "" },
                { word: "Infuse", definition: "Truyền, pha (trà)", example: "" },
                { word: "Biweekly", definition: "Hai tuần một lần", example: "" },
                { word: "Affordably", definition: "Giá cả phải chăng", example: "" },
                { word: "Crease", definition: "Nếp nhăn, nếp gấp", example: "" },
                { word: "Encyclopaedia", definition: "Bách khoa toàn thư", example: "" },
                { word: "Enquiry", definition: "Sự hỏi thăm, điều tra", example: "" },
                { word: "Inherit", definition: "Thừa kế", example: "" },
                { word: "Onboarding", definition: "Quy trình nhập môn", example: "" },
                { word: "Interact", definition: "Tương tác", example: "" },
                { word: "Enrollment", definition: "Sự ghi danh, tuyển sinh", example: "" },
                { word: "Breathtaking", definition: "Ngoạn mục, hấp dẫn", example: "" },
                { word: "Certification", definition: "Chứng chỉ, sự chứng nhận", example: "" },
                { word: "Precondition", definition: "Điều kiện tiên quyết", example: "" },
                { word: "Authority", definition: "Thẩm quyền, chính quyền", example: "" },
            ]
        },
        {
            id: 202610,
            title: "Test 10",
            words: [
                { word: "Commend", definition: "Khen ngợi, tán dương", example: "" },
                { word: "Garment", definition: "Quần áo, hàng may mặc", example: "" },
                { word: "Patron", definition: "Khách quen, người bảo trợ", example: "" },
                { word: "Majority", definition: "Đa số, phần lớn", example: "" },
                { word: "Quarter", definition: "Quý (thời gian), một phần tư", example: "" },
                { word: "Diplomat", definition: "Nhà ngoại giao", example: "" },
                { word: "Removal", definition: "Sự dời đi, sự loại bỏ", example: "" },
                { word: "Organizer", definition: "Người tổ chức, khay sắp xếp", example: "" },
                { word: "Sound", definition: "Hợp lý, vững chắc, đúng đắn", example: "" },
                { word: "Aspiring", definition: "Có khát vọng, đầy tham vọng", example: "" },
                { word: "Flourishing", definition: "Hưng thịnh, phát triển mạnh", example: "" },
                { word: "Finalize", definition: "Hoàn tất, chốt lại", example: "" },
                { word: "Caution", definition: "Sự thận trọng, lời cảnh báo", example: "" },
                { word: "Inferior", definition: "Thấp kém hơn", example: "" },
                { word: "Adjustable", definition: "Có thể điều chỉnh được", example: "" },
                { word: "Argument", definition: "Sự tranh luận, lý lẽ", example: "" },
                { word: "Shrink", definition: "Co lại, rút ngắn", example: "" },
                { word: "Collapsible", definition: "Có thể gập lại", example: "" },
                { word: "Durable", definition: "Bền, lâu bền", example: "" },
                { word: "Replacement", definition: "Sự thay thế, người/vật thay thế", example: "" },
                { word: "Wholesaler", definition: "Người bán buôn (bán sỉ)", example: "" },
                { word: "Whisper", definition: "Thì thầm", example: "" },
                { word: "Illusion", definition: "Ảo giác, ảo tưởng", example: "" },
                { word: "Argue", definition: "Tranh luận, biện hộ", example: "" },
                { word: "Plotline", definition: "Cốt truyện", example: "" },
                { word: "Abundance", definition: "Sự phong phú, thừa thãi", example: "" },
                { word: "Challenging", definition: "Đầy thách thức, khó khăn", example: "" },
                { word: "Recipe", definition: "Công thức (nấu ăn)", example: "" },
                { word: "Separate", definition: "Tách rời, chia ra", example: "" },
                { word: "Promotional", definition: "(Thuộc) quảng cáo, khuyến mãi", example: "" },
                { word: "Apparel", definition: "Trang phục, quần áo", example: "" },
                { word: "Involvement", definition: "Sự tham gia, sự liên quan", example: "" },
                { word: "Invention", definition: "Sự phát minh, sáng chế", example: "" },
                { word: "Timely", definition: "Kịp thời, đúng lúc", example: "" },
                { word: "Customize", definition: "Tùy chỉnh (theo yêu cầu)", example: "" },
                { word: "Punctuality", definition: "Sự đúng giờ", example: "" },
                { word: "Performance", definition: "Hiệu suất, màn trình diễn", example: "" },
                { word: "Tricky", definition: "Phức tạp, khó nắm bắt", example: "" },
                { word: "Stop by", definition: "Ghé qua", example: "" },
                { word: "Compile", definition: "Biên soạn, tập hợp", example: "" },
                { word: "Notification", definition: "Thông báo", example: "" },
                { word: "Manuscript", definition: "Bản thảo", example: "" },
                { word: "Margin", definition: "Lề, biên độ (lợi nhuận)", example: "" },
                { word: "Ignore", definition: "Phớt lờ, bỏ qua", example: "" },
                { word: "Modification", definition: "Sự sửa đổi, biến đổi", example: "" },
                { word: "Establish", definition: "Thành lập, thiết lập", example: "" },
                { word: "Diverse", definition: "Đa dạng", example: "" },
                { word: "Negotiate", definition: "Đàm phán, thương lượng", example: "" },
                { word: "Exceptionally", definition: "Một cách đặc biệt, phi thường", example: "" },
                { word: "Exposure", definition: "Sự phơi bày, sự tiếp xúc", example: "" },
                { word: "Triumph", definition: "Chiến thắng, thắng lợi", example: "" },
                { word: "Criteria", definition: "Tiêu chí, tiêu chuẩn", example: "" },
                { word: "Exceptional", definition: "Đặc biệt, xuất chúng", example: "" },
                { word: "Extremely", definition: "Cực kỳ, vô cùng", example: "" },
                { word: "Forefront", definition: "Hàng đầu, đi đầu", example: "" },
                { word: "Endeavour", definition: "Sự nỗ lực, cố gắng", example: "" },
                { word: "Spotless", definition: "Không tì vết, sạch bong", example: "" },
                { word: "Subsequently", definition: "Sau đó, rồi thì", example: "" },
                { word: "Disruption", definition: "Sự gián đoạn, phá vỡ", example: "" },
                { word: "Embrace", definition: "Đón nhận, ôm lấy", example: "" },
                { word: "Life-size", definition: "Kích thước thật (bằng người thật)", example: "" },
                { word: "Synthetic", definition: "Tổng hợp, nhân tạo", example: "" },
                { word: "Perimeter", definition: "Chu vi, vành đai", example: "" },
                { word: "Dismantle", definition: "Tháo dỡ", example: "" },
                { word: "Promising", definition: "Đầy hứa hẹn, triển vọng", example: "" },
                { word: "Symbolise", definition: "Tượng trưng cho", example: "" },
                { word: "Cement", definition: "Củng cố, thắt chặt", example: "" },
                { word: "Flavourful", definition: "Đầy hương vị, đậm đà", example: "" },
                { word: "Shred", definition: "Cắt nhỏ, xé vụn", example: "" },
                { word: "Institute", definition: "Học viện, viện", example: "" },
                { word: "Disease", definition: "Bệnh tật", example: "" },
                { word: "Quality", definition: "Chất lượng", example: "" },
                { word: "Appreciative", definition: "Biết ơn, trân trọng", example: "" },
                { word: "Consignment", definition: "Lô hàng, hàng ký gửi", example: "" },
                { word: "Assess", definition: "Đánh giá, định giá", example: "" },
                { word: "Deduct", definition: "Khấu trừ, trừ đi", example: "" },
                { word: "Stipulate", definition: "Quy định (trong hợp đồng)", example: "" },
                { word: "Identification", definition: "Sự nhận dạng, giấy tờ tùy thân", example: "" },
                { word: "Liability", definition: "Trách nhiệm pháp lý, khoản nợ", example: "" },
                { word: "Caterer", definition: "Nhà cung cấp thực phẩm/tiệc", example: "" },
            ]
        }
    ],
};