import { VocabItem, VocabularyPart } from '../../types';

const test1_176_180_words = [
    { word: "press release", definition: "thông cáo báo chí", example: "" },
    { word: "review", definition: "bài đánh giá", example: "" },
    { word: "together", definition: "cùng nhau", example: "" },
    { word: "cooks", definition: "nấu ăn", example: "" },
    { word: "culinary", definition: "thuộc về ẩm thực", example: "" },
    { word: "owner", definition: "chủ sở hữu", example: "" },
    { word: "recently", definition: "gần đây", example: "" },
    { word: "opened", definition: "đã mở", example: "" },
    { word: "cooking", definition: "nấu ăn", example: "" },
    { word: "reflects", definition: "phản ánh", example: "" },
    { word: "heritage", definition: "di sản", example: "" },
    { word: "blend", definition: "sự pha trộn", example: "" },
    { word: "cultures", definition: "các nền văn hóa", example: "" },
    { word: "simplified", definition: "đã được đơn giản hóa", example: "" },
    { word: "flavours", definition: "các hương vị", example: "" },
    { word: "ease", definition: "sự dễ dàng", example: "" },
    { word: "preparing", definition: "đang chuẩn bị", example: "" },
    { word: "meals", definition: "các bữa ăn", example: "" },
    { word: "vice president", definition: "phó chủ tịch", example: "" },
    { word: "supplies", definition: "cung cấp", example: "" },
    { word: "ingredients", definition: "các nguyên liệu", example: "" },
    { word: "vegetarian", definition: "ăn chay", example: "" },
    { word: "appropriate", definition: "phù hợp", example: "" },
    { word: "meal", definition: "bữa ăn", example: "" },
    { word: "options", definition: "các lựa chọn", example: "" },
    { word: "partnership", definition: "sự hợp tác", example: "" },
    { word: "wonderful", definition: "tuyệt vời", example: "" },
    { word: "instead", definition: "thay vào đó", example: "" },
    { word: "treat", definition: "món ăn đặc biệt", example: "" },
    { word: "on-site", definition: "tại chỗ", example: "" },
    { word: "worthwhile", definition: "đáng giá", example: "" },
    { word: "promote", definition: "quảng bá", example: "" },
    { word: "opening", definition: "sự khai trương", example: "" },
    { word: "congratulate", definition: "chúc mừng", example: "" },
    { word: "recipient", definition: "người nhận", example: "" },
    { word: "revised", definition: "đã xem xét lại, đã sửa đổi", example: "" },
    { word: "several", definition: "một vài", example: "" },
    { word: "local", definition: "địa phương", example: "" },
    { word: "reservations", definition: "các sự đặt chỗ", example: "" },
    { word: "limited", definition: "hạn chế", example: "" },
];

const test1_181_185_words = [
    { word: "pick up", definition: "lấy, nhận", example: "" },
    { word: "order", definition: "đơn hàng", example: "" },
    { word: "extra", definition: "thêm", example: "" },
    { word: "transport", definition: "vận chuyển", example: "" },
    { word: "arrangement", definition: "sự sắp xếp", example: "" },
    { word: "necessary", definition: "cần thiết", example: "" },
    { word: "deliver", definition: "giao hàng", example: "" },
    { word: "nearby", definition: "gần đó", example: "" },
    { word: "rental", definition: "cho thuê", example: "" },
    { word: "merchandise", definition: "hàng hóa", example: "" },
    { word: "handcrafted", definition: "làm thủ công", example: "" },
    { word: "occurs", definition: "xảy ra", example: "" },
    { word: "in transit", definition: "đang vận chuyển", example: "" },
    { word: "time-consuming", definition: "tốn thời gian", example: "" },
    { word: "ordeal", definition: "trải nghiệm khó khăn", example: "" },
    { word: "inattentive", definition: "lơ đễnh, không chú ý", example: "" },
    { word: "baggage", definition: "hành lý", example: "" },
    { word: "personally", definition: "đích thân", example: "" },
    { word: "feasible", definition: "khả thi", example: "" },
    { word: "hire", definition: "thuê", example: "" },
    { word: "ground- or sea-based", definition: "đường bộ hoặc đường biển", example: "" },
    { word: "courier", definition: "người giao hàng", example: "" },
    { word: "trust", definition: "tin tưởng", example: "" },
    { word: "expect", definition: "mong đợi", example: "" },
    { word: "arrive", definition: "đến", example: "" },
    { word: "Passenger", definition: "hành khách", example: "" },
    { word: "Departing", definition: "đang khởi hành", example: "" },
    { word: "Docking", definition: "đang cập bến", example: "" },
    { word: "suitcase", definition: "vali", example: "" },
    { word: "instrument", definition: "nhạc cụ", example: "" },
    { word: "cases", definition: "các hộp đựng", example: "" },
    { word: "guitar", definition: "đàn guitar", example: "" },
    { word: "Vehicle", definition: "xe cộ", example: "" },
    { word: "Standard", definition: "tiêu chuẩn", example: "" },
    { word: "finalize", definition: "Hoàn thành, chốt", example: "" },
    { word: "invitation", definition: "Lời mời", example: "" },
    { word: "feedback", definition: "Phản hồi", example: "" },
    { word: "attend", definition: "Tham dự", example: "" },
    { word: "drop off", definition: "Thả xuống, gửi", example: "" },
    { word: "cofounder", definition: "Đồng sáng lập", example: "" },
    { word: "disappointed", definition: "Thất vọng", example: "" },
    { word: "freight", definition: "Hàng hóa, vận chuyển hàng hóa", example: "" },
    { word: "purchased", definition: "Đã mua", example: "" },
    { word: "prefers", definition: "Thích hơn, ưu tiên hơn", example: "" },
    { word: "specific", definition: "Cụ thể, đặc trưng", example: "" },
];

const test1_186_190_words = [
    { word: "profiled", definition: "Được giới thiệu, mô tả", example: "" },
    { word: "innovative", definition: "Sáng tạo, đổi mới", example: "" },
    { word: "entirely", definition: "Hoàn toàn", example: "" },
    { word: "individual", definition: "Cá nhân, riêng lẻ", example: "" },
    { word: "taught", definition: "Đã dạy (quá khứ của teach)", example: "" },
    { word: "recognized", definition: "Được công nhận", example: "" },
    { word: "valuable", definition: "Có giá trị", example: "" },
    { word: "addition", definition: "Sự bổ sung, thêm vào", example: "" },
    { word: "popular", definition: "Phổ biến, được ưa chuộng", example: "" },
    { word: "consultant", definition: "Chuyên gia tư vấn", example: "" },
    { word: "equips", definition: "Trang bị", example: "" },
    { word: "guidance", definition: "Sự hướng dẫn", example: "" },
    { word: "appeal", definition: "Thu hút, hấp dẫn", example: "" },
    { word: "target", definition: "Mục tiêu, nhắm đến", example: "" },
    { word: "practical", definition: "Thực tế, thực hành", example: "" },
    { word: "veteran", definition: "Lão luyện, có kinh nghiệm", example: "" },
    { word: "acquire", definition: "Thu được, đạt được", example: "" },
    { word: "basic", definition: "Cơ bản", example: "" },
    { word: "publishes", definition: "Xuất bản", example: "" },
    { word: "across", definition: "Khắp", example: "" },
    { word: "certification", definition: "Chứng chỉ", example: "" },
    { word: "previously", definition: "Trước đây", example: "" },
    { word: "develops", definition: "Phát triển", example: "" },
    { word: "videoconferencing", definition: "Họp trực tuyến qua video", example: "" },
    { word: "explore", definition: "Khám phá, tìm hiểu", example: "" },
    { word: "browse", definition: "Duyệt qua, xem lướt", example: "" },
    { word: "outline", definition: "Dàn ý, phác thảo", example: "" },
    { word: "vivid", definition: "Sống động, rực rỡ", example: "" },
    { word: "newsletter", definition: "Bản tin", example: "" },
    { word: "follow-up", definition: "Sự theo dõi, tiếp theo", example: "" },
    { word: "job postings", definition: "Các tin tuyển dụng", example: "" },
];

const test1_191_195_words = [
    { word: "serving up", definition: "phục vụ, dọn ra", example: "" },
    { word: "infusion", definition: "sự pha trộn, truyền vào", example: "" },
    { word: "laid-back", definition: "thoải mái, thư giãn", example: "" },
    { word: "atmosphere", definition: "bầu không khí", example: "" },
    { word: "Managed", definition: "được quản lý", example: "" },
    { word: "aromatic", definition: "thơm ngát", example: "" },
    { word: "jewel", definition: "viên ngọc, báu vật", example: "" },
    { word: "bustling", definition: "nhộn nhịp, tấp nập", example: "" },
    { word: "eateries", definition: "quán ăn", example: "" },
    { word: "servers", definition: "người phục vụ", example: "" },
    { word: "diners", definition: "thực khách", example: "" },
    { word: "variety", definition: "sự đa dạng", example: "" },
    { word: "delights", definition: "điều thú vị, món ngon", example: "" },
    { word: "extensive", definition: "rộng lớn, phong phú", example: "" },
    { word: "famous", definition: "nổi tiếng", example: "" },
    { word: "Marinated", definition: "ướp (gia vị)", example: "" },
    { word: "prior to", definition: "trước khi", example: "" },
    { word: "grilling", definition: "nướng (vỉ)", example: "" },
    { word: "sides", definition: "món ăn kèm", example: "" },
    { word: "dish", definition: "món ăn", example: "" },
    { word: "glowing", definition: "rạng rỡ, ca ngợi", example: "" },
    { word: "article", definition: "bài báo", example: "" },
    { word: "eager", definition: "háo hức", example: "" },
    { word: "Unfortunately", definition: "thật không may", example: "" },
    { word: "performance", definition: "buổi biểu diễn, hiệu suất", example: "" },
    { word: "cancelled", definition: "bị hủy", example: "" },
    { word: "Undeterred", definition: "không nản lòng", example: "" },
    { word: "smoky", definition: "có vị khói", example: "" },
    { word: "flavour", definition: "hương vị", example: "" },
    { word: "outstanding", definition: "nổi bật, xuất sắc", example: "" },
    { word: "lacking", definition: "thiếu", example: "" },
    { word: "portion", definition: "phần ăn", example: "" },
    { word: "anticipated", definition: "dự đoán, mong đợi", example: "" },
    { word: "appetiser", definition: "món khai vị", example: "" },
    { word: "avoid", definition: "tránh", example: "" },
    { word: "hungry", definition: "đói", example: "" },
    { word: "apologise", definition: "xin lỗi", example: "" },
    { word: "extremely", definition: "cực kỳ", example: "" },
    { word: "nice", definition: "dễ chịu, tốt", example: "" },
    { word: "probably", definition: "có lẽ", example: "" },
    { word: "expectations", definition: "sự mong đợi, kỳ vọng", example: "" },
    { word: "gift certificate", definition: "phiếu quà tặng", example: "" },
    { word: "equipment", definition: "thiết bị", example: "" },
    { word: "malfunction", definition: "trục trặc, hỏng hóc", example: "" },
    { word: "performing", definition: "biểu diễn", example: "" },
    { word: "weekly", definition: "hàng tuần", example: "" },
    { word: "spices", definition: "gia vị", example: "" },
    { word: "delightful", definition: "thú vị, dễ chịu", example: "" },
];

const test1_196_200_words = [
    { word: "query", definition: "truy vấn, câu hỏi", example: "" },
    { word: "very first", definition: "đầu tiên, ban đầu", example: "" },
    { word: "made purchases", definition: "đã mua hàng", example: "" },
    { word: "on a regular basis", definition: "thường xuyên, đều đặn", example: "" },
    { word: "also", definition: "cũng", example: "" },
    { word: "absolutely", definition: "hoàn toàn, tuyệt đối", example: "" },
    { word: "lose", definition: "mất", example: "" },
    { word: "rollout", definition: "sự ra mắt, triển khai", example: "" },
    { word: "smoothly", definition: "trôi chảy, suôn sẻ", example: "" },
    { word: "investigate", definition: "điều tra, xem xét", example: "" },
    { word: "without delay", definition: "ngay lập tức, không chậm trễ", example: "" },
    { word: "landscaping", definition: "cảnh quan", example: "" },
    { word: "highways", definition: "đường cao tốc", example: "" },
    { word: "operates", definition: "vận hành, hoạt động", example: "" },
    { word: "belongs to", definition: "thuộc về", example: "" },
    { word: "spent", definition: "đã chi tiêu", example: "" },
    { word: "merchandise", definition: "hàng hóa", example: "" },
    { word: "employment", definition: "việc làm", example: "" },
    { word: "construction machinery", definition: "máy móc xây dựng", example: "" },
    { word: "Solve", definition: "giải quyết", example: "" },
    { word: "Grand Total", definition: "tổng cộng, tổng số", example: "" },
    { word: "enclosed", definition: "đính kèm", example: "" },
    { word: "outlining", definition: "phác thảo, mô tả", example: "" },
    { word: "billing", definition: "việc lập hóa đơn", example: "" },
    { word: "valued", definition: "có giá trị, đáng quý", example: "" },
    { word: "founded", definition: "thành lập", example: "" },
    { word: "upgrade", definition: "nâng cấp", example: "" },
    { word: "automatically", definition: "tự động", example: "" },
    { word: "associated with", definition: "liên kết với, liên quan đến", example: "" },
    { word: "long-standing", definition: "lâu năm, lâu đời", example: "" },
    { word: "incentives", definition: "ưu đãi, khuyến khích", example: "" },
    { word: "remain in place", definition: "vẫn được giữ nguyên", example: "" },
    { word: "charitable", definition: "từ thiện", example: "" },
    { word: "within", definition: "trong vòng", example: "" },
    { word: "supply", definition: "nguồn cung", example: "" },
    { word: "samples", definition: "mẫu", example: "" },
    { word: "transition", definition: "chuyển đổi", example: "" },
    { word: "appreciates", definition: "đánh giá cao", example: "" },
];

const test2_147_150_words = [
    { word: "owners", definition: "chủ sở hữu", example: "" },
    { word: "challenge", definition: "thách thức", example: "" },
    { word: "competitive", definition: "cạnh tranh", example: "" },
    { word: "environment", definition: "môi trường", example: "" },
    { word: "Successfully", definition: "thành công", example: "" },
    { word: "reaching", definition: "tiếp cận, đạt được", example: "" },
    { word: "involves", definition: "liên quan, bao gồm", example: "" },
    { word: "effective", definition: "hiệu quả", example: "" },
    { word: "boost", definition: "thúc đẩy, tăng cường", example: "" },
    { word: "entrepreneurs", definition: "doanh nhân", example: "" },
    { word: "insight", definition: "cái nhìn sâu sắc", example: "" },
    { word: "current", definition: "hiện tại", example: "" },
    { word: "unique", definition: "độc đáo, riêng biệt", example: "" },
    { word: "organized", definition: "có tổ chức", example: "" },
    { word: "latest", definition: "mới nhất", example: "" },
    { word: "webinar", definition: "hội thảo trực tuyến", example: "" },
    { word: "related", definition: "liên quan", example: "" },
    { word: "stand out", definition: "nổi bật", example: "" },
    { word: "newsletter", definition: "bản tin", example: "" },
    { word: "launched", definition: "ra mắt, khởi động", example: "" },
    { word: "seeking", definition: "tìm kiếm", example: "" },
    { word: "features", definition: "có, bao gồm, nổi bật", example: "" },
    { word: "promotional", definition: "quảng cáo", example: "" },
    { word: "requires", definition: "yêu cầu, đòi hỏi", example: "" },
    { word: "attend", definition: "tham dự", example: "" },
    { word: "perfect", definition: "hoàn hảo", example: "" },
    { word: "revisit", definition: "thăm lại, xem xét lại", example: "" },
    { word: "multiple", definition: "nhiều, đa dạng", example: "" },
    { word: "weeklong", definition: "kéo dài một tuần", example: "" },
    { word: "popular", definition: "phổ biến, được ưa chuộng", example: "" },
    { word: "main course", definition: "món chính", example: "" },
    { word: "highly", definition: "rất, cực kỳ", example: "" },
    { word: "recommended", definition: "được đề xuất", example: "" },
    { word: "locals", definition: "người dân địa phương", example: "" },
    { word: "tourists", definition: "khách du lịch", example: "" },
    { word: "opportunity", definition: "cơ hội", example: "" },
    { word: "participating", definition: "tham gia", example: "" },
    { word: "reduced-price", definition: "giá đã giảm", example: "" },
    { word: "beverage", definition: "đồ uống", example: "" },
    { word: "lasts", definition: "kéo dài", example: "" },
    { word: "held", definition: "được tổ chức", example: "" },
];

const test2_151_157_words = [
    { word: "announced", definition: "thông báo", example: "" },
    { word: "headquarters", definition: "trụ sở chính", example: "" },
    { word: "storage", definition: "lưu trữ", example: "" },
    { word: "analytics", definition: "phân tích dữ liệu", example: "" },
    { word: "firm", definition: "công ty, hãng", example: "" },
    { word: "retailers", definition: "các nhà bán lẻ", example: "" },
    { word: "manage", definition: "quản lý", example: "" },
    { word: "current", definition: "hiện tại", example: "" },
    { word: "base", definition: "căn cứ, nền tảng", example: "" },
    { word: "executive", definition: "người điều hành, giám đốc điều hành", example: "" },
    { word: "relocate", definition: "di dời, chuyển địa điểm", example: "" },
    { word: "remain", definition: "ở lại, duy trì", example: "" },
    { word: "analyzes", definition: "phân tích", example: "" },
    { word: "processes", definition: "xử lý", example: "" },
    { word: "entire", definition: "toàn bộ", example: "" },
    { word: "out of stock", definition: "hết hàng", example: "" },
    { word: "options", definition: "các lựa chọn", example: "" },
    { word: "prefer", definition: "thích hơn", example: "" },
    { word: "cost", definition: "tốn, trị giá", example: "" },
    { word: "place an order", definition: "đặt hàng", example: "" },
    { word: "light blue", definition: "màu xanh nhạt", example: "" },
    { word: "exclusively", definition: "độc quyền", example: "" },
    { word: "discontinued", definition: "ngừng sản xuất", example: "" },
    { word: "budget", definition: "ngân sách", example: "" },
    { word: "purchase", definition: "mua", example: "" },
    { word: "cancel", definition: "hủy bỏ", example: "" },
    { word: "inquiry", definition: "yêu cầu, thắc mắc", example: "" },
    { word: "financial", definition: "thuộc về tài chính", example: "" },
    { word: "advisors", definition: "cố vấn", example: "" },
    { word: "partner", definition: "hợp tác", example: "" },
    { word: "basic", definition: "cơ bản", example: "" },
    { word: "widely", definition: "rộng rãi", example: "" },
    { word: "lead", definition: "chỉ đạo, hướng dẫn", example: "" },
    { word: "introductory", definition: "giới thiệu, nhập môn", example: "" },
    { word: "branches", definition: "chi nhánh", example: "" },
    { word: "courses", definition: "các khóa học", example: "" },
    { word: "graduates", definition: "người tốt nghiệp", example: "" },
    { word: "investors", definition: "nhà đầu tư", example: "" },
    { word: "host", definition: "tổ chức", example: "" },
    { word: "facilitators", definition: "người hỗ trợ, điều phối viên", example: "" },
    { word: "general", definition: "chung chung", example: "" },
    { word: "attendees", definition: "những người tham dự", example: "" },
    { word: "tailor", definition: "điều chỉnh, tùy chỉnh", example: "" },
    { word: "develop", definition: "phát triển", example: "" },
    { word: "discuss", definition: "thảo luận", example: "" },
    { word: "register", definition: "đăng ký", example: "" },
    { word: "confirm", definition: "xác nhận", example: "" },
    { word: "credentials", definition: "chứng chỉ, bằng cấp", example: "" },
    { word: "reply", definition: "trả lời", example: "" },
    { word: "arrange", definition: "sắp xếp", example: "" },
];

const test2_158_167_words = [
    { word: "Vision", definition: "Thị lực, tầm nhìn", example: "" },
    { word: "limited", definition: "Giới hạn", example: "" },
    { word: "eyeglass", definition: "Kính mắt", example: "" },
    { word: "frames", definition: "Gọng kính", example: "" },
    { word: "fittings", definition: "Sự lắp ráp, phụ kiện", example: "" },
    { word: "adjustments", definition: "Sự điều chỉnh", example: "" },
    { word: "guarantee", definition: "Sự bảo hành, cam kết", example: "" },
    { word: "satisfied", definition: "Hài lòng, thỏa mãn", example: "" },
    { word: "throughout", definition: "Khắp, suốt", example: "" },
    { word: "Low-cost", definition: "Chi phí thấp, giá rẻ", example: "" },
    { word: "checkups", definition: "Kiểm tra sức khỏe định kỳ", example: "" },
    { word: "licensed", definition: "Được cấp phép", example: "" },
    { word: "draw attention", definition: "Gây chú ý", example: "" },
    { word: "underused", definition: "Ít được sử dụng", example: "" },
    { word: "publicize", definition: "Công khai, quảng bá", example: "" },
    { word: "warranty", definition: "Bảo hành", example: "" },
    { word: "temporary", definition: "Tạm thời", example: "" },
    { word: "price discount", definition: "Giảm giá", example: "" },
    { word: "competitors", definition: "Đối thủ cạnh tranh", example: "" },
    { word: "at no cost", definition: "Miễn phí", example: "" },
    { word: "certified", definition: "Được chứng nhận", example: "" },
    { word: "limited number", definition: "Số lượng có hạn", example: "" },
    { word: "lease", definition: "Hợp đồng cho thuê", example: "" },
    { word: "renew", definition: "Gia hạn", example: "" },
    { word: "rent", definition: "Tiền thuê nhà", example: "" },
    { word: "rising", definition: "Tăng lên", example: "" },
    { word: "costs", definition: "Chi phí", example: "" },
    { word: "renewal", definition: "Sự gia hạn", example: "" },
    { word: "monthly", definition: "Hàng tháng", example: "" },
    { word: "charge", definition: "Khoản phí", example: "" },
    { word: "notify", definition: "Thông báo", example: "" },
    { word: "vacate", definition: "Dọn đi, bỏ trống", example: "" },
    { word: "inspection", definition: "Sự kiểm tra", example: "" },
    { word: "beyond", definition: "Vượt quá", example: "" },
    { word: "usage", definition: "Sự sử dụng", example: "" },
    { word: "installation", definition: "Sự lắp đặt", example: "" },
    { word: "agreement", definition: "Thỏa thuận", example: "" },
    { word: "amenity", definition: "Tiện nghi", example: "" },
    { word: "cleaning", definition: "Việc dọn dẹp", example: "" },
    { word: "revisions", definition: "sự sửa đổi, bản sửa đổi", example: "" },
    { word: "forwarding", definition: "gửi đi, chuyển tiếp", example: "" },
    { word: "wholesale", definition: "bán buôn, sỉ", example: "" },
    { word: "extension", definition: "sự gia hạn", example: "" },
    { word: "concerns", definition: "những mối quan ngại, lo lắng", example: "" },
    { word: "packaging", definition: "bao bì, đóng gói", example: "" },
    { word: "crates", definition: "thùng, két", example: "" },
    { word: "innovative", definition: "mang tính đổi mới, sáng tạo", example: "" },
    { word: "reduce", definition: "giảm, cắt giảm", example: "" },
    { word: "risk", definition: "rủi ro, nguy cơ", example: "" },
    { word: "breakage", definition: "sự vỡ, hư hỏng", example: "" },
    { word: "transit", definition: "sự vận chuyển, quá cảnh", example: "" },
    { word: "penalty", definition: "tiền phạt, hình phạt", example: "" },
    { word: "fee", definition: "phí, lệ phí", example: "" },
    { word: "out of", definition: "không có mặt ở, đi khỏi", example: "" },
    { word: "possible", definition: "có thể, khả thi", example: "" },
    { word: "convenient", definition: "thuận tiện", example: "" },
    { word: "finalize", definition: "hoàn tất, chốt lại", example: "" },
    { word: "negotiate", definition: "đàm phán, thương lượng", example: "" },
    { word: "redesigned", definition: "được thiết kế lại", example: "" },
    { word: "respond", definition: "phản hồi, đáp lại", example: "" },
    { word: "greet", definition: "chào hỏi, đón tiếp", example: "" },
];

const test2_168_175_words = [
    { word: "demand", definition: "nhu cầu", example: "" },
    { word: "containers", definition: "thùng chứa", example: "" },
    { word: "shortage", definition: "sự thiếu hụt", example: "" },
    { word: "drop", definition: "sự giảm", example: "" },
    { word: "rolls", definition: "cuộn", example: "" },
    { word: "raw", definition: "thô, nguyên", example: "" },
    { word: "complicated", definition: "phức tạp", example: "" },
    { word: "exporters", definition: "nhà xuất khẩu", example: "" },
    { word: "substantially", definition: "đáng kể", example: "" },
    { word: "risks", definition: "rủi ro", example: "" },
    { word: "triggering", definition: "gây ra", example: "" },
    { word: "dissatisfaction", definition: "sự không hài lòng", example: "" },
    { word: "solutions", definition: "giải pháp", example: "" },
    { word: "cooperation", definition: "sự hợp tác", example: "" },
    { word: "stakeholders", definition: "các bên liên quan", example: "" },
    { word: "suffering", definition: "chịu đựng", example: "" },
    { word: "athletic", definition: "thể thao", example: "" },
    { word: "footwear", definition: "giày dép", example: "" },
    { word: "implemented", definition: "đã thực hiện", example: "" },
    { word: "overcome", definition: "vượt qua", example: "" },
    { word: "refocused", definition: "đã tập trung lại", example: "" },
    { word: "domestic", definition: "trong nước", example: "" },
    { word: "regional", definition: "khu vực", example: "" },
    { word: "caused", definition: "đã gây ra", example: "" },
    { word: "significant", definition: "đáng kể", example: "" },
    { word: "impact", definition: "tác động", example: "" },
    { word: "readily", definition: "dễ dàng", example: "" },
    { word: "uniforms", definition: "đồng phục", example: "" },
    { word: "status", definition: "trạng thái, tình hình", example: "" },
    { word: "Phase", definition: "giai đoạn", example: "" },
    { word: "job site", definition: "công trường", example: "" },
    { word: "pouring", definition: "đổ, rót", example: "" },
    { word: "concrete", definition: "bê tông", example: "" },
    { word: "sidewalks", definition: "vỉa hè", example: "" },
    { word: "conditions", definition: "điều kiện", example: "" },
    { word: "situation", definition: "tình hình", example: "" },
    { word: "break ground", definition: "khởi công", example: "" },
    { word: "knowledgeable", definition: "am hiểu, có kiến thức", example: "" },
    { word: "finisher", definition: "người hoàn thiện", example: "" },
    { word: "opinion", definition: "ý kiến", example: "" },
    { word: "keep me posted", definition: "cập nhật thông tin cho tôi", example: "" },
    { word: "rush", definition: "vội vàng, gấp gáp", example: "" },
    { word: "wet", definition: "ẩm ướt, ướt", example: "" },
    { word: "will do", definition: "sẽ làm", example: "" },
    { word: "weather forecast", definition: "dự báo thời tiết", example: "" },
    { word: "obtain", definition: "đạt được, có được", example: "" },
    { word: "outcome", definition: "kết quả", example: "" },
    { word: "progress", definition: "tiến độ", example: "" },
    { word: "client", definition: "khách hàng", example: "" },
    { word: "delivery", definition: "sự giao hàng", example: "" },
];

const test2_176_185_words = [
    { word: "texture", definition: "kết cấu, cấu trúc", example: "" },
    { word: "sweetness", definition: "độ ngọt", example: "" },
    { word: "scale", definition: "thang đo, quy mô", example: "" },
    { word: "unpleasant", definition: "khó chịu, không dễ chịu", example: "" },
    { word: "sour", definition: "chua", example: "" },
    { word: "potential", definition: "tiềm năng", example: "" },
    { word: "adding", definition: "thêm vào", example: "" },
    { word: "popularity", definition: "sự phổ biến", example: "" },
    { word: "manufactures", definition: "sản xuất, chế tạo", example: "" },
    { word: "regularly", definition: "thường xuyên, đều đặn", example: "" },
    { word: "survey", definition: "cuộc khảo sát, cuộc điều tra", example: "" },
    { word: "disappointing", definition: "gây thất vọng", example: "" },
    { word: "consistent", definition: "nhất quán, kiên định", example: "" },
    { word: "laboratory", definition: "phòng thí nghiệm", example: "" },
    { word: "adjust", definition: "điều chỉnh", example: "" },
    { word: "grocery", definition: "hàng tạp hóa, thực phẩm", example: "" },
    { word: "proceed", definition: "tiến hành, tiếp tục", example: "" },
    { word: "freeze", definition: "đông lạnh, đóng băng", example: "" },
    { word: "based", definition: "có trụ sở tại, dựa trên", example: "" },
    { word: "seeking", definition: "tìm kiếm", example: "" },
    { word: "handles", definition: "xử lý, đảm đương", example: "" },
    { word: "fast-paced", definition: "nhịp độ nhanh", example: "" },
    { word: "collaborate", definition: "cộng tác, hợp tác", example: "" },
    { word: "strategies", definition: "chiến lược", example: "" },
    { word: "publicity", definition: "sự quảng bá, công khai", example: "" },
    { word: "remote", definition: "xa xôi, từ xa", example: "" },
    { word: "residence", definition: "nơi cư trú, chỗ ở", example: "" },
    { word: "recipient", definition: "người nhận", example: "" },
    { word: "suit", definition: "phù hợp, thích hợp", example: "" },
    { word: "determine", definition: "xác định, quyết định", example: "" },
    { word: "satisfy", definition: "làm hài lòng, thỏa mãn", example: "" },
    { word: "responsibilities", definition: "trách nhiệm", example: "" },
    { word: "drafts", definition: "bản nháp, bản phác thảo", example: "" },
    { word: "expert", definition: "chuyên gia, thành thạo", example: "" },
    { word: "valuable", definition: "có giá trị", example: "" },
    { word: "decade", definition: "thập kỷ (10 năm)", example: "" },
    { word: "collections", definition: "bộ sưu tập", example: "" },
    { word: "oversee", definition: "giám sát, quản lý", example: "" },
    { word: "initial", definition: "ban đầu", example: "" },
    { word: "partnership", definition: "quan hệ đối tác, hợp tác", example: "" },
    { word: "hobby", definition: "sở thích", example: "" },
    { word: "attracted", definition: "thu hút", example: "" },
    { word: "sustainable", definition: "bền vững", example: "" },
    { word: "cosmetics", definition: "mỹ phẩm", example: "" },
    { word: "considering", definition: "xem xét", example: "" },
];

const test2_186_195_words = [
    { word: "Toner", definition: "mực in", example: "" },
    { word: "Gel pens", definition: "bút gel", example: "" },
    { word: "Staples", definition: "ghim bấm", example: "" },
    { word: "Unopened merchandise", definition: "hàng hóa chưa mở", example: "" },
    { word: "Returned", definition: "trả lại", example: "" },
    { word: "Label", definition: "nhãn", example: "" },
    { word: "Apology", definition: "lời xin lỗi", example: "" },
    { word: "Inconvenience", definition: "sự bất tiện", example: "" },
    { word: "Previous", definition: "trước đó", example: "" },
    { word: "Identical", definition: "giống hệt", example: "" },
    { word: "Recurring", definition: "tái diễn", example: "" },
    { word: "Query", definition: "câu hỏi", example: "" },
    { word: "Technical team", definition: "đội kỹ thuật", example: "" },
    { word: "Itemized", definition: "được liệt kê chi tiết", example: "" },
    { word: "Supervisor", definition: "người giám sát", example: "" },
    { word: "Charges", definition: "các khoản phí", example: "" },
    { word: "Separately", definition: "riêng biệt", example: "" },
    { word: "Automatically", definition: "tự động", example: "" },
    { word: "Mistakenly", definition: "một cách nhầm lẫn", example: "" },
    { word: "Detailed", definition: "chi tiết", example: "" },
    { word: "Printable", definition: "có thể in được", example: "" },
    { word: "Bamboo", definition: "Cây tre", example: "" },
    { word: "Cushions", definition: "Đệm, gối tựa", example: "" },
    { word: "Aloe", definition: "Cây lô hội, nha đam", example: "" },
    { word: "Litre", definition: "Lít", example: "" },
    { word: "Machine-washable", definition: "Có thể giặt máy", example: "" },
    { word: "Wool", definition: "Len", example: "" },
    { word: "Brick-and-mortar", definition: "Cửa hàng truyền thống", example: "" },
    { word: "Handcrafted", definition: "Làm thủ công", example: "" },
    { word: "Established", definition: "Thành lập", example: "" },
    { word: "Boutique", definition: "Cửa hàng thời trang nhỏ", example: "" },
    { word: "Department store", definition: "Cửa hàng bách hóa", example: "" },
    { word: "Popular", definition: "Phổ biến", example: "" },
    { word: "Merchandise", definition: "Hàng hóa", example: "" },
    { word: "Interior", definition: "Nội thất", example: "" },
    { word: "On staff", definition: "Có trong biên chế", example: "" },
    { word: "Consult", definition: "Tham khảo ý kiến", example: "" },
    { word: "In person", definition: "Trực tiếp", example: "" },
    { word: "Browse", definition: "Xem qua, lướt qua", example: "" },
    { word: "Attached", definition: "Đính kèm, gắn liền", example: "" },
    { word: "Grand-opening", definition: "Lễ khai trương", example: "" },
    { word: "Frequent", definition: "Thường xuyên", example: "" },
    { word: "Compare", definition: "So sánh", example: "" },
    { word: "Locally", definition: "Tại địa phương", example: "" },
];

const test2_196_200_words = [
    { word: "cooperation", definition: "sự hợp tác, sự cộng tác", example: "" },
    { word: "satisfaction", definition: "sự hài lòng, sự thỏa mãn", example: "" },
    { word: "engagement", definition: "sự tham gia, sự gắn kết", example: "" },
    { word: "high-energy", definition: "giàu năng lượng, sôi nổi, hoạt bát", example: "" },
    { word: "problem-solving", definition: "giải quyết vấn đề (kỹ năng)", example: "" },
    { word: "predetermined", definition: "được định trước, được xác định trước", example: "" },
    { word: "engineering", definition: "kỹ thuật, công trình", example: "" },
    { word: "chocolatier", definition: "thợ làm sô cô la, người/công ty bán sô cô la", example: "" },
    { word: "outdoor", definition: "ngoài trời", example: "" },
    { word: "Scavenger Hunt", definition: "trò chơi tìm kiếm (săn lùng đồ vật)", example: "" },
    { word: "suitable", definition: "phù hợp, thích hợp", example: "" },
    { word: "indoors", definition: "ở trong nhà, vào trong nhà", example: "" },
    { word: "hold", definition: "tổ chức, tiến hành (sự kiện); giữ, nắm", example: "" },
    { word: "focus", definition: "sự tập trung, trọng tâm; tập trung", example: "" },
    { word: "lack", definition: "sự thiếu hụt, thiếu sót; thiếu", example: "" },
    { word: "uninteresting", definition: "không thú vị, tẻ nhạt", example: "" },
    { word: "facilitator", definition: "người điều phối, người hỗ trợ, điều hành", example: "" },
    { word: "local attractions", definition: "điểm tham quan địa phương", example: "" },
    { word: "walking distances", definition: "khoảng cách đi bộ", example: "" },
    { word: "prizes", definition: "giải thưởng, phần thưởng", example: "" },
    { word: "free passes", definition: "vé miễn phí, giấy thông hành miễn phí", example: "" },
    { word: "event planner", definition: "người lập kế hoạch sự kiện", example: "" },
];


export const readingPart7Vocabulary: VocabularyPart = {
    id: 7,
    title: "Reading Cơ bản",
    description: "Tập trung vào những từ vựng cơ bản và phổ biến trong Reading Part 7",
    tests: [
        {
            id: 6, title: "Test 1 (147-150)", words: [
                { word: "purchasing", definition: "mua sắm, mua hàng", example: "" },
                { word: "unpacking", definition: "mở hộp, tháo gói", example: "" },
                { word: "verify", definition: "xác minh, kiểm tra", example: "" },
                { word: "components", definition: "các bộ phận, linh kiện", example: "" },
                { word: "included", definition: "bao gồm", example: "" },
                { word: "place", definition: "đặt, để", example: "" },
                { word: "safe", definition: "an toàn", example: "" },
                { word: "avoid", definition: "tránh, né", example: "" },
                { word: "loss", definition: "mất mát, hư hỏng", example: "" },
                { word: "damage", definition: "hư hỏng, làm hỏng", example: "" },
                { word: "assemble", definition: "lắp ráp, lắp đặt", example: "" },
                { word: "soft", definition: "mềm", example: "" },
                { word: "flattened", definition: "làm phẳng, bị ép phẳng", example: "" },
                { word: "empty", definition: "trống rỗng", example: "" },
                { word: "assembly", definition: "sự lắp ráp", example: "" },
                { word: "main", definition: "chính", example: "" },
                { word: "side", definition: "mặt, bên", example: "" },
                { word: "never", definition: "không bao giờ", example: "" },
                { word: "overtighten", definition: "vặn quá chặt", example: "" },
                { word: "screws", definition: "ốc vít", example: "" },
                { word: "bolts", definition: "bu lông", example: "" },
                { word: "wood", definition: "gỗ", example: "" },
                { word: "cushioning", definition: "đệm, lót đệm", example: "" },
                { word: "obtain", definition: "đạt được, lấy được", example: "" },
                { word: "maintenance", definition: "bảo trì, bảo dưỡng", example: "" },
                { word: "register", definition: "đăng ký", example: "" },
                { word: "product", definition: "sản phẩm", example: "" },
                { word: "warranty", definition: "bảo hành", example: "" },
                { word: "coverage", definition: "phạm vi, sự bao phủ", example: "" },
                { word: "staff", definition: "nhân viên", example: "" },
                { word: "keep", definition: "giữ, giữ lại", example: "" },
                { word: "copy", definition: "bản sao, bản in", example: "" },
                { word: "schedule", definition: "lịch trình, thời gian biểu", example: "" },
                { word: "desks", definition: "bàn làm việc", example: "" },
                { word: "quick", definition: "nhanh, nhanh chóng", example: "" },
                { word: "reference", definition: "tham khảo, tài liệu tham khảo", example: "" },
                { word: "interoffice", definition: "nội bộ văn phòng", example: "" },
                { word: "meetings", definition: "các cuộc họp", example: "" },
                { word: "whenever", definition: "bất cứ khi nào", example: "" },
                { word: "possible", definition: "có thể", example: "" },
                { word: "underlined", definition: "được gạch chân", example: "" },
                { word: "hours", definition: "giờ, khoảng thời gian", example: "" },
                { word: "conference", definition: "hội nghị, cuộc họp", example: "" },
                { word: "firm", definition: "công ty, hãng", example: "" },
                { word: "administrative", definition: "thuộc về hành chính", example: "" },
                { word: "assistants", definition: "trợ lý", example: "" },
                { word: "preferred", definition: "được ưu tiên, được yêu thích", example: "" }
            ]
        },
        {
            id: 7, title: "Test 1 (151-152)", words: [
                { word: "premier", definition: "hàng đầu, tốt nhất", example: "" },
                { word: "spaces", definition: "các không gian", example: "" },
                { word: "a hill", definition: "một ngọn đồi", example: "" },
                { word: "expansive", definition: "rộng lớn, bao quát", example: "" },
                { word: "sweeping", definition: "rộng lớn, bao quát (thường dùng với tầm nhìn)", example: "" },
                { word: "adjacent", definition: "liền kề, gần kề", example: "" },
                { word: "botanical", definition: "thuộc về thực vật, thực vật học", example: "" },
                { word: "renovation", definition: "sự cải tạo, nâng cấp", example: "" },
                { word: "accommodate", definition: "chứa đựng, đáp ứng", example: "" },
                { word: "guests", definition: "khách mời", example: "" },
                { word: "receptions", definition: "tiệc chiêu đãi", example: "" },
                { word: "office parties", definition: "tiệc văn phòng", example: "" },
                { word: "panel", definition: "thuộc về hội thảo, diễn đàn", example: "" },
                { word: "presentations", definition: "bài thuyết trình", example: "" },
                { word: "marble", definition: "làm bằng đá cẩm thạch", example: "" },
                { word: "floors", definition: "sàn nhà", example: "" },
                { word: "cathedral", definition: "thuộc về nhà thờ lớn", example: "" },
                { word: "ceiling", definition: "trần nhà", example: "" },
                { word: "stunning", definition: "tuyệt đẹp, gây ấn tượng", example: "" },
                { word: "artwork", definition: "tác phẩm nghệ thuật", example: "" },
                { word: "ideal", definition: "lý tưởng", example: "" },
                { word: "gathering", definition: "sự tụ họp, buổi gặp mặt", example: "" },
                { word: "on-site", definition: "tại chỗ", example: "" },
                { word: "restaurant", definition: "nhà hàng", example: "" },
                { word: "caters", definition: "phục vụ (thức ăn, đồ uống)", example: "" },
                { word: "operates", definition: "hoạt động, điều hành", example: "" },
                { word: "dietary", definition: "thuộc về chế độ ăn uống", example: "" },
                { word: "revolutionized", definition: "cách mạng hóa, thay đổi hoàn toàn", example: "" },
                { word: "local", definition: "địa phương", example: "" },
                { word: "scene", definition: "bối cảnh, khu vực", example: "" },
                { word: "residents", definition: "cư dân", example: "" },
                { word: "reserve", definition: "đặt trước, giữ chỗ", example: "" },
                { word: "reservation", definition: "sự đặt trước, sự giữ chỗ", example: "" },
                { word: "snores", definition: "ngủ ngáy", example: "" },
                { word: "solely", definition: "duy nhất, chỉ", example: "" },
                { word: "corporate", definition: "thuộc về công ty", example: "" },
                { word: "international", definition: "quốc tế", example: "" },
                { word: "limited", definition: "hạn chế", example: "" },
                { word: "offers", definition: "cung cấp", example: "" },
                { word: "funded", definition: "được tài trợ", example: "" },
                { word: "charitable", definition: "từ thiện", example: "" },
                { word: "popular", definition: "phổ biến, nổi tiếng", example: "" }
            ]
        },
        {
            id: 8, title: "Test 1 (153-157)", words: [
                { word: "almost", definition: "hầu như, gần như", example: "" },
                { word: "field measurements", definition: "các phép đo thực địa", example: "" },
                { word: "afraid", definition: "sợ, e rằng", example: "" },
                { word: "without", definition: "không có", example: "" },
                { word: "site coordinates", definition: "tọa độ địa điểm", example: "" },
                { word: "correct", definition: "chính xác", example: "" },
                { word: "double-checked", definition: "đã kiểm tra lại một lần nữa", example: "" },
                { word: "season", definition: "của mùa vụ", example: "" },
                { word: "excellent", definition: "tuyệt vời", example: "" },
                { word: "weather", definition: "thời tiết", example: "" },
                { word: "yielded", definition: "đã mang lại, đã tạo ra", example: "" },
                { word: "substantial", definition: "đáng kể", example: "" },
                { word: "harvest", definition: "vụ mùa, thu hoạch", example: "" },
                { word: "growers", definition: "người trồng trọt", example: "" },
                { word: "buyers", definition: "người mua", example: "" },
                { word: "wishing", definition: "mong muốn", example: "" },
                { word: "donate", definition: "quyên góp, hiến tặng", example: "" },
                { word: "surplus", definition: "số dư, thặng dư", example: "" },
                { word: "produce", definition: "nông sản", example: "" },
                { word: "community", definition: "cộng đồng", example: "" },
                { word: "organizations", definition: "các tổ chức", example: "" },
                { word: "list", definition: "danh sách", example: "" },
                { word: "instead", definition: "thay vào đó", example: "" },
                { word: "contact", definition: "liên hệ", example: "" },
                { word: "reach out", definition: "tiếp cận, liên hệ", example: "" },
                { word: "independent", definition: "độc lập", example: "" },
                { word: "truck drivers", definition: "các tài xế xe tải", example: "" },
                { word: "kindly", definition: "vui lòng, tử tế", example: "" },
                { word: "volunteered", definition: "đã tình nguyện", example: "" },
                { word: "transport", definition: "vận chuyển", example: "" },
                { word: "distribute", definition: "phân phát, phân phối", example: "" },
                { word: "vetted", definition: "đã được kiểm tra, xác minh", example: "" },
                { word: "insights", definition: "sự hiểu biết sâu sắc", example: "" },
                { word: "related", definition: "liên quan", example: "" },
                { word: "region", definition: "vùng, khu vực", example: "" },
                { word: "caused", definition: "đã gây ra", example: "" },
                { word: "frequently", definition: "thường xuyên", example: "" },
                { word: "beneficial", definition: "có lợi", example: "" }
            ]
        },
        {
            id: 9, title: "Test 1 (158-160)", words: [
                { word: "delighted", definition: "rất vui mừng, hài lòng", example: "" },
                { word: "joining", definition: "đang tham gia", example: "" },
                { word: "adhere", definition: "tuân thủ, tuân theo", example: "" },
                { word: "following", definition: "sau đây, tiếp theo", example: "" },
                { word: "guidelines", definition: "các hướng dẫn", example: "" },
                { word: "ensure", definition: "đảm bảo", example: "" },
                { word: "attendees", definition: "những người tham dự", example: "" },
                { word: "enjoyable", definition: "thú vị, có thể tận hưởng", example: "" },
                { word: "venue", definition: "địa điểm", example: "" },
                { word: "electronic", definition: "điện tử", example: "" },
                { word: "devices", definition: "các thiết bị", example: "" },
                { word: "silent mode", definition: "chế độ im lặng", example: "" },
                { word: "distracting", definition: "gây xao lãng", example: "" },
                { word: "performers", definition: "các nghệ sĩ biểu diễn", example: "" },
                { word: "fellow", definition: "cùng, đồng", example: "" },
                { word: "audience", definition: "khán giả", example: "" },
                { word: "members", definition: "thành viên", example: "" },
                { word: "allowed", definition: "được phép", example: "" },
                { word: "recording", definition: "sự ghi âm, ghi hình", example: "" },
                { word: "aisles", definition: "lối đi", example: "" },
                { word: "pose", definition: "gây ra, đặt ra", example: "" },
                { word: "concern", definition: "mối quan ngại", example: "" },
                { word: "fit", definition: "vừa vặn", example: "" },
                { word: "properly", definition: "đúng cách", example: "" },
                { word: "storing", definition: "đang cất giữ", example: "" },
                { word: "locker", definition: "tủ khóa", example: "" },
                { word: "attendants", definition: "người phục vụ", example: "" },
                { word: "gladly", definition: "một cách vui vẻ, sẵn lòng", example: "" },
                { word: "assist", definition: "giúp đỡ", example: "" },
                { word: "cooperation", definition: "sự hợp tác", example: "" },
                { word: "concert hall", definition: "phòng hòa nhạc", example: "" },
                { word: "post office", definition: "bưu điện", example: "" },
                { word: "locked", definition: "được khóa", example: "" },
                { word: "inspected", definition: "đã được kiểm tra", example: "" }
            ]
        },
        {
            id: 10, title: "Test 1 (161-164)", words: [
                { word: "selecting", definition: "đang chọn", example: "" },
                { word: "baked", definition: "đã được nướng", example: "" },
                { word: "goods", definition: "hàng hóa", example: "" },
                { word: "conference", definition: "hội nghị", example: "" },
                { word: "chosen", definition: "đã chọn", example: "" },
                { word: "in a row", definition: "liên tiếp", example: "" },
                { word: "custom-baked", definition: "được nướng theo yêu cầu", example: "" },
                { word: "multilayer", definition: "nhiều lớp", example: "" },
                { word: "billed", definition: "đã được lập hóa đơn", example: "" },
                { word: "attached", definition: "được đính kèm", example: "" },
                { word: "form", definition: "mẫu đơn", example: "" },
                { word: "return", definition: "gửi lại", example: "" },
                { word: "within", definition: "trong vòng", example: "" },
                { word: "Regarding", definition: "liên quan đến, về", example: "" },
                { word: "pastry", definition: "bánh ngọt", example: "" },
                { word: "produce", definition: "sản xuất, làm ra", example: "" },
                { word: "specifications", definition: "các thông số kỹ thuật", example: "" },
                { word: "recipe", definition: "công thức", example: "" },
                { word: "fresh", definition: "tươi", example: "" },
                { word: "raspberry", definition: "quả mâm xôi", example: "" },
                { word: "judged", definition: "đã đánh giá, đã phán xét", example: "" },
                { word: "delectable", definition: "ngon, hấp dẫn", example: "" },
                { word: "treat", definition: "món ăn đặc biệt", example: "" },
                { word: "concerns", definition: "các mối quan ngại", example: "" },
                { word: "value", definition: "đánh giá cao", example: "" },
                { word: "request", definition: "yêu cầu", example: "" },
                { word: "confirmation", definition: "sự xác nhận", example: "" },
                { word: "adjust", definition: "điều chỉnh", example: "" },
                { word: "delivery", definition: "sự giao hàng", example: "" },
                { word: "announce", definition: "thông báo", example: "" },
                { word: "expansion", definition: "sự mở rộng", example: "" },
                { word: "promote", definition: "quảng bá", example: "" },
                { word: "dessert", definition: "món tráng miệng", example: "" },
                { word: "products", definition: "các sản phẩm", example: "" },
                { word: "professional", definition: "chuyên nghiệp", example: "" },
                { word: "award", definition: "giải thưởng", example: "" },
                { word: "client", definition: "khách hàng", example: "" },
                { word: "positive", definition: "tích cực", example: "" },
                { word: "recommendation", definition: "sự giới thiệu, đề xuất", example: "" },
                { word: "best-selling", definition: "bán chạy nhất", example: "" },
                { word: "annually", definition: "hàng năm", example: "" },
                { word: "expensive", definition: "đắt tiền", example: "" },
                { word: "flavor", definition: "hương vị", example: "" },
                { word: "combination", definition: "sự kết hợp", example: "" }
            ]
        },
        {
            id: 11, title: "Test 1 (165-167)", words: [
                { word: "dishwasher", definition: "máy rửa bát", example: "" },
                { word: "remodeling", definition: "đang sửa sang", example: "" },
                { word: "kitchen", definition: "nhà bếp", example: "" },
                { word: "had", definition: "đã có", example: "" },
                { word: "compact", definition: "nhỏ gọn", example: "" },
                { word: "choice", definition: "sự lựa chọn", example: "" },
                { word: "pricier", definition: "đắt hơn", example: "" },
                { word: "models", definition: "các mẫu", example: "" },
                { word: "extra", definition: "thêm", example: "" },
                { word: "decided", definition: "đã quyết định", example: "" },
                { word: "decision", definition: "quyết định", example: "" },
                { word: "sparkling", definition: "lấp lánh, sáng bóng", example: "" },
                { word: "clean", definition: "sạch", example: "" },
                { word: "designed", definition: "được thiết kế", example: "" },
                { word: "efficiently", definition: "một cách hiệu quả", example: "" },
                { word: "important", definition: "quan trọng", example: "" },
                { word: "available", definition: "có sẵn", example: "" },
                { word: "rated", definition: "được đánh giá", example: "" },
                { word: "brand", definition: "nhãn hiệu", example: "" },
                { word: "operating", definition: "đang hoạt động", example: "" },
                { word: "recently", definition: "gần đây", example: "" },
                { word: "bought", definition: "đã mua", example: "" },
                { word: "remodeled", definition: "đã sửa sang", example: "" },
                { word: "professionally", definition: "một cách chuyên nghiệp", example: "" }
            ]
        },
        {
            id: 12, title: "Test 1 (168-171)", words: [
                { word: "employs", definition: "tuyển dụng", example: "" },
                { word: "world", definition: "thế giới", example: "" },
                { word: "growing", definition: "đang phát triển", example: "" },
                { word: "fast", definition: "nhanh", example: "" },
                { word: "positions", definition: "các vị trí (công việc)", example: "" },
                { word: "background", definition: "nền tảng, kinh nghiệm", example: "" },
                { word: "probably", definition: "có lẽ", example: "" },
                { word: "employees", definition: "các nhân viên", example: "" },
                { word: "perks", definition: "các phúc lợi", example: "" },
                { word: "discount", definition: "chiết khấu, giảm giá", example: "" },
                { word: "enables", definition: "cho phép", example: "" },
                { word: "destinations", definition: "các điểm đến", example: "" },
                { word: "fraction", definition: "một phần nhỏ", example: "" },
                { word: "upward", definition: "hướng lên", example: "" },
                { word: "global", definition: "toàn cầu", example: "" },
                { word: "mobility", definition: "sự di chuyển, tính di động", example: "" },
                { word: "tuition", definition: "học phí", example: "" },
                { word: "reimbursement", definition: "sự hoàn trả", example: "" },
                { word: "mentorship", definition: "sự cố vấn", example: "" },
                { word: "generous", definition: "hào phóng", example: "" },
                { word: "compensation", definition: "sự đền bù, bồi thường", example: "" },
                { word: "work-life", definition: "công việc và cuộc sống", example: "" },
                { word: "balance", definition: "sự cân bằng", example: "" },
                { word: "no wonder", definition: "chẳng có gì đáng ngạc nhiên", example: "" },
                { word: "job seekers", definition: "người tìm việc", example: "" },
                { word: "educational", definition: "thuộc về giáo dục", example: "" },
                { word: "expenses", definition: "chi phí", example: "" },
                { word: "opportunities", definition: "các cơ hội", example: "" },
                { word: "paid", definition: "được trả lương", example: "" },
                { word: "days", definition: "các ngày", example: "" },
                { word: "off", definition: "nghỉ", example: "" },
                { word: "merge", definition: "sáp nhập", example: "" },
                { word: "praised", definition: "đã được ca ngợi", example: "" },
                { word: "trade", definition: "thuộc về ngành, thương mại", example: "" },
                { word: "publication", definition: "ấn phẩm", example: "" },
                { word: "replaced", definition: "đã thay thế", example: "" },
                { word: "openings", definition: "các vị trí trống", example: "" },
                { word: "broad", definition: "rộng", example: "" },
                { word: "range", definition: "phạm vi", example: "" },
                { word: "skill", definition: "kỹ năng", example: "" },
                { word: "sets", definition: "các bộ, nhóm", example: "" }
            ]
        },
        {
            id: 13, title: "Test 1 (172-175)", words: [
                { word: "highlight", definition: "làm nổi bật", example: "" },
                { word: "multiple", definition: "nhiều", example: "" },
                { word: "locations", definition: "các địa điểm", example: "" },
                { word: "attend", definition: "tham dự", example: "" },
                { word: "smoothly", definition: "một cách suôn sẻ", example: "" },
                { word: "notified", definition: "đã được thông báo", example: "" },
                { word: "upcoming", definition: "sắp tới", example: "" },
                { word: "amateur", definition: "nghiệp dư", example: "" },
                { word: "athlete", definition: "vận động viên", example: "" },
                { word: "product", definition: "sản phẩm", example: "" },
                { word: "researcher", definition: "nhà nghiên cứu", example: "" },
                { word: "advertising", definition: "quảng cáo", example: "" },
                { word: "executive", definition: "giám đốc điều hành", example: "" },
                { word: "line", definition: "dòng, loại", example: "" },
                { word: "partner", definition: "đối tác", example: "" },
                { word: "on track", definition: "đúng tiến độ", example: "" },
                { word: "missing", definition: "thiếu", example: "" },
                { word: "elements", definition: "các yếu tố", example: "" },
                { word: "mainly", definition: "chủ yếu", example: "" },
                { word: "development", definition: "sự phát triển", example: "" },
                { word: "overlook", definition: "bỏ qua, quên", example: "" },
                { word: "expedite", definition: "xúc tiến, đẩy nhanh", example: "" },
                { word: "summary", definition: "bản tóm tắt", example: "" },
                { word: "assuming", definition: "giả sử rằng", example: "" },
                { word: "incorporate", definition: "kết hợp", example: "" },
                { word: "findings", definition: "các phát hiện", example: "" },
                { word: "trial", definition: "thử nghiệm", example: "" },
                { word: "necessary", definition: "cần thiết", example: "" }
            ]
        },
        { id: 14, title: "Test 1 (176-180)", words: test1_176_180_words },
        { id: 15, title: "Test 1 (181-185)", words: test1_181_185_words },
        { id: 16, title: "Test 1 (186-190)", words: test1_186_190_words },
        { id: 17, title: "Test 1 (191-195)", words: test1_191_195_words },
        { id: 18, title: "Test 1 (196-200)", words: test1_196_200_words },
        { id: 19, title: "Test 2 (147-150)", words: test2_147_150_words },
        { id: 20, title: "Test 2 (151-157)", words: test2_151_157_words },
        { id: 21, title: "Test 2 (158-167)", words: test2_158_167_words },
        { id: 22, title: "Test 2 (168-175)", words: test2_168_175_words },
        { id: 23, title: "Test 2 (176-185)", words: test2_176_185_words },
        { id: 24, title: "Test 2 (186-195)", words: test2_186_195_words },
        { id: 25, title: "Test 2 (196-200)", words: test2_196_200_words },
    ]
};
