import { VocabItem, VocabularyPart } from '../../types';

const test1_words: VocabItem[] = [
    { word: "Allocate", definition: "phân bổ", example: "" },
    { word: "Collaborate", definition: "hợp tác", example: "" },
    { word: "Contingency", definition: "tình huống bất ngờ", example: "" },
    { word: "Discrepancy", definition: "sự khác biệt, sự không phù hợp", example: "" },
    { word: "Fluctuate", definition: "dao động", example: "" },
    { word: "Hinder", definition: "cản trở", example: "" },
    { word: "Lucrative", definition: "có lợi nhuận, sinh lời", example: "" },
    { word: "Obligation", definition: "nghĩa vụ, trách nhiệm", example: "" },
    { word: "Oversee", definition: "giám sát", example: "" },
    { word: "Precaution", definition: "biện pháp phòng ngừa", example: "" },
    { word: "Rectify", definition: "sửa chữa, điều chỉnh", example: "" },
    { word: "Speculate", definition: "suy đoán, phỏng đoán", example: "" },
    { word: "Streamline", definition: "hợp lý hóa, đơn gian hóa", example: "" },
    { word: "Subsequent", definition: "tiếp theo, sau đó", example: "" },
    { word: "Tentative", definition: "tạm thời, dự kiến, không chắc chắn", example: "" },
    { word: "Terminate", definition: "chấm dứt", example: "" },
    { word: "Unanimous", definition: "nhất trí, đồng tình", example: "" },
    { word: "Verify", definition: "xác minh, kiểm tra", example: "" },
    { word: "Withstand", definition: "chịu đựng, chống lại", example: "" },
    { word: "Yield", definition: "sản xuất, mang lại", example: "" },
    { word: "Amend", definition: "sửa đổi, chỉnh sửa", example: "" },
    { word: "Appraisal", definition: "sự đánh giá, sự thẩm định", example: "" },
    { word: "Attain", definition: "đạt được", example: "" },
    { word: "Authorize", definition: "ủy quyền, cho phép", example: "" },
    { word: "Commence", definition: "bắt đầu", example: "" },
    { word: "Comprehensive", definition: "toàn diện, bao quát", example: "" },
    { word: "Consecutive", definition: "liên tiếp", example: "" },
    { word: "Constitute", definition: "tạo thành, cấu thành", example: "" },
    { word: "Disseminate", definition: "phổ biến, phát tán, lan truyền", example: "" },
    { word: "Enforce", definition: "thi hành, thực thi", example: "" },
    { word: "Entail", definition: "bao gồm, đòi hỏi", example: "" },
    { word: "Expedite", definition: "đẩy nhanh, xúc tiến", example: "" },
    { word: "Fraudulent", definition: "gian lận", example: "" },
    { word: "Incentive", definition: "động lực, sự khuyến khích", example: "" },
    { word: "Overhaul", definition: "cải tiến, đại tu", example: "" },
    { word: "Perishable", definition: "dễ hỏng, dễ hư", example: "" },
    { word: "Prospect", definition: "triển vọng, viễn cảnh", example: "" },
    { word: "Retention", definition: "sự duy trì, giữ lại", example: "" },
    { word: "Subordinate", definition: "cấp dưới, phụ thuộc", example: "" },
    { word: "Proximity", definition: "sự gần gũi, sự tiếp cận", example: "" },
    { word: "Consignment", definition: "hàng gửi bán, việc gửi hàng", example: "" },
    { word: "Gauge", definition: "đo lường, đánh giá", example: "" },
    { word: "Endorsement", definition: "sự chứng thực, sự ủng hộ", example: "" },
    { word: "Liaison", definition: "người liên lạc, mối quan hệ", example: "" },
    { word: "Foreseeable", definition: "có thể thấy trước", example: "" },
    { word: "Liable", definition: "chịu trách nhiệm, có khả năng", example: "" },
    { word: "Redundant", definition: "thừa thãi, không cần thiết", example: "" },
    { word: "Preliminary", definition: "sơ bộ, ban đầu", example: "" },
    { word: "Delegation", definition: "sự ủy thác, sự phân công", example: "" },
    { word: "Arbitrary", definition: "tùy ý, tùy tiện, độc đoán", example: "" },
    { word: "Viable", definition: "khả thi, có thể thực hiện được", example: "" },
    { word: "Scrutiny", definition: "sự xem xét kỹ lưỡng, soi xét", example: "" },
];

const test2_words: VocabItem[] = [
    { word: "Cable", definition: "dây cáp", example: "" },
    { word: "Enclose", definition: "bao gồm, đính kèm", example: "" },
    { word: "Handheld", definition: "cầm tay, nhỏ gọn", example: "" },
    { word: "External", definition: "bên ngoài", example: "" },
    { word: "Charge", definition: "sạc, phí", example: "" },
    { word: "Site", definition: "địa điểm", example: "" },
    { word: "Electrify", definition: "làm điện hóa, gây ấn tượng", example: "" },
    { word: "Vice president", definition: "phó giám đốc", example: "" },
    { word: "Fabric", definition: "vải", example: "" },
    { word: "Go on sale", definition: "được bán ra", example: "" },
    { word: "Elated", definition: "vui mừng, phấn khởi", example: "" },
    { word: "Reliable", definition: "đáng tin cậy", example: "" },
    { word: "Demonstrate", definition: "chứng minh, thể hiện", example: "" },
    { word: "Reimburse", definition: "hoàn trả, bồi thường", example: "" },
    { word: "Patron", definition: "khách hàng, người bảo trợ", example: "" },
    { word: "Payroll", definition: "bảng lương", example: "" },
    { word: "Associated with", definition: "liên quan đến", example: "" },
    { word: "Obscure", definition: "mơ hồ, làm mờ đi", example: "" },
    { word: "Properly", definition: "một cách đúng đắn, phù hợp", example: "" },
    { word: "Matching", definition: "phù hợp, đồng bộ", example: "" },
    { word: "Oak", definition: "cây sồi", example: "" },
    { word: "Appliance", definition: "thiết bị gia dụng", example: "" },
    { word: "Refund", definition: "hoàn tiền", example: "" },
    { word: "Peace of mind", definition: "sự an tâm", example: "" },
    { word: "Stand out", definition: "nổi bật", example: "" },
    { word: "Ongoing", definition: "tiếp tục, đang diễn ra", example: "" },
    { word: "Cost-efficient", definition: "tiết kiệm chi phí", example: "" },
    { word: "Enact", definition: "ban hành, thực hiện", example: "" },
    { word: "Vary", definition: "thay đổi, khác nhau", example: "" },
    { word: "Exclusive", definition: "độc quyền, dành riêng", example: "" },
    { word: "Workmanship", definition: "tay nghề, chất lượng công việc", example: "" },
    { word: "Memorable", definition: "đáng nhớ", example: "" },
    { word: "Far-reaching", definition: "ảnh hưởng rộng lớn, sâu rộng", example: "" },
    { word: "Webinar", definition: "hội thảo trực tuyến", example: "" },
    { word: "Related to", definition: "liên quan đến", example: "" },
    { word: "Workforce", definition: "lực lượng lao động", example: "" },
    { word: "Inquiry", definition: "sự điều tra, yêu cầu thông tin", example: "" },
    { word: "Host", definition: "người dẫn chương trình, tổ chức", example: "" },
    { word: "Facilitator", definition: "người hướng dẫn, người tạo điều kiện", example: "" },
    { word: "Tailor", definition: "thợ may, điều chỉnh", example: "" },
    { word: "Advantage", definition: "lợi thế, ưu điểm", example: "" },
    { word: "Lease", definition: "hợp đồng cho thuê, thuê mướn", example: "" },
    { word: "Property", definition: "tài sản, bất động sản", example: "" },
    { word: "Usage", definition: "sự sử dụng, cách dùng", example: "" },
    { word: "Amenity", definition: "tiện nghi", example: "" },
    { word: "Forward", definition: "hướng về phía trước", example: "" },
    { word: "Custom-built", definition: "xây dựng theo yêu cầu", example: "" },
    { word: "In transit", definition: "đang vận chuyển", example: "" },
    { word: "Outpace", definition: "vượt qua", example: "" },
    { word: "Trigger", definition: "kích hoạt, gây ra", example: "" },
    { word: "Spokesperson", definition: "người phát ngôn", example: "" },
    { word: "Profits", definition: "lợi nhuận", example: "" },
    { word: "Pour", definition: "rót, đổ", example: "" },
    { word: "On hold", definition: "tạm hoãn", example: "" },
    { word: "Behind schedule", definition: "chậm tiến độ", example: "" },
    { word: "Sidewalk", definition: "vỉa hè", example: "" },
    { word: "Outcome", definition: "kết quả, hậu quả", example: "" },
    { word: "Scale", definition: "quy mô, tỷ lệ", example: "" },
    { word: "Texture", definition: "kết cấu, kết cấu bề mặt", example: "" },
    { word: "Bet", definition: "cược, đánh cược", example: "" },
    { word: "With ease", definition: "một cách dễ dàng", example: "" },
    { word: "Initial", definition: "ban đầu", example: "" },
    { word: "Sustainable", definition: "bền vững", example: "" },
    { word: "Itemize", definition: "liệt kê chi tiết", example: "" },
    { word: "Query", definition: "câu hỏi, thắc mắc", example: "" },
    { word: "Boast", definition: "khoe khoang", example: "" },
    { word: "Downside", definition: "nhược điểm, mặt trái", example: "" },
];

const test3_words: VocabItem[] = [
    { word: "Process", definition: "quá trình, tiến trình", example: "" },
    { word: "State", definition: "tuyên bố, phát biểu", example: "" },
    { word: "Dozens of Ns", definition: "hàng tá, rất nhiều", example: "" },
    { word: "Annual", definition: "hàng năm, định kỳ", example: "" },
    { word: "Enforce", definition: "thi hành, thực thi", example: "" },
    { word: "Harm", definition: "gây hại", example: "" },
    { word: "Name tag", definition: "bảng tên", example: "" },
    { word: "Extended", definition: "kéo dài, mở rộng", example: "" },
    { word: "Engine", definition: "động cơ, máy móc", example: "" },
    { word: "Sincerely", definition: "chân thành, thành thật", example: "" },
    { word: "Common", definition: "phổ biến, thông thường", example: "" },
    { word: "Fragile", definition: "dễ vỡ, mỏng manh", example: "" },
    { word: "Accidental", definition: "tình cờ, ngẫu nhiên", example: "" },
    { word: "Orientation", definition: "sự định hướng, giới thiệu", example: "" },
    { word: "Approach", definition: "tiếp cận, đến gần", example: "" },
    { word: "Claim", definition: "yêu cầu, đòi hỏi", example: "" },
    { word: "Outline", definition: "phác thảo, vạch ra", example: "" },
    { word: "Procedure", definition: "thủ tục, quy trình", example: "" },
    { word: "Handbook", definition: "sổ tay, cẩm nang", example: "" },
    { word: "Embark", definition: "bắt đầu, khởi hành", example: "" },
    { word: "Intensely", definition: "một cách mạnh mẽ, quyết liệt", example: "" },
    { word: "Profound", definition: "sâu sắc, thâm thúy", example: "" },
    { word: "Turnover", definition: "doanh thu, sự thay đổi nhân viên", example: "" },
    { word: "Bidder", definition: "người đấu giá, người chào giá", example: "" },
    { word: "In demand", definition: "được yêu cầu, đang cần", example: "" },
    { word: "Needs", definition: "nhu cầu", example: "" },
    { word: "Agent", definition: "đại lý, tác nhân", example: "" },
    { word: "Reside", definition: "cư trú, sinh sống", example: "" },
    { word: "Hard-earned", definition: "kiếm được nhọc nhằn", example: "" },
    { word: "Savings", definition: "tiền tiết kiệm", example: "" },
    { word: "Segment", definition: "phân khúc, đoạn", example: "" },
    { word: "Introduce", definition: "giới thiệu, ra mắt", example: "" },
    { word: "Supplemental", definition: "bổ sung", example: "" },
    { word: "Consult", definition: "sự tư vấn, sự tham khảo", example: "" },
    { word: "In response to", definition: "để đáp lại, phản hồi", example: "" },
    { word: "Aspect", definition: "khía cạnh, mặt", example: "" },
    { word: "Vending machine", definition: "máy bán hàng tự động", example: "" },
    { word: "Wellness", definition: "sức khỏe toàn diện", example: "" },
    { word: "Cost-effective", definition: "hiệu quả về chi phí", example: "" },
    { word: "On hand", definition: "sẵn có, có mặt", example: "" },
    { word: "Alliance", definition: "liên minh, đồng minh", example: "" },
    { word: "Absence", definition: "sự vắng mặt", example: "" },
    { word: "Simplify", definition: "đơn giản hóa, làm dễ dàng", example: "" },
    { word: "Restriction", definition: "sự hạn chế, điều kiện", example: "" },
    { word: "Boarding", definition: "sự lên tàu, lên xe", example: "" },
    { word: "Run out of", definition: "hết, cạn kiệt", example: "" },
    { word: "Pick up", definition: "nhặt lên, đón, tiếp thu", example: "" },
    { word: "Refreshment", definition: "món ăn nhẹ, đồ uống", example: "" },
    { word: "Juggle", definition: "xử lý, xoay sở", example: "" },
    { word: "Payroll", definition: "bảng lương, chi trả lương", example: "" },
    { word: "Take advantage of", definition: "tận dụng, lợi dụng", example: "" },
    { word: "Bookkeeping", definition: "kế toán, ghi sổ", example: "" },
    { word: "Enterprise", definition: "doanh nghiệp, công ty", example: "" },
    { word: "Concierge", definition: "nhân viên hướng dẫn, quản lý dịch vụ", example: "" },
    { word: "Esteemed", definition: "kính trọng, quý trọng", example: "" },
    { word: "Foresight", definition: "sự dự đoán, tầm nhìn xa", example: "" },
    { word: "Viability", definition: "khả năng tồn tại, tính khả thi", example: "" },
    { word: "Bankruptcy", definition: "sự phá sản", example: "" },
    { word: "Under the direction of", definition: "dưới sự chỉ đạo của", example: "" },
    { word: "Sector", definition: "ngành, lĩnh vực", example: "" },
    { word: "Gratifying", definition: "đáng hài lòng, thỏa mãn", example: "" },
    { word: "Employment", definition: "việc làm, sự tuyển dụng", example: "" },
    { word: "Seek", definition: "tìm kiếm, tìm ra", example: "" },
    { word: "Seek to", definition: "cố gắng làm, tìm cách", example: "" },
    { word: "Straightforward", definition: "thẳng thắn, dễ hiểu", example: "" },
    { word: "Top-notch", definition: "xuất sắc, đỉnh cao", example: "" },
    { word: "Responsive", definition: "phản ứng nhanh, nhạy bén", example: "" },
    { word: "Catering", definition: "dịch vụ ăn uống, phục vụ tiệc", example: "" },
    { word: "Adapt", definition: "thích nghi, điều chỉnh", example: "" },
    { word: "Vegetarian", definition: "(người) ăn chay", example: "" },
    { word: "Knowledgeable", definition: "thông thạo, am hiểu", example: "" },
    { word: "In anticipation for", definition: "trong sự mong đợi", example: "" },
    { word: "Inclement", definition: "khắc nghiệt, không thuận lợi", example: "" },
    { word: "Vendor", definition: "nhà cung cấp, người bán hàng", example: "" },
    { word: "Mandatory", definition: "bắt buộc, có tính bắt buộc", example: "" },
    { word: "Frustrated", definition: "thất vọng, bực bội", example: "" },
    { word: "In person", definition: "trực tiếp", example: "" },
    { word: "Switch", definition: "chuyển đổi, thay thế", example: "" },
    { word: "Clunky", definition: "cồng kềnh, khó sử dụng", example: "" },
    { word: "Privacy", definition: "sự riêng tư, quyền riêng tư", example: "" },
    { word: "Prioritize", definition: "ưu tiên", example: "" },
    { word: "In the process of", definition: "trong quá trình", example: "" },
    { word: "Territory", definition: "lãnh thổ, vùng đất", example: "" },
    { word: "Mindful", definition: "chú ý, lưu tâm", example: "" },
    { word: "Delightful", definition: "dễ chịu, thú vị", example: "" },
    { word: "Catch up", definition: "gặp gỡ, trò chuyện để bắt kịp", example: "" },
    { word: "Priced", definition: "có giá, định giá", example: "" },
    { word: "Reasonable", definition: "hợp lý, phải chăng", example: "" },
    { word: "N/A = not applicable", definition: "không áp dụng", example: "" },
    { word: "Incur", definition: "gánh chịu, mắc phải", example: "" },
    { word: "Recipient", definition: "người nhận", example: "" },
    { word: "Morale", definition: "tinh thần, tinh thần đoàn kết", example: "" },
    { word: "Perspective", definition: "quan điểm, góc nhìn", example: "" },
    { word: "Worthwhile", definition: "xứng đáng, đáng giá", example: "" },
    { word: "Implement", definition: "thực hiện, triển khai", example: "" },
    { word: "Condense", definition: "làm đặc lại, rút ngắn", example: "" },
    { word: "Disposable", definition: "dùng một lần, có thể vứt đi", example: "" },
    { word: "Stain", definition: "vết bẩn, làm bẩn", example: "" },
    { word: "Dedicated to", definition: "tận tâm với, cống hiến cho", example: "" },
    { word: "In use", definition: "đang được sử dụng", example: "" },
    { word: "Considerable", definition: "đáng kể, lớn", example: "" },
    { word: "For instance", definition: "ví dụ, chẳng hạn", example: "" },
    { word: "Correspond with", definition: "liên lạc với, trao đổi với", example: "" },
];

const test4_words: VocabItem[] = [
    { word: "End-of-season", definition: "cuối mùa", example: "" },
    { word: "Significant", definition: "quan trọng, đáng kể", example: "" },
    { word: "Remedy", definition: "phương thuốc, cứu chữa", example: "" },
    { word: "Respective", definition: "tương ứng", example: "" },
    { word: "Noticeable", definition: "dễ nhận thấy, rõ ràng", example: "" },
    { word: "Manuscript", definition: "bản thảo", example: "" },
    { word: "Takeover", definition: "sự tiếp quản", example: "" },
    { word: "Streamline", definition: "hợp lý hóa, làm cho đơn giản", example: "" },
    { word: "Janitor", definition: "người lao công", example: "" },
    { word: "Legislator", definition: "nhà lập pháp", example: "" },
    { word: "Infrastructure", definition: "cơ sở hạ tầng", example: "" },
    { word: "Full range of", definition: "đầy đủ, toàn bộ", example: "" },
    { word: "Virtuosic", definition: "tài ba, xuất sắc", example: "" },
    { word: "Orchestra", definition: "dàn nhạc", example: "" },
    { word: "Clerk", definition: "nhân viên văn phòng", example: "" },
    { word: "Lean", definition: "mảnh mai, gầy, nghiêng", example: "" },
    { word: "Constantly", definition: "liên tục, không ngừng", example: "" },
    { word: "Apparel", definition: "trang phục", example: "" },
    { word: "Periodic", definition: "định kỳ, chu kỳ", example: "" },
    { word: "Contingent", definition: "phụ thuộc vào, tình huống", example: "" },
    { word: "Consent", definition: "sự đồng ý, đồng ý", example: "" },
    { word: "Controversy", definition: "tranh cãi, sự bất đồng", example: "" },
    { word: "Evolve", definition: "tiến hóa, phát triển", example: "" },
    { word: "Dismiss", definition: "sa thải, đuổi đi", example: "" },
    { word: "Occupy", definition: "chiếm đóng, cư trú", example: "" },
    { word: "Discard", definition: "vứt bỏ, loại bỏ", example: "" },
    { word: "Convert", definition: "chuyển đổi", example: "" },
    { word: "Landfill", definition: "bãi chôn lấp, rác thải", example: "" },
    { word: "Rewards card", definition: "thẻ thưởng", example: "" },
    { word: "Transaction", definition: "giao dịch", example: "" },
    { word: "Pricing", definition: "định giá, giá cả", example: "" },
    { word: "Detour", definition: "đường vòng, lạc đường", example: "" },
    { word: "Eager", definition: "háo hức, sẵn sàng", example: "" },
    { word: "Verify", definition: "xác minh, kiểm tra", example: "" },
    { word: "Redeem", definition: "đổi lấy, chuộc lại", example: "" },
    { word: "Appeal", definition: "lời kêu gọi, kháng cáo", example: "" },
    { word: "Rewarding", definition: "đáng giá, bổ ích", example: "" },
    { word: "Vary", definition: "thay đổi, biến đổi", example: "" },
    { word: "Irrigation", definition: "sự tưới tiêu", example: "" },
    { word: "Seek", definition: "tìm kiếm", example: "" },
    { word: "Track record", definition: "thành tích, hồ sơ theo dõi", example: "" },
    { word: "Majority", definition: "đa số", example: "" },
    { word: "Honor", definition: "danh dự, tôn vinh", example: "" },
    { word: "Intend to", definition: "có ý định", example: "" },
    { word: "Envelope", definition: "phong bì", example: "" },
    { word: "Wrap up", definition: "hoàn tất, kết thúc", example: "" },
    { word: "On behalf of", definition: "thay mặt", example: "" },
    { word: "Plaque", definition: "bảng tưởng niệm, tấm biển", example: "" },
    { word: "Open-ended", definition: "không có kết thúc rõ ràng", example: "" },
    { word: "Lag time", definition: "thời gian trễ, độ trễ", example: "" },
    { word: "Take up", definition: "bắt đầu, chiếm lĩnh", example: "" },
    { word: "Hospitality", definition: "lòng hiếu khách, sự tiếp đón", example: "" },
    { word: "Housekeeper", definition: "người quản gia", example: "" },
    { word: "Referral", definition: "sự giới thiệu, sự chuyển tiếp", example: "" },
    { word: "Former", definition: "trước đây, cũ", example: "" },
    { word: "Comprehensive", definition: "toàn diện, bao quát", example: "" },
    { word: "Trustworthy", definition: "đáng tin cậy", example: "" },
    { word: "Initial", definition: "ban đầu, khởi đầu", example: "" },
    { word: "Superior", definition: "vượt trội, cao cấp", example: "" },
    { word: "Autograph", definition: "chữ ký, ký tên", example: "" },
    { word: "Afterward", definition: "sau đó, tiếp theo", example: "" },
    { word: "Newcomer", definition: "người mới, tân binh", example: "" },
    { word: "Suspense", definition: "sự hồi hộp, căng thẳng", example: "" },
    { word: "Devoted", definition: "tận tâm, trung thành", example: "" },
    { word: "Loan", definition: "khoản vay, cho vay", example: "" },
    { word: "Scenic", definition: "đẹp, thơ mộng", example: "" },
    { word: "Surpass", definition: "vượt qua", example: "" },
    { word: "Cordially", definition: "nhiệt tình, thân ái", example: "" },
    { word: "Sector", definition: "lĩnh vực, khu vực", example: "" },
    { word: "Cultivate", definition: "trồng trọt, nuôi dưỡng", example: "" },
    { word: "Clarify", definition: "làm rõ, giải thích", example: "" },
    { word: "Wildlife", definition: "động vật hoang dã", example: "" },
    { word: "Observe", definition: "quan sát, theo dõi", example: "" },
    { word: "Pending", definition: "chờ xử lý, chưa giải quyết", example: "" },
    { word: "Emerging", definition: "mới nổi, đang phát triển", example: "" },
    { word: "Reputation", definition: "danh tiếng", example: "" },
    { word: "Compliance", definition: "sự tuân thủ", example: "" },
    { word: "Substantial", definition: "đáng kể, quan trọng", example: "" },
    { word: "Evaluate", definition: "đánh giá", example: "" },
];

const test5_words: VocabItem[] = [
    { word: "Reach", definition: "đạt tới, tiếp cận", example: "" },
    { word: "Catering", definition: "dịch vụ ăn uống", example: "" },
    { word: "Various", definition: "đa dạng", example: "" },
    { word: "Innovative", definition: "sáng tạo, đổi mới", example: "" },
    { word: "Circumstance", definition: "hoàn cảnh, tình huống", example: "" },
    { word: "Outreach", definition: "sự mở rộng, tiếp cận", example: "" },
    { word: "Stream", definition: "dòng, luồng", example: "" },
    { word: "Considerable", definition: "đáng kể, lớn", example: "" },
    { word: "Considerate", definition: "ân cần, chu đáo", example: "" },
    { word: "Permanent", definition: "vĩnh viễn", example: "" },
    { word: "Suitable", definition: "phù hợp", example: "" },
    { word: "Satisfied", definition: "hài lòng", example: "" },
    { word: "Retain", definition: "giữ lại, duy trì", example: "" },
    { word: "Familiarize with", definition: "làm quen với", example: "" },
    { word: "Meet the demand", definition: "đáp ứng nhu cầu", example: "" },
    { word: "Lecture", definition: "bài giảng, diễn thuyết", example: "" },
    { word: "Debate", definition: "cuộc tranh luận", example: "" },
    { word: "Trustee", definition: "người được ủy thác", example: "" },
    { word: "Initiate", definition: "khởi xướng, bắt đầu", example: "" },
    { word: "Initiative", definition: "sáng kiến, chủ động", example: "" },
    { word: "Seek", definition: "tìm kiếm, theo đuổi", example: "" },
    { word: "Filter", definition: "lọc, bộ lọc", example: "" },
    { word: "Diminish", definition: "giảm bớt", example: "" },
    { word: "Signal", definition: "tín hiệu, ra dấu", example: "" },
    { word: "Clogged", definition: "bị tắc nghẽn", example: "" },
    { word: "Pitcher", definition: "bình đựng nước", example: "" },
    { word: "Object", definition: "vật thể, phản đối", example: "" },
    { word: "Commit", definition: "cam kết, ủy thác", example: "" },
    { word: "Authorization", definition: "sự ủy quyền", example: "" },
    { word: "Session", definition: "phiên họp, buổi học", example: "" },
    { word: "Scam", definition: "lừa đảo", example: "" },
    { word: "Cyberattack", definition: "cuộc tấn công mạng", example: "" },
    { word: "Accommodate", definition: "cung cấp chỗ ở, đáp ứng", example: "" },
    { word: "Intranet", definition: "mạng nội bộ", example: "" },
    { word: "Alternative", definition: "thay thế, sự lựa chọn khác", example: "" },
    { word: "Remotely", definition: "từ xa, không trực tiếp", example: "" },
    { word: "Binder", definition: "bìa tài liệu, tập hồ sơ", example: "" },
    { word: "Savings", definition: "tiết kiệm", example: "" },
    { word: "Chequing", definition: "tài khoản séc, tài khoản thanh toán", example: "" },
    { word: "Initial", definition: "ban đầu, khởi đầu", example: "" },
    { word: "Compliance", definition: "sự tuân thủ", example: "" },
    { word: "Payroll", definition: "bảng lương, chi trả lương", example: "" },
    { word: "Burdensome", definition: "gây gánh nặng, khó khăn", example: "" },
    { word: "Oriented", definition: "định hướng, hướng tới", example: "" },
    { word: "Assortment", definition: "sự pha trộn, lựa chọn đa dạng", example: "" },
    { word: "Separate", definition: "tách biệt, phân tách", example: "" },
    { word: "Modest", definition: "khiêm tốn, giản dị", example: "" },
    { word: "Move forward", definition: "tiến lên, tiếp tục", example: "" },
    { word: "Extensive", definition: "rộng rãi, bao quát", example: "" },
    { word: "Archive", definition: "lưu trữ, kho tài liệu", example: "" },
    { word: "Remarks", definition: "lời nhận xét, lời phát biểu", example: "" },
    { word: "Elect", definition: "bầu chọn", example: "" },
    { word: "Back-order", definition: "đơn hàng chưa xử lý", example: "" },
    { word: "Proceed", definition: "tiếp tục, tiến hành", example: "" },
    { word: "Affordable", definition: "phải chăng, giá cả hợp lý", example: "" },
    { word: "Patron", definition: "khách hàng, ân nhân", example: "" },
    { word: "Craft", definition: "nghề thủ công, chế tác", example: "" },
    { word: "Acquire", definition: "đạt được, thu được", example: "" },
    { word: "Supplement", definition: "bổ sung, phụ lục", example: "" },
    { word: "Up-and-coming", definition: "mới nổi, triển vọng", example: "" },
];

const test6_words: VocabItem[] = [
    { word: "Projection", definition: "dự đoán, sự chiếu", example: "" },
    { word: "Commercial", definition: "thương mại, quảng cáo", example: "" },
    { word: "Publication", definition: "ấn phẩm, xuất bản", example: "" },
    { word: "Nominate", definition: "đề cử", example: "" },
    { word: "Boost", definition: "nâng cao, sự thúc đẩy", example: "" },
    { word: "Be able to V", definition: "có khả năng làm gì", example: "" },
    { word: "Be likely to V", definition: "có khả năng làm gì", example: "" },
    { word: "Neutral", definition: "trung lập, không thiên vị", example: "" },
    { word: "Make room for", definition: "tạo chỗ cho", example: "" },
    { word: "Rear", definition: "phía sau, nuôi dưỡng", example: "" },
    { word: "Badge", definition: "huy hiệu", example: "" },
    { word: "Visible", definition: "có thể nhìn thấy", example: "" },
    { word: "Evenly", definition: "đều đặn, đều", example: "" },
    { word: "Exclusive", definition: "độc quyền, riêng biệt", example: "" },
    { word: "Resign", definition: "từ chức", example: "" },
    { word: "Risk", definition: "rủi ro", example: "" },
    { word: "Motivate", definition: "động viên, khuyến khích", example: "" },
    { word: "Adopt", definition: "nhận nuôi, áp dụng", example: "" },
    { word: "Reinforce", definition: "tăng cường", example: "" },
    { word: "Inquire", definition: "hỏi thăm, yêu cầu thông tin", example: "" },
    { word: "Address", definition: "giải quyết, địa chỉ", example: "" },
    { word: "Biography", definition: "tiểu sử", example: "" },
    { word: "Consume", definition: "tiêu thụ, sử dụng", example: "" },
    { word: "Sight", definition: "cảnh, thị lực", example: "" },
    { word: "Imprint", definition: "dấu ấn, in dấu", example: "" },
    { word: "Rationalize", definition: "hợp lý hóa, biện minh", example: "" },
    { word: "Considerate", definition: "ân cần, chu đáo", example: "" },
    { word: "Considerable", definition: "đáng kể, lớn", example: "" },
    { word: "Minus", definition: "trừ đi", example: "" },
    { word: "Ability", definition: "khả năng", example: "" },
    { word: "Craft", definition: "nghề thủ công, chế tác", example: "" },
    { word: "Qualified", definition: "đủ điều kiện", example: "" },
    { word: "Tailor", definition: "may đo, thợ may", example: "" },
    { word: "Focus on", definition: "tập trung vào", example: "" },
    { word: "Overcome", definition: "vượt qua", example: "" },
    { word: "Discouraged", definition: "nản lòng, chán nản", example: "" },
    { word: "Record", definition: "hồ sơ, ghi chép", example: "" },
    { word: "Approximately", definition: "khoảng chừng", example: "" },
    { word: "Actual", definition: "thực sự, thực tế", example: "" },
    { word: "Carrier", definition: "người/vật vận chuyển", example: "" },
    { word: "Upon arrival", definition: "khi đến", example: "" },
    { word: "Furnish", definition: "trang bị nội thất", example: "" },
    { word: "Promptly", definition: "ngay lập tức", example: "" },
    { word: "Be responsible for", definition: "chịu trách nhiệm về", example: "" },
    { word: "Appropriate", definition: "thích hợp, chiếm đoạt", example: "" },
    { word: "Allow SB to V", definition: "cho phép ai làm gì", example: "" },
    { word: "Reliability", definition: "độ tin cậy", example: "" },
    { word: "Typically", definition: "thông thường, điển hình", example: "" },
    { word: "In bulk", definition: "số lượng lớn", example: "" },
    { word: "Initiate", definition: "bắt đầu, khởi xướng", example: "" },
    { word: "Verify", definition: "xác minh", example: "" },
    { word: "Generate", definition: "tạo ra", example: "" },
    { word: "Pleased", definition: "hài lòng", example: "" },
    { word: "Landlord", definition: "chủ nhà", example: "" },
    { word: "Income", definition: "thu nhập", example: "" },
    { word: "Proof", definition: "bằng chứng", example: "" },
    { word: "Entry-level", definition: "cấp độ đầu vào", example: "" },
    { word: "Set SB apart from", definition: "làm nổi bật ai", example: "" },
    { word: "Common", definition: "phổ biến", example: "" },
    { word: "Mock", definition: "giả, chế giễu", example: "" },
    { word: "Occur", definition: "xảy ra", example: "" },
    { word: "Free of charge", definition: "miễn phí", example: "" },
    { word: "Indicate", definition: "chỉ ra", example: "" },
    { word: "Under construction", definition: "đang xây dựng", example: "" },
    { word: "Prospective", definition: "tiềm năng", example: "" },
    { word: "Resident", definition: "cư dân", example: "" },
    { word: "Praise", definition: "khen ngợi", example: "" },
    { word: "Attractive", definition: "hấp dẫn, lôi cuốn", example: "" },
    { word: "Obviously", definition: "rõ ràng, hiển nhiên", example: "" },
    { word: "Prioritize", definition: "ưu tiên", example: "" },
    { word: "Preserve", definition: "bảo tồn, giữ gìn", example: "" },
    { word: "Alternatively", definition: "hoặc là, thay thế", example: "" },
    { word: "Narrative", definition: "câu chuyện, bài tường thuật", example: "" },
    { word: "Steep", definition: "dốc, cao", example: "" },
    { word: "Anticipate", definition: "dự đoán, mong đợi", example: "" },
    { word: "Reputation", definition: "danh tiếng", example: "" },
    { word: "Organized", definition: "có tổ chức, ngăn nắp", example: "" },
    { word: "Compensate", definition: "đền bù", example: "" },
    { word: "Transaction", definition: "giao dịch", example: "" },
    { word: "Simplify", definition: "đơn giản hóa", example: "" },
    { word: "Designate", definition: "chỉ định, bổ nhiệm", example: "" },
    { word: "Exclude", definition: "loại trừ", example: "" },
    { word: "Insight", definition: "sự hiểu biết", example: "" },
    { word: "Memoir", definition: "hồi ký", example: "" },
    { word: "Counselor", definition: "cố vấn, tư vấn viên", example: "" },
    { word: "Shuttle", definition: "xe đưa đón", example: "" },
    { word: "State-of-the-art", definition: "hiện đại nhất, tối tân", example: "" },
    { word: "In response to", definition: "để đáp lại", example: "" },
    { word: "Diploma", definition: "bằng cấp", example: "" },
    { word: "Thoroughly", definition: "hoàn toàn, kỹ lưỡng", example: "" },
    { word: "Sculpture", definition: "tác phẩm điêu khắc", example: "" },
    { word: "Neglect", definition: "sao lãng, bỏ bê", example: "" },
    { word: "Bookkeeper", definition: "nhân viên kế toán", example: "" },
];

const test7_words: VocabItem[] = [
    { word: "boarding pass", definition: "thẻ lên máy bày", example: "" },
    { word: "thankful", definition: "biết ơn", example: "" },
    { word: "crew", definition: "đội, nhóm làm việc", example: "" },
    { word: "panel", definition: "hội đồng, bảng điều khiển", example: "" },
    { word: "expertise", definition: "chuyên môn, kỹ năng sâu", example: "" },
    { word: "approach", definition: "phương pháp, tiếp cận", example: "" },
    { word: "executive", definition: "giám đốc điều hành", example: "" },
    { word: "counsel", definition: "tư vấn, lời khuyên", example: "" },
    { word: "measure", definition: "biện pháp, đo lường", example: "" },
    { word: "grounds", definition: "lý do, cơ sở", example: "" },
    { word: "reasonable", definition: "hợp lý, phải chăng", example: "" },
    { word: "eager", definition: "háo hức, sẵn lòng", example: "" },
    { word: "anticipate", definition: "dự đoán, trông đợi", example: "" },
    { word: "pickup truck", definition: "xe bán tải", example: "" },
    { word: "sharply", definition: "mạnh mẽ, đột ngột", example: "" },
    { word: "post", definition: "bài đăng, đăng tải", example: "" },
    { word: "broaden", definition: "mở rộng, làm phong phú", example: "" },
    { word: "extensive", definition: "rộng rãi, toàn diện", example: "" },
    { word: "commercial", definition: "liên quan đến thương mại", example: "" },
    { word: "accurate", definition: "chính xác", example: "" },
    { word: "intersection", definition: "giao lộ, ngã tư", example: "" },
    { word: "shorten", definition: "rút ngắn, thu gọn", example: "" },
    { word: "pedestrian", definition: "người đi bộ", example: "" },
    { word: "impose on", definition: "áp đặt, bắt buộc", example: "" },
    { word: "remotely", definition: "từ xa, ở xa", example: "" },
    { word: "brighten", definition: "làm sáng, làm tươi tắn", example: "" },
    { word: "refrain from", definition: "kiềm chế, tránh làm gì", example: "" },
    { word: "retreat", definition: "rút lui, buổi nghỉ dưỡng", example: "" },
    { word: "signature", definition: "chữ ký, dấu hiệu đặc trưng", example: "" },
    { word: "fertilizer", definition: "phân bón", example: "" },
    { word: "dramatically", definition: "đột ngột, đáng kể", example: "" },
    { word: "in recognition of", definition: "ghi nhận, tôn vinh", example: "" },
    { word: "dedicate", definition: "cống hiến, dành cho", example: "" },
    { word: "repetitious", definition: "lặp đi lặp lại", example: "" },
    { word: "initiate", definition: "khởi xướng, bắt đầu", example: "" },
    { word: "initiative", definition: "sáng kiến", example: "" },
    { word: "exclusive", definition: "độc quyền, riêng biệt", example: "" },
    { word: "credential", definition: "thông tin xác thực, chứng chỉ", example: "" },
    { word: "move ahead with", definition: "tiến hành, tiếp tục", example: "" },
    { word: "pay rate", definition: "mức lương", example: "" },
    { word: "coordinator", definition: "điều phối viên", example: "" },
    { word: "consequently", definition: "do đó, vì vậy", example: "" },
    { word: "internal", definition: "bên trong, nội bộ", example: "" },
    { word: "authorization", definition: "sự cho phép, sự phê duyệt", example: "" },
    { word: "deal", definition: "giải quyết, xử lý", example: "" },
    { word: "demonstration", definition: "sự trình bày, minh họa", example: "" },
    { word: "renovate", definition: "cải tạo, sửa chữa", example: "" },
    { word: "merely", definition: "chỉ, đơn thuần", example: "" },
    { word: "maintenance", definition: "sự bảo trì, bảo dưỡng", example: "" },
    { word: "lane", definition: "làn đường", example: "" },
    { word: "alternate", definition: "luân phiên, xen kẽ", example: "" },
    { word: "refer", definition: "tham khảo, giới thiệu", example: "" },
    { word: "enclose", definition: "đính kèm, bao quanh", example: "" },
    { word: "signage", definition: "biển báo, bảng hiệu", example: "" },
    { word: "planetarium", definition: "cung thiên văn", example: "" },
    { word: "underway", definition: "đang tiến hành", example: "" },
    { word: "complex", definition: "phức tạp", example: "" },
    { word: "public", definition: "công cộng, công khai", example: "" },
    { word: "attraction", definition: "điểm hấp dẫn, điểm tham quan", example: "" },
    { word: "projection", definition: "sự dự đoán, hình chiếu", example: "" },
    { word: "interact", definition: "tương tác", example: "" },
    { word: "trail", definition: "đường mòn, dấu vết", example: "" },
    { word: "elevator", definition: "thang máy", example: "" },
    { word: "resident", definition: "cư dân", example: "" },
    { word: "stairwell", definition: "cầu thang bộ, giếng thang", example: "" },
    { word: "cuisine", definition: "ẩm thực", example: "" },
    { word: "complimentary", definition: "miễn phí, tặng kèm", example: "" },
    { word: "valid", definition: "hợp lệ", example: "" },
    { word: "appetizer", definition: "món khai vị", example: "" },
    { word: "platter", definition: "đĩa lớn, mâm", example: "" },
    { word: "in writing", definition: "bằng văn bản", example: "" },
    { word: "switch", definition: "đổi, thay thế", example: "" },
    { word: "malfunction", definition: "sự trục trặc, lỗi", example: "" },
    { word: "postpone", definition: "hoãn lại", example: "" },
    { word: "fulfill", definition: "hoàn thành, đáp ứng", example: "" },
    { word: "frustrated", definition: "thất vọng, bực bội", example: "" },
    { word: "review", definition: "xem xét, đánh giá", example: "" },
    { word: "up-to-date", definition: "cập nhật", example: "" },
    { word: "primary", definition: "chính, chủ yếu", example: "" },
    { word: "enroll in", definition: "ghi danh, đăng ký", example: "" },
    { word: "branch", definition: "chi nhánh, nhánh cây", example: "" },
    { word: "inquire", definition: "hỏi thăm, tìm hiểu", example: "" },
    { word: "deposit", definition: "tiền cọc, khoản ký gửi", example: "" },
    { word: "wood crafting", definition: "nghề làm đồ gỗ", example: "" },
    { word: "personalize", definition: "cá nhân hóa", example: "" },
    { word: "seek", definition: "tìm kiếm", example: "" },
    { word: "seek to + V", definition: "cố gắng làm gì", example: "" },
    { word: "solid wood", definition: "gỗ nguyên khối", example: "" },
    { word: "mass-produced", definition: "sản xuất hàng loạt", example: "" },
    { word: "agreeable", definition: "dễ chịu, dễ thương", example: "" },
    { word: "skillful", definition: "khéo léo, tài giỏi", example: "" },
    { word: "assembly", definition: "sự lắp ráp, hội đồng", example: "" },
    { word: "exceptional", definition: "đặc biệt, nổi bật", example: "" },
    { word: "take up to", definition: "mất tối đa", example: "" },
    { word: "workshop", definition: "hội thảo, xưởng", example: "" },
    { word: "artisan", definition: "nghệ nhân", example: "" },
    { word: "biography", definition: "tiểu sử", example: "" },
    { word: "instability", definition: "sự bất ổn", example: "" },
    { word: "raw", definition: "thô, chưa chế biến", example: "" },
    { word: "surpass", definition: "vượt qua, vượt trội", example: "" },
    { word: "respective", definition: "tương ứng", example: "" },
    { word: "represent", definition: "đại diện", example: "" },
    { word: "processed food", definition: "thực phẩm chế biến", example: "" },
    { word: "volatility", definition: "đáng kể, đột ngột", example: "" },
    { word: "moderate", definition: "vừa phải", example: "" },
    { word: "forecast", definition: "dự báo", example: "" },
    { word: "illustrate", definition: "minh họa", example: "" },
    { word: "impact", definition: "sự ảnh hưởng, tác động", example: "" },
    { word: "staffing", definition: "bố trí nhân sự", example: "" },
    { word: "attendee", definition: "người tham dự", example: "" },
    { word: "encourage", definition: "khuyến khích", example: "" },
    { word: "transfer", definition: "chuyển", example: "" },
    { word: "manual", definition: "thủ công, sách hướng dẫn", example: "" },
    { word: "proper", definition: "đúng, thích hợp", example: "" },
    { word: "misleading", definition: "gây hiểu lầm", example: "" },
    { word: "compatible", definition: "tương thích", example: "" },
    { word: "in person", definition: "trực tiếp", example: "" },
    { word: "manual", definition: "sách hướng dẫn", example: "" },
    { word: "impact", definition: "ảnh hưởng, tác động", example: "" },
    { word: "forecast", definition: "dự báo", example: "" },
    { word: "moderate", definition: "làm dịu đi, điều chỉnh", example: "" },
    { word: "properly", definition: "một cách đúng đắn", example: "" },
    { word: "verify", definition: "xác minh, kiểm tra", example: "" },
    { word: "statement", definition: "tuyên bố, bản sao kê", example: "" },
    { word: "adjust", definition: "điều chỉnh", example: "" },
    { word: "documentation", definition: "tài liệu", example: "" },
    { word: "separate", definition: "riêng biệt, khác nhau", example: "" },
    { word: "thorough", definition: "kỹ lưỡng, cẩn thận", example: "" },
    { word: "beverage", definition: "đồ uống", example: "" },
    { word: "prior to", definition: "trước khi", example: "" },
    { word: "be subject to", definition: "chịu, phải tuân theo", example: "" },
    { word: "shuttle", definition: "đưa đón, di chuyển qua lại", example: "" },
    { word: "in order", definition: "để, nhằm", example: "" },
    { word: "reimburse", definition: "hoàn lại, bồi hoàn", example: "" },
    { word: "appreciate", definition: "đánh giá cao, cảm kích", example: "" },
    { word: "reputation", definition: "danh tiếng, uy tín", example: "" },
    { word: "interior", definition: "bên trong, nội thất", example: "" },
    { word: "suitable", definition: "phù hợp", example: "" },
    { word: "whether", definition: "liệu rằng, có hay không", example: "" },
    { word: "budget", definition: "ngân sách", example: "" },
    { word: "budget", definition: "lên ngân sách", example: "" },
    { word: "scheme", definition: "kế hoạch, đề án", example: "" },
    { word: "scheme", definition: "lên kế hoạch (mưu mẹo)", example: "" },
    { word: "incorporate", definition: "kết hợp", example: "" },
    { word: "sculpture", definition: "tác phẩm điêu khắc", example: "" },
    { word: "perspective", definition: "góc nhìn, quan điểm", example: "" },
    { word: "tailor", definition: "may đo", example: "" },
    { word: "determine", definition: "xác định, quyết định", example: "" },
    { word: "priority", definition: "ưu tiên", example: "" },
    { word: "simplify", definition: "đơn giản hóa", example: "" },
    { word: "administer", definition: "quản lý, cung cấp", example: "" },
    { word: "landfill", definition: "bãi rác", example: "" },
    { word: "chairperson", definition: "chủ tịch", example: "" },
    { word: "squeeze", definition: "sự ép, vắt, tình trạng eo hẹp", example: "" },
    { word: "facility", definition: "cơ sở vật chất", example: "" },
    { word: "stringent", definition: "nghiêm ngặt", example: "" },
    { word: "anonymous", definition: "ẩn danh", example: "" },
    { word: "acknowledge", definition: "thừa nhận, xác nhận", example: "" },
    { word: "newsletter", definition: "bản tin", example: "" },
    { word: "inventory", definition: "hàng tồn kho", example: "" },
    { word: "recruit", definition: "nhân viên mới", example: "" },
    { word: "optician", definition: "chuyên gia đo mắt, bán kính", example: "" },
    { word: "awareness of", definition: "nhận thức về", example: "" },
    { word: "steer", definition: "điều hướng, chỉ đạo", example: "" },
    { word: "vending machine", definition: "máy bán hàng tự động", example: "" },
    { word: "accommodate", definition: "cung cấp chỗ ở, đáp ứng", example: "" },
];

const test8_words: VocabItem[] = [
    { word: "Belongings", definition: "đồ dùng cá nhân, cảm giác thuộc về", example: "" },
    { word: "Sight", definition: "cảnh tượng, tầm nhìn", example: "" },
    { word: "Fold", definition: "gấp, nếp gấp", example: "" },
    { word: "Neat", definition: "gọn gàng, ngăn nắp", example: "" },
    { word: "Restrict", definition: "hạn chế", example: "" },
    { word: "Facility", definition: "cơ sở vật chất", example: "" },
    { word: "Nationwide", definition: "trên toàn quốc", example: "" },
    { word: "Cashier", definition: "nhân viên thu ngân", example: "" },
    { word: "Take on", definition: "đảm nhận, nhận trách nhiệm", example: "" },
    { word: "Take over", definition: "tiếp quản", example: "" },
    { word: "Role", definition: "vai trò", example: "" },
    { word: "Session", definition: "buổi họp, phiên", example: "" },
    { word: "Prevent", definition: "ngăn chặn", example: "" },
    { word: "Scorch", definition: "làm cháy sém, cháy nắng", example: "" },
    { word: "Spread", definition: "lan rộng, sự lan tỏa", example: "" },
    { word: "Mine", definition: "mỏ, khai thác mỏ", example: "" },
    { word: "Mineral-rich", definition: "giàu khoáng chất", example: "" },
    { word: "Spring", definition: "suối nước nóng", example: "" },
    { word: "Bid", definition: "đấu thầu, giá thầu", example: "" },
    { word: "Garment", definition: "quần áo", example: "" },
    { word: "Portion", definition: "phần, chia ra", example: "" },
    { word: "Specialist", definition: "chuyên gia", example: "" },
    { word: "Discard", definition: "vứt bỏ", example: "" },
    { word: "Typically", definition: "điển hình, thông thường", example: "" },
    { word: "Furnace", definition: "lò sưởi, lò nung", example: "" },
    { word: "Boost", definition: "thúc đẩy, sự tăng cường", example: "" },
    { word: "Guarantee", definition: "bảo đảm, sự bảo đảm", example: "" },
    { word: "Expire", definition: "hết hạn, hết hiệu lực", example: "" },
    { word: "Contractor", definition: "nhà thầu", example: "" },
    { word: "Result from", definition: "do, là kết quả của", example: "" },
    { word: "Result in", definition: "dẫn đến, gây ra", example: "" },
    { word: "As if", definition: "như thể, dường như", example: "" },
    { word: "Author", definition: "tác giả, viết", example: "" },
    { word: "Joint", definition: "khớp, chung", example: "" },
    { word: "Admission", definition: "sự vào cửa, sự thú nhận", example: "" },
    { word: "Capable", definition: "có khả năng", example: "" },
    { word: "Dense", definition: "dày đặc, đông đúc", example: "" },
    { word: "Absent", definition: "vắng mặt", example: "" },
    { word: "Proprietary", definition: "thuộc quyền sở hữu", example: "" },
    { word: "Compound", definition: "hợp chất, pha trộn", example: "" },
    { word: "Affiliation", definition: "sự liên kết", example: "" },
    { word: "Lightly", definition: "nhẹ nhàng, một cách nhẹ", example: "" },
    { word: "Find oneself", definition: "rơi vào tình huống nào đó", example: "" },
    { word: "Essential", definition: "cần thiết; yếu tố cần thiết", example: "" },
    { word: "Competent", definition: "có năng lực", example: "" },
    { word: "Offerings", definition: "các sản phẩm, dịch vụ được cung cấp", example: "" },
    { word: "Keep up with", definition: "theo kịp", example: "" },
    { word: "Substantially", definition: "đáng kể, lớn lao", example: "" },
    { word: "Pastry", definition: "bánh ngọt, bột bánh", example: "" },
    { word: "Take place", definition: "diễn ra", example: "" },
    { word: "Smooth", definition: "mượt mà, làm mịn", example: "" },
    { word: "Insurance", definition: "bảo hiểm", example: "" },
    { word: "Acquire", definition: "đạt được, mua lại", example: "" },
    { word: "Reflect", definition: "phản ánh, phản chiếu", example: "" },
    { word: "Business partner", definition: "đối tác kinh doanh", example: "" },
    { word: "Stakeholder", definition: "bên liên quan", example: "" },
    { word: "Enable SB to V", definition: "giúp ai có thể làm gì", example: "" },
    { word: "Meet the needs", definition: "đáp ứng nhu cầu", example: "" },
    { word: "Short-term", definition: "ngắn hạn", example: "" },
    { word: "Supplement", definition: "bổ sung, phụ thêm", example: "" },
    { word: "Cereal", definition: "ngũ cốc", example: "" },
    { word: "Wellness", definition: "sức khỏe toàn diện", example: "" },
    { word: "Consumer", definition: "người tiêu dùng", example: "" },
    { word: "Advertise", definition: "quảng cáo", example: "" },
    { word: "Terrace", definition: "sân thượng, sân hiên", example: "" },
    { word: "Host", definition: "người chủ trì, tổ chức", example: "" },
    { word: "Spacious", definition: "rộng rãi", example: "" },
    { word: "Retreat", definition: "sự lui lại, nơi ẩn náu", example: "" },
    { word: "Picturesque", definition: "đẹp như tranh vẽ", example: "" },
    { word: "Bonding", definition: "sự gắn kết, mối quan hệ", example: "" },
    { word: "Gourmet", definition: "tinh tế, cao cấp", example: "" },
    { word: "Take advantage of", definition: "tận dụng, lợi dụng", example: "" },
    { word: "Advantage", definition: "lợi thế, ưu thế", example: "" },
    { word: "Catering", definition: "dịch vụ ăn uống", example: "" },
    { word: "Seaside", definition: "bờ biển, gần biển", example: "" },
    { word: "Individual", definition: "cá nhân, riêng biệt", example: "" },
    { word: "Interaction", definition: "sự tương tác", example: "" },
    { word: "Insert", definition: "chèn vào, sự chèn vào", example: "" },
    { word: "Packing slip", definition: "phiếu đóng gói", example: "" },
    { word: "Magnet", definition: "nam châm", example: "" },
    { word: "Property", definition: "tài sản, bất động sản", example: "" },
    { word: "Enhance", definition: "nâng cao, cải thiện", example: "" },
    { word: "Overview", definition: "cái nhìn tổng quan", example: "" },
    { word: "Landscape", definition: "cảnh quan, phong cảnh", example: "" },
    { word: "Groundskeeping", definition: "công việc chăm sóc đất đai", example: "" },
    { word: "Utility", definition: "tiện ích, công cụ hữu ích", example: "" },
    { word: "Amusement park", definition: "công viên giải trí", example: "" },
    { word: "Contest", definition: "cuộc thi, tranh giành", example: "" },
    { word: "Chemicals", definition: "hóa chất", example: "" },
    { word: "Manual", definition: "thủ công, sách hướng dẫn", example: "" },
    { word: "Prerequisite", definition: "yêu cầu tiên quyết", example: "" },
    { word: "Mandatory", definition: "bắt buộc", example: "" },
    { word: "Goggles", definition: "kính bảo hộ", example: "" },
    { word: "Direction", definition: "hướng, sự chỉ đạo", example: "" },
    { word: "Fire extinguisher", definition: "bình chữa cháy", example: "" },
    { word: "Refrain from", definition: "kiềm chế, tránh làm gì", example: "" },
    { word: "Obtain", definition: "đạt được, có được", example: "" },
    { word: "Malfunction", definition: "sự cố, trục trặc", example: "" },
    { word: "Stabilize", definition: "ổn định", example: "" },
    { word: "Encounter", definition: "gặp phải, cuộc gặp gỡ", example: "" },
    { word: "Attempt", definition: "sự cố gắng, thử làm", example: "" },
    { word: "Projector", definition: "máy chiếu", example: "" },
    { word: "Procedure", definition: "thủ tục, quy trình", example: "" },
    { word: "Orientation", definition: "định hướng, buổi giới thiệu", example: "" },
    { word: "Alert", definition: "cảnh báo, tỉnh táo", example: "" },
    { word: "Appropriate", definition: "thích hợp", example: "" },
    { word: "Extreme", definition: "cực kỳ, khắc nghiệt", example: "" },
    { word: "Retain", definition: "giữ lại", example: "" },
    { word: "Durability", definition: "độ bền", example: "" },
    { word: "Pleased", definition: "hài lòng, vui mừng", example: "" },
    { word: "Object", definition: "vật thể, đối tượng", example: "" },
    { word: "Permanent", definition: "vĩnh viễn, lâu dài", example: "" },
    { word: "Curator", definition: "người quản lý, người phụ trách", example: "" },
    { word: "Reveal", definition: "tiết lộ, phơi bày", example: "" },
    { word: "Sponsor", definition: "nhà tài trợ, tài trợ", example: "" },
    { word: "Perspective", definition: "quan điểm, góc nhìn", example: "" },
    { word: "Argue", definition: "tranh luận, biện luận", example: "" },
    { word: "Sandwich", definition: "bánh mì kẹp, sandwich", example: "" },
    { word: "Flat", definition: "phẳng, căn hộ", example: "" },
    { word: "Complimentary", definition: "miễn phí, khen ngợi", example: "" },
    { word: "Input", definition: "đầu vào, sự đóng góp", example: "" },
    { word: "Favorable", definition: "thuận lợi, tốt đẹp", example: "" },
    { word: "Trail", definition: "đường mòn, vệt", example: "" },
    { word: "Permit", definition: "giấy phép, cho phép", example: "" },
    { word: "Boast", definition: "khoe khoang, sự khoe khoang", example: "" },
    { word: "Amenity", definition: "tiện nghi, cơ sở vật chất", example: "" },
    { word: "Expert", definition: "chuyên gia, thành thạo", example: "" },
    { word: "Brief", definition: "ngắn gọn, tóm tắt", example: "" },
];

const test9_words: VocabItem[] = [
    { word: "Dispute", definition: "tranh chấp, tranh luận", example: "" },
    { word: "Calm", definition: "bình tĩnh, làm dịu", example: "" },
    { word: "Maintain", definition: "duy trì, bảo dưỡng", example: "" },
    { word: "Divide", definition: "chia, chia cắt", example: "" },
    { word: "Play", definition: "vở kịch", example: "" },
    { word: "Musical", definition: "nhạc kịch", example: "" },
    { word: "Remaining", definition: "còn lại", example: "" },
    { word: "Expense", definition: "chi phí", example: "" },
    { word: "Associate", definition: "liên kết, đồng nghiệp", example: "" },
    { word: "Outcome", definition: "kết quả", example: "" },
    { word: "Clinic", definition: "phòng khám", example: "" },
    { word: "Isolate", definition: "cô lập, cách ly", example: "" },
    { word: "Primary", definition: "chính, cơ bản", example: "" },
    { word: "Skillful", definition: "khéo léo, tài giỏi", example: "" },
    { word: "Complicated", definition: "phức tạp", example: "" },
    { word: "Theory", definition: "lý thuyết", example: "" },
    { word: "Folk story", definition: "truyện dân gian", example: "" },
    { word: "Flock", definition: "đàn (chim, cừu), tụ tập", example: "" },
    { word: "Initial", definition: "ban đầu, chữ cái đầu", example: "" },
    { word: "Assembly", definition: "cuộc họp, sự lắp ráp", example: "" },
    { word: "Distinct", definition: "riêng biệt, rõ ràng", example: "" },
    { word: "Eligible", definition: "đủ điều kiện", example: "" },
    { word: "Handout", definition: "tài liệu phát tay", example: "" },
    { word: "Seminar", definition: "hội thảo", example: "" },
    { word: "Determine", definition: "xác định, quyết định", example: "" },
    { word: "Accountable", definition: "chịu trách nhiệm", example: "" },
    { word: "Knowledgeable", definition: "am hiểu, có kiến thức", example: "" },
    { word: "Express stop", definition: "trạm dừng nhanh", example: "" },
    { word: "Praise", definition: "khen ngợi, lời khen", example: "" },
    { word: "Agent", definition: "đại lý, tác nhân", example: "" },
    { word: "Indicate", definition: "chỉ ra, biểu thị", example: "" },
    { word: "Revolutionize", definition: "cách mạng hóa", example: "" },
    { word: "Retain", definition: "giữ lại, duy trì", example: "" },
    { word: "Memorable", definition: "đáng nhớ", example: "" },
    { word: "Seamless", definition: "liền mạch", example: "" },
    { word: "Factual", definition: "thực tế, dựa trên sự thật", example: "" },
    { word: "Collective", definition: "tập thể, chung", example: "" },
    { word: "Take advantage of", definition: "tận dụng", example: "" },
    { word: "Exclusive", definition: "độc quyền, riêng biệt", example: "" },
    { word: "Lounge", definition: "phòng chờ", example: "" },
    { word: "Flight attendant", definition: "tiếp viên hàng không", example: "" },
    { word: "Priority", definition: "sự ưu tiên", example: "" },
    { word: "Minimal", definition: "tối thiểu", example: "" },
    { word: "Producer", definition: "nhà sản xuất", example: "" },
    { word: "Relation", definition: "mối quan hệ", example: "" },
    { word: "Responsive", definition: "phản ứng nhanh", example: "" },
    { word: "Responsible", definition: "chịu trách nhiệm", example: "" },
    { word: "Hire", definition: "người được thuê", example: "" },
    { word: "Mark", definition: "đánh dấu, dấu vết", example: "" },
    { word: "Stitch", definition: "mũi khâu, khâu", example: "" },
    { word: "Eager", definition: "háo hức, hăm hở", example: "" },
    { word: "Seamstress", definition: "thợ may nữ", example: "" },
    { word: "Fulfill", definition: "hoàn thành, đáp ứng", example: "" },
    { word: "Opt", definition: "chọn", example: "" },
    { word: "Personalization", definition: "cá nhân hóa", example: "" },
    { word: "Absence", definition: "sự vắng mặt", example: "" },
    { word: "Compensate", definition: "đền bù", example: "" },
    { word: "Appreciate", definition: "cảm kích, đánh giá cao", example: "" },
    { word: "Initial", definition: "chữ cái đầu", example: "" },
    { word: "Hybrid", definition: "lai, hỗn hợp", example: "" },
    { word: "Achieve", definition: "đạt được", example: "" },
    { word: "Capacity", definition: "sức chứa, năng lực", example: "" },
    { word: "Emission", definition: "sự phát thải", example: "" },
    { word: "Combine", definition: "kết hợp", example: "" },
    { word: "Recipe", definition: "công thức nấu ăn", example: "" },
    { word: "Certified", definition: "được chứng nhận", example: "" },
    { word: "Demonstrate", definition: "trình bày, minh họa", example: "" },
    { word: "Challenging", definition: "đầy thử thách", example: "" },
    { word: "Motivate", definition: "thúc đẩy", example: "" },
    { word: "Former", definition: "trước đây", example: "" },
    { word: "Front desk", definition: "bàn tiếp tân", example: "" },
    { word: "Switch", definition: "đổi, công tắc", example: "" },
    { word: "Shift", definition: "ca làm việc, thay đổi", example: "" },
    { word: "Bustling", definition: "nhộn nhịp", example: "" },
    { word: "Do a favor", definition: "giúp đỡ ai", example: "" },
    { word: "Offerings", definition: "vật phẩm, sản phẩm", example: "" },
    { word: "Continent", definition: "lục địa", example: "" },
    { word: "Compete", definition: "cạnh tranh", example: "" },
    { word: "Vulnerable", definition: "dễ tổn thương", example: "" },
    { word: "Freight", definition: "hàng hóa vận chuyển", example: "" },
    { word: "Acquire", definition: "đạt được, mua lại", example: "" },
    { word: "Clerk", definition: "nhân viên bán hàng", example: "" },
    { word: "Institute", definition: "học viện, thiết lập", example: "" },
    { word: "Wish SB well", definition: "chúc ai điều tốt đẹp", example: "" },
    { word: "Assemble", definition: "lắp ráp, tập hợp", example: "" },
    { word: "Reach out", definition: "liên hệ, tiếp cận", example: "" },
    { word: "Ability", definition: "khả năng", example: "" },
    { word: "Collaborate", definition: "hợp tác", example: "" },
    { word: "Familiar with", definition: "quen thuộc với", example: "" },
    { word: "Comfort", definition: "sự thoải mái, an ủi", example: "" },
    { word: "Independent", definition: "độc lập", example: "" },
    { word: "Dependable", definition: "đáng tin cậy", example: "" },
    { word: "Entrance", definition: "lối vào", example: "" },
    { word: "Tailor", definition: "điều chỉnh, may đo", example: "" },
    { word: "Guideline", definition: "hướng dẫn", example: "" },
    { word: "Journalist", definition: "nhà báo", example: "" },
    { word: "Mindful", definition: "để tâm, lưu ý", example: "" },
    { word: "Impressive", definition: "ấn tượng", example: "" },
    { word: "Vital", definition: "quan trọng, sống còn", example: "" },
    { word: "Attach", definition: "đính kèm", example: "" },
    { word: "On timing", definition: "về thời gian", example: "" },
    { word: "Conduct", definition: "thực hiện, hạnh kiểm", example: "" },
    { word: "Facility", definition: "cơ sở, tiện nghi", example: "" },
    { word: "Procedure", definition: "quy trình", example: "" },
    { word: "Gear", definition: "thiết bị, điều chỉnh", example: "" },
    { word: "Adapt", definition: "thích nghi, điều chỉnh", example: "" },
    { word: "Accommodate", definition: "cung cấp chỗ ở, đáp ứng", example: "" },
    { word: "Restriction", definition: "sự hạn chế", example: "" },
    { word: "Arise", definition: "nảy sinh, phát sinh", example: "" },
    { word: "Pleasant", definition: "dễ chịu", example: "" },
    { word: "Mural", definition: "tranh tường", example: "" },
    { word: "Accommodation", definition: "chỗ ở", example: "" },
    { word: "Convention", definition: "hội nghị, quy ước", example: "" },
    { word: "Lean toward", definition: "nghiêng về, ủng hộ", example: "" },
    { word: "Settle into", definition: "ổn định", example: "" },
    { word: "Quaint", definition: "cổ kính, độc đáo", example: "" },
    { word: "Networking", definition: "kết nối mạng, xây dựng mối quan hệ", example: "" },
    { word: "Socialize", definition: "giao lưu, hòa nhập", example: "" },
    { word: "Occasion", definition: "dịp, cơ hội", example: "" },
    { word: "Goer", definition: "người tham dự", example: "" },
    { word: "Reception", definition: "tiệc chiêu đãi, sự đón tiếp", example: "" },
    { word: "Catch up", definition: "bắt kịp", example: "" },
    { word: "Attractions", definition: "điểm tham quan, sự hấp dẫn", example: "" },
    { word: "Due", definition: "đến hạn, thích hợp", example: "" },
    { word: "Sediment", definition: "trầm tích", example: "" },
    { word: "Discoloration", definition: "sự đổi màu", example: "" },
    { word: "In the process", definition: "trong quá trình", example: "" },
    { word: "Faucet", definition: "vòi nước", example: "" },
    { word: "Harmful", definition: "gây hại", example: "" },
    { word: "Occur", definition: "xảy ra", example: "" },
    { word: "Hesitate", definition: "do dự", example: "" },
    { word: "Alert", definition: "cảnh giác, thông báo", example: "" },
    { word: "Measure", definition: "biện pháp, đo lường", example: "" },
    { word: "Naturally", definition: "một cách tự nhiên", example: "" },
];

const test10_words: VocabItem[] = [
    { word: "Sizable", definition: "đáng kể, khá lớn", example: "" },
    { word: "Strict", definition: "nghiêm ngặt", example: "" },
    { word: "Lead", definition: "dẫn dắt", example: "" },
    { word: "Relation", definition: "mối quan hệ", example: "" },
    { word: "Value", definition: "đánh giá cao, coi trọng", example: "" },
    { word: "Lift", definition: "nâng, nhấc", example: "" },
    { word: "Prescription", definition: "đơn thuốc", example: "" },
    { word: "Surround", definition: "bao quanh", example: "" },
    { word: "Water station", definition: "trạm cấp nước", example: "" },
    { word: "Route", definition: "tuyến đường, lộ trình", example: "" },
    { word: "Scenic", definition: "có cảnh đẹp", example: "" },
    { word: "Charity", definition: "tổ chức từ thiện", example: "" },
    { word: "Chart", definition: "biểu đồ, lập biểu đồ", example: "" },
    { word: "Material", definition: "nguyên liệu, vật liệu", example: "" },
    { word: "Deal with", definition: "xử lý, giải quyết", example: "" },
    { word: "Excess", definition: "sự dư thừa, vượt quá", example: "" },
    { word: "Inventory", definition: "hàng tồn kho", example: "" },
    { word: "Consist of", definition: "bao gồm", example: "" },
    { word: "Advocate", definition: "người ủng hộ, ủng hộ", example: "" },
    { word: "Reform", definition: "cải cách, cải thiện", example: "" },
    { word: "Oversee", definition: "giám sát", example: "" },
    { word: "Franchise", definition: "nhượng quyền thương mại", example: "" },
    { word: "Abundant", definition: "phong phú, dồi dào", example: "" },
    { word: "Momentary", definition: "thoáng qua, tạm thời", example: "" },
    { word: "Protocol", definition: "giao thức, quy tắc", example: "" },
    { word: "Enhance", definition: "nâng cao, cải thiện", example: "" },
    { word: "Greet", definition: "chào hỏi", example: "" },
    { word: "Chaotic", definition: "hỗn loạn", example: "" },
    { word: "Magnetic", definition: "có từ tính, cuốn hút", example: "" },
    { word: "Substantial", definition: "đáng kể, quan trọng", example: "" },
    { word: "Refer", definition: "tham khảo, nhắc đến", example: "" },
    { word: "Elect", definition: "bầu chọn", example: "" },
    { word: "Solicit", definition: "kêu gọi, thu hút", example: "" },
    { word: "Supplement", definition: "bổ sung, phần bổ sung", example: "" },
    { word: "Consequence", definition: "hậu quả, kết quả", example: "" },
    { word: "Authorization", definition: "sự cho phép, phê duyệt", example: "" },
    { word: "Festivity", definition: "lễ hội, sự vui mừng", example: "" },
    { word: "House", definition: "cung cấp nơi ở, chứa đựng", example: "" },
    { word: "Imposing", definition: "ấn tượng, oai nghiêm", example: "" },
    { word: "Abandon", definition: "từ bỏ, bỏ rơi", example: "" },
    { word: "Subsequently", definition: "sau đó, kế tiếp", example: "" },
    { word: "Restore", definition: "khôi phục, phục hồi", example: "" },
    { word: "Furnish", definition: "trang bị nội thất, cung cấp", example: "" },
    { word: "Admission", definition: "sự cho vào, tiền vào cửa", example: "" },
    { word: "Converse", definition: "trò chuyện, nói chuyện", example: "" },
    { word: "To this end", definition: "để đạt được mục tiêu này", example: "" },
    { word: "Experience", definition: "trải nghiệm", example: "" },
    { word: "Corrupt", definition: "tham nhũng, làm hư hỏng", example: "" },
    { word: "Savings", definition: "tiền tiết kiệm", example: "" },
    { word: "Ensure", definition: "đảm bảo", example: "" },
    { word: "Avoid", definition: "tránh xa", example: "" },
    { word: "Address", definition: "giải quyết, hướng tới", example: "" },
    { word: "Anticipate", definition: "dự đoán, mong đợi", example: "" },
    { word: "Functional", definition: "hữu dụng, thiết thực", example: "" },
    { word: "Internalize", definition: "tiếp thu, nội tâm hóa", example: "" },
    { word: "Internal", definition: "bên trong, nội bộ", example: "" },
    { word: "Dependable", definition: "đáng tin cậy", example: "" },
    { word: "Crew", definition: "đội, nhóm", example: "" },
    { word: "Shut off", definition: "tắt, ngừng hoạt động", example: "" },
    { word: "Residence", definition: "nơi cư trú", example: "" },
    { word: "Disruption", definition: "sự gián đoạn", example: "" },
    { word: "Outage", definition: "sự mất điện, ngừng hoạt động", example: "" },
    { word: "Record", definition: "hồ sơ, kỷ lục", example: "" },
    { word: "Nonetheless", definition: "tuy nhiên", example: "" },
    { word: "Portal", definition: "cổng thông tin điện tử", example: "" },
    { word: "Roll out", definition: "triển khai, tung ra", example: "" },
    { word: "Exchange", definition: "trao đổi, sự trao đổi", example: "" },
    { word: "Intend to V", definition: "dự định làm gì", example: "" },
    { word: "Invention", definition: "phát minh", example: "" },
    { word: "Attempt", definition: "cố gắng, sự cố gắng", example: "" },
    { word: "Pharmaceutical", definition: "dược phẩm, thuộc về thuốc", example: "" },
    { word: "Trespass", definition: "xâm phạm, sự xâm nhập", example: "" },
    { word: "Physical therapy", definition: "vật lý trị liệu", example: "" },
    { word: "Diagnose", definition: "chẩn đoán", example: "" },
    { word: "Complex", definition: "phức tạp, khu phức hợp", example: "" },
    { word: "Sink", definition: "chìm, bồn rửa", example: "" },
    { word: "Clog", definition: "tắc nghẽn, làm tắc", example: "" },
    { word: "Custodian", definition: "người bảo vệ, người dọn dẹp", example: "" },
    { word: "Plumber", definition: "thợ sửa ống nước", example: "" },
    { word: "Draft", definition: "bản phác thảo, soạn thảo", example: "" },
    { word: "Description", definition: "sự mô tả", example: "" },
    { word: "Architect", definition: "kiến trúc sư", example: "" },
    { word: "Diploma", definition: "bằng tốt nghiệp", example: "" },
    { word: "Garment", definition: "trang phục", example: "" },
    { word: "Flourish", definition: "thăng hoa, sự thịnh vượng", example: "" },
    { word: "Demanding", definition: "đòi hỏi khắt khe", example: "" },
    { word: "Known", definition: "nổi tiếng, được biết đến", example: "" },
    { word: "Tend to V", definition: "có xu hướng làm gì", example: "" },
    { word: "Suit", definition: "bộ đồ, phù hợp", example: "" },
    { word: "Rotation", definition: "sự xoay vòng", example: "" },
    { word: "Automobile", definition: "ô tô", example: "" },
    { word: "Filter", definition: "bộ lọc, lọc", example: "" },
    { word: "Quote", definition: "trích dẫn, báo giá", example: "" },
    { word: "Renowned", definition: "nổi tiếng, lừng danh", example: "" },
    { word: "Dedicate", definition: "cống hiến, tận tụy", example: "" },
    { word: "Innovative", definition: "sáng tạo, đổi mới", example: "" },
    { word: "Press release", definition: "thông cáo báo chí", example: "" },
    { word: "Ballroom", definition: "phòng khiêu vũ", example: "" },
    { word: "In demand", definition: "đang có nhu cầu", example: "" },
    { word: "Wage", definition: "tiền lương", example: "" },
    { word: "Demolish", definition: "phá hủy, triệt phá", example: "" },
    { word: "Landmark", definition: "điểm mốc, công trình nổi bật", example: "" },
    { word: "Outdated", definition: "lỗi thời, không còn phù hợp", example: "" },
    { word: "Navigation", definition: "điều hướng", example: "" },
    { word: "Council", definition: "hội đồng", example: "" },
    { word: "Fabric", definition: "vải, cấu trúc", example: "" },
    { word: "Subcontract", definition: "giao khoán, hợp đồng phụ", example: "" },
    { word: "Treatment", definition: "sự điều trị", example: "" },
    { word: "Workforce", definition: "lực lượng lao động", example: "" },
    { word: "Reveal", definition: "tiết lộ, làm lộ ra", example: "" },
    { word: "Infrastructure", definition: "cơ sở hạ tầng", example: "" },
    { word: "Outstanding", definition: "xuất sắc, nổi bật", example: "" },
    { word: "Hospitality", definition: "sự hiếu khách, ngành khách sạn", example: "" },
    { word: "Diverse", definition: "đa dạng, phong phú", example: "" },
    { word: "Basic", definition: "cơ bản", example: "" },
    { word: "Conflict", definition: "xung đột, mâu thuẫn", example: "" },
    { word: "Spread", definition: "lan rộng, sự lan truyền", example: "" },
    { word: "On a regular basis", definition: "thường xuyên", example: "" },
    { word: "Credit sth to sb", definition: "công nhận ai đó vì điều gì", example: "" },
    { word: "Persuade", definition: "thuyết phục", example: "" },
    { word: "Charming", definition: "quyến rũ, duyên dáng", example: "" },
    { word: "Gourmet", definition: "ẩm thực cao cấp, đầu bếp", example: "" },
    { word: "Treat", definition: "món quà, sự đối xử", example: "" },
    { word: "Flock", definition: "tụ tập, đàn (chim, cừu)", example: "" },
    { word: "Momentum", definition: "động lực, đà", example: "" },
    { word: "Flavor", definition: "hương vị", example: "" },
    { word: "Exceed", definition: "vượt quá", example: "" },
    { word: "Respondent", definition: "người trả lời", example: "" },
    { word: "Revenue", definition: "doanh thu", example: "" },
    { word: "Presence", definition: "sự hiện diện", example: "" },
    { word: "Advantage", definition: "lợi thế", example: "" },
    { word: "Engagement", definition: "sự tham gia, sự cam kết", example: "" },
    { word: "Preach", definition: "giảng đạo, thuyết giảng", example: "" },
];

export const readingComprehensiveVocabulary: VocabularyPart = {
    id: 200,
    title: "Reading tổng hợp",
    description: "Từ vựng Reading phổ biến, có tỉ lệ xuất hiện cao",
    tests: [
        { id: 2001, title: "Test 1", words: test1_words },
        { id: 2002, title: "Test 2", words: test2_words },
        { id: 2003, title: "Test 3", words: test3_words },
        { id: 2004, title: "Test 4", words: test4_words },
        { id: 2005, title: "Test 5", words: test5_words },
        { id: 2006, title: "Test 6", words: test6_words },
        { id: 2007, title: "Test 7", words: test7_words },
        { id: 2008, title: "Test 8", words: test8_words },
        { id: 2009, title: "Test 9", words: test9_words },
        { id: 2010, title: "Test 10", words: test10_words },
    ]
};
