import { VocabularyPart } from '../../types';

export const readingBasic2026Vocabulary: VocabularyPart = {
    id: 400,
    title: "Reading Cơ Bản 2026",
    description: "Bộ từ vựng Reading nền tảng cập nhật cho năm 2026.",
    isComingSoon: false,
    isNew: true,
    tests: [
        { 
            id: 40001, 
            title: "Part 5 (101-115)", 
            words: [
                { word: "take place", definition: "diễn ra", example: "" },
                { word: "attendee", definition: "người tham dự", example: "" },
                { word: "among", definition: "giữa, trong số", example: "" },
                { word: "antique", definition: "đồ cổ", example: "" },
                { word: "close down", definition: "đóng cửa, ngừng hoạt động", example: "" },
                { word: "resident", definition: "cư dân", example: "" },
                { word: "receive", definition: "nhận", example: "" },
                { word: "status", definition: "trạng thái, tình trạng", example: "" },
                { word: "ongoing", definition: "đang diễn ra", example: "" },
                { word: "construction", definition: "sự xây dựng", example: "" },
                { word: "payment", definition: "sự thanh toán", example: "" },
                { word: "request", definition: "yêu cầu", example: "" },
                { word: "as a result of", definition: "kết quả của, do", example: "" },
                { word: "leading organization", definition: "tổ chức hàng đầu", example: "" },
                { word: "select", definition: "lựa chọn", example: "" },
                { word: "virus", definition: "vi-rút", example: "" },
                { word: "suspicious", definition: "khả nghi, nghi ngờ", example: "" },
                { word: "break", definition: "sự nghỉ ngơi, giờ nghỉ", example: "" },
                { word: "spread", definition: "sự lan truyền", example: "" },
                { word: "balance", definition: "số dư, sự cân bằng", example: "" },
                { word: "surface", definition: "bề mặt", example: "" },
                { word: "consider", definition: "cân nhắc, xem xét", example: "" },
                { word: "applicant", definition: "ứng viên", example: "" },
                { word: "qualification", definition: "bằng cấp, trình độ chuyên môn", example: "" },
                { word: "careful", definition: "cẩn thận", example: "" },
                { word: "leave for", definition: "rời đi để đến (một nơi nào đó)", example: "" },
                { word: "oversee", definition: "giám sát", example: "" },
                { word: "opening", definition: "lễ khai trương, vị trí trống", example: "" },
                { word: "prior to", definition: "trước khi", example: "" },
                { word: "vary", definition: "thay đổi, biến đổi", example: "" },
                { word: "product line", definition: "dòng sản phẩm", example: "" },
                { word: "over-the-counter", definition: "không kê đơn (thuốc)", example: "" },
                { word: "medication", definition: "thuốc, dược phẩm", example: "" },
                { word: "continuously", definition: "liên tục", example: "" },
                { word: "seek", definition: "tìm kiếm", example: "" },
                { word: "reduce", definition: "giảm bớt", example: "" },
                { word: "plastic", definition: "nhựa", example: "" },
                { word: "cash register", definition: "máy tính tiền", example: "" },
                { word: "automatically", definition: "một cách tự động", example: "" },
                { word: "calculate", definition: "tính toán", example: "" },
                { word: "remaining", definition: "còn lại", example: "" },
                { word: "inventory", definition: "hàng tồn kho", example: "" },
                { word: "mapping", definition: "sự lập bản đồ", example: "" },
                { word: "software", definition: "phần mềm", example: "" },
                { word: "locate", definition: "xác định vị trí, định vị", example: "" },
                { word: "underground mineral", definition: "khoáng sản dưới lòng đất", example: "" },
                { word: "infinitely", definition: "vô tận, vô hạn", example: "" },
                { word: "sincerely", definition: "chân thành", example: "" },
                { word: "precisely", definition: "một cách chính xác", example: "" },
                { word: "greatly", definition: "rất nhiều, đáng kể", example: "" },
                { word: "responsible", definition: "chiểu trách nhiệm", example: "" },
                { word: "expand", definition: "mở rộng", example: "" },
                { word: "warehouse", definition: "nhà kho", example: "" },
                { word: "finance", definition: "tài chính", example: "" },
                { word: "financial", definition: "thuộc về tài chính", example: "" },
                { word: "regional", definition: "thuộc về vùng, khu vực", example: "" },
                { word: "demand", definition: "nhu cầu", example: "" },
                { word: "electric", definition: "thuộc về điện", example: "" },
                { word: "certainty", definition: "sự chắc chắn", example: "" },
                { word: "justice", definition: "công lý, sự công bằng", example: "" },
                { word: "excellence", definition: "sự xuất sắc", example: "" },
                { word: "denial", definition: "sự từ chối, phủ nhận", example: "" },
                { word: "campaign", definition: "chiến dịch", example: "" },
                { word: "solicit", definition: "kêu gọi, thu hút", example: "" },
                { word: "lightly", definition: "nhẹ nhàng", example: "" },
                { word: "loyally", definition: "một cách trung thành", example: "" },
                { word: "actively", definition: "một cách tích cực, chủ động", example: "" },
                { word: "intend", definition: "dự định", example: "" },
                { word: "prevent", definition: "ngăn chặn", example: "" },
                { word: "flooding", definition: "sự ngập lụt", example: "" },
                { word: "local", definition: "địa phương", example: "" },
                { word: "engage", definition: "tham gia, thuê, cam kết", example: "" },
                { word: "undergo", definition: "trải qua", example: "" },
                { word: "absorb", definition: "hấp thụ", example: "" },
                { word: "overwheelm", definition: "áp đảo, tràn ngập", example: "" }
            ] 
        },
        { 
            id: 40002, 
            title: "Part 5 (116-130)", 
            words: [
                { word: "aim", definition: "mục tiêu, nhắm tới", example: "" },
                { word: "increase", definition: "tăng lên", example: "" },
                { word: "manufacturing", definition: "sản xuất", example: "" },
                { word: "system", definition: "hệ thống", example: "" },
                { word: "productive", definition: "năng suất, hiệu quả", example: "" },
                { word: "workplace", definition: "nơi làm việc", example: "" },
                { word: "experience", definition: "kinh nghiệm, trải nghiệm", example: "" },
                { word: "reply", definition: "phản hồi, trả lời", example: "" },
                { word: "capture", definition: "bắt giữ, thu hút (sự chú ý)", example: "" },
                { word: "compensate", definition: "bồi thường, đền bù", example: "" },
                { word: "accumulate", definition: "tích lũy", example: "" },
                { word: "highly", definition: "rất, cực kỳ", example: "" },
                { word: "qualified", definition: "đủ năng lực, đủ điều kiện", example: "" },
                { word: "neither", definition: "không... cũng không", example: "" },
                { word: "whoever", definition: "bất cứ ai", example: "" },
                { word: "purchase", definition: "mua, sự mua sắm", example: "" },
                { word: "lighting equipment", definition: "thiết bị chiếu sáng", example: "" },
                { word: "cost", definition: "chi phí, trị giá", example: "" },
                { word: "resident", definition: "cư dân", example: "" },
                { word: "award-winning", definition: "từng đoạt giải thưởng", example: "" },
                { word: "real estate", definition: "bất động sản", example: "" },
                { word: "agreement", definition: "thỏa thuận, hợp đồng", example: "" },
                { word: "farmer", definition: "nông dân", example: "" },
                { word: "produce (noun/verb)", definition: "nông sản / sản xuất", example: "" },
                { word: "disruptive", definition: "gây gián đoạn, đột phá", example: "" },
                { word: "cooperative", definition: "hợp tác", example: "" },
                { word: "grateful", definition: "biết ơn", example: "" },
                { word: "concern", definition: "mối quan ngại, lo lắng", example: "" },
                { word: "downtown", definition: "trung tâm thành phố", example: "" },
                { word: "opposition", definition: "sự đối lập, sự phản đối", example: "" },
                { word: "restrict", definition: "hạn chế", example: "" },
                { word: "plumbing", definition: "hệ thống ống nước", example: "" },
                { word: "extensive", definition: "rộng rãi, bao quát", example: "" },
                { word: "position", definition: "vị trí, chức vụ", example: "" },
                { word: "diligently", definition: "một cách chăm chỉ", example: "" },
                { word: "objectively", definition: "một cách khách quan", example: "" },
                { word: "decidedly", definition: "một cách dứt khoát, rõ rệt", example: "" },
                { word: "fixed (adj)", definition: "cố định, được sửa chữa", example: "" },
                { word: "guarantee", definition: "bảo đảm, cam kết", example: "" },
                { word: "assure", definition: "cam đoan, quả quyết", example: "" },
                { word: "analytic", definition: "thuộc về phân tích", example: "" },
                { word: "deduction", definition: "sự khấu trừ, sự suy luận", example: "" },
                { word: "duplication", definition: "sự sao chép, sự trùng lặp", example: "" },
                { word: "declaration", definition: "sự tuyên bố", example: "" },
                { word: "dedication", definition: "sự tận tâm, cống hiến", example: "" },
                { word: "cafeteria", definition: "quán ăn tự phục vụ", example: "" },
                { word: "serve", definition: "phục vụ", example: "" },
                { word: "as though", definition: "như thể là", example: "" },
                { word: "rather than", definition: "thay vì", example: "" },
                { word: "entire", definition: "toàn bộ", example: "" },
                { word: "inventory", definition: "hàng tồn kho, sự kiểm kê", example: "" },
                { word: "nearby", definition: "gần đây", example: "" },
                { word: "supplier", definition: "nhà cung cấp", example: "" },
                { word: "promotional", definition: "thuộc về quảng cáo, khuyến mãi", example: "" },
                { word: "chemical", definition: "hóa chất, thuộc về hóa học", example: "" },
                { word: "commercial", definition: "thương mại, quảng cáo", example: "" },
                { word: "mechanic", definition: "thợ cơ khí", example: "" },
                { word: "determine", definition: "xác định, quyết định", example: "" },
                { word: "diagnose", definition: "chẩn đoán", example: "" },
                { word: "diagnostic", definition: "thuộc về chẩn đoán", example: "" },
                { word: "diagnosable", definition: "có thể chẩn đoán được", example: "" },
                { word: "productivity", definition: "năng suất", example: "" },
                { word: "board of director (BOD)", definition: "hội đồng quản trị", example: "" },
                { word: "vote", definition: "bầu chọn, bỏ phiếu", example: "" },
                { word: "award (verb)", definition: "trao thưởng", example: "" },
                { word: "role", definition: "vai trò", example: "" },
                { word: "obtain", definition: "đạt được, giành được", example: "" },
                { word: "international", definition: "quốc tế", example: "" },
                { word: "except", definition: "ngoại trừ", example: "" },
                { word: "apart", definition: "tách biệt", example: "" },
                { word: "finance", definition: "tài chính", example: "" },
                { word: "director", definition: "giám đốc", example: "" },
                { word: "approval", definition: "sự chấp thuận, phê duyệt", example: "" },
                { word: "project", definition: "dự án", example: "" },
                { word: "move forward", definition: "tiến tới, triển khai", example: "" },
                { word: "furthermore", definition: "hơn nữa", example: "" },
                { word: "cautiously", definition: "một cách thận trọng", example: "" },
                { word: "article", definition: "bài báo, điều khoản", example: "" },
                { word: "describe", definition: "mô tả", example: "" },
                { word: "seek", definition: "tìm kiếm", example: "" }
            ] 
        },
        { 
            id: 40003, 
            title: "Part 6 (131-138)", 
            words: [
                { word: "create", definition: "tạo ra", example: "" },
                { word: "match", definition: "phù hợp, trận đấu", example: "" },
                { word: "desire", definition: "khao khát", example: "" },
                { word: "nursery", definition: "nhà trẻ, vườn ươm", example: "" },
                { word: "variety", definition: "sự đa dạng", example: "" },
                { word: "burst", definition: "bùng nổ", example: "" },
                { word: "eye-catching", definition: "bắt mắt", example: "" },
                { word: "year-round", definition: "quanh năm", example: "" },
                { word: "equip", definition: "trang bị", example: "" },
                { word: "construct", definition: "xây dựng", example: "" },
                { word: "pond", definition: "cái ao", example: "" },
                { word: "feature", definition: "đặc điểm, bao gồm", example: "" },
                { word: "ambitious", definition: "đầy tham vọng", example: "" },
                { word: "landscaping", definition: "cảnh quan", example: "" },
                { word: "project", definition: "dự án", example: "" },
                { word: "expertise", definition: "chuyên môn", example: "" },
                { word: "unmatch", definition: "không thể sánh bằng", example: "" },
                { word: "install", definition: "lắp đặt", example: "" },
                { word: "enhance", definition: "nâng cao", example: "" },
                { word: "effect", definition: "tác động, hiệu quả", example: "" },
                { word: "well-designed", definition: "được thiết kế tốt", example: "" },
                { word: "local", definition: "địa phương", example: "" },
                { word: "competitor", definition: "đối thủ cạnh tranh", example: "" },
                { word: "beat (verb)", definition: "đánh bại", example: "" },
                { word: "charge (verb)", definition: "tính phí", example: "" },
                { word: "goal", definition: "mục tiêu", example: "" },
                { word: "vision", definition: "tầm nhìn", example: "" },
                { word: "reality", definition: "thực tế", example: "" },
                { word: "moisture", definition: "độ ẩm", example: "" },
                { word: "rarely", definition: "hiếm khi", example: "" },
                { word: "somehow", definition: "bằng cách nào đó", example: "" },
                { word: "nevertheless", definition: "tuy nhiên", example: "" },
                { word: "delighted", definition: "vui mừng", example: "" },
                { word: "celebrate", definition: "kỷ niệm", example: "" },
                { word: "contribute", definition: "đóng góp", example: "" },
                { word: "success", definition: "thành công", example: "" },
                { word: "appreciate", definition: "trân trọng, đánh giá cao", example: "" },
                { word: "commitment", definition: "cam kết", example: "" },
                { word: "initiative", definition: "sáng kiến", example: "" },
                { word: "commemorative", definition: "kỷ niệm", example: "" },
                { word: "plaque", definition: "tấm bảng", example: "" },
                { word: "token", definition: "dấu hiệu, biểu tượng", example: "" },
                { word: "gratitude", definition: " lòng biết ơn", example: "" },
                { word: "reach", definition: "đạt được, liên hệ", example: "" },
                { word: "value (verb)", definition: "coi trọng", example: "" },
                { word: "long-term", definition: "dài hạn", example: "" },
                { word: "annual", definition: "hàng năm", example: "" },
                { word: "release", definition: "phát hành", example: "" },
                { word: "instead", definition: "thay vào đó", example: "" },
                { word: "likewise", definition: "tương tự như vậy", example: "" },
                { word: "milestone", definition: "cột mốc", example: "" },
                { word: "consensus", definition: "sự đồng thuận", example: "" },
                { word: "destination", definition: "điểm đến", example: "" }
            ] 
        },
        { 
            id: 40004, 
            title: "Part 6 (139-146)", 
            words: [
                { word: "process", definition: "quá trình, xử lý", example: "" },
                { word: "finalize", definition: "hoàn tất", example: "" },
                { word: "based on", definition: "dựa trên", example: "" },
                { word: "conversation", definition: "cuộc trò chuyện", example: "" },
                { word: "paint", definition: "sơn, vẽ", example: "" },
                { word: "wall", definition: "bức tường", example: "" },
                { word: "border", definition: "biên giới, viền", example: "" },
                { word: "attached", definition: "đính kèm", example: "" },
                { word: "decide", definition: "quyết định", example: "" },
                { word: "refine", definition: "tinh chỉnh", example: "" },
                { word: "organization", definition: "tổ chức", example: "" },
                { word: "schedule", definition: "lịch trình", example: "" },
                { word: "particularly", definition: "đặc biệt", example: "" },
                { word: "spacious", definition: "rộng rãi", example: "" },
                { word: "airy", definition: "thoáng mát", example: "" },
                { word: "receive", definition: "nhận", example: "" },
                { word: "current", definition: "hienti", example: "" },
                { word: "payment", definition: "thanh toán", example: "" },
                { word: "recent", definition: "gần đây", example: "" },
                { word: "suggestion", definition: "gợi ý", example: "" },
                { word: "improvement", definition: "sự cải thiện", example: "" },
                { word: "post (verb)", definition: "đăng", example: "" },
                { word: "consultation", definition: "sự tư vấn", example: "" },
                { word: "portal", definition: "cổng thông tin", example: "" },
                { word: "moment", definition: "khoảnh khắc, lát", example: "" },
                { word: "go through", definition: "xem qua, trải qua", example: "" },
                { word: "reminder", definition: "lời nhắc", example: "" },
                { word: "various", definition: "đa dạng", example: "" },
                { word: "activities", definition: "các hoạt động", example: "" },
                { word: "make an appointment", definition: "đặt lịch hẹn", example: "" },
                { word: "medical", definition: "thuộc về y tế", example: "" },
                { word: "request", definition: "yêu cầu", example: "" },
                { word: "refill", definition: "làm đầy lại", example: "" },
                { word: "personal", definition: "cá nhân", example: "" },
                { word: "safe", definition: "an toàn", example: "" },
                { word: "secure", definition: "bảo đảm, an ninh", example: "" },
                { word: "satisfactory", definition: "thỏa đáng", example: "" },
                { word: "satisfy", definition: "làm hài lòng", example: "" },
                { word: "lecture", definition: "bài giảng", example: "" },
                { word: "summary", definition: "bản tóm tắt", example: "" },
                { word: "to repeat", definition: "để lặp lại", example: "" },
                { word: "for instance", definition: "ví dụ", example: "" },
                { word: "otherwise", definition: "nếu không thì", example: "" },
                { word: "consequently", definition: "do đó", example: "" },
                { word: "resource", definition: "nguồn lực", example: "" },
                { word: "manage", definition: "quản lý", example: "" },
                { word: "health-care", definition: "chăm sóc sức khỏe", example: "" },
                { word: "in advance", definition: "trước", example: "" },
                { word: "apologize", definition: "xin lỗi", example: "" },
                { word: "confusion", definition: "sự nhầm lẫn", example: "" }
            ] 
        },
        { 
            id: 40005, 
            title: "Part 7 (147-150)", 
            words: [
                { word: "resurface", definition: "trải lại mặt (đường), nổi lại", example: "" },
                { word: "vehicle", definition: "phương tiện, xe cộ", example: "" },
                { word: "commence", definition: "bắt đầu", example: "" },
                { word: "inconvenient", definition: "bất tiện", example: "" },
                { word: "necessary", definition: "cần thiết", example: "" },
                { word: "widen", definition: "mở rộng", example: "" },
                { word: "previous", definition: "trước đó", example: "" },
                { word: "invite", definition: "mời", example: "" },
                { word: "facilities", definition: "cơ sở vật chất, tiện nghi", example: "" },
                { word: "inform", definition: "thông báo, cho biết", example: "" },
                { word: "upcoming", definition: "sắp tới", example: "" },
                { word: "announce", definition: "thông báo, công bố", example: "" },
                { word: "maintenance", definition: "sự bảo trì", example: "" },
                { word: "recently", definition: "gần đây", example: "" },
                { word: "hire", definition: "thuê, tuyển dụng", example: "" },
                { word: "property", definition: "tài sản, bất động sản", example: "" },
                { word: "repave", definition: "lát lại (đường)", example: "" },
                { word: "assign", definition: "phân công, chỉ định", example: "" },
                { word: "tenant", definition: "người thuê nhà", example: "" },
                { word: "specific", definition: "cụ thể", example: "" },
                { word: "spot", definition: "địa điểm, nơi", example: "" },
                { word: "popular", definition: "phổ biến, được ưa chuộng", example: "" },
                { word: "material", definition: "vật liệu, tài liệu", example: "" },
                { word: "on hand", definition: "có sẵn, sẵn có", example: "" },
                { word: "participant", definition: "người tham gia", example: "" },
                { word: "plenty", definition: "nhiều, phong phú", example: "" },
                { word: "vacation", definition: "kỳ nghỉ", example: "" },
                { word: "perfectly", definition: "một cách hoàn hảo", example: "" },
                { word: "instructor", definition: "người hướng dẫn, giáo viên", example: "" },
                { word: "lifeguard", definition: "nhân viên cứu hộ", example: "" },
                { word: "administrator", definition: "người quản lý, quản trị viên", example: "" },
                { word: "intend", definition: "dự định, ý định", example: "" },
                { word: "extra", definition: "thêm, phụ", example: "" },
                { word: "collect", definition: "thu thập, sưu tầm", example: "" }
            ] 
        },
        { 
            id: 40006, 
            title: "Part 7 (151-157)", 
            words: [
                { word: "newsletter", definition: "bản tin", example: "" },
                { word: "performance", definition: "sự trình diễn, hiệu suất", example: "" },
                { word: "consistently", definition: "một cách nhất quán", example: "" },
                { word: "accomplishment", definition: "thành tựu, sự hoàn thành", example: "" },
                { word: "transfer", definition: "thuyên chuyển, di chuyển", example: "" },
                { word: "headquarter", definition: "trụ sở chính", example: "" },
                { word: "acknowledge", definition: "công nhận, xác nhận", example: "" },
                { word: "perhap", definition: "có lẽ", example: "" },
                { word: "decoration", definition: "sự trang trí", example: "" },
                { word: "attend", definition: "tham dự", example: "" },
                { word: "potential", definition: "tiềm năng", example: "" },
                { word: "tourist", definition: "khách du lịch", example: "" },
                { word: "celebrate", definition: "kỷ niệm, ăn mừng", example: "" },
                { word: "saddened", definition: "buồn bã", example: "" },
                { word: "former", definition: "cựu, trước đây", example: "" },
                { word: "venue", definition: "địa điểm tổ chức", example: "" },
                { word: "renovation", definition: "sự cải tạo, nâng cấp", example: "" },
                { word: "fortunately", definition: "may mắn thay", example: "" },
                { word: "owner", definition: "chủ sở hữu", example: "" },
                { word: "interior", definition: "nội thất", example: "" },
                { word: "projection system", definition: "hệ thống trình chiếu", example: "" },
                { word: "theater", definition: "nhà hát", example: "" },
                { word: "grow up", definition: "trưởng thành, lớn lên", example: "" },
                { word: "thriving", definition: "phát triển mạnh mẽ", example: "" },
                { word: "condition", definition: "điều kiện, tình trạng", example: "" },
                { word: "reopening", definition: "sự mở cửa trở lại", example: "" },
                { word: "premiere", definition: "buổi công chiếu, ra mắt", example: "" },
                { word: "advertise", definition: "quảng cáo", example: "" },
                { word: "coordinator", definition: "điều phối viên", example: "" },
                { word: "council", definition: "hội đồng", example: "" },
                { word: "partner", definition: "đối tác", example: "" },
                { word: "unfortunately", definition: "không may thay", example: "" },
                { word: "on back order", definition: "đơn hàng đang chờ (do hết hàng)", example: "" },
                { word: "prefer", definition: "thích hơn", example: "" },
                { word: "similar", definition: "tương tự", example: "" },
                { word: "manufacturer", definition: "nhà sản xuất", example: "" },
                { word: "model", definition: "mẫu, đời máy", example: "" },
                { word: "carrying case", definition: "túi đựng, hộp đựng xách tay", example: "" },
                { word: "revise", definition: "xem xét lại, chỉnh sửa", example: "" },
                { word: "representative", definition: "người đại diện", example: "" },
                { word: "refund", definition: "hoàn tiền", example: "" },
                { word: "overnight", definition: "qua đêm", example: "" },
                { word: "notify", definition: "thông báo", example: "" },
                { word: "in stock", definition: "còn hàng", example: "" },
                { word: "operating", definition: "vận hành, đang hoạt động", example: "" },
                { word: "instruction", definition: "sự hướng dẫn", example: "" },
                { word: "substitute", definition: "thay thế", example: "" },
                { word: "protective", definition: "bảo vệ", example: "" },
                { word: "specification", definition: "thông số kỹ thuật", example: "" }
            ] 
        },
        { 
            id: 40007, 
            title: "Part 7 (158-163)", 
            words: [
                { word: "currently", definition: "hiện tại", example: "" },
                { word: "return", definition: "trả lại, quay lại", example: "" },
                { word: "respond to", definition: "phản hồi", example: "" },
                { word: "general", definition: "chung, tổng quát", example: "" },
                { word: "assistance", definition: "sự hỗ trợ", example: "" },
                { word: "absence", definition: "sự vắng mặt", example: "" },
                { word: "open position", definition: "vị trí trống", example: "" },
                { word: "department", definition: "phòng ban", example: "" },
                { word: "graphic design", definition: "thiết kế đồ họa", example: "" },
                { word: "newly", definition: "mới", example: "" },
                { word: "sign up", definition: "đăng ký", example: "" },
                { word: "launch", definition: "ra mắt, tung ra", example: "" },
                { word: "take place", definition: "diễn ra", example: "" },
                { word: "goods (noun)", definition: "hàng hóa", example: "" },
                { word: "nutrition", definition: "dinh dưỡng", example: "" },
                { word: "convenience", definition: "sự thuận tiện", example: "" },
                { word: "press conference", definition: "cuộc họp báo", example: "" },
                { word: "concept", definition: "khái niệm, ý tưởng", example: "" },
                { word: "method", definition: "phương pháp", example: "" },
                { word: "ensure", definition: "đảm bảo", example: "" },
                { word: "retain", definition: "giữ lại", example: "" },
                { word: "texture", definition: "kết cấu", example: "" },
                { word: "flavour", definition: "hương vị", example: "" },
                { word: "quality", definition: "chất lượng", example: "" },
                { word: "obtain", definition: "đạt được, có được", example: "" },
                { word: "operation", definition: "sự vận hành, hoạt động", example: "" },
                { word: "avoid", definition: "tránh", example: "" },
                { word: "harvest", definition: "vụ mùa, thu hoạch", example: "" },
                { word: "freezer", definition: "tủ đông", example: "" },
                { word: "technique", definition: "kỹ thuật", example: "" },
                { word: "corporate", definition: "thuộc về công ty, tập đoàn", example: "" },
                { word: "merger", definition: "sự sáp nhập", example: "" },
                { word: "product line", definition: "dòng sản phẩm", example: "" },
                { word: "executive", definition: "người điều hành, cấp cao", example: "" },
                { word: "slightly", definition: "một chút, hơi", example: "" },
                { word: "flavorful", definition: "đầy hương vị, đậm đà", example: "" }
            ] 
        },
        { 
            id: 40008, 
            title: "Part 7 (164-167)", 
            words: [
                { word: "like-minded", definition: "cùng chí hướng", example: "" },
                { word: "individuals", definition: "cá nhân", example: "" },
                { word: "willing to", definition: "sẵn lòng", example: "" },
                { word: "imagination", definition: "trí tưởng tượng", example: "" },
                { word: "expand", definition: "mở rộng", example: "" },
                { word: "opportunity", definition: "cơ hội", example: "" },
                { word: "employ", definition: "thuê, tuyển dụng", example: "" },
                { word: "brochure", definition: "tờ rơi quảng cáo", example: "" },
                { word: "collaborative", definition: "cộng tác, hợp tác", example: "" },
                { word: "environment", definition: "môi trường", example: "" },
                { word: "ideal", definition: "lý tưởng", example: "" },
                { word: "candidate", definition: "ứng viên", example: "" },
                { word: "degree", definition: "bằng cấp", example: "" },
                { word: "several", definition: "một vài", example: "" },
                { word: "demonstrate ability", definition: "thể hiện khả năng", example: "" },
                { word: "work closely with", definition: "làm việc chặt chẽ với", example: "" },
                { word: "colleague", definition: "đồng nghiệp", example: "" },
                { word: "maintain", definition: "duy trì", example: "" },
                { word: "detail", definition: "chi tiết", example: "" },
                { word: "consistently", definition: "một cách nhất quán", example: "" },
                { word: "pressure", definition: "áp lực", example: "" },
                { word: "related", definition: "liên quan", example: "" },
                { word: "primary", definition: "chính, chủ yếu", example: "" },
                { word: "focus", definition: "tập trung", example: "" },
                { word: "initially", definition: "ban đầu", example: "" },
                { word: "permit (verb/ noun)", definition: "cho phép / giấy phép", example: "" },
                { word: "previous", definition: "trước đó", example: "" },
                { word: "certain", definition: "chắc chắn, nhất định", example: "" },
                { word: "occur", definition: "xảy ra", example: "" },
                { word: "relocate", definition: "di dời, chuyển chỗ", example: "" },
                // Add comment above fix: Added missing 'example' property to fix type error
                { word: "available", definition: "có sẵn, rảnh", example: "" }
            ] 
        },
        { 
            id: 40009, 
            title: "Part 7 (168-171)", 
            words: [
                { word: "damage", definition: "hư hỏng, thiệt hại", example: "" },
                { word: "amount", definition: "số lượng, lượng", example: "" },
                { word: "significant", definition: "đáng kể, quan trọng", example: "" },
                { word: "dining", definition: "việc dùng bữa", example: "" },
                { word: "accommodate", definition: "đáp ứng, chứa được", example: "" },
                { word: "opposite", definition: "đối diện, ngược lại", example: "" },
                { word: "temporarily", definition: "tạm thời", example: "" },
                { word: "grand opening", definition: "lễ khai trương", example: "" },
                { word: "tasting", definition: "việc nếm thử", example: "" },
                { word: "reservation", definition: "sự đặt chỗ", example: "" },
                { word: "be able to", definition: "có thể", example: "" },
                { word: "prepare", definition: "chuẩn bị", example: "" },
                { word: "traditional dish", definition: "món ăn truyền thống", example: "" },
                { word: "community", definition: "cộng đồng", example: "" },
                { word: "chef", definition: "đầu bếp", example: "" },
                { word: "major", definition: "chính, chủ yếu", example: "" },
                { word: "ingredient", definition: "thành phần, nguyên liệu", example: "" },
                { word: "occasionally", definition: "thỉnh thoảng", example: "" },
                { word: "reduce", definition: "giảm", example: "" },
                { word: "retirement", definition: "sự nghỉ hưu", example: "" },
                { word: "honor (Verb)", definition: "tôn vinh, vinh danh", example: "" },
                // Add comment above fix: Added missing 'example' property to fix type error
                { word: "additional", definition: "thêm vào, bổ sung", example: "" }
            ] 
        },
        { 
            id: 40010, 
            title: "Part 7 (172-175)", 
            words: [
                { word: "analysis", definition: "sự phân tích", example: "" },
                { word: "email address", definition: "địa chỉ email", example: "" },
                { word: "account holder", definition: "chủ tài khoản", example: "" },
                { word: "sort", definition: "sắp xếp, phân loại", example: "" },
                { word: "complete", definition: "hoàn thành, đầy đủ", example: "" },
                { word: "huge", definition: "khổng lồ, to lớn", example: "" },
                { word: "expert", definition: "chuyên gia", example: "" },
                { word: "submit", definition: "nộp, đệ trình", example: "" },
                { word: "form", definition: "mẫu đơn, hình thức", example: "" },
                { word: "queue", definition: "hàng đợi", example: "" },
                { word: "right away", definition: "ngay lập tức", example: "" },
                { word: "ahead of", definition: "trước, phía trước", example: "" },
                { word: "invitation", definition: "lời mời", example: "" },
                { word: "as soon as", definition: "ngay khi", example: "" },
                { word: "refer", definition: "tham khảo, đề cập", example: "" },
                { word: "decline", definition: "từ chối, suy giảm", example: "" },
                { word: "issue (verb)", definition: "ban hành, đưa ra", example: "" },
                { word: "apology", definition: "lời xin lỗi", example: "" },
                { word: "clarification", definition: "sự làm rõ", example: "" },
                { word: "policy", definition: "chính sách", example: "" },
                // Add comment above fix: Added missing 'example' property to fix type error
                { word: "assist", definition: "hỗ trợ, giúp đỡ", example: "" }
            ] 
        },
        { id: 40011, title: "Set 11", words: [] },
        { id: 40012, title: "Set 12", words: [] },
        { id: 40013, title: "Set 13", words: [] },
        { id: 40014, title: "Set 14", words: [] },
        { id: 40015, title: "Set 15", words: [] },
        { id: 40016, title: "Set 16", words: [] },
        { id: 40017, title: "Set 17", words: [] },
        { id: 40018, title: "Set 18", words: [] },
        { id: 40019, title: "Set 19", words: [] },
        { id: 40020, title: "Set 20", words: [] },
    ]
};