
import { VocabularyPart, VocabItem } from '../../types';

const test1_176_185_words: VocabItem[] = [
    { word: "establishment", definition: "sự thành lập, cơ sở", example: "" },
    { word: "variety", definition: "sự đa dạng, chủng loại", example: "" },
    { word: "option", definition: "sự lựa chọn, tùy chọn", example: "" },
    { word: "ideal", definition: "lý tưởng, hoàn hảo", example: "" },
    { word: "fewer", definition: "ít hơn (dùng cho danh từ đếm được)", example: "" },
    { word: "transactions", definition: "giao dịch", example: "" },
    { word: "frequently", definition: "thường xuyên", example: "" },
    { word: "customers", definition: "khách hàng", example: "" },
    { word: "attractive", definition: "hấp dẫn, thu hút", example: "" },
    { word: "interest", definition: "tiền lãi, sự quan tâm", example: "" },
    { word: "savings", definition: "tiền tiết kiệm", example: "" },
    { word: "teenager", definition: "thanh thiếu niên", example: "" },
    { word: "involve", definition: "liên quan, bao gồm", example: "" },
    { word: "initiate", definition: "bắt đầu, khởi xướng", example: "" },
    { word: "registration", definition: "sự đăng ký", example: "" },
    { word: "drop by", definition: "ghé qua, tạt qua", example: "" },
    { word: "commercial", definition: "Thương mại, thuộc về thương mại", example: "" },
    { word: "comply", definition: "Tuân thủ, chấp hành", example: "" },
    { word: "regulations", definition: "Quy định, điều lệ", example: "" },
    { word: "restrictions", definition: "Sự hạn chế, giới hạn", example: "" },
    { word: "individual", definition: "Cá nhân, riêng lẻ", example: "" },
    { word: "complete", definition: "Hoàn chỉnh, đầy đủ", example: "" },
    { word: "enforcement", definition: "Sự thi hành, sự cưỡng chế", example: "" },
    { word: "load", definition: "Tải trọng, hàng hóa (trên xe)", example: "" },
    { word: "limits", definition: "Giới hạn, mức tối đa", example: "" },
    { word: "weigh", definition: "Cân (xác định trọng lượng)", example: "" },
    { word: "pull over", definition: "Tấp vào lề, dừng xe (ở lề đường)", example: "" },
    { word: "conduct", definition: "Tiến hành, thực hiện", example: "" },
    { word: "visual", definition: "Thuộc về thị giác, bằng mắt", example: "" },
    { word: "inspections", definition: "Sự kiểm tra, thanh tra", example: "" },
    { word: "ensure", definition: "Đảm bảo, chắc chắn", example: "" },
    { word: "measures", definition: "Biện pháp, phương sách", example: "" },
    { word: "determines", definition: "Xác định, quyết định", example: "" },
    { word: "sensors", definition: "Cảm biến, bộ cảm ứng", example: "" },
    { word: "installed", definition: "Lắp đặt, cài đặt", example: "" },
    { word: "blinks", definition: "Nháy mắt, chớp nháy (đèn)", example: "" },
    { word: "fined", definition: "Bị phạt tiền", example: "" },
    { word: "traffic jams", definition: "Tắc đường, kẹt xe", example: "" },
    { word: "on account of", definition: "Bởi vì, do", example: "" },
    { word: "numerous", definition: "Nhiều, vô số", example: "" },
    { word: "accurately", definition: "Một cách chính xác", example: "" },
    { word: "suffer", definition: "Chịu đựng, trải qua (điều tồi tệ)", example: "" },
    { word: "signify", definition: "Biểu thị", example: "" },
];

const test1_186_200_words: VocabItem[] = [
    { word: "preserved", definition: "bảo tồn, giữ gìn", example: "" },
    { word: "appeared", definition: "đã xuất hiện, dường như", example: "" },
    { word: "complimentary", definition: "miễn phí, ca ngợi", example: "" },
    { word: "Features", definition: "có tính năng, nổi bật", example: "" },
    { word: "finest", definition: "tốt nhất, chất lượng cao nhất", example: "" },
    { word: "dining", definition: "việc ăn uống, dùng bữa", example: "" },
    { word: "specialties", definition: "đặc sản, món đặc trưng", example: "" },
    { word: "pier", definition: "cầu tàu, bến tàu", example: "" },
    { word: "Decorated", definition: "được trang trí, được trang hoàng", example: "" },
    { word: "ranch", definition: "trang trại (chăn nuôi gia súc)", example: "" },
    { word: "region", definition: "vùng, khu vực", example: "" },
    { word: "distracted", definition: "bị phân tâm, mất tập trung", example: "" },
    { word: "casual", definition: "bình thường, không trang trọng", example: "" },
    { word: "atmosphere", definition: "bầu không khí, môi trường", example: "" },
    { word: "incredible", definition: "không thể tin được, tuyệt vời", example: "" },
    { word: "hearty", definition: "thịnh soạn, ấm cúng, chân thành", example: "" },
    { word: "must", definition: "điều bắt buộc, sự cần thiết", example: "" },
    { word: "taste", definition: "vị, sự nếm; khiếu thẩm mỹ", example: "" },
    { word: "establishment", definition: "cơ sở, sự thành lập", example: "" },
    { word: "down", definition: "Xuống, phía dưới, dọc theo", example: "" },
    { word: "waterfront", definition: "Bờ sông, bờ hồ, bờ biển (khu vực ven nước)", example: "" },
    { word: "return", definition: "Trở về, quay lại", example: "" },
    { word: "excursion", definition: "Chuyến đi chơi, chuyến tham quan ngắn", example: "" },
    { word: "label", definition: "Nhãn, nhãn mác", example: "" },
    { word: "misspelling", definition: "Lỗi chính tả", example: "" },
    { word: "rectified", definition: "Đã sửa, đã chỉnh sửa", example: "" },
    { word: "charges", definition: "Tính phí, đòi tiền", example: "" },
    { word: "affix", definition: "Dán, đính kèm, gắn vào", example: "" },
    { word: "emergency", definition: "Tình trạng khẩn cấp", example: "" },
    { word: "solve", definition: "Giải quyết, hóa giải", example: "" },
    { word: "reduce", definition: "Giảm, cắt giảm", example: "" },
    { word: "handle", definition: "Xử lý, giải quyết", example: "" },
    { word: "Ingredients", definition: "Thành phần", example: "" },
    { word: "Manufactured", definition: "Đã sản xuất, đã chế tạo", example: "" },
    { word: "Distributed", definition: "Đã phân phối", example: "" },
    { word: "amount", definition: "Số lượng", example: "" },
    { word: "submissions", definition: "Các bài nộp, hồ sơ dự thầu", example: "" },
    { word: "narrowed", definition: "Thu hẹp, giới hạn lại", example: "" },
    { word: "impressive", definition: "Ấn tượng, gây cảm phục", example: "" },
    { word: "in person", definition: "Trực tiếp, đích thân", example: "" },
    { word: "matter", definition: "Vấn đề, sự việc", example: "" },
    { word: "redesign", definition: "Thiết kế lại", example: "" },
    { word: "individuals", definition: "Cá nhân", example: "" },
    { word: "measurements", definition: "Số đo, kích thước", example: "" },
    { word: "fine dining", definition: "Ẩm thực cao cấp", example: "" },
    { word: "diners", definition: "Thực khách", example: "" },
    { word: "imagining", definition: "Tưởng tượng, hình dung", example: "" },
    { word: "exclusive", definition: "Độc quyền, riêng biệt", example: "" },
    { word: "dishes", definition: "Món ăn", example: "" },
    { word: "bid", definition: "Đấu thầu; trả giá", example: "" },
];

const test2_176_185_words: VocabItem[] = [
    { word: "pleasure", definition: "Niềm vinh dự, niềm vui, sự hân hạnh", example: "" },
    { word: "proposal", definition: "Đề xuất, kiến nghị", example: "" },
    { word: "Impressed", definition: "Bị ấn tượng, thán phục", example: "" },
    { word: "cover issues", definition: "Giải quyết/đề cập các vấn đề", example: "" },
    { word: "releasing", definition: "Giải ngân, cấp phát", example: "" },
    { word: "engaging", definition: "Tham gia, bắt đầu (dự án)", example: "" },
    { word: "intend", definition: "Dự định, có ý định", example: "" },
    { word: "arrangements", definition: "Sự sắp xếp, kế hoạch", example: "" },
    { word: "elected", definition: "Được bầu cử", example: "" },
    { word: "undergoing", definition: "Đang trải qua, đang được tiến hành", example: "" },
    { word: "platforms", definition: "Cương lĩnh, chương trình hành động", example: "" },
    { word: "livable", definition: "Đáng sống, có thể ở được", example: "" },
    { word: "enhancements", definition: "Sự cải thiện, nâng cấp", example: "" },
    { word: "infrastructure", definition: "Cơ sở hạ tầng", example: "" },
    { word: "wider variety", definition: "Đa dạng hơn, nhiều loại hơn", example: "" },
    { word: "emphasized", definition: "Nhấn mạnh, làm nổi bật", example: "" },
    { word: "clearly evident", definition: "Rõ ràng, hiển nhiên", example: "" },
    { word: "flocking", definition: "Tụ tập, đổ xô đến", example: "" },
    { word: "benefitted", definition: "Được hưởng lợi", example: "" },
    { word: "city hall", definition: "Tòa thị chính", example: "" },
    { word: "lending", definition: "Cho vay, cho mượn", example: "" },
    { word: "appreciate", definition: "Đánh giá cao, cảm kích", example: "" },
    { word: "inform", definition: "Thông báo, cho biết", example: "" },
    { word: "containing", definition: "Chứa đựng, bao gồm", example: "" },
    { word: "importing", definition: "Nhập khẩu", example: "" },
    { word: "college", definition: "Trường đại học/cao đẳng", example: "" },
    { word: "pass along", definition: "Chuyển tiếp, truyền lại", example: "" },
    { word: "get in touch", definition: "Liên lạc, giữ liên lạc", example: "" },
    { word: "reached", definition: "Liên lạc, đến, đạt tới", example: "" },
    { word: "wound up", definition: "Cuối cùng thì (kết thúc ở một tình huống/địa điểm bất ngờ)", example: "" },
    { word: "diploma", definition: "Bằng cấp (sau khi tốt nghiệp)", example: "" },
    { word: "engineer", definition: "Kỹ sư", example: "" },
    { word: "decided", definition: "Quyết định", example: "" },
    { word: "main", definition: "Chính, chủ yếu", example: "" },
    { word: "disappointed", definition: "Thất vọng", example: "" },
    { word: "native land", definition: "Quê hương, xứ sở", example: "" },
    { word: "appropriately", definition: "Một cách thích hợp, hợp lý", example: "" },
    { word: "thoroughly", definition: "Hoàn toàn, kỹ lưỡng", example: "" },
    { word: "overcooked", definition: "Nấu quá chín", example: "" },
    { word: "exceptional", definition: "Nổi bật, xuất sắc", example: "" },
    { word: "authentic", definition: "Đúng kiểu, chính thống, xác thực", example: "" },
    { word: "title", definition: "Tiêu đề, danh hiệu", example: "" },
    { word: "acquainted", definition: "Quen biết", example: "" },
];

const test2_186_200_words: VocabItem[] = [
    { word: "strive", definition: "phấn đấu, cố gắng", example: "" },
    { word: "professional", definition: "chuyên nghiệp, thuộc về nghề nghiệp", example: "" },
    { word: "skills", definition: "kĩ năng", example: "" },
    { word: "endeavor", definition: "nỗ lực, sự cố gắng", example: "" },
    { word: "job-related", definition: "liên quan đến công việc", example: "" },
    { word: "accredited", definition: "được công nhận chính thức", example: "" },
    { word: "reimbursed", definition: "được hoàn lại tiền, được bồi hoàn", example: "" },
    { word: "determine", definition: "xác định, quyết định", example: "" },
    { word: "financial", definition: "(thuộc về) tài chính", example: "" },
    { word: "assistance", definition: "sự hỗ trợ, sự giúp đỡ", example: "" },
    { word: "obtained", definition: "đạt được, giành được", example: "" },
    { word: "textbooks", definition: "sách giáo khoa", example: "" },
    { word: "conducted", definition: "được tiến hành, được thực hiện", example: "" },
    { word: "enroll", definition: "đăng ký, ghi danh", example: "" },
    { word: "upcoming", definition: "sắp tới", example: "" },
    { word: "semester", definition: "học kỳ", example: "" },
    { word: "has yet to", definition: "vẫn chưa", example: "" },
    { word: "register", definition: "đăng ký", example: "" },
    { word: "alternative", definition: "thay thế, lựa chọn khác", example: "" },
    { word: "entirely", definition: "toàn bộ", example: "" },
    { word: "satisfied", definition: "Hài lòng, thoả mãn", example: "" },
    { word: "lighter", definition: "Nhạt hơn, nhẹ hơn", example: "" },
    { word: "play", definition: "Vở kịch", example: "" },
    { word: "bulk rate", definition: "Giá sỉ, giá số lượng lớn", example: "" },
    { word: "aside", definition: "Để qua một bên, sang một bên", example: "" },
    { word: "front row tickets", definition: "Vé hàng ghế đầu", example: "" },
    { word: "theater", definition: "Nhà hát, rạp hát", example: "" },
    { word: "brochure", definition: "Tờ quảng cáo, sách mỏng", example: "" },
    { word: "performance", definition: "Buổi biểu diễn, sự trình diễn", example: "" },
    { word: "included", definition: "Đã bao gồm, đã đính kèm", example: "" },
    { word: "look over", definition: "Xem qua, kiểm tra", example: "" },
    { word: "mistakes", definition: "Sai sót, lỗi", example: "" },
    { word: "wish", definition: "Mong muốn, muốn", example: "" },
    { word: "initiate", definition: "Bắt đầu, khởi xướng", example: "" },
    { word: "invoice", definition: "Hoá đơn", example: "" },
    { word: "pair", definition: "Một cặp, đôi", example: "" },
    { word: "cast", definition: "Dàn diễn viên", example: "" },
    { word: "altered", definition: "Đã thay đổi, đã sửa đổi", example: "" },
    { word: "vacation season", definition: "mùa nghỉ mát, mùa du lịch", example: "" },
    { word: "approaching", definition: "đang đến gần", example: "" },
    { word: "regarding", definition: "về việc, liên quan đến", example: "" },
    { word: "vital", definition: "quan trọng, thiết yếu", example: "" },
    { word: "immediate", definition: "trực tiếp, ngay lập tức", example: "" },
    { word: "supervisor", definition: "người giám sát, quản lý", example: "" },
    { word: "aware", definition: "ý thức, nhận thức", example: "" },
    { word: "time off", definition: "thời gian nghỉ ngơi", example: "" },
    { word: "granted", definition: "được chấp thuận, được cấp", example: "" },
    { word: "duties", definition: "nhiệm vụ, công việc", example: "" },
    { word: "coworker", definition: "đồng nghiệp", example: "" },
    { word: "handling", definition: "xử lý, giải quyết", example: "" },
    { word: "calendar", definition: "lịch", example: "" },
    { word: "replacements", definition: "người thay thế, vật thay thế", example: "" },
    { word: "cloth", definition: "vải", example: "" },
    { word: "several", definition: "một vài, một số", example: "" },
    { word: "bolts", definition: "cuộn (vải)", example: "" },
    { word: "fabric", definition: "vải, chất liệu", example: "" },
    { word: "rush", definition: "khẩn cấp, vội vã", example: "" },
    { word: "respond", definition: "phản hồi, trả lời", example: "" },
    { word: "textile", definition: "hàng dệt may, dệt", example: "" },
    { word: "tailor", definition: "thợ may; điều chỉnh", example: "" },
    { word: "multiple", definition: "nhiều, đa", example: "" },
    { word: "branches", definition: "chi nhánh, cành cây", example: "" },
    { word: "speak with", definition: "nói chuyện với", example: "" },
];

const test3_176_185_words: VocabItem[] = [
    { word: "eligible", definition: "Đủ điều kiện, hội đủ tiêu chuẩn", example: "" },
    { word: "adjacent", definition: "Kề bên, liền kề", example: "" },
    { word: "volunteers", definition: "Tình nguyện viên", example: "" },
    { word: "Jewelry", definition: "Trang sức, đồ trang sức", example: "" },
    { word: "forklift", definition: "Xe nâng", example: "" },
    { word: "personally", definition: "Cá nhân, đích thân", example: "" },
    { word: "previous", definition: "Trước, trước đây", example: "" },
    { word: "taken part", definition: "Đã tham gia", example: "" },
    { word: "reserve", definition: "Đặt trước, giữ chỗ", example: "" },
    { word: "freight elevator", definition: "Thang máy chở hàng", example: "" },
    { word: "guarantee", definition: "Bảo đảm, sự bảo đảm", example: "" },
    { word: "first-come, first-served", definition: "Ai đến trước được phục vụ trước", example: "" },
    { word: "event coordinator", definition: "Điều phối viên sự kiện", example: "" },
    { word: "regarding", definition: "Về, liên quan đến", example: "" },
    { word: "acceptance", definition: "Sự chấp nhận", example: "" },
    { word: "rejection", definition: "Sự từ chối", example: "" },
    { word: "rental fee", definition: "Phí thuê", example: "" },
    { word: "available", definition: "Có sẵn, rảnh", example: "" },
    { word: "booth", definition: "Gian hàng, buồng", example: "" },
    { word: "antique", definition: "Cổ, đồ cổ", example: "" },
    { word: "redo", definition: "Làm lại, trang trí lại", example: "" },
    { word: "interior", definition: "Nội thất, bên trong", example: "" },
    { word: "capable", definition: "Có khả năng, có năng lực", example: "" },
    { word: "realize", definition: "Nhận ra, hiểu ra", example: "" },
    { word: "avoid", definition: "Tránh, né tránh", example: "" },
    { word: "specializing", definition: "Chuyên môn hóa, chuyên về", example: "" },
    { word: "residential", definition: "Thuộc về khu dân cư, nhà ở", example: "" },
    { word: "simply", definition: "Đơn giản chỉ là, chỉ", example: "" },
    { word: "desire", definition: "Mong muốn, khao khát", example: "" },
    { word: "budget", definition: "Ngân sách", example: "" },
    { word: "tasteful", definition: "Có thẩm mỹ, trang nhã", example: "" },
    { word: "under no circumstances", definition: "Dưới bất kỳ trường hợp nào cũng không", example: "" },
    { word: "criteria", definition: "Tiêu chí, chuẩn mực", example: "" },
    { word: "unfortunately", definition: "Không may thay", example: "" },
    { word: "fulfill", definition: "Hoàn thành, đáp ứng", example: "" },
    { word: "conditions", definition: "Điều kiện, yêu cầu", example: "" },
    { word: "consumer", definition: "Khách hàng, người tiêu dùng", example: "" },
    { word: "recent", definition: "Gần đây", example: "" },
    { word: "expert", definition: "Chuyên gia, chuyên viên", example: "" },
    { word: "on staff", definition: "Là nhân viên chính thức, có trong đội ngũ", example: "" },
    { word: "staffers", definition: "Nhân viên, thành viên", example: "" },
    { word: "stock brokerage", definition: "Công ty môi giới chứng khoán", example: "" },
    { word: "quoted", definition: "Được báo giá, được định giá", example: "" },
    { word: "indicated", definition: "Chỉ ra, cho biết", example: "" },
    { word: "various", definition: "Khác nhau, đa dạng", example: "" },
];

const test3_186_200_words: VocabItem[] = [
    { word: "insurance", definition: "Bảo hiểm", example: "" },
    { word: "coverage", definition: "Phạm vi bảo hiểm", example: "" },
    { word: "extra", definition: "Thêm, phụ", example: "" },
    { word: "unlimited", definition: "Không giới hạn", example: "" },
    { word: "mileage", definition: "Quãng đường (tính bằng dặm)", example: "" },
    { word: "additional", definition: "Bổ sung, thêm", example: "" },
    { word: "valid", definition: "Hợp lệ, có giá trị", example: "" },
    { word: "pick up", definition: "Đón, nhận xe", example: "" },
    { word: "drop-off", definition: "Điểm trả xe, việc trả xe", example: "" },
    { word: "involved in", definition: "Liên quan đến, dính líu vào", example: "" },
    { word: "assessed", definition: "Đã được tính/định giá", example: "" },
    { word: "renter", definition: "Người thuê, bên thuê", example: "" },
    { word: "inquiries", definition: "Các câu hỏi, thắc mắc", example: "" },
    { word: "unauthorized", definition: "không được phép, trái phép", example: "" },
    { word: "permit", definition: "cho phép", example: "" },
    { word: "security guard", definition: "nhân viên bảo vệ", example: "" },
    { word: "on duty", definition: "đang làm nhiệm vụ, đang trực", example: "" },
    { word: "refuse", definition: "từ chối", example: "" },
    { word: "expecting", definition: "đang mong đợi, đang chờ", example: "" },
    { word: "usage", definition: "sự sử dụng, mức sử dụng", example: "" },
    { word: "adequate", definition: "đủ, đầy đủ", example: "" },
    { word: "detergent", definition: "chất tẩy rửa (bột giặt, nước rửa)", example: "" },
    { word: "manufacturer", definition: "nhà sản xuất", example: "" },
    { word: "press", definition: "nhấn, ấn", example: "" },
    { word: "with regard to", definition: "liên quan đến, về việc", example: "" },
    { word: "High-Capacity", definition: "sức chứa lớn", example: "" },
    { word: "Presoak", definition: "ngâm trước", example: "" },
    { word: "amounts", definition: "số lượng, lượng", example: "" },
    { word: "similar", definition: "tương tự, giống nhau", example: "" },
    { word: "own", definition: "sở hữu", example: "" },
    { word: "complex", definition: "khu phức hợp", example: "" },
    { word: "furnished", definition: "được trang bị nội thất", example: "" },
    { word: "tenant", definition: "người thuê nhà", example: "" },
    { word: "outstanding", definition: "xuất sắc, nổi bật", example: "" },
    { word: "loads", definition: "mẻ (giặt/rửa), tải trọng", example: "" },
    { word: "commented", definition: "bình luận, nhận xét", example: "" },
    { word: "barely", definition: "hầu như không, vừa đủ", example: "" },
    { word: "operating", definition: "đang vận hành, đang hoạt động", example: "" },
    { word: "units", definition: "căn hộ, đơn vị", example: "" },
    { word: "Activate", definition: "kích hoạt", example: "" },
    { word: "mechanism", definition: "cơ chế, bộ máy", example: "" },
    { word: "Utilize", definition: "tận dụng, sử dụng", example: "" },
    { word: "Rinse off", definition: "xả sạch, rửa trôi", example: "" },
    { word: "dirty", definition: "bẩn, dơ", example: "" },
    { word: "Malfunctioning", definition: "bị trục trặc, hỏng hóc", example: "" },
    { word: "extremely", definition: "Cực kỳ, vô cùng", example: "" },
    { word: "diners", definition: "Thực khách", example: "" },
    { word: "refunded", definition: "Đã hoàn tiền", example: "" },
    { word: "making up (for)", definition: "Bù đắp, đền bù (cho)", example: "" },
    { word: "bulk", definition: "Số lượng lớn, sỉ", example: "" },
    { word: "route", definition: "Tuyến đường, lộ trình", example: "" },
    { word: "dairy", definition: "(Sản phẩm từ) sữa", example: "" },
    { word: "combined", definition: "(Được) kết hợp, gộp lại", example: "" },
    { word: "charged", definition: "Đã tính phí", example: "" },
    { word: "reimburse", definition: "Hoàn lại, bồi hoàn", example: "" },
    { word: "on a regular basis", definition: "Một cách thường xuyên, đều đặn", example: "" },
    { word: "physical store", definition: "Cửa hàng vật lý, cửa hàng truyền thống", example: "" },
    { word: "point out", definition: "Chỉ ra, lưu ý", example: "" },
    { word: "overnight", definition: "Qua đêm, trong một đêm; nhanh chóng", example: "" },
];

const test4_176_185_words: VocabItem[] = [
    { word: "invited", definition: "được mời", example: "" },
    { word: "focused", definition: "tập trung vào", example: "" },
    { word: "astronomy", definition: "thiên văn học", example: "" },
    { word: "humanity", definition: "nhân loại", example: "" },
    { word: "lecture", definition: "bài giảng", example: "" },
    { word: "lunar colony", definition: "khu định cư trên mặt trăng", example: "" },
    { word: "faculty", definition: "giảng viên, ban giảng huấn", example: "" },
    { word: "general", definition: "chung, phổ thông", example: "" },
    { word: "gain entry", definition: "được vào, vào cửa", example: "" },
    { word: "asteroid mining", definition: "khai thác tiểu hành tinh", example: "" },
    { word: "danger", definition: "sự nguy hiểm", example: "" },
    { word: "potential", definition: "tiềm năng", example: "" },
    { word: "owner", definition: "chủ sở hữu", example: "" },
    { word: "interstellar travel", definition: "du hành liên sao", example: "" },
    { word: "system", definition: "hệ thống", example: "" },
    { word: "a couple of", definition: "một vài", example: "" },
    { word: "semester", definition: "học kỳ", example: "" },
    { word: "visual", definition: "(thuộc) thị giác, trực quan", example: "" },
    { word: "attendee", definition: "người tham dự", example: "" },
    { word: "candidness", definition: "sự thẳng thắn, sự bộc trực", example: "" },
    { word: "wonder", definition: "tự hỏi, thắc mắc", example: "" },
    { word: "arrange", definition: "sắp xếp, thu xếp", example: "" },
    { word: "look forward to", definition: "mong chờ, mong đợi", example: "" },
    { word: "response", definition: "sự phản hồi, câu trả lời", example: "" },
    { word: "pleasure", definition: "niềm vinh hạnh, niềm vui", example: "" },
    { word: "possibility", definition: "khả năng, cơ hội", example: "" },
    { word: "laboratory", definition: "phòng thí nghiệm", example: "" },
    { word: "opted (to opt)", definition: "chọn lựa, quyết định", example: "" },
    { word: "lack", definition: "thiếu, không có", example: "" },
    { word: "graduate", definition: "(thuộc) sau đại học", example: "" },
    { word: "typically", definition: "thông thường, thường", example: "" },
    { word: "references", definition: "người/thư giới thiệu", example: "" },
    { word: "complimented (to compliment)", definition: "khen ngợi, ca ngợi", example: "" },
    { word: "ethic", definition: "đạo đức (làm việc)", example: "" },
    { word: "urge", definition: "hối thúc, khuyến nghị", example: "" },
    { word: "eventually", definition: "cuối cùng, rốt cuộc", example: "" },
    { word: "course", definition: "khóa học", example: "" },
    { word: "additional", definition: "thêm, bổ sung", example: "" },
    { word: "current", definition: "hiện tại, hiện hành", example: "" },
    { word: "degree", definition: "bằng cấp", example: "" },
    { word: "fluent", definition: "trôi chảy, lưu loát", example: "" },
    { word: "foreign", definition: "(thuộc) nước ngoài", example: "" },
    { word: "senior", definition: "cao cấp", example: "" },
    { word: "advance", definition: "thăng tiến, tiến bộ", example: "" },
    { word: "accelerate", definition: "tăng tốc, thúc đẩy", example: "" },
];

const test4_186_200_words: VocabItem[] = [
    { word: "inquiry", definition: "câu hỏi, sự thắc mắc", example: "" },
    { word: "properly", definition: "một cách đúng đắn", example: "" },
    { word: "town", definition: "thị trấn", example: "" },
    { word: "drop off", definition: "giao hàng, thả xuống", example: "" },
    { word: "Distributor", definition: "nhà phân phối", example: "" },
    { word: "in-season", definition: "(đang) vào mùa", example: "" },
    { word: "amount", definition: "số lượng, lượng", example: "" },
    { word: "pastries", definition: "bánh ngọt (các loại)", example: "" },
    { word: "downtown", definition: "(ở) trung tâm thành phố", example: "" },
    { word: "specialty", definition: "đặc sản, chuyên môn", example: "" },
    { word: "highly regarded", definition: "được đánh giá cao", example: "" },
    { word: "regular", definition: "đều đặn, thường xuyên", example: "" },
    { word: "on a regular basis", definition: "một cách thường xuyên", example: "" },
    { word: "depending", definition: "tùy thuộc vào", example: "" },
    { word: "regarding", definition: "về, liên quan đến", example: "" },
    { word: "roughly", definition: "khoảng, xấp xỉ", example: "" },
    { word: "largest", definition: "lớn nhất", example: "" },
    { word: "region", definition: "vùng, khu vực", example: "" },
    { word: "supply", definition: "cung cấp", example: "" },
    { word: "entire", definition: "toàn bộ", example: "" },
    { word: "year round", definition: "quanh năm", example: "" },
    { word: "quality", definition: "chất lượng", example: "" },
    { word: "handles", definition: "xử lý, quản lý", example: "" },
    { word: "aspects", definition: "khía cạnh, mặt", example: "" },
    { word: "agricultural", definition: "(thuộc về) nông nghiệp", example: "" },
    { word: "yields", definition: "sản lượng, lợi nhuận", example: "" },
    { word: "distance", definition: "khoảng cách", example: "" },
    { word: "Remarks", definition: "Bài phát biểu, nhận xét", example: "" },
    { word: "Manuscript", definition: "Bản thảo", example: "" },
    { word: "across from", definition: "Đối diện", example: "" },
    { word: "front desk", definition: "Quầy lễ tân", example: "" },
    { word: "nametag", definition: "Thẻ tên", example: "" },
    { word: "following", definition: "Sau đây, tiếp theo", example: "" },
    { word: "novels", definition: "Tiểu thuyết", example: "" },
    { word: "reception", definition: "Tiệc chiêu đãi", example: "" },
    { word: "sponsored", definition: "Được tài trợ", example: "" },
    { word: "opportunity", definition: "Cơ hội", example: "" },
    { word: "previously", definition: "Trước đây", example: "" },
    { word: "wish", definition: "Mong muốn", example: "" },
    { word: "notifications", definition: "Thông báo", example: "" },
    { word: "respond", definition: "Phản hồi", example: "" },
    { word: "participants", definition: "Người tham gia", example: "" },
    { word: "normal", definition: "Bình thường", example: "" },
    { word: "famous", definition: "Nổi tiếng", example: "" },
    { word: "authors", definition: "Tác giả", example: "" },
    { word: "publishers", definition: "Nhà xuất bản", example: "" },
    { word: "booth", definition: "Gian hàng", example: "" },
    { word: "attendance", definition: "Sự tham dự, số người tham dự", example: "" },
    { word: "attendees", definition: "Người tham dự", example: "" },
    { word: "entire", definition: "Toàn bộ", example: "" },
    { word: "recording", definition: "Bản thu âm, video", example: "" },
    { word: "simply", definition: "Đơn giản là, chỉ là", example: "" },
    { word: "announce", definition: "Thông báo, công bố", example: "" },
    { word: "staff", definition: "Nhân viên, đội ngũ", example: "" },
    { word: "concert", definition: "Buổi hòa nhạc", example: "" },
    { word: "hall", definition: "Sảnh, đại sảnh, hội trường", example: "" },
    { word: "individual", definition: "Cá nhân", example: "" },
    { word: "own", definition: "Của riêng mình", example: "" },
    { word: "native", definition: "Người bản xứ, thuộc về bản xứ", example: "" },
    { word: "decades", definition: "Thập kỷ (Mười năm)", example: "" },
    { word: "retired", definition: "Đã nghỉ hưu", example: "" },
    { word: "influence", definition: "Ảnh hưởng", example: "" },
    { word: "various", definition: "Khác nhau, đa dạng", example: "" },
    { word: "numerous", definition: "Nhiều, vô số", example: "" },
    { word: "occupied", definition: "Chiếm đóng, ở (tại)", example: "" },
    { word: "prestigious", definition: "Danh giá, uy tín", example: "" },
    { word: "transform", definition: "Biến đổi, chuyển đổi", example: "" },
    { word: "responsible", definition: "Chịu trách nhiệm", example: "" },
    { word: "renovations", definition: "Sự cải tạo, sửa chữa", example: "" },
    { word: "homage", definition: "Sự kính trọng, tôn vinh", example: "" },
    { word: "orchestras", definition: "Dàn nhạc giao hưởng", example: "" },
    { word: "academy", definition: "Học viện", example: "" },
    { word: "solely", definition: "Chỉ, duy nhất", example: "" },
    { word: "classical", definition: "Cổ điển", example: "" },
    { word: "inquiries", definition: "Yêu cầu, sự hỏi thăm", example: "" },
    { word: "meaning", definition: "Ý nghĩa", example: "" },
    { word: "pleasantly", definition: "Một cách dễ chịu, vui vẻ", example: "" },
    { word: "attentive", definition: "Chu đáo, ân cần", example: "" },
];

const test5_176_185_words: VocabItem[] = [
    { word: "dreadful", definition: "Khủng khiếp, tồi tệ", example: "" },
    { word: "resulted in", definition: "Dẫn đến, gây ra", example: "" },
    { word: "cancelation", definition: "Sự hủy bỏ", example: "" },
    { word: "unable to depart", definition: "Không thể khởi hành", example: "" },
    { word: "overbooked", definition: "Bán quá số chỗ", example: "" },
    { word: "volunteers", definition: "Tình nguyện viên", example: "" },
    { word: "worth", definition: "Có giá trị", example: "" },
    { word: "willing to exchange", definition: "Sẵn lòng đổi", example: "" },
    { word: "remain", definition: "Ở lại, giữ lại", example: "" },
    { word: "weather conditions", definition: "Điều kiện thời tiết", example: "" },
    { word: "expiration date", definition: "Ngày hết hạn", example: "" },
    { word: "domestic", definition: "Nội địa, trong nước", example: "" },
    { word: "redeemed", definition: "Đã đổi, đã quy đổi", example: "" },
    { word: "multiple", definition: "Nhiều", example: "" },
    { word: "business-class", definition: "Hạng thương gia", example: "" },
    { word: "carry-on bag", definition: "Túi xách tay", example: "" },
    { word: "purse", definition: "Ví/Túi xách nhỏ", example: "" },
    { word: "stopover", definition: "Điểm dừng chân (quá cảnh)", example: "" },
    { word: "Webcast", definition: "Hội thảo/Buổi phát sóng trực tuyến qua web", example: "" },
    { word: "Sponsored", definition: "Được tài trợ", example: "" },
    { word: "Interactive", definition: "Tương tác", example: "" },
    { word: "Cultures", definition: "Các nền văn hóa", example: "" },
    { word: "Broadcast", definition: "Phát sóng, truyền hình", example: "" },
    { word: "Archive", definition: "Kho lưu trữ, tài liệu lưu trữ", example: "" },
    { word: "Options", definition: "Các lựa chọn, các phương án", example: "" },
    { word: "Collaborate", definition: "Cộng tác, hợp tác", example: "" },
    { word: "Expertise", definition: "Chuyên môn, sự tinh thông", example: "" },
    { word: "Informative", definition: "Giàu thông tin, mang tính thông tin", example: "" },
    { word: "Relevant", definition: "Liên quan, thích đáng", example: "" },
];

const test5_186_200_words: VocabItem[] = [
    { word: "check", definition: "Séc (ngân phiếu); Phiếu hoàn tiền", example: "" },
    { word: "portion", definition: "Phần, một phần", example: "" },
    { word: "excessive", definition: "Quá mức, quá đáng", example: "" },
    { word: "refund", definition: "Hoàn lại, trả lại tiền (v); Tiền hoàn lại (n)", example: "" },
    { word: "satisfactory", definition: "Thỏa đáng, đạt yêu cầu", example: "" },
    { word: "tiles", definition: "Gạch (men, lát sàn/tường)", example: "" },
    { word: "stain", definition: "Vết bẩn, vết ố (n); Làm bẩn (v)", example: "" },
    { word: "Rent", definition: "Tiền thuê nhà/đất (n); Thuê (v)", example: "" },
    { word: "Utilities", definition: "Chi phí tiện ích (điện, nước, gas)", example: "" },
    { word: "responsibility", definition: "Trách nhiệm", example: "" },
    { word: "termination", definition: "Sự chấm dứt, sự kết thúc", example: "" },
    { word: "lease", definition: "Hợp đồng cho thuê (n); Cho thuê (v)", example: "" },
    { word: "deemed", definition: "Được coi là, được cho là", example: "" },
    { word: "furnishings", definition: "Đồ đạc, nội thất", example: "" },
    { word: "tenant", definition: "Người thuê nhà", example: "" },
    { word: "premises", definition: "Cơ sở, khuôn viên (nhà, đất)", example: "" },
    { word: "necessary", definition: "Cần thiết, thiết yếu", example: "" },
    { word: "deposit", definition: "Tiền đặt cọc (n); Gửi tiền (v)", example: "" },
    { word: "identification", definition: "sự nhận dạng, sự xác định", example: "" },
    { word: "moderators", definition: "người điều hành, kiểm duyệt viên", example: "" },
    { word: "unrelated", definition: "không liên quan", example: "" },
    { word: "formatted", definition: "được định dạng", example: "" },
    { word: "good subject line", definition: "dòng tiêu đề tốt", example: "" },
    { word: "active", definition: "hoạt động, năng động", example: "" },
    { word: "contributions", definition: "sự đóng góp", example: "" },
    { word: "formal training", definition: "đào tạo chính quy, huấn luyện chính thức", example: "" },
    { word: "judge", definition: "đánh giá, phán xét", example: "" },
    { word: "accurate", definition: "chính xác", example: "" },
    { word: "third parties", definition: "bên thứ ba, bên ngoài", example: "" },
    { word: "invasive", definition: "xâm lấn, xâm hại", example: "" },
    { word: "former students", definition: "cựu sinh viên, học sinh cũ", example: "" },
    { word: "forested part", definition: "khu vực nhiều cây, khu rừng", example: "" },
    { word: "eliminate", definition: "loại bỏ, loại trừ", example: "" },
    { word: "private", definition: "riêng tư, cá nhân", example: "" },
    { word: "guarantee", definition: "bảo đảm, cam đoan", example: "" },
    { word: "inquiries", definition: "các yêu cầu, câu hỏi", example: "" },
    { word: "insufficient", definition: "không đủ", example: "" },
    { word: "arranging", definition: "sắp xếp, bố trí", example: "" },
    { word: "acquire", definition: "mua lại, đạt được", example: "" },
    { word: "downtown", definition: "Trung tâm thành phố, khu thương mại", example: "" },
    { word: "instructor", definition: "Người hướng dẫn, huấn luyện viên", example: "" },
    { word: "negotiable", definition: "Có thể thương lượng, đàm phán", example: "" },
    { word: "determine", definition: "Quyết định, xác định", example: "" },
    { word: "drop", definition: "Tham gia (một lớp học), bỏ qua, thả", example: "" },
    { word: "take part in", definition: "Tham gia vào", example: "" },
    { word: "unless otherwise", definition: "Trừ khi có chỉ dẫn khác", example: "" },
    { word: "permitted", definition: "Được phép, được cho phép", example: "" },
    { word: "pilates", definition: "Môn tập Pilates", example: "" },
    { word: "aerobics", definition: "Môn thể dục nhịp điệu", example: "" },
    { word: "attention", definition: "Sự chú ý, quan tâm", example: "" },
    { word: "Apparently", definition: "Dường như, hình như, rõ ràng là", example: "" },
    { word: "length", definition: "Chiều dài, độ dài, khoảng thời gian", example: "" },
];

const test6_176_185_words: VocabItem[] = [
    { word: "adult", definition: "Người lớn, trưởng thành", example: "" },
    { word: "inventing", definition: "Việc phát minh, sáng chế", example: "" },
    { word: "take part in", definition: "Tham gia", example: "" },
    { word: "event", definition: "Sự kiện", example: "" },
    { word: "hosted", definition: "Đăng cai, dẫn chương trình", example: "" },
    { word: "well-known", definition: "Nổi tiếng", example: "" },
    { word: "focuses", definition: "Tập trung", example: "" },
    { word: "promising", definition: "Đầy hứa hẹn, triển vọng", example: "" },
    { word: "various", definition: "Đa dạng, khác nhau", example: "" },
    { word: "categories", definition: "Các hạng mục, thể loại", example: "" },
    { word: "primary", definition: "Chính, chủ yếu", example: "" },
    { word: "transportation", definition: "Giao thông, vận tải", example: "" },
    { word: "participate", definition: "Tham gia", example: "" },
    { word: "judges", definition: "Các giám khảo", example: "" },
    { word: "expert", definition: "Chuyên gia", example: "" },
    { word: "prize", definition: "Giải thưởng", example: "" },
    { word: "proposal", definition: "Bản đề xuất", example: "" },
    { word: "inform", definition: "Thông báo", example: "" },
    { word: "submission", definition: "Bài nộp, sự đệ trình", example: "" },
    { word: "committee", definition: "Ủy ban, hội đồng", example: "" },
    { word: "intriguing", definition: "Hấp dẫn, gợi thích thú", example: "" },
    { word: "contains", definition: "Chứa đựng, bao gồm", example: "" },
    { word: "a yearly basis", definition: "Hàng năm, định kỳ hàng năm", example: "" },
    { word: "awards", definition: "Các giải thưởng", example: "" },
    { word: "broadcast", definition: "Phát sóng", example: "" },
    { word: "Descriptions", definition: "Các sự mô tả", example: "" },
    { word: "Guidelines", definition: "Các nguyên tắc chỉ đạo", example: "" },
    { word: "specialties", definition: "Các chuyên môn, đặc sản", example: "" },
    { word: "pleasure", definition: "Niềm vinh hạnh, sự hài lòng", example: "" },
    { word: "conduct", definition: "Tổ chức, tiến hành", example: "" },
    { word: "ideal", definition: "Lý tưởng, hoàn hảo", example: "" },
    { word: "depart", definition: "Rời đi, khởi hành", example: "" },
    { word: "willing", definition: "Sẵn lòng", example: "" },
    { word: "went over", definition: "Đã xem xét kỹ, đã ôn lại", example: "" },
    { word: "rather", definition: "Khá là, hơi", example: "" },
    { word: "attendees", definition: "Những người tham dự", example: "" },
    { word: "entrance fee", definition: "Phí vào cửa", example: "" },
    { word: "several", definition: "Một vài, nhiều", example: "" },
    { word: "demonstrations", definition: "Các buổi trình diễn, minh họa", example: "" },
    { word: "options", definition: "Các lựa chọn", example: "" },
    { word: "terms", definition: "Các điều khoản", example: "" },
    { word: "likeminded", definition: "Cùng chí hướng", example: "" },
    { word: "individuals", definition: "Các cá nhân", example: "" },
    { word: "foreign", definition: "Nước ngoài", example: "" },
    { word: "accommodations", definition: "Chỗ ở, tiện nghi ăn ở", example: "" },
    { word: "summary", definition: "Bản tóm tắt", example: "" },
    { word: "Assistance", definition: "Sự hỗ trợ, giúp đỡ", example: "" },
    { word: "Entrepreneurs", definition: "Các doanh nhân, nhà khởi nghiệp", example: "" },
    { word: "Convention", definition: "Hội nghị", example: "" },
    { word: "register", definition: "Đăng ký", example: "" },
    { word: "large", definition: "Lớn, rộng", example: "" },
    { word: "sessions", definition: "Các phiên họp, buổi đào tạo", example: "" },
    { word: "limited", definition: "Có giới hạn", example: "" },
    { word: "altered", definition: "Đã thay đổi", example: "" },
    { word: "published", definition: "Được xuất bản, công bố", example: "" },
];

const test6_186_200_words: VocabItem[] = [
    { word: "Refrain", definition: "Kiềm chế, tránh làm gì", example: "" },
    { word: "Conclusion", definition: "Sự kết thúc, phần kết", example: "" },
    { word: "Attend", definition: "Tham dự, có mặt", example: "" },
    { word: "Cast", definition: "Dàn diễn viên", example: "" },
    { word: "Opportunity", definition: "Cơ hội", example: "" },
    { word: "Eligible", definition: "Đủ tư cách, đủ điều kiện", example: "" },
    { word: "Lined up", definition: "Sắp xếp, lên lịch (có sẵn)", example: "" },
    { word: "Pick up", definition: "Lấy, nhận (đồ/người)", example: "" },
    { word: "Countless", definition: "Vô số, không đếm xuể", example: "" },
    { word: "Extensive", definition: "Rộng rãi, bao quát", example: "" },
    { word: "Originally", definition: "Ban đầu, vốn dĩ", example: "" },
    { word: "Prominent", definition: "Nổi bật, quan trọng", example: "" },
    { word: "Decided", definition: "Đã quyết định", example: "" },
    { word: "Expanded", definition: "Mở rộng", example: "" },
    { word: "Modernized", definition: "Hiện đại hóa", example: "" },
    { word: "Comfortable", definition: "Thoải mái", example: "" },
    { word: "Appearance", definition: "Vẻ bề ngoài, diện mạo", example: "" },
    { word: "Renovations", definition: "Sự trùng tu, đổi mới", example: "" },
    { word: "Playwright", definition: "Nhà soạn kịch", example: "" },
    { word: "Premiered", definition: "Công chiếu/Ra mắt lần đầu", example: "" },
    { word: "Encourage", definition: "Khuyến khích, cổ vũ", example: "" },
    { word: "Concession stand", definition: "Quầy bán đồ ăn vặt (tại rạp)", example: "" },
    { word: "Depositing", definition: "Bỏ vào, nộp, gửi", example: "" },
    { word: "quality", definition: "chất lượng, phẩm chất tốt", example: "" },
    { word: "features", definition: "đặc điểm, tính năng", example: "" },
    { word: "ingredients", definition: "nguyên liệu, thành phần", example: "" },
    { word: "unable", definition: "không thể", example: "" },
    { word: "various", definition: "đa dạng, nhiều loại khác nhau", example: "" },
    { word: "entertainment", definition: "sự giải trí, tiết mục văn nghệ", example: "" },
    { word: "arrangements", definition: "sự sắp xếp, chuẩn bị", example: "" },
    { word: "aware", definition: "nhận thức, biết", example: "" },
    { word: "complicated", definition: "phức tạp", example: "" },
    { word: "agreement", definition: "thỏa thuận, hợp đồng", example: "" },
    { word: "negotiating", definition: "đàm phán, thương lượng", example: "" },
    { word: "restrictions", definition: "sự hạn chế, điều kiện ràng buộc", example: "" },
    { word: "preparations", definition: "công tác chuẩn bị", example: "" },
    { word: "reception", definition: "tiệc chiêu đãi", example: "" },
    { word: "take place", definition: "diễn ra, tổ chức", example: "" },
    { word: "desire", definition: "mong muốn, nguyện vọng", example: "" },
    { word: "acquainted with", definition: "làm quen với, quen biết với", example: "" },
    { word: "coordinate with", definition: "phối hợp với", example: "" },
    { word: "revise", definition: "xem lại, sửa đổi", example: "" },
    { word: "agenda", definition: "chương trình nghị sự", example: "" },
    { word: "flexible", definition: "linh hoạt", example: "" },
    { word: "Vary", definition: "Thay đổi, khác nhau", example: "" },
    { word: "In advance", definition: "Trước (thời gian)", example: "" },
    { word: "Additional", definition: "Bổ sung, thêm", example: "" },
    { word: "Respond", definition: "Phản hồi, trả lời", example: "" },
    { word: "Movers", definition: "Người/đội vận chuyển nhà", example: "" },
    { word: "Comply with", definition: "Tuân thủ", example: "" },
    { word: "Relocation", definition: "Sự di dời (nơi ở/làm việc)", example: "" },
    { word: "Estimate", definition: "Bảng báo giá ước tính", example: "" },
    { word: "Storage", definition: "Kho lưu trữ / Sự lưu trữ", example: "" },
    { word: "Entire", definition: "Toàn bộ", example: "" },
    { word: "Contents", definition: "Đồ đạc bên trong / Nội dung", example: "" },
    { word: "Vacuum", definition: "Hút bụi", example: "" },
    { word: "Stains", definition: "Vết bẩn, vết ố", example: "" },
    { word: "Facility", definition: "Cơ sở vật chất / Địa điểm", example: "" },
    { word: "Residence", definition: "Nơi cư trú, nhà ở", example: "" },
    { word: "Extend", definition: "Kéo dài (thời gian), gia hạn", example: "" },
    { word: "Charged", definition: "Bị tính phí", example: "" },
    { word: "Based", definition: "Dựa trên", example: "" },
    { word: "Realtor", definition: "Môi giới bất động sản", example: "" },
    { word: "Belongings", definition: "Đồ đạc cá nhân", example: "" },
    { word: "Climate", definition: "Khí hậu (nhiệt độ/độ ẩm)", example: "" },
    { word: "Harmed", definition: "Bị hư hại, bị tổn hại", example: "" },
    { word: "Conditions", definition: "Điều kiện (môi trường)", example: "" },
    { word: "Appropriate", definition: "Thích hợp, phù hợp", example: "" },
];

const test7_176_185_words: VocabItem[] = [
    { word: "Headquarters", definition: "Trụ sở chính", example: "" },
    { word: "Print division", definition: "Bộ phận in ấn", example: "" },
    { word: "Medical", definition: "(Thuộc) y tế, y học", example: "" },
    { word: "Undergo", definition: "Trải qua, chịu đựng", example: "" },
    { word: "Expansion", definition: "Sự mở rộng, sự phát triển", example: "" },
    { word: "Satisfy", definition: "Làm hài lòng, đáp ứng", example: "" },
    { word: "Seek", definition: "Tìm kiếm", example: "" },
    { word: "Responsible", definition: "Chịu trách nhiệm", example: "" },
    { word: "Original", definition: "Gốc, nguyên bản, độc đáo", example: "" },
    { word: "Independently", definition: "Một cách độc lập", example: "" },
    { word: "Collaboratively", definition: "Một cách hợp tác", example: "" },
    { word: "Individual", definition: "Cá nhân", example: "" },
    { word: "Editorial", definition: "(Thuộc) biên tập", example: "" },
    { word: "Ensure", definition: "Đảm bảo", example: "" },
    { word: "Conduct", definition: "Tiến hành, tổ chức", example: "" },
    { word: "Express", definition: "Bày tỏ, thể hiện", example: "" },
    { word: "Senior", definition: "Cấp cao, có thâm niên", example: "" },
    { word: "Employ", definition: "Thuê, tuyển dụng", example: "" },
    { word: "Journalist", definition: "Nhà báo", example: "" },
    { word: "Long-term", definition: "Dài hạn", example: "" },
    { word: "Perfect fit", definition: "Sự phù hợp hoàn hảo", example: "" },
    { word: "Required", definition: "Được yêu cầu, bắt buộc", example: "" },
    { word: "Seminar", definition: "Hội thảo", example: "" },
    { word: "Centered", definition: "Tập trung vào, xoay quanh", example: "" },
    { word: "Operation", definition: "Sự hoạt động, vận hành", example: "" },
    { word: "Opinionated", definition: "Bảo thủ, cứng đầu, khăng khăng ý mình", example: "" },
    { word: "Qualification", definition: "Bằng cấp, trình độ chuyên môn", example: "" },
    { word: "Evaluation", definition: "Sự đánh giá", example: "" },
    { word: "Attendees", definition: "Người tham dự", example: "" },
    { word: "Unusual", definition: "Lạ, khác thường", example: "" },
    { word: "Sell out", definition: "Bán hết (vé/hàng)", example: "" },
    { word: "Feature", definition: "Có, bao gồm (như nét đặc biệt)", example: "" },
    { word: "Appreciate", definition: "Trân trọng, đánh giá cao", example: "" },
    { word: "Venue", definition: "Địa điểm (tổ chức sự kiện)", example: "" },
    { word: "Reduced", definition: "Đã giảm (giá, số lượng)", example: "" },
    { word: "Particular", definition: "Cụ thể, đặc biệt", example: "" },
    { word: "Brochure", definition: "Cuốn sách nhỏ (quảng cáo)", example: "" },
    { word: "Audition", definition: "Thử giọng, thử vai", example: "" },
    { word: "Grew up", definition: "Lớn lên", example: "" },
    { word: "Allowance", definition: "Tiền tiêu vặt", example: "" },
    { word: "Afford", definition: "Đủ khả năng chi trả", example: "" },
    { word: "Effect", definition: "Ảnh hưởng, tác động", example: "" },
    { word: "Comprehensive", definition: "Toàn diện", example: "" },
    { word: "Hometown", definition: "Quê hương", example: "" },
    { word: "Suddenly", definition: "Đột ngột", example: "" },
    { word: "Tourists", definition: "Khách du lịch", example: "" },
    { word: "Attempt", definition: "Sự nỗ lực / Cố gắng", example: "" },
    { word: "Notice", definition: "Nhận thấy, chú ý", example: "" },
    { word: "Orchestra", definition: "Dàn nhạc", example: "" },
    { word: "Culture", definition: "Văn hóa", example: "" },
    { word: "Established", definition: "Thành lập", example: "" },
    { word: "Directed", definition: "Được chỉ đạo/hướng dẫn", example: "" },
    { word: "Contain", definition: "Chứa đựng, bao gồm", example: "" },
    { word: "Takes place", definition: "Diễn ra", example: "" },
    { word: "Guaranteed", definition: "Được đảm bảo", example: "" },
];

const test7_186_200_words: VocabItem[] = [
    { word: "Unfortunately", definition: "Thật không may, đáng tiếc", example: "" },
    { word: "Limited", definition: "Có giới hạn, hạn chế", example: "" },
    { word: "Bulk", definition: "Số lượng lớn, sỉ", example: "" },
    { word: "Automatically", definition: "Một cách tự động", example: "" },
    { word: "Qualified", definition: "Đủ điều kiện, đạt tiêu chuẩn", example: "" },
    { word: "Description", definition: "Sự mô tả", example: "" },
    { word: "Exchange", definition: "Trao đổi, đổi hàng", example: "" },
    { word: "Supplies last", definition: "(Khi) nguồn hàng vẫn còn", example: "" },
    { word: "Handle", definition: "Xử lý, giải quyết, phụ trách", example: "" },
    { word: "Advertisement", definition: "Quảng cáo", example: "" },
    { word: "Upcoming", definition: "Sắp tới, sắp diễn ra", example: "" },
    { word: "Heavily", definition: "Nặng, nhiều (mức độ cao)", example: "" },
    { word: "Firm", definition: "Công ty, hãng", example: "" },
    { word: "Return", definition: "Trả lại, hoàn lại", example: "" },
    { word: "Physical", definition: "Vật lý, thực tế (cửa hàng)", example: "" },
    { word: "Broken", definition: "Bị hỏng, bị vỡ", example: "" },
    { word: "Receipt", definition: "Hóa đơn, biên lai", example: "" },
    { word: "Profiled", definition: "Được viết tiểu sử, giới thiệu sơ lược", example: "" },
    { word: "Ceremony", definition: "Buổi lễ, nghi thức", example: "" },
    { word: "Held", definition: "Được tổ chức", example: "" },
    { word: "Sufficiently", definition: "Một cách đầy đủ", example: "" },
    { word: "Assisted", definition: "Đã hỗ trợ, giúp đỡ", example: "" },
    { word: "Intern", definition: "Thực tập sinh", example: "" },
    { word: "Organize", definition: "Tổ chức, sắp xếp", example: "" },
    { word: "Farewell", definition: "Chia tay, tạm biệt", example: "" },
    { word: "Colleagues", definition: "Đồng nghiệp", example: "" },
    { word: "Aired", definition: "Được phát sóng", example: "" },
    { word: "Graduating", definition: "Tốt nghiệp", example: "" },
    { word: "Tremendous", definition: "To lớn, tuyệt vời, khủng khiếp", example: "" },
    { word: "Broadcasting", definition: "Ngành phát thanh truyền hình", example: "" },
    { word: "Tutoring", definition: "Sự dạy kèm, hướng dẫn", example: "" },
    { word: "Advice", definition: "Lời khuyên", example: "" },
    { word: "Nominated", definition: "Được đề cử", example: "" },
    { word: "Quality", definition: "Chất lượng", example: "" },
    { word: "Commercials", definition: "Quảng cáo (trên TV/đài)", example: "" },
    { word: "Wise", definition: "Khôn ngoan, sáng suốt", example: "" },
    { word: "Decision", definition: "Quyết định", example: "" },
    { word: "Ads", definition: "Các quảng cáo (viết tắt)", example: "" },
    { word: "Encountered", definition: "Gặp phải, đối mặt", example: "" },
    { word: "Regarding", definition: "Về việc, liên quan đến", example: "" },
    { word: "Unexpected", definition: "Bất ngờ, không lường trước", example: "" },
    { word: "Charges", definition: "Các khoản phí", example: "" },
    { word: "Handled", definition: "Xử lý, giải quyết", example: "" },
    { word: "Resolved", definition: "Đã được giải quyết", example: "" },
    { word: "Satisfaction", definition: "Sự hài lòng", example: "" },
    { word: "downtown", definition: "Trung tâm thành phố", example: "" },
    { word: "subsequently", definition: "Sau đó, rồi thì", example: "" },
    { word: "numerous", definition: "Nhiều, đông đảo", example: "" },
    { word: "fulfilling", definition: "Thực hiện, hoàn thành (ước mơ/nhiệm vụ)", example: "" },
    { word: "lifelong", definition: "Suốt đời", example: "" },
    { word: "establishment", definition: "Cơ sở kinh doanh (nhà hàng, tổ chức)", example: "" },
    { word: "influenced", definition: "Bị ảnh hưởng, tác động", example: "" },
    { word: "officially", definition: "Một cách chính thức", example: "" },
    { word: "complimentary", definition: "Miễn phí (kính biếu)", example: "" },
    { word: "invitation", definition: "Lời mời, giấy mời", example: "" },
    { word: "bearer", definition: "Người cầm (vé, séc, giấy tờ)", example: "" },
    { word: "attend", definition: "Tham dự, có mặt", example: "" },
    { word: "drop by", definition: "Ghé qua (trong thời gian ngắn)", example: "" },
    { word: "promote", definition: "Quảng bá, thúc đẩy", example: "" },
    { word: "method", definition: "Phương pháp", example: "" },
    { word: "fellow", definition: "Đồng nghiệp, cùng hội cùng thuyền", example: "" },
    { word: "Payment", definition: "Sự thanh toán", example: "" },
    { word: "in advance", definition: "Trước (về thời gian)", example: "" },
    { word: "decline", definition: "Từ chối", example: "" },
    { word: "specializes", definition: "Chuyên về", example: "" },
];

const test8_176_185_words: VocabItem[] = [
    { word: "Publicize", definition: "Công khai, quảng bá", example: "" },
    { word: "Nominate", definition: "Đề cử", example: "" },
    { word: "Automotive", definition: "(Thuộc) ô tô, xe hơi", example: "" },
    { word: "Inexpensive", definition: "Không đắt, rẻ", example: "" },
    { word: "Appearance", definition: "Diện mạo, vẻ ngoài", example: "" },
    { word: "Uncommon", definition: "Hiếm, không phổ biến", example: "" },
    { word: "Government", definition: "Chính phủ", example: "" },
    { word: "Pleasure", definition: "Niềm vinh hạnh, hân hạnh", example: "" },
    { word: "Announce", definition: "Thông báo", example: "" },
    { word: "Utilized", definition: "Được sử dụng, tận dụng", example: "" },
    { word: "Working closely", definition: "Làm việc chặt chẽ, sát sao", example: "" },
    { word: "Passes", definition: "Vượt qua, đạt chuẩn", example: "" },
    { word: "Lightweight", definition: "Nhẹ", example: "" },
    { word: "Durable", definition: "Bền", example: "" },
    { word: "Resulting in", definition: "Dẫn đến, gây ra", example: "" },
    { word: "Cost-efficient", definition: "Tiết kiệm chi phí, hiệu quả kinh tế", example: "" },
    { word: "Process", definition: "Quy trình, quá trình", example: "" },
    { word: "Numerous", definition: "Nhiều, đông đảo", example: "" },
    { word: "Consumer", definition: "Người tiêu dùng", example: "" },
    { word: "solely", definition: "Duy nhất, chỉ", example: "" },
    { word: "underwent", definition: "Đã trải qua", example: "" },
    { word: "profile", definition: "Viết sơ lược tiểu sử, mô tả", example: "" },
    { word: "inquire", definition: "Hỏi thăm, yêu cầu thông tin", example: "" },
    { word: "opportunity", definition: "Cơ hội", example: "" },
    { word: "undertake", definition: "Đảm nhận, thực hiện", example: "" },
    { word: "high-end", definition: "Cao cấp, sang trọng", example: "" },
    { word: "imported", definition: "Nhập khẩu", example: "" },
    { word: "tourists", definition: "Khách du lịch", example: "" },
    { word: "short-term", definition: "Ngắn hạn", example: "" },
    { word: "firm", definition: "Công ty, hãng", example: "" },
    { word: "variety", definition: "Sự đa dạng", example: "" },
    { word: "currently", definition: "Hiện tại", example: "" },
    { word: "expand", definition: "Mở rộng, phát triển", example: "" },
    { word: "fit", definition: "Sự phù hợp / Vừa vặn", example: "" },
    { word: "high-class", definition: "Thượng lưu, cao cấp", example: "" },
    { word: "clientele", definition: "Nhóm khách hàng", example: "" },
    { word: "dominates", definition: "Thống trị, chiếm ưu thế (tầm nhìn)", example: "" },
    { word: "exclusively", definition: "Dành riêng, độc quyền", example: "" },
    { word: "foot traffic", definition: "Lưu lượng người đi bộ", example: "" },
    { word: "retail", definition: "Bán lẻ", example: "" },
    { word: "leasing", definition: "Cho thuê", example: "" },
    { word: "long-term", definition: "Dài hạn", example: "" },
];

const test8_186_200_words: VocabItem[] = [
    { word: "Former", definition: "Cựu, trước đây", example: "" },
    { word: "Occupies", definition: "Chiếm, sử dụng (không gian)", example: "" },
    { word: "Vacant", definition: "Trống, bỏ không", example: "" },
    { word: "Features", definition: "Có nét đặc trưng, bao gồm", example: "" },
    { word: "Capable of", definition: "Có khả năng", example: "" },
    { word: "Decorated", definition: "Được trang trí", example: "" },
    { word: "Interior", definition: "Nội thất, bên trong", example: "" },
    { word: "Retains", definition: "Giữ lại, duy trì", example: "" },
    { word: "Intimate", definition: "Thân mật, ấm cúng", example: "" },
    { word: "Unfortunate", definition: "Không may, đáng tiếc", example: "" },
    { word: "Carpets", definition: "Tấm thảm", example: "" },
    { word: "Pattern", definition: "Hoa văn, mẫu", example: "" },
    { word: "Alternative", definition: "Thay thế, sự lựa chọn khác", example: "" },
    { word: "Previous", definition: "Trước đó", example: "" },
    { word: "Comparable", definition: "Tương đương, có thể so sánh", example: "" },
    { word: "Selection", definition: "Sự lựa chọn, tuyển tập", example: "" },
    { word: "Minor", definition: "Nhỏ, không đáng kể", example: "" },
    { word: "Ambience", definition: "Bầu không khí", example: "" },
    { word: "Desire", definition: "Mong muốn, khao khát", example: "" },
    { word: "Affordable", definition: "Giá cả phải chăng", example: "" },
    { word: "Establishment", definition: "Cơ sở kinh doanh", example: "" },
    { word: "Allows", definition: "Cho phép", example: "" },
    { word: "finalist", definition: "Người vào vòng chung kết", example: "" },
    { word: "assistant", definition: "Trợ lý, phụ tá", example: "" },
    { word: "appreciate", definition: "Cảm kích, đánh giá cao", example: "" },
    { word: "a couple of", definition: "Một vài, một đôi", example: "" },
    { word: "survey", definition: "Cuộc khảo sát", example: "" },
    { word: "shuttle bus", definition: "Xe buýt đưa đón (tuyến ngắn)", example: "" },
    { word: "due to", definition: "Bởi vì, do", example: "" },
    { word: "popularity", definition: "Sự phổ biến, được yêu thích", example: "" },
    { word: "system", definition: "Hệ thống", example: "" },
    { word: "maintenance", definition: "Sự bảo trì", example: "" },
    { word: "current", definition: "Hiện tại, hiện nay", example: "" },
    { word: "accommodate", definition: "Đáp ứng, cung cấp chỗ (cho ai)", example: "" },
    { word: "distant", definition: "Xa xôi, cách biệt", example: "" },
    { word: "encouraging", definition: "Khuyến khích, động viên", example: "" },
    { word: "grant", definition: "Khoản trợ cấp, tài trợ", example: "" },
    { word: "facilities", definition: "Cơ sở vật chất, tiện nghi", example: "" },
    { word: "operate", definition: "Vận hành, hoạt động", example: "" },
    { word: "frequently", definition: "Thường xuyên", example: "" },
    { word: "pollution", definition: "Sự ô nhiễm", example: "" },
    { word: "depart", definition: "Khởi hành", example: "" },
    { word: "pursue", definition: "Theo đuổi, tìm kiếm", example: "" },
    { word: "conduct", definition: "Tiến hành, thực hiện", example: "" },
    { word: "inspection", definition: "Sự kiểm tra, thanh tra", example: "" },
    { word: "Clerk", definition: "Nhân viên bán hàng / Thư ký", example: "" },
    { word: "Supplies", definition: "Nhu yếu phẩm / Vật tư", example: "" },
    { word: "Same-day", definition: "Trong cùng ngày", example: "" },
    { word: "Several", definition: "Một vài / Một số", example: "" },
    { word: "Experts", definition: "Chuyên gia", example: "" },
    { word: "Policy", definition: "Chính sách", example: "" },
    { word: "Option", definition: "Sự lựa chọn", example: "" },
    { word: "Convenient", definition: "Tiện lợi / Thuận tiện", example: "" },
    { word: "Waste", definition: "Lãng phí", example: "" },
    { word: "Shelves", definition: "Các kệ / Giá đỡ", example: "" },
    { word: "Renovating", definition: "Cải tạo / Sửa chữa", example: "" },
    { word: "Arranged", definition: "Sắp xếp / Thu xếp", example: "" },
    { word: "Pick up", definition: "Lấy / Đón / Nhặt lên", example: "" },
    { word: "Refunded", definition: "Hoàn tiền", example: "" },
    { word: "Patronizing", definition: "Ủng hộ (thường xuyên lui tới mua hàng)", example: "" },
    { word: "Noticed", definition: "Nhận thấy / Để ý", example: "" },
    { word: "Worksite", definition: "Công trường / Nơi làm việc", example: "" },
    { word: "Acquire", definition: "Đạt được / Có được / Mua được", example: "" },
    { word: "Tools", definition: "Công cụ / Dụng cụ", example: "" },
];

export const readingPart7IntenseVocabularyData: VocabularyPart = {
    id: 9,
    title: "Reading Part 7 - Chuyên sâu",
    description: "Dành cho học viên cần mở rộng từ vựng.",
    tests: [
        { id: 901, title: "Test 1 (176-185)", words: test1_176_185_words },
        { id: 902, title: "Test 1 (186-200)", words: test1_186_200_words },
        { id: 903, title: "Test 2 (176-185)", words: test2_176_185_words },
        { id: 904, title: "Test 2 (186-200)", words: test2_186_200_words },
        { id: 905, title: "Test 3 (176-185)", words: test3_176_185_words },
        { id: 906, title: "Test 3 (186-200)", words: test3_186_200_words },
        { id: 907, title: "Test 4 (176-185)", words: test4_176_185_words },
        { id: 908, title: "Test 4 (186-200)", words: test4_186_200_words },
        { id: 909, title: "Test 5 (176-185)", words: test5_176_185_words },
        { id: 910, title: "Test 5 (186-200)", words: test5_186_200_words },
        { id: 911, title: "Test 6 (176-185)", words: test6_176_185_words },
        { id: 912, title: "Test 6 (186-200)", words: test6_186_200_words },
        { id: 913, title: "Test 7 (176-185)", words: test7_176_185_words },
        { id: 914, title: "Test 7 (186-200)", words: test7_186_200_words },
        { id: 915, title: "Test 8 (176-185)", words: test8_176_185_words },
        { id: 916, title: "Test 8 (186-200)", words: test8_186_200_words },
    ]
};
